import 'server-only';
import {createHash} from 'node:crypto';
import type {SupabaseClient} from '@supabase/supabase-js';
import {createServiceClient} from '@/lib/supabase/service';
import {ManagedError,unwrap} from './server';
import {signObjectCapability} from '../../../services/managed-objects/protocol.mjs';
export type ObjectRecord={id:string;project_id:string;name:string;bytes:number;sha256:string;status:'pending'|'ready'|'deleting'|'deleted'};
export function objectsConfigured(){return Boolean(process.env.MANAGED_OBJECT_GATEWAY_URL&&process.env.MANAGED_OBJECT_SIGNING_SECRET?.length&&process.env.MANAGED_OBJECT_SIGNING_SECRET.length>=32);}
function configuration(){
 if(!objectsConfigured())throw new ManagedError(503,'Armazenamento privado ainda não configurado.');
 const root=new URL(process.env.MANAGED_OBJECT_GATEWAY_URL!);
 if(root.username||root.password||root.pathname!=='/'||root.search||root.hash||(root.protocol!=='https:'&&!(root.protocol==='http:'&&['127.0.0.1','localhost','managed-objects'].includes(root.hostname))))throw new ManagedError(503,'Configuração do armazenamento inválida.');
 return {root,secret:process.env.MANAGED_OBJECT_SIGNING_SECRET!};
}
async function transport(row:ObjectRecord,method:'GET'|'PUT'|'DELETE',bytes?:Buffer){const {root,secret}=configuration();const path=`/objects/${row.project_id}/${row.id}`;const token=signObjectCapability({project:row.project_id,object:row.id,method,bytes:Number(row.bytes),sha256:row.sha256,expires:Date.now()+30000},secret);const response=await fetch(new URL(path,root),{method,redirect:'error',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/octet-stream'},body:bytes?new Uint8Array(bytes):undefined,signal:AbortSignal.timeout(25000)});if(!response.ok)throw new ManagedError(503,'Objeto não confirmado. O estado foi preservado para nova tentativa.');return response;}
export async function putObject(db:SupabaseClient,project:string,object:string,name:string,bytes:Buffer){configuration();if(bytes.length>1048576)throw new ManagedError(413,'Limite de 1 MB por envio nesta etapa.');const sha256=createHash('sha256').update(bytes).digest('hex');const row=unwrap(await db.rpc('managed_object_reserve',{p_project:project,p_object:object,p_name:name,p_bytes:bytes.length,p_sha256:sha256})) as ObjectRecord;if(row.status==='ready')return row;await transport(row,'PUT',bytes);if(unwrap(await db.rpc('can_access_managed_project',{p_project:project,p_write:true}))!==true)throw new ManagedError(403,'Acesso revogado antes da confirmação.');const done=unwrap(await createServiceClient().rpc('managed_object_complete',{p_project:project,p_object:object,p_deleted:false}));if(done!==true)throw new ManagedError(409,'Objeto mudou de estado durante o envio.');return {...row,status:'ready'};}
export async function getObject(db:SupabaseClient,project:string,object:string){const row=unwrap(await db.from('managed_objects').select('*').eq('project_id',project).eq('id',object).maybeSingle()) as ObjectRecord|null;if(!row||row.status!=='ready')throw new ManagedError(404,'Arquivo indisponível.');const response=await transport(row,'GET');const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length!==Number(row.bytes)||createHash('sha256').update(bytes).digest('hex')!==row.sha256)throw new ManagedError(503,'Integridade do arquivo não confirmada.');return {row,bytes};}
export async function deleteObject(db:SupabaseClient,project:string,object:string){configuration();const row=unwrap(await db.rpc('managed_object_delete_begin',{p_project:project,p_object:object})) as ObjectRecord;if(row.status==='deleted')return true;await transport(row,'DELETE');return unwrap(await createServiceClient().rpc('managed_object_complete',{p_project:project,p_object:object,p_deleted:true}));}
