import { aiEmbeddingExample, aiNativeExample, aiFileExample } from "./advanced-examples";
import { publicAiModelDefinitions } from "./public-models";
const ref=(name:string)=>({$ref:`#/components/schemas/${name}`});
const json=(schema:object)=>({"application/json":{schema}});
const error=(description:string)=>({description,content:json(ref("AiError"))});
const responses={"400":error("JSON inválido"),"401":error("Chave inválida"),"402":error("Confira acesso e créditos"),"403":error("Acesso bloqueado"),"404":error("Recurso não encontrado neste projeto"),"409":error("Operação em processamento ou identidade em conflito"),"413":error("Corpo acima do tamanho aceito"),"422":error("Configuração ou recurso não disponível no modelo"),"502":error("Execução não concluída; consulte a solicitação"),"503":error("Serviço indisponível")};
const identity={name:"Idempotency-Key",in:"header",required:false,schema:{type:"string",maxLength:128},description:"Identidade da operação. Preserve o mesmo corpo e esta identidade para recuperar sem duplicar a execução."};
const modelParam={name:"model",in:"path",required:true,schema:{type:"string"},example:"flash-3.5"};
const resourceParam={name:"id",in:"path",required:true,schema:{type:"string",format:"uuid"}};
const nativeOperation=(stream:boolean)=>({
  operationId:stream?"streamAiContent":"generateAiContent",tags:["Geração"],summary:stream?"Receber conteúdo em SSE":"Gerar conteúdo multimodal",
  description:"Modelo da URL deve ser o vinculado à chave. JSON completo de até 20 MB. Texto, funções, imagens e voz conforme o modelo da chave. SSE entrega partes durante a geração, seguido da confirmação dos créditos.",
  parameters:[modelParam,identity],requestBody:{required:true,content:{"application/json":{schema:ref("ContentRequest"),example:aiNativeExample}}},
  responses:{"200":{description:"Conteúdo e créditos confirmados",content:stream?{"text/event-stream":{schema:{type:"string"},description:"Eventos ContentResponse incrementais, content.completed com créditos e data: [DONE]."}}:json(ref("ContentResponse"))},...responses},
});
export const advancedAiPaths={
  "/models/{model}":{get:{operationId:"getAiModel",summary:"Consultar modelo e recursos",tags:["Identificação"],parameters:[modelParam],responses:{"200":{description:"Modelo disponível e compatibilidade com a chave",content:json(ref("PublicModel"))},...responses}}},
  "/models/{model}:generateContent":{post:nativeOperation(false)},
  "/models/{model}:streamGenerateContent":{post:nativeOperation(true)},
  "/embeddings":{post:{operationId:"createAiEmbedding",tags:["Vetores"],summary:"Transformar conteúdo em vetores",description:"Use uma chave vinculada a um modelo Embedding. Texto único, lista com até 100 textos ou conteúdo multimodal nos modelos compatíveis. A ConnectyHub retorna o vetor e os créditos; o índice e a comparação ficam no seu sistema. O conteúdo não é truncado silenciosamente.",parameters:[identity],requestBody:{required:true,content:{"application/json":{schema:ref("EmbeddingRequest"),example:aiEmbeddingExample}}},responses:{"200":{description:"Vetor e créditos confirmados",content:json(ref("EmbeddingResponse"))},...responses}}},
  "/files":{
    post:{operationId:"uploadAiFile",tags:["Arquivos"],summary:"Enviar arquivo do projeto",description:"Arquivo de até 20 MB em base64 puro (sem prefixo data:); JSON de até 28 MB. O arquivo precisa estar active antes do uso. Upload não gera conteúdo nem debita créditos; a análise é uma chamada cobrada. Cada envio cria um arquivo distinto.",requestBody:{required:true,content:{"application/json":{schema:ref("FileUpload"),example:aiFileExample}}},responses:{"201":{description:"Arquivo registrado",content:json(ref("AiFile"))},...responses}},
    get:{operationId:"listAiFiles",tags:["Arquivos"],summary:"Listar arquivos do projeto",description:"Até 100 arquivos recentes, incluindo estados de processamento e expiração. Chaves do mesmo projeto compartilham arquivos.",responses:{"200":{description:"Arquivos deste projeto",content:json({type:"object",properties:{object:{const:"list"},data:{type:"array",items:ref("AiFile")}}})},...responses}},
  },
  "/files/{id}":{
    get:{operationId:"getAiFile",tags:["Arquivos"],summary:"Atualizar estado do arquivo",parameters:[resourceParam],responses:{"200":{description:"Estado atualizado",content:json(ref("AiFile"))},...responses}},
    delete:{operationId:"deleteAiFile",tags:["Arquivos"],summary:"Excluir arquivo do projeto",parameters:[resourceParam],responses:{"200":{description:"Arquivo excluído",content:json(ref("AiFile"))},...responses}},
  },
};
export const advancedAiSchemas={
  PublicModel:{type:"object",properties:{id:{type:"string",enum:publicAiModelDefinitions.map(model=>model.id)},object:{const:"model"},name:{type:"string"},family:{type:"string"},profile:{type:"string"},consumption:{type:"string",description:"Perfil de uso em créditos; não representa um valor fixo por chamada."},recommended:{type:"boolean"},available:{type:"boolean"},capabilities:{type:"array",items:{type:"string"}},usable_with_key:{type:"boolean"},unavailable_reason:{type:["string","null"]}}},
  FunctionCall:{type:"object",required:["id","type","function"],properties:{id:{type:"string"},type:{const:"function"},function:{type:"object",required:["name","arguments"],properties:{name:{type:"string"},arguments:{type:"string",description:"Objeto JSON serializado."}}},context:{type:"string",description:"Se recebido, devolva este contexto opaco sem alteração no histórico."}}},
  AiTool:{oneOf:[{type:"object",required:["type","function"],properties:{type:{const:"function"},function:{type:"object",required:["name"],properties:{name:{type:"string",pattern:"^[A-Za-z_][A-Za-z0-9_.:-]{0,63}$"},description:{type:"string"},parameters:{type:"object",description:"JSON Schema dos argumentos."}}}}},{type:"object",additionalProperties:false,required:["type"],properties:{type:{enum:["code_execution","url_context"]}}}]},
  ResponseFormat:{oneOf:[{type:"object",required:["type"],properties:{type:{enum:["text","json_object"]}}},{type:"object",required:["type","json_schema"],properties:{type:{const:"json_schema"},json_schema:{type:"object",required:["schema"],properties:{name:{type:"string"},schema:{type:"object",minProperties:1}}}}}]},
  FilePart:{type:"object",required:["type","file"],properties:{type:{const:"file"},file:{type:"object",required:["file_data"],properties:{file_data:{type:"string",description:"Data URL de PDF, áudio ou vídeo em base64."}}}}},
  AudioPart:{type:"object",required:["type","input_audio"],properties:{type:{const:"input_audio"},input_audio:{type:"object",required:["data","format"],properties:{data:{type:"string",contentEncoding:"base64"},format:{enum:["mp3","wav"]}}}}},
  ContentPart:{type:"object",minProperties:1,properties:{text:{type:"string"},inlineData:{type:"object",required:["mimeType","data"],properties:{mimeType:{type:"string"},data:{type:"string",contentEncoding:"base64"}}},fileData:{type:"object",required:["fileUri"],properties:{fileUri:{type:"string",pattern:"^files/[a-f0-9-]{36}$",description:"Nome do arquivo deste projeto, retornado por /files."}}},functionCall:{type:"object",required:["name"],properties:{name:{type:"string"},id:{type:"string"},args:{type:"object"}}},functionResponse:{type:"object",required:["name","response"],properties:{name:{type:"string"},id:{type:"string"},response:{type:"object"}}},thoughtSignature:{type:"string",description:"Contexto opaco; preserve ao reenviar uma chamada de função."},videoMetadata:{type:"object",properties:{startOffset:{type:"string"},endOffset:{type:"string"},fps:{type:"number"}}}},description:"Exatamente um de text, inlineData, fileData, functionCall ou functionResponse por parte."},
  ContentRequest:{type:"object",additionalProperties:false,required:["contents"],properties:{contents:{type:"array",minItems:1,items:{type:"object",required:["parts"],properties:{role:{enum:["user","model"],default:"user"},parts:{type:"array",minItems:1,items:ref("ContentPart")}}}},systemInstruction:{type:"object",properties:{parts:{type:"array",items:{type:"object",required:["text"],properties:{text:{type:"string"}}}}}},generationConfig:{type:"object",description:"Configurações opcionais, aceitas conforme o modelo. Uma alternativa por solicitação. Saída textual ou mídia conforme o modelo.",properties:{temperature:{type:"number"},topP:{type:"number"},topK:{type:"integer"},candidateCount:{const:1},maxOutputTokens:{type:"integer",minimum:1,maximum:65536,description:"Capacidade da resposta; configuração automática quando omitida."},stopSequences:{type:"array",items:{type:"string"}},responseMimeType:{enum:["text/plain","application/json"]},responseSchema:{type:"object"},responseJsonSchema:{type:"object"},responseModalities:{type:"array",items:{enum:["TEXT","IMAGE","AUDIO"]}},speechConfig:{type:"object"},imageConfig:{type:"object"},thinkingConfig:{type:"object"},mediaResolution:{type:"string"},seed:{type:"integer"},presencePenalty:{type:"number"},frequencyPenalty:{type:"number"}}},tools:{type:"array",items:{oneOf:[{type:"object",required:["functionDeclarations"],properties:{functionDeclarations:{type:"array",items:{type:"object",properties:{name:{type:"string"},description:{type:"string"},parameters:{type:"object"},parametersJsonSchema:{type:"object"}}}}}},{type:"object",required:["codeExecution"],properties:{codeExecution:{type:"object"}}},{type:"object",required:["urlContext"],properties:{urlContext:{type:"object"}}},{type:"object",required:["webSearch"],properties:{webSearch:{type:"object"}}},{type:"object",required:["computerUse"],properties:{computerUse:{type:"object"}}},{type:"object",required:["fileSearch"],properties:{fileSearch:{type:"object",required:["stores"],properties:{stores:{type:"array",items:{type:"string"}},metadataFilter:{type:"string"},topK:{type:"integer"}}}}}]}},cachedContent:{type:"string",description:"Nome caches/ID deste projeto."},toolConfig:{type:"object"},safetySettings:{type:"array",items:{type:"object",properties:{category:{type:"string"},threshold:{type:"string"}}}}}},
  ContentResponse:{type:"object",properties:{id:{type:"string"},object:{const:"content.response"},model:{type:"string"},created:{type:"integer"},candidates:{type:"array",items:{type:"object",properties:{index:{type:"integer"},finishReason:{type:"string"},content:{type:"object",properties:{role:{const:"model"},parts:{type:"array",items:{type:"object",properties:{text:{type:"string"},functionCall:{type:"object"},thoughtSignature:{type:"string"},executableCode:{type:"object",properties:{language:{type:"string"},code:{type:"string"}}},codeExecutionResult:{type:"object",properties:{outcome:{type:"string"},output:{type:"string"}}}}}}}},sources:{type:"array",items:{type:"object",properties:{url:{type:"string"},title:{type:"string"}}}}}}},connectyhub:ref("CreditUsage")}},
  EmbeddingRequest:{type:"object",additionalProperties:false,oneOf:[{required:["input"]},{required:["content"]}],properties:{model:{type:"string",description:"Opcional; deve corresponder à chave."},input:{oneOf:[{type:"string",minLength:1},{type:"array",minItems:1,maxItems:100,items:{type:"string",minLength:1}}]},content:{type:"object",required:["parts"],properties:{parts:{type:"array",items:ref("ContentPart")}}},document_ocr:{type:"boolean"},audio_track_extraction:{type:"boolean"},dimensions:{type:"integer",minimum:1,maximum:3072},task_type:{enum:["RETRIEVAL_QUERY","RETRIEVAL_DOCUMENT","SEMANTIC_SIMILARITY","CLASSIFICATION","CLUSTERING","QUESTION_ANSWERING","FACT_VERIFICATION","CODE_RETRIEVAL_QUERY"]},title:{type:"string",description:"Somente com RETRIEVAL_DOCUMENT."}}},
  EmbeddingResponse:{type:"object",properties:{id:{type:"string"},object:{const:"embedding.list"},model:{type:"string"},data:{type:"array",items:{type:"object",properties:{object:{const:"embedding"},index:{type:"integer"},embedding:{type:"array",items:{type:"number"}}}}},connectyhub:ref("CreditUsage")}},
  FileUpload:{type:"object",required:["data","mime_type"],properties:{data:{type:"string",contentEncoding:"base64"},mime_type:{enum:["image/png","image/jpeg","image/webp","audio/mpeg","audio/mp4","audio/wav","audio/aac","audio/ogg","audio/flac","video/mp4","video/webm","video/quicktime","application/pdf","text/plain"]},display_name:{type:"string",maxLength:200}}},
  AiFile:{type:"object",properties:{id:{type:"string",format:"uuid"},name:{type:"string"},display_name:{type:"string"},mime_type:{type:"string"},size_bytes:{type:"integer"},status:{enum:["preparing","processing","active","failed","expired","deleted"]},created_at:{type:"string",format:"date-time"},expires_at:{type:["string","null"],format:"date-time"}}},
};
