const ref=(name:string)=>({$ref:`#/components/schemas/${name}`});
const json=(schema:object)=>({'application/json':{schema}});
const id={name:'id',in:'path',required:true,schema:{type:'string',format:'uuid'}};
const errors={'401':{description:'Chave inválida'},'403':{description:'Projeto ou acesso suspenso'},'404':{description:'Recurso de outro projeto ou inexistente'},'422':{description:'Configuração inválida'},'503':{description:'Serviço indisponível'}};
export const aiAutomationPaths=Object.fromEntries(['webhooks','triggers'].flatMap(kind=>{
  const schema=kind==='webhooks'?'AiWebhook':'AiTrigger';
  return [
    [`/${kind}`,{
      post:{operationId:`create${schema}`,tags:['Automações'],summary:kind==='webhooks'?'Cadastrar webhook':'Criar agendamento',description:kind==='webhooks'?'Notifica alterações futuras das solicitações do projeto. Não executa IA. A chave de assinatura é exibida somente na criação.':'Cada horário inicia uma Interação com a chave original, revalida o acesso e reserva créditos. Cadastrar não executa imediatamente. Uma nova criação é um novo agendamento; confira a listagem antes de repetir após perda de conexão.',requestBody:{required:true,content:json(ref(schema+'Request'))},responses:{'200':{description:'Configuração criada',content:json(ref(schema+'Created'))},...errors}},
      get:{operationId:`list${schema}`,tags:['Automações'],summary:'Listar '+kind,description:'Até 100 configurações recentes do projeto da chave, incluindo pausadas.',responses:{'200':{description:'Lista de configurações',content:json({type:'object',properties:{object:{const:'list'},data:{type:'array',items:ref(schema)}}})},...errors}},
    }],
    [`/${kind}/{id}`,{
      get:{operationId:`get${schema}`,tags:['Automações'],summary:'Consultar configuração',parameters:[id],responses:{'200':{description:'Configuração do projeto',content:json(ref(schema))},...errors}},
      patch:{operationId:`update${schema}`,tags:['Automações'],summary:'Pausar ou reativar',description:'Envie enabled. Reativar um agendamento começa no próximo horário futuro; não recupera horários perdidos. Para mudar URL, segredo ou instruções, pause e crie outra configuração.',parameters:[id],requestBody:{required:true,content:json({type:'object',required:['enabled'],additionalProperties:false,properties:{enabled:{type:'boolean',description:'true ativa; false pausa novas execuções ou entregas.'}}})},responses:{'200':{description:'Configuração atualizada',content:json(ref(schema))},...errors}},
      delete:{operationId:`disable${schema}`,tags:['Automações'],summary:'Desativar configuração',description:'Desativação preserva o histórico. Execuções já enviadas continuam com sua cobrança; desativar não estorna nem cancela uma geração em andamento.',parameters:[id],responses:{'200':{description:'Configuração desativada',content:json(ref(schema))},...errors}},
    }],
    [`/${kind}/{id}/${kind==='webhooks'?'deliveries':'runs'}`,{get:{operationId:`history${schema}`,tags:['Automações'],summary:'Histórico de '+(kind==='webhooks'?'entregas':'execuções'),description:'Até 100 registros recentes. Consulte request_id na API de solicitações para o resultado financeiro e a resposta.',parameters:[id],responses:{'200':{description:'Histórico',content:json({type:'object',properties:{object:{const:'list'},data:{type:'array',items:ref(kind==='webhooks'?'AiWebhookDelivery':'AiTriggerRun')}}})},...errors}}}],
  ];
}));
const webhook={id:{type:'string',format:'uuid'},project_id:{type:'string',format:'uuid'},url:{type:'string',format:'uri'},events:{type:'array',items:{enum:['request.completed','request.failed']}},enabled:{type:'boolean'},created_at:{type:'string',format:'date-time'}};
const trigger={id:{type:'string',format:'uuid'},project_id:{type:'string',format:'uuid'},display_name:{type:'string'},schedule:{type:'string',description:'Cron de cinco campos: minuto, hora, dia do mês, mês e dia da semana.'},time_zone:{type:'string',description:'Fuso IANA, como America/Sao_Paulo.'},interaction:ref('InteractionRequest'),enabled:{type:'boolean'},next_run_at:{type:'string',format:'date-time'},created_at:{type:'string',format:'date-time'}};
export const aiAutomationSchemas={
  AiWebhook:{type:'object',properties:webhook},AiWebhookCreated:{type:'object',properties:{...webhook,signing_secret:{type:'string',description:'Segredo de assinatura retornado somente na criação. Guarde no servidor.'}}},
  AiWebhookRequest:{type:'object',required:['url'],additionalProperties:false,properties:{url:{type:'string',format:'uri',description:'HTTPS público na porta 443, DNS IPv4 público, sem credenciais ou redirecionamento.'},events:{type:'array',minItems:1,items:{enum:['request.completed','request.failed']},default:['request.completed','request.failed']}}},
  AiTrigger:{type:'object',properties:trigger},AiTriggerCreated:{type:'object',properties:trigger},
  AiTriggerRequest:{type:'object',required:['schedule','interaction'],additionalProperties:false,properties:{display_name:{type:'string',maxLength:200},schedule:trigger.schedule,time_zone:{...trigger.time_zone,default:'America/Sao_Paulo'},interaction:ref('InteractionRequest')}},
  AiWebhookDelivery:{type:'object',properties:{id:{type:'string'},request_id:{type:'string'},event_type:{enum:['request.completed','request.failed']},status:{enum:['pending','delivered','failed','skipped']},attempts:{type:'integer'},http_status:{type:['integer','null']},created_at:{type:'string',format:'date-time'}}},
  AiTriggerRun:{type:'object',properties:{id:{type:'string'},request_id:{type:['string','null']},status:{enum:['pending','submitted','failed','skipped'],description:'submitted informa despacho/recuperação da solicitação, não conclusão da geração. Consulte request_id.'},error_code:{type:['string','null']},created_at:{type:'string',format:'date-time'}}},
  AiWebhookEvent:{type:'object',required:['id','type','created_at','data'],properties:{id:{type:'string',format:'uuid'},type:{enum:['request.completed','request.failed']},created_at:{type:'string',format:'date-time'},data:{type:'object',properties:{request_id:{type:'string',format:'uuid'},project_id:{type:'string',format:'uuid'},status:{enum:['completed','failed']},credits:{type:'number',minimum:0},request_url:{type:'string',description:'Caminho relativo para buscar o resultado com sua chave.'}}}}},
};
