const ref=(name:string)=>({$ref:`#/components/schemas/${name}`});
const text=(description:string)=>({type:'string',description});
const schema={type:'object',description:'JSON Schema definido pelo seu sistema. Descreva properties, required e additionalProperties conforme o resultado esperado.'};
const media={type:'object',required:['type'],properties:{type:{enum:['image','audio','video','document']},data:{type:'string',contentEncoding:'base64',description:'Conteúdo em base64 puro; use data ou uri.'},uri:text('Nome files/ID de um arquivo ativo deste projeto. URLs externas não são aceitas aqui.'),mime_type:text('Tipo MIME do conteúdo; por exemplo image/png ou audio/wav.')}};
export const detailedAiSchemas:Record<string,Record<string,unknown>>={
  ContentResponse:{type:'object',properties:{id:{type:'string'},object:{const:'content.response'},model:{type:'string'},created:{type:'integer',description:'Data Unix em segundos.'},candidates:{type:'array',items:{type:'object',properties:{index:{type:'integer'},finishReason:{type:'string',description:'Motivo da conclusão, por exemplo STOP, MAX_TOKENS ou SAFETY. Trate saída parcial antes de utilizá-la.'},content:{type:'object',properties:{role:{const:'model'},parts:{type:'array',items:ref('OutputPart')}}},grounding:ref('AiGrounding')}}},connectyhub:ref('CreditUsage')}},
  OutputPart:{type:'object',properties:{text:{type:'string'},inlineData:{type:'object',properties:{mimeType:{type:'string'},data:{type:'string',contentEncoding:'base64'}}},functionCall:{type:'object',properties:{id:{type:'string'},name:{type:'string'},args:{type:'object'}}},functionResponse:{type:'object',properties:{name:{type:'string'},response:{type:'object'}}},executableCode:{type:'object',properties:{language:{type:'string'},code:{type:'string'}}},codeExecutionResult:{type:'object',properties:{outcome:{type:'string'},output:{type:'string'}}},thoughtSignature:text('Contexto opaco; preserve em continuações de funções. Não é raciocínio legível.')}},
  AiGrounding:{type:'object',properties:{sources:{type:'array',items:{type:'object',properties:{url:{type:'string'},title:{type:'string'},text:{type:'string'},place_id:{type:'string'}}}},supports:{type:'array',items:{type:'object',properties:{segment:{type:'object',properties:{startIndex:{type:'integer'},endIndex:{type:'integer'},text:{type:'string'}}},groundingChunkIndices:{type:'array',items:{type:'integer'}}}}},attribution:text('Atribuição da fonte quando retornada. Renderize de forma segura e preserve o conteúdo exigido.'),maps_attribution:text('Contexto de atribuição para mapas, quando aplicável.')}},
  InteractionInputPart:{oneOf:[{type:'object',required:['type','text'],properties:{type:{const:'text'},text:text('Texto da pergunta ou do contexto.')}},media,{type:'object',required:['type','call_id','result'],properties:{type:{const:'function_result'},call_id:text('Identidade recebida na chamada de função.'),name:text('Nome da função executada.'),result:{oneOf:[{type:'string'},{type:'object'}]},is_error:{type:'boolean',description:'true quando a execução no seu sistema falhou.'}}}]},
  InteractionTool:{oneOf:[
    {type:'object',required:['type','name'],properties:{type:{const:'function'},name:text('Identificador da função no seu sistema.'),description:text('Quando e como a função deve ser usada.'),parameters:schema}},
    {type:'object',required:['type'],properties:{type:{enum:['web_search','code_execution','url_context']}}},
    {type:'object',required:['type'],properties:{type:{const:'maps'},latitude:{type:'number',minimum:-90,maximum:90},longitude:{type:'number',minimum:-180,maximum:180}}},
    {type:'object',required:['type','stores'],properties:{type:{const:'file_search'},stores:{type:'array',minItems:1,items:text('ID de uma coleção ativa deste projeto.')}}},
    {type:'object',required:['type','environment'],properties:{type:{const:'computer_use'},environment:{const:'browser'}}},
    {type:'object',required:['type','url'],properties:{type:{const:'mcp_server'},url:{type:'string',format:'uri'},name:text('Nome público do servidor de ferramentas.'),allowed_tools:{type:'array',items:{type:'object',properties:{mode:{enum:['auto','any','none','validated']},tools:{type:'array',items:{type:'string'}}}}},headers:{type:'object',additionalProperties:{type:'string'},description:'Cabeçalhos do seu servidor MCP. Não envie sua chave ConnectyHub.'}}},
  ]},
  InteractionGenerationConfig:{type:'object',properties:{temperature:{type:'number',minimum:0,maximum:2,description:'Variação da resposta, conforme suporte do modelo.'},top_p:{type:'number',minimum:0,maximum:1},seed:{type:'integer'},stop_sequences:{type:'array',items:{type:'string'}},thinking_level:{enum:['minimal','low','medium','high'],description:'Esforço de raciocínio. Maior esforço pode consumir mais créditos.'},speech_config:{type:'object',properties:{voice:text('Voz aceita pelo modelo.'),language:text('Idioma da fala.')}},transcription_config:{type:'object',properties:{language_codes:{type:'array',items:text('Idioma BCP-47, por exemplo pt-BR.')},custom_vocabulary:{type:'array',items:{type:'string'}},mode:{oneOf:[{type:'object',properties:{type:{const:'smart'}}},{type:'object',properties:{type:{const:'verbatim'},diarization_mode:{const:'speaker'},timestamp_granularities:{type:'array',items:{const:'word'}}}}]}}},video_config:{type:'object',properties:{task:{enum:['text_to_video','image_to_video','reference_to_video','edit','extend']}}}}},
  InteractionRequest:{type:'object',additionalProperties:false,required:['input'],properties:{model:text('Opcional: ID público vinculado à chave; a omissão usa o modelo da chave.'),input:{oneOf:[{type:'string',minLength:1},{type:'array',minItems:1,items:ref('InteractionInputPart')}]},system_instruction:text('Instruções fixas para esta execução.'),previous_interaction_id:{type:'string',format:'uuid',description:'Interação concluída ou aguardando ação, pertencente ao mesmo projeto.'},agent_id:{type:'string',format:'uuid',description:'Agente ativo criado em /agents com o modelo da chave.'},environment_id:{type:'string',format:'uuid',description:'Ambiente ativo deste projeto.'},response_format:{type:'object',properties:{type:{enum:['json','text','image','audio','video']},schema,aspect_ratio:text('Proporção da mídia, conforme o modelo.'),resolution:text('Resolução de saída suportada pelo modelo.')}},agent_config:{type:'object',additionalProperties:false,description:'Opções exclusivas de pesquisa aprofundada, quando disponível para a chave.',properties:{collaborative_planning:{type:'boolean'},visualization:{enum:['off','auto']},thinking_summaries:{enum:['none','auto']}}},generation_config:ref('InteractionGenerationConfig'),tools:{type:'array',items:ref('InteractionTool')}}},
  InteractionStep:{type:'object',properties:{type:text('model_output, function_call, function_result, web_search_call, web_search_result, maps_call, maps_result e eventos de ferramentas compatíveis.'),id:text('Identificador da etapa, quando disponível.'),call_id:text('Identificador usado para devolver o resultado de uma função.'),name:text('Nome da função.'),arguments:{type:'object',description:'Argumentos propostos; valide antes de executar no seu sistema.'},result:{description:'Resultado da ferramenta, cujo formato depende da função.'},content:{type:'array',items:{oneOf:[{type:'object',properties:{type:{const:'text'},text:{type:'string'}}},{...media,properties:{...media.properties,uri:text('Caminho de download autenticado pela chave do projeto.')}}]}},signature:text('Contexto opaco que deve ser preservado quando retornado.'),is_error:{type:'boolean'}}},
  InteractionResult:{type:'object',properties:{id:{type:'string'},object:{const:'interaction'},model:{type:'string'},status:{enum:['completed','requires_action','failed','cancelled']},steps:{type:'array',items:ref('InteractionStep')},connectyhub:ref('CreditUsage')}},
  VideoResult:{type:'object',properties:{id:{type:'string'},object:{const:'video'},videos:{type:'array',items:{type:'object',properties:{url:text('Caminho de download autenticado pela chave do projeto.'),mime_type:{const:'video/mp4'}}}},connectyhub:ref('CreditUsage')}},
  BatchResult:{type:'object',properties:{id:{type:'string'},object:{const:'batch'},results:{type:'array',items:{type:'object',properties:{key:text('Identidade original do item.'),response:{oneOf:[ref('ContentResponse'),{type:'object',properties:{object:{const:'embedding'},embedding:{type:'array',items:{type:'number'}}}}]},error:ref('AiError')}}},connectyhub:ref('CreditUsage')}},
  SpeechConfig:{type:'object',properties:{languageCode:text('Idioma da fala, conforme suporte.'),voiceConfig:{type:'object',properties:{prebuiltVoiceConfig:{type:'object',required:['voiceName'],properties:{voiceName:text('Voz selecionada, por exemplo Kore.')}}}},multiSpeakerVoiceConfig:{type:'object',properties:{speakerVoiceConfigs:{type:'array',items:{type:'object',properties:{speaker:text('Nome do personagem no texto.'),voiceConfig:{type:'object',properties:{prebuiltVoiceConfig:{type:'object',properties:{voiceName:{type:'string'}}}}}}}}}}}},
  ImageConfig:{type:'object',properties:{aspectRatio:{enum:['1:1','2:3','3:2','3:4','4:3','4:5','5:4','9:16','16:9','21:9']},imageSize:{enum:['512','1K','2K','4K'],description:'Resoluções aceitas variam por modelo e têm consumo diferente.'}}},
  ThinkingConfig:{type:'object',properties:{thinkingLevel:{enum:['MINIMAL','LOW','MEDIUM','HIGH'],description:'Esforço de raciocínio conforme suporte do modelo.'},includeThoughts:{type:'boolean',description:'O contrato público não entrega raciocínio interno; use o resultado e as justificativas da resposta.'}}},
  LiveClientMessage:{oneOf:[{type:'object',required:['id','access_key'],properties:{id:{type:'string',format:'uuid'},access_key:text('Acesso descartável retornado por POST /live. Primeiro envio após conectar.')}},{type:'object',properties:{clientContent:{type:'object',properties:{turns:{type:'array',items:{type:'object',properties:{role:{enum:['user','model']},parts:{type:'array',items:ref('ContentPart')}}}},turnComplete:{type:'boolean'}}}}},{type:'object',properties:{realtimeInput:{type:'object',properties:{audio:{type:'object',properties:{mimeType:text('Formato PCM com frequência, conforme o modelo.'),data:{type:'string',contentEncoding:'base64'}}},video:{type:'object',properties:{mimeType:{const:'image/jpeg'},data:{type:'string',contentEncoding:'base64'}}},audioStreamEnd:{type:'boolean'}}}}},{type:'object',properties:{toolResponse:{type:'object',properties:{functionResponses:{type:'array',items:{type:'object',properties:{id:{type:'string'},name:{type:'string'},response:{type:'object'}}}}}}}}]},
  LiveRequest:{type:'object',properties:{model:text('Opcional; deve corresponder ao modelo da chave.'),config:{type:'object',additionalProperties:false,properties:{generationConfig:{type:'object',properties:{responseModalities:{type:'array',items:{enum:['TEXT','AUDIO']}},temperature:{type:'number'},speechConfig:ref('SpeechConfig')}},systemInstruction:{type:'object',properties:{parts:{type:'array',items:{type:'object',properties:{text:{type:'string'}}}}}},tools:{type:'array',items:{type:'object',properties:{functionDeclarations:{type:'array',items:{type:'object',properties:{name:{type:'string'},description:{type:'string'},parameters:schema}}}}}},inputAudioTranscription:{type:'object',description:'Envie {} para solicitar transcrição da entrada, conforme o modelo.'},outputAudioTranscription:{type:'object',description:'Envie {} para solicitar transcrição da saída.'},realtimeInputConfig:{type:'object',properties:{automaticActivityDetection:{type:'object',properties:{disabled:{type:'boolean'},silenceDurationMs:{type:'integer'},prefixPaddingMs:{type:'integer'}}},activityHandling:{enum:['START_OF_ACTIVITY_INTERRUPTS','NO_INTERRUPTION']}}},contextWindowCompression:{type:'object',properties:{slidingWindow:{type:'object'}}},proactivity:{type:'object',properties:{proactiveAudio:{type:'boolean'}}}}}}},
};
