const ref=(name:string)=>({$ref:`#/components/schemas/${name}`});
const content=(schema:object)=>({'application/json':{schema}});
const model={name:'model',in:'path',required:true,schema:{type:'string'}};
const batch={name:'id',in:'path',required:true,schema:{type:'string',format:'uuid'}};
const errors=Object.fromEntries([400,401,402,403,404,409,422,429,503].map(code=>[code,{description:'Falha com motivo em error.details; preserve a identidade ao repetir.',content:content(ref('Error'))}]));
const operation={description:'Operação com identidade do próprio projeto',content:content(ref('BatchOperation'))};
const create=(embedding:boolean)=>({parameters:[model,{name:'Idempotency-Key',in:'header',schema:{type:'string'}}],description:'Lote inline de 1 a 100 itens. Arquivo de entrada, priority e webhooks ainda não suportados. Uma única reserva/liquidação por lote; consulta não repete geração.',requestBody:{required:true,content:content(ref(embedding?'EmbedBatchRequest':'GenerateBatchRequest'))},responses:{200:operation,...errors}});
export const geminiBatchPaths={
  '/models/{model}:batchGenerateContent':{post:{operationId:'geminiBatchGenerateContent',...create(false)}},
  '/models/{model}:asyncBatchEmbedContent':{post:{operationId:'geminiAsyncBatchEmbedContent',...create(true)}},
  '/batches':{get:{operationId:'geminiListBatches',parameters:[{name:'pageSize',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:20}},{name:'pageToken',in:'query',schema:{type:'string'}}],description:'Estado persistido das operações do projeto. Consulte um lote para atualizar; filtro e returnPartialSuccess não suportados.',responses:{200:{description:'Operações do projeto',content:content({type:'object',properties:{operations:{type:'array',items:ref('BatchOperation')},nextPageToken:{type:'string'}}})},...errors}}},
  '/batches/{id}':{get:{operationId:'geminiGetBatch',parameters:[batch],responses:{200:operation,...errors}},delete:{operationId:'geminiDeleteBatch',parameters:[batch],description:'Remove somente operações encerradas. Uma operação em andamento retorna 409; excluir não substitui cancelar nem elimina consumo pendente.',responses:{200:{description:'Removida',content:content({type:'object'})},...errors}}},
  '/batches/{id}:cancel':{post:{operationId:'geminiCancelBatch',parameters:[batch],description:'Solicita cancelamento; resposta vazia não garante cancelamento. Consulte o lote e seus créditos. Não libera uma reserva incerta.',responses:{200:{description:'Solicitação processada',content:content({type:'object'})},...errors}}},
};
const request=(schema:string)=>({type:'object',additionalProperties:false,required:['batch'],properties:{batch:{type:'object',additionalProperties:false,required:['displayName','inputConfig'],properties:{model:{type:'string'},displayName:{type:'string',minLength:1,maxLength:200},inputConfig:{type:'object',additionalProperties:false,required:['requests'],properties:{requests:{type:'object',additionalProperties:false,required:['requests'],properties:{requests:{type:'array',minItems:1,maxItems:100,items:{type:'object',additionalProperties:false,required:['request'],properties:{request:ref(schema),metadata:{type:'object',additionalProperties:{type:'string'}}}}}}}}}}}}});
export const geminiBatchSchemas={
  GenerateBatchRequest:request('ContentRequest'),EmbedBatchRequest:request('EmbedRequest'),
  BatchOperation:{type:'object',properties:{name:{type:'string'},done:{type:'boolean'},metadata:{type:'object',properties:{name:{type:'string'},model:{type:'string'},displayName:{type:'string'},state:{type:'string'},batchStats:{type:'object'}}},response:{type:'object',properties:{inlinedResponses:{type:'object',properties:{inlinedResponses:{type:'array',items:{type:'object',properties:{response:{oneOf:[ref('GenerateContentResponse'),ref('EmbedResponse')]},error:{type:'object'},metadata:{type:'object',additionalProperties:{type:'string'}}}}}}}}},error:{type:'object',properties:{code:{type:'integer'},message:{type:'string'}}},connectyhub:ref('Credits')}},
};
