import type {AiDocPage} from './documentation';
const example=(title:string,value:unknown)=>({kind:'code' as const,title,language:'json',code:JSON.stringify(value,null,2)});
export const aiIntegrationGuides:AiDocPage[]=[
  {id:'ia-escolher-interface',label:'Qual integração usar',group:'Começar',title:'Escolha o caminho para sua aplicação',description:'Comece pela tarefa. A chave define o modelo; cada interface tem um formato próprio.',blocks:[
    {kind:'table',title:'Interfaces',columns:['Necessidade','Operação','Resultado'],rows:[['Conversa simples ou cliente com messages','POST /chat/completions','choices[0].message; stream entrega após concluir.'],['Controle multimodal e geração incremental','POST /models/{model}:generateContent ou :streamGenerateContent','candidates[].content.parts; SSE incremental na segunda rota.'],['Ferramentas, pesquisa e continuação gerenciada','POST /interactions','Recurso consultável; resultado em result.steps.'],['Vídeo assíncrono','POST /videos','Acompanhe até concluir e baixe com autenticação.'],['Voz interativa','POST /live + WebSocket','Eventos bidirecionais; exige serviço ativo.'],['Execução recorrente','POST /triggers','Cada ocorrência cria uma Interação cobrada.']]},
    {kind:'text',text:'Os formatos não são intercambiáveis: messages pertence a Chat Completions, contents à geração multimodal e input às Interações. Bibliotecas de terceiros só funcionam com o subconjunto que implementam e com a base correta. Não existe compatibilidade universal com qualquer SDK.'},
  ]},
  {id:'ia-creditos-detalhados',label:'Cobrança por recurso',group:'Créditos e operação',title:'Como cada recurso usa seus créditos',description:'A carteira da conta é compartilhada entre projetos. O sistema registra automaticamente o consumo das execuções faturáveis.',blocks:[
    {kind:'table',title:'O que entra na conta',columns:['Recurso','Base do consumo','Quando é confirmado'],rows:[['Texto, análise e raciocínio','Conteúdo processado e resposta; especialidade e esforço do modelo','Após receber a medição final.'],['Imagem e voz','Entrada e mídia produzida, conforme modalidade','Após gerar e conferir a medição.'],['Vídeo','Duração, resolução e saídas produzidas','Na conclusão da operação.'],['Música','Músicas produzidas','Na conclusão.'],['Pesquisa e mapas','Consultas executadas, além da geração','Na conclusão, com contagem das ferramentas.'],['Vetores','Conteúdo de entrada e modalidade','Após a medição final.'],['Lotes','Consumo de cada item processado; tarifa de lote','Na conferência dos resultados individuais.'],['Cache','Leitura reutilizada e armazenamento por tamanho e tempo','Leitura na geração; armazenamento ao expirar ou encerrar.'],['Indexação','Conteúdo medido na importação','Após indexar com sucesso.'],['Agentes e agendamentos','Todas as etapas faturáveis de cada execução','Cada Interação tem seu próprio registro.'],['Tempo real','Conteúdo processado durante a sessão','Acompanhamento durante a sessão e liquidação ao encerrar.']]},
    {kind:'steps',title:'Ciclo de uma operação',items:['A API verifica a chave, o projeto, o acesso e os preços do recurso.','Antes de executar, separa uma estimativa do saldo disponível. Essa reserva não é uma cobrança adicional.','A execução produz a medição do consumo.','A API confirma o débito, libera eventual sobra da reserva e registra os créditos da operação.','Se a medição estiver incompleta, a operação fica em conferência; não inicie outra execução equivalente sem consultar o estado.']},
    example('Exemplo ilustrativo de uma geração concluída',{connectyhub:{request_id:'00000000-0000-4000-8000-000000000001',project_id:'00000000-0000-4000-8000-000000000002',credits:7.25}}),
    {kind:'text',text:'Exemplo ilustrativo: se foram reservados 12 créditos e o consumo final foi 7,25, o débito é 7,25 e os 4,75 restantes voltam a ficar disponíveis. Não há cobrança de 12 mais 7,25. Se o consumo confirmado ultrapassar a reserva, a liquidação utiliza apenas saldo livre; sem saldo suficiente, aguarda regularização.'},
    {kind:'note',title:'Operações administrativas',text:'Ler esta documentação, baixar o JSON, consultar modelos/resultados, configurar webhooks e cadastrar agendamentos não inicia uma geração. Upload não equivale a análise. O consumo ocorre nas execuções, ferramentas e armazenamento faturável descritos acima. Serviços externos conectados pelo cliente podem ter cobrança própria.'},
    {kind:'text',text:'O modelo, o conteúdo e a tarifa vigente determinam o consumo; os exemplos não são preços fixos. A tarifa usada fica associada à execução. Uma resposta parcial ou um cancelamento pode ter consumo já realizado. Repetir a consulta ou receber o mesmo webhook não duplica o débito.'},
  ]},
  {id:'ia-webhooks',label:'Webhooks de resultados',group:'Automações',title:'Receba avisos de conclusão no seu servidor',description:'A ConnectyHub envia eventos do projeto após registrar a situação financeira da solicitação.',method:'POST',path:'/webhooks',blocks:[
    example('Cadastrar',{url:'https://seu-sistema.example/api/avisos-ia',events:['request.completed','request.failed']}),
    {kind:'steps',title:'Integração',items:['Cadastre uma URL HTTPS pública no servidor do seu sistema.','Guarde signing_secret retornado na criação; ele não aparece na consulta posterior.','Leia o corpo HTTP bruto e verifique a assinatura antes de interpretar o JSON.','Registre o id do evento com unicidade, coloque seu processamento em uma fila e responda com HTTP 2xx.','Consulte data.request_url com sua chave para buscar a resposta. O aviso não contém o conteúdo da conversa.']},
    example('Evento',{id:'00000000-0000-4000-8000-000000000003',type:'request.completed',created_at:'2026-09-10T12:00:00Z',data:{request_id:'00000000-0000-4000-8000-000000000001',project_id:'00000000-0000-4000-8000-000000000002',status:'completed',credits:7.25,request_url:'/api/v1/ai/requests/00000000-0000-4000-8000-000000000001'}}),
    {kind:'code',title:'Validar assinatura · Node.js',language:'javascript',code:`import { createHmac, timingSafeEqual } from 'node:crypto';
export function validSignature(rawBody, headers, secret, now = Date.now()) {
  const id = headers.get('x-connectyhub-event-id');
  const timestamp = headers.get('x-connectyhub-timestamp');
  const signature = headers.get('x-connectyhub-signature') ?? '';
  if (!id || !/^\\d+$/.test(timestamp ?? '') || Math.abs(now / 1000 - Number(timestamp)) > 300) return false;
  if (!/^v1=[a-f0-9]{64}$/.test(signature)) return false;
  const expected = createHmac('sha256', secret).update(id + '.' + timestamp + '.' + rawBody).digest();
  return timingSafeEqual(expected, Buffer.from(signature.slice(3), 'hex'));
}
// rawBody é o texto exato recebido; não serialize novamente o JSON.
// Depois de validar: confira id do corpo == id do cabeçalho e deduplique por id.
// Guarde o evento de forma durável antes de responder 2xx.`},
    {kind:'text',text:'Entrega pelo menos uma vez: o mesmo evento pode chegar novamente. Cada tentativa tem uma assinatura com horário atualizado e preserva o id. Falhas têm até oito tentativas automáticas; consulte GET /webhooks/{id}/deliveries. Não há garantia de ordem entre eventos. O worker processa a fila periodicamente, portanto o aviso não é instantâneo.'},
    {kind:'note',title:'URLs e reativação',text:'São aceitos destinos HTTPS na porta padrão com DNS IPv4 público. Redirecionamentos não são seguidos. PATCH com enabled=false pausa o webhook; DELETE o desativa preservando o histórico. Para trocar o destino ou segredo, desative e crie outro. Não são enviados eventos anteriores ao cadastro.'},
    {kind:'text',text:'request.completed significa que a solicitação foi liquidada. Em lotes ou interações, confira o resultado interno: pode haver itens com falha, cancelamento ou necessidade de ação. Reentregar o aviso não executa a IA nem cobra a geração novamente.'},
  ]},
  {id:'ia-agendamentos',label:'Agendamentos cobrados',group:'Automações',title:'Execute tarefas automaticamente',description:'Defina quando a Interação deve ocorrer. Em cada execução, o sistema verifica novamente acesso, chave, modelo, preços e saldo.',method:'POST',path:'/triggers',blocks:[
    example('Todo dia às 9h em São Paulo',{display_name:'Resumo diário',schedule:'0 9 * * *',time_zone:'America/Sao_Paulo',interaction:{input:'Pesquise as notícias mais recentes sobre atendimento ao cliente e faça um resumo com fontes.',tools:[{type:'web_search'}]}}),
    {kind:'table',title:'Exemplos de cron',columns:['Expressão','Quando'],rows:[['0 9 * * *','Todos os dias às 9h.'],['0 9 * * 1-5','Dias úteis às 9h.'],['0 */6 * * *','A cada seis horas, na hora cheia.'],['30 8 1 * *','Dia 1 de cada mês às 8h30.']]},
    {kind:'steps',title:'Acompanhar',items:['Crie o agendamento com a chave do modelo que deseja utilizar.','Confira next_run_at na resposta. Cadastrar não executa imediatamente.','Consulte GET /triggers/{id}/runs para localizar request_id de cada ocorrência.','Consulte /requests/{request_id} para a resposta, estado e créditos.','Cadastre um webhook do projeto para receber os avisos de conclusão.']},
    {kind:'note',title:'Cobrança automática',text:'Cada ocorrência é uma nova operação faturável e usa os créditos da conta. O agendamento não cria saldo. Uma chave revogada, acesso suspenso, ausência de preço ou saldo insuficiente impede o envio da nova execução. Repetições internas da mesma ocorrência preservam a identidade para evitar geração e débito duplicados.'},
    {kind:'text',text:'PATCH com enabled=false pausa; enabled=true agenda o próximo horário futuro. DELETE desativa e mantém o histórico. Horários perdidos durante indisponibilidade não são executados em massa depois. Uma ocorrência é ignorada se a anterior ainda estiver pendente, evitando sobreposição. Tarefas já enviadas precisam ser canceladas pela rota da Interação quando suportado.'},
    {kind:'text',text:'A precisão é de minutos e depende da fila. Não use para disparos com horário garantido. Para mudar instruções ou horário, pause a configuração anterior e crie outra; as execuções antigas permanecem vinculadas ao conteúdo original.'},
  ]},
  {id:'ia-estados-recuperacao',label:'Estados e recuperação',group:'Créditos e operação',title:'Trate cada estado sem duplicar chamadas',description:'Uma falha de conexão não significa que a execução foi cancelada.',blocks:[
    {kind:'table',title:'Estados',columns:['Estado','Significado','Ação'],rows:[['preparing / reserved','Preparação e autorização financeira.','Guarde o identificador; aguarde.'],['processing','Execução em andamento.','Consulte o mesmo recurso com intervalo.'],['active','Arquivo, coleção, ambiente ou cache utilizável.','Use conforme validade e modelo.'],['cancelling','Cancelamento solicitado.','Aguarde a conferência do consumo já realizado.'],['settling','Conferência e débito em andamento.','Aguarde; não dispare outra execução.'],['requires_action','Interação precisa do resultado de uma função.','Valide e execute no seu sistema; envie continuação.'],['completed','Operação concluída e liquidada.','Leia a resposta e os créditos; confira resultados parciais internos.'],['uncertain','Não foi possível confirmar resultado ou medição.','Consulte /requests/{request_id}; evite refazer.'],['failed','Falha confirmada.','Corrija a causa; uma nova operação exige nova identidade.'],['expired / deleted','Recurso encerrado.','Crie outro se precisar; o histórico de cobrança permanece.']]},
    {kind:'text',text:'Use a mesma Idempotency-Key e o mesmo corpo para recuperar uma execução. Se mudar o conteúdo com a mesma identidade, haverá conflito. A proteção é por projeto: duas operações de negócios diferentes precisam de identidades diferentes. Em operações administrativas como upload e cadastro de webhook, a criação gera outro recurso; confira a listagem antes de repetir.'},
    {kind:'table',title:'Diagnóstico',columns:['HTTP','Verifique'],rows:[['401','Chave ausente, errada ou revogada.'],['402','Saldo disponível e acesso da conta; reservas também ocupam saldo.'],['403','Projeto pausado ou recurso fora do acesso contratado.'],['404','ID e projeto da chave; outro projeto não pode acessar esse recurso.'],['409','Execução em andamento, recurso em uso ou conflito de identidade.'],['413','Tamanho do JSON ou da mídia; use /files quando apropriado.'],['422','Campos aceitos, modelo da chave e compatibilidade das ferramentas.'],['502 / 503','Registre request_id; consulte antes de repetir.']]},
  ]},
  {id:'ia-tempo-real-guia',label:'Integrar tempo real',group:'Tutoriais completos',title:'Do acesso descartável à sessão de voz',description:'Use um modelo Live liberado e um serviço WebSocket ativo. A chave permanente fica no backend.',blocks:[
    {kind:'steps',title:'Fluxo',items:['Seu backend chama POST /live com a chave permanente.','Envie ao frontend somente url, id, access_key e expires_at da sessão.','O frontend abre WebSocket e envia {id, access_key}. Esse acesso só pode ser usado uma vez e expira em 60 segundos.','Espere setupComplete antes de enviar clientContent, realtimeInput ou toolResponse.','Reproduza serverContent e trate interrupções. Ao finalizar, feche o socket.','O backend consulta /requests/{id} para confirmar consumo e encerramento.']},
    {kind:'code',title:'Frontend · sessão obtida do seu backend',language:'javascript',code:`export function connectSession(session) {
  const socket = new WebSocket(session.url);
  socket.addEventListener('open', () => socket.send(JSON.stringify({id: session.id, access_key: session.access_key})));
  socket.addEventListener('message', event => {
    const data = JSON.parse(event.data);
    if (data.setupComplete) socket.send(JSON.stringify({clientContent: {turns: [{role: 'user', parts: [{text: 'Olá, apresente-se em português.'}]}], turnComplete: true}}));
    if (data.serverContent) console.log(data.serverContent);
    if (data.toolCall) console.log('Valide a função no backend:', data.toolCall);
  });
  socket.addEventListener('close', () => console.log('Consulte o consumo da sessão no backend.'));
  return socket;
}`},
    {kind:'text',text:'O exemplo registra os eventos; a reprodução de áudio precisa decodificar o formato informado. Entrada contínua usa realtimeInput.audio com dados PCM e tipo MIME correto. Vídeo usa quadros de imagem. Não envie um arquivo MP3 como se fosse PCM.'},
    {kind:'note',title:'Saldo e reconexão',text:'O serviço acompanha e renova as reservas da sessão. Quando o saldo não cobre a continuidade, encerra a conexão. Uma conexão perdida não pode reutilizar o acesso descartável; confira a operação anterior antes de criar outra sessão. Música em tempo real tem eventos próprios e depende de liberação de acesso e preço.'},
  ]},
  {id:'ia-base-conhecimento',label:'Documentos do começo ao fim',group:'Tutoriais completos',title:'Monte uma base de conhecimento',description:'Upload, indexação e geração são operações distintas, todas isoladas por projeto.',blocks:[
    example('1. POST /files',{display_name:'politica.txt',mime_type:'text/plain',data:'VHJvY2FzIGVtIHNldGUgZGlhcy4='}),
    example('2. POST /stores',{display_name:'Políticas da empresa'}),
    example('3. POST /documents · substitua os IDs',{store:'00000000-0000-4000-8000-000000000001',file:'00000000-0000-4000-8000-000000000002'}),
    example('4. POST /interactions · depois da indexação',{input:'Qual é a política de trocas?',tools:[{type:'file_search',stores:['00000000-0000-4000-8000-000000000001']}]}),
    {kind:'text',text:'Aguarde /files/{id} ficar active antes de indexar. Aguarde /documents/{id} concluir antes de pesquisar. Guarde request_id da indexação e da geração: são dois consumos diferentes. Cada consulta posterior é outra geração. Excluir a coleção não estorna importações e consultas já realizadas.'},
  ]},
  {id:'ia-versoes',label:'Versões e compatibilidade',group:'Referência',title:'Evolução da API',description:'A versão da documentação identifica o contrato publicado. O caminho /api/v1/ai continua sendo a base de integração.',blocks:[
    {kind:'table',title:'Histórico',columns:['Versão','Mudança'],rows:[['1.5.0','Webhooks de solicitações e agendamentos com execução pela carteira. Referência por operação e exemplos completos.'],['1.4.0','Recursos multimodais, Interações, lotes, cache, ambientes e protocolo de tempo real.'],['1.3.x','Catálogo por modelo, funções, arquivos, vetores e ampliação da referência pública.']]},
    {kind:'text',text:'Para atualizar uma integração, baixe o novo OpenAPI, revise os campos usados e teste com dados do seu projeto. Preserve a chave no servidor e mantenha identidades de operações pendentes. Não troque de interface apenas alterando a URL: adapte messages, contents ou input e a leitura da resposta.'},
    {kind:'note',title:'Disponibilidade efetiva',text:'O catálogo pode listar modelos indisponíveis. available indica configuração operacional, não substitui testar sua tarefa. Acesso experimental, formatos de mídia e ferramentas variam por modelo. A documentação não garante recursos que o modelo selecionado não oferece.'},
  ]},
];
