const ref=(name:string)=>({$ref:`#/components/schemas/${name}`});
const content=(schema:object)=>({'application/json':{schema}});
const id={name:'id',in:'path',required:true,schema:{type:'string',format:'uuid'}};
const identity={name:'Idempotency-Key',in:'header',schema:{type:'string',maxLength:128},description:'Use a mesma identidade e corpo para recuperar a operação.'};
const errors={'401':{description:'Chave inválida'},'402':{description:'Acesso ou créditos indisponíveis'},'404':{description:'Recurso não pertence ao projeto'},'409':{description:'Operação pendente ou em uso'},'422':{description:'Modelo ou configuração incompatível'},'503':{description:'Serviço indisponível; consulte a solicitação antes de repetir'}};
const catalogs=[['caches','Cache','CacheRequest'],['batches','Lote','BatchRequest'],['videos','Vídeo','VideoRequest'],['stores','Coleção','StoreRequest'],['documents','Documento indexado','DocumentRequest'],['interactions','Interação','InteractionRequest'],['agents','Agente especializado','ManagedAgentRequest'],['environments','Ambiente','EnvironmentRequest']] as const;
export const resourceAiPaths={
  ...Object.fromEntries(catalogs.flatMap(([path,label,schema])=>[
    [`/${path}`,{
      post:{operationId:`createAi${schema}`,tags:['Recursos'],summary:`Criar ${label.toLowerCase()}`,description:'Recurso isolado por projeto. As execuções reservam créditos antes do envio e confirmam o consumo na conclusão. Consulte o estado retornado; não reenvie com outra identidade.',parameters:[identity],requestBody:{required:true,content:content(ref(schema))},responses:{'200':{description:'Recurso registrado; execução pode estar em andamento',content:content(ref('AiResource'))},...errors}},
      get:{operationId:`listAi${schema}`,tags:['Recursos'],summary:`Listar ${label.toLowerCase()}`,description:'Até 100 recursos recentes do projeto da chave.',responses:{'200':{description:'Recursos do projeto',content:content({type:'object',properties:{object:{const:'list'},data:{type:'array',items:ref('AiResource')}}})},...errors}},
    }],
    [`/${path}/{id}`,{
      ...(path==='caches'?{patch:{operationId:'updateAiCache',tags:['Recursos'],summary:'Alterar validade do cache',parameters:[id],requestBody:{required:true,content:content({type:'object',required:['ttl_seconds'],properties:{ttl_seconds:{type:'integer',minimum:1,maximum:604800}}})},responses:{'200':{description:'Validade atualizada com reserva de créditos',content:content(ref('AiResource'))},...errors}}}:{}),
      get:{operationId:`getAi${schema}`,tags:['Recursos'],summary:`Consultar ${label.toLowerCase()}`,parameters:[id],responses:{'200':{description:'Estado, resultado e créditos quando concluído',content:content(ref('AiResource'))},...errors}},
      delete:{operationId:`deleteAi${schema}`,tags:['Recursos'],summary:`Excluir ${label.toLowerCase()}`,description:'Cache é cobrado pelo período efetivamente armazenado. Excluir resultados concluídos não estorna o processamento já realizado. Cancele execuções ativas antes de excluir.',parameters:[id],responses:{'200':{description:'Recurso excluído',content:content(ref('AiResource'))},...errors}},
    }],
  ])),
  ...Object.fromEntries(['batches','interactions'].map(path=>[`/${path}/{id}/cancel`,{post:{operationId:`cancelAi${path}`,tags:['Recursos'],summary:'Solicitar cancelamento',description:'O consumo confirmado até o cancelamento permanece cobrado. Aguarde a situação final; o pedido não garante interrupção imediata.',parameters:[id],responses:{'200':{description:'Cancelamento solicitado',content:content(ref('AiResource'))},...errors}}}])),
  '/videos/{id}/content':{get:{operationId:'downloadAiVideo',tags:['Recursos'],summary:'Baixar vídeo concluído',parameters:[id,{name:'index',in:'query',schema:{type:'integer',minimum:0,default:0}}],responses:{'200':{description:'Arquivo MP4',content:{'video/mp4':{schema:{type:'string',format:'binary'}}}},...errors}}},
  '/interactions/{id}/content':{get:{operationId:'downloadAiInteractionMedia',tags:['Recursos'],summary:'Baixar mídia da interação',parameters:[id,{name:'index',in:'query',schema:{type:'integer',minimum:0}}],responses:{'200':{description:'Arquivo gerado',content:{'application/octet-stream':{schema:{type:'string',format:'binary'}}}},...errors}}},
  '/environments/{id}/files':{get:{operationId:'listAiEnvironmentFiles',tags:['Recursos'],summary:'Consultar ou baixar arquivos do ambiente',parameters:[id,{name:'path',in:'query',schema:{type:'string'},description:'Caminho relativo; vazio lista a raiz.'},{name:'download',in:'query',schema:{type:'boolean'}},{name:'recursive',in:'query',schema:{type:'boolean'}},{name:'cursor',in:'query',schema:{type:'string'}}],responses:{'200':{description:'Arquivos do ambiente ou download autenticado',content:{...content({type:'object'}),'application/octet-stream':{schema:{type:'string',format:'binary'}}}},...errors}}},
  '/live':{post:{operationId:'createAiLiveSession',tags:['Tempo real'],summary:'Abrir sessão em tempo real',description:'Retorna endereço WebSocket e acesso descartável válido por 60 segundos. Envie {id, access_key} como primeira mensagem. Aguarde setupComplete; então envie clientContent, realtimeInput ou toolResponse. Música aceita clientContent, musicGenerationConfig e playbackControl. O consumo é acompanhado pela carteira; novas execuções param se o saldo não puder cobrir a sessão.',parameters:[identity],requestBody:{required:true,content:content(ref('LiveRequest'))},responses:{'200':{description:'Sessão pronta para conexão',content:content({type:'object',properties:{id:{type:'string'},url:{type:'string'},access_key:{type:'string',description:'Acesso temporário exclusivo da sessão; não reutilize.'},expires_at:{type:'string',format:'date-time'}}})},...errors}}},
};
export const resourceAiSchemas={
  AiResource:{type:'object',properties:{id:{type:'string',format:'uuid'},object:{type:'string'},kind:{type:'string'},model:{type:'string'},status:{enum:['preparing','processing','active','cancelling','settling','completed','requires_action','failed','uncertain','deleted','expired']},request_id:{type:['string','null']},display_name:{type:'string'},created_at:{type:'string',format:'date-time'},expires_at:{type:['string','null'],format:'date-time'},result:{type:'object',description:'Resultado confirmado da operação, incluindo connectyhub.credits. Disponível após a conferência do consumo.'}}},
  CacheRequest:{type:'object',required:['contents'],properties:{model:{type:'string'},contents:ref('ContentRequestContents'),systemInstruction:{type:'object'},tools:{type:'array',items:{type:'object'}},ttl_seconds:{type:'number',minimum:1,maximum:604800,default:3600},display_name:{type:'string'}}},
  ContentRequestContents:{type:'array',minItems:1,items:{type:'object',required:['parts'],properties:{role:{enum:['user','model']},parts:{type:'array',items:ref('ContentPart')}}}},
  BatchRequest:{type:'object',required:['requests'],properties:{model:{type:'string'},display_name:{type:'string'},requests:{type:'array',minItems:1,maxItems:100,items:{type:'object',required:['request'],properties:{key:{type:'string'},request:{oneOf:[ref('ContentRequest'),ref('EmbeddingRequest')]}}}}}},
  VideoRequest:{type:'object',properties:{model:{type:'string'},prompt:{type:'string'},duration_seconds:{enum:[4,6,8],default:8},resolution:{enum:['720p','1080p','4k'],default:'720p'},aspect_ratio:{enum:['16:9','9:16']},image:{type:'object'},lastFrame:{type:'object'},referenceImages:{type:'array',items:{type:'object'}},video:{type:'string',description:'ID de um vídeo concluído deste projeto para extensão.'},negative_prompt:{type:'string'},seed:{type:'integer'},person_generation:{type:'string'}}},
  StoreRequest:{type:'object',properties:{display_name:{type:'string'}}},
  DocumentRequest:{type:'object',required:['store','file'],properties:{store:{type:'string'},file:{type:'string'},custom_metadata:{type:'array',items:{type:'object'}},chunking_config:{type:'object'}}},
  InteractionRequest:{type:'object',required:['input'],properties:{model:{type:'string'},input:{oneOf:[{type:'string'},{type:'array',items:{type:'object',description:'Partes text, image, audio, video ou resultados de funções; uri só aceita files/ID deste projeto.'}}]},system_instruction:{type:'string'},previous_interaction_id:{type:'string',format:'uuid'},agent_id:{type:'string',format:'uuid'},environment_id:{type:'string',format:'uuid'},response_format:{type:'object'},generation_config:{type:'object'},agent_config:{type:'object'},tools:{type:'array',items:{type:'object',required:['type'],properties:{type:{enum:['function','web_search','maps','code_execution','url_context','computer_use','file_search','mcp_server']},stores:{type:'array',items:{type:'string'}},name:{type:'string'},parameters:{type:'object'},latitude:{type:'number'},longitude:{type:'number'},url:{type:'string'}}}}}},
  ManagedAgentRequest:{type:'object',properties:{display_name:{type:'string'},system_instruction:{type:'string'},environment_id:{type:'string'},tools:{type:'array',items:{type:'object'}},network:{oneOf:[{type:'object'},{const:'disabled'}]},sources:{type:'array',items:ref('EnvironmentSource')}}},
  EnvironmentSource:{type:'object',required:['type','content','target'],properties:{type:{const:'inline'},content:{type:'string'},target:{type:'string'},encoding:{type:'string'}}},
  EnvironmentRequest:{type:'object',properties:{display_name:{type:'string'},network:{oneOf:[{type:'object'},{const:'disabled'}]},sources:{type:'array',items:ref('EnvironmentSource')}}},
  LiveRequest:{type:'object',properties:{model:{type:'string'},config:{type:'object',description:'Configuração fixa da sessão. generationConfig, systemInstruction, declarações de funções, entrada em tempo real e transcrições. O modelo vem da chave.'}}},
};
