import {studioPaths,studioSchemas,studioGuide} from './studio-openapi';
const json=(schema:object)=>({'application/json':{schema}});
const ref=(name:string)=>({$ref:`#/components/schemas/${name}`});
const id={name:'id',in:'path',required:true,schema:{type:'string'},description:'ID da solicitação ou ID da voz do catálogo, conforme a rota.'};
const idem={name:'Idempotency-Key',in:'header',required:true,schema:{type:'string',minLength:1,maxLength:128,pattern:'^[!-~]+$'}};
const errors=Object.fromEntries([401,402,403,404,409,413,422,429,502,503].map(status=>[status,{description:'Consulte error.code; não use nova chave automaticamente após resultado incerto.',content:json(ref('Error'))}]));
const ok=(schema:object)=>({'200':{description:'Resultado; confira status antes de considerar a operação concluída.',content:json(schema)},...errors});
export const voiceOpenApiSpec={openapi:'3.1.0',info:{title:'ConnectyHub Estúdio de Voz e Áudio AI',version:'1.1.0',description:'Voz por projeto, com carteira ConnectyHub. Chave dedicada; clones privados e recibos idempotentes. Não é um proxy irrestrito da API do fornecedor.'},servers:[{url:'https://www.connectyhub.com.br/api/v1/voice'}],security:[{VoiceKey:[]}],externalDocs:{url:'https://www.connectyhub.com.br/docs/api#voz'},paths:{
 '/models':{get:{operationId:'voiceModels',summary:'Modelos e tarifas disponíveis',responses:ok({type:'object',properties:{project_id:{type:'string'},billing_organization_id:{type:'string'},models:{type:'array',items:{type:'object',properties:{model_id:{type:'string'},name:{type:'string'},available:{type:'boolean'},reason:{type:'string'},credits_per_character:{type:'number'},minimum_credits:{type:'number'}}}}}})}},
 '/voices':{get:{operationId:'voiceCatalog',summary:'Vozes comuns autorizadas e clones privados deste projeto',responses:ok({type:'object',properties:{project_id:{type:'string'},billing_organization_id:{type:'string'},partial:{type:'boolean'},voices:{type:'array',items:ref('Voice')}}})},post:{operationId:'createVoiceClone',summary:'Clonar voz com consentimento, no projeto autenticado',parameters:[idem],requestBody:{required:true,content:{'multipart/form-data':{schema:{type:'object',required:['name','consent_accepted','files'],additionalProperties:false,properties:{name:{type:'string',minLength:2,maxLength:80},consent_accepted:{type:'string',const:'true'},remove_background_noise:{type:'string',enum:['true','false']},files:{type:'array',minItems:1,maxItems:5,items:{type:'string',format:'binary'},description:'Áudio; soma até 3 MB.'}}}}}},responses:ok(ref('CloneResult'))}},
 '/voices/{id}':{get:{operationId:'getPrivateVoice',summary:'Consultar clone do próprio projeto',parameters:[id],responses:ok({type:'object',properties:{clone:ref('Clone')}})},patch:{operationId:'renamePrivateVoice',summary:'Renomear clone próprio',parameters:[id],requestBody:{required:true,content:json({type:'object',required:['name'],additionalProperties:false,properties:{name:{type:'string',minLength:2,maxLength:80}}})},responses:ok({type:'object',properties:{clone:ref('Clone')}})},delete:{operationId:'deletePrivateVoice',summary:'Excluir clone próprio; áudios históricos permanecem privados',parameters:[id],responses:ok({type:'object',properties:{deleted:{type:'boolean'}}})}},
 '/voices/{id}/samples':{get:{operationId:'listPrivateVoiceSamples',summary:'Listar amostras do clone próprio',parameters:[id],responses:ok({type:'object',properties:{samples:{type:'array',items:{type:'object',properties:{id:{type:'string'},name:{type:'string'},content_type:{type:'string'}}}}}})}},
 '/voices/{id}/samples/{sample_id}/audio':{get:{operationId:'downloadPrivateVoiceSample',summary:'Áudio da amostra, com autenticação',parameters:[id,{name:'sample_id',in:'path',required:true,schema:{type:'string'}}],responses:{200:{description:'Áudio privado',content:{'audio/mpeg':{schema:{type:'string',format:'binary'}}}},...errors}}},
 '/voices/{id}/preview':{post:{operationId:'previewPrivateVoice',summary:'Uma prévia incluída por clone; repetições recuperam o mesmo recibo',parameters:[id],responses:ok(ref('Generation'))}},
 '/generations':{post:{operationId:'generateVoice',summary:'Gerar ou recuperar áudio com a mesma chave e corpo',parameters:[idem],requestBody:{required:true,content:json(ref('VoiceInput'))},responses:{...ok(ref('Generation')),202:{description:'Reservada, processando ou incerta; consulte/reenvie a mesma chave.',content:json(ref('Generation'))}}},get:{operationId:'listVoiceGenerations',summary:'Últimas 50 solicitações deste projeto',responses:ok({type:'object',properties:{project_id:{type:'string'},billing_organization_id:{type:'string'},generations:{type:'array',items:ref('Generation')},limit:{type:'integer'}}})}},
 '/generations/{id}':{get:{operationId:'getVoiceGeneration',summary:'Consultar recibo e recuperar áudio conhecido, sem nova síntese',parameters:[id],responses:ok(ref('Generation'))}},
 '/generations/{id}/audio':{get:{operationId:'downloadVoiceAudio',summary:'Baixar MP3 privado após liquidação concluída',parameters:[id],responses:{200:{description:'MP3 autenticado, sem cache público',content:{'audio/mpeg':{schema:{type:'string',format:'binary'}}}},...errors}}},
 ...studioPaths,
},components:{securitySchemes:{VoiceKey:{type:'http',scheme:'bearer',bearerFormat:'ch_voice_…'}},schemas:{
 ...studioSchemas,
 Error:{type:'object',properties:{error:{type:'object',required:['code','message'],properties:{code:{type:'string'},message:{type:'string'},request_id:{type:'string'}}}}},
 VoiceInput:{type:'object',additionalProperties:false,required:['text','voice_id'],properties:{dictionary_ids:{type:'array',maxItems:3,uniqueItems:true,items:{type:'string',format:'uuid'}},text:{type:'string',minLength:1,maxLength:4800,description:'Espaços normalizados antes da medição.'},voice_id:{type:'string'},model_id:{type:'string',description:'Opcional. Consulte GET /models para obter os identificadores compatíveis.'},voice_settings:{type:'object',additionalProperties:false,properties:{stability:{type:'number',minimum:0,maximum:1,default:.48},similarity_boost:{type:'number',minimum:0,maximum:1,default:.78},style:{type:'number',minimum:0,maximum:1,default:.22},use_speaker_boost:{type:'boolean',default:true}}}}},
 Voice:{type:'object',properties:{voice_id:{type:'string'},name:{type:'string'},kind:{type:'string',enum:['common','private','designed']},status:{type:'string'},preview_url:{type:['string','null']},language:{type:['string','null']}}},
 Clone:{type:'object',properties:{id:{type:'string'},voice_id:{type:['string','null']},project_id:{type:'string'},generation_id:{type:'string'},name:{type:'string'},status:{type:'string',enum:['creating','ready','verification_required','uncertain','deleting','deleted','failed']},kind:{type:'string',const:'private'}}},
 CloneResult:{type:'object',properties:{clone:ref('Clone'),generation:ref('Generation'),billing_organization_id:{type:'string'},replayed:{type:'boolean'}}},
 Generation:{type:'object',required:['id','project_id','billing_organization_id','status','usage'],properties:{id:{type:'string',format:'uuid'},project_id:{type:'string',format:'uuid'},billing_organization_id:{type:'string',format:'uuid'},operation:{type:'string',enum:['text_to_speech','voice_clone','voice_clone_preview']},status:{type:'string',enum:['reserved','processing','uncertain','completed','failed']},voice_id:{type:'string'},model_id:{type:'string'},usage:{type:'object',properties:{characters:{type:'integer'},credits:{type:'number'},reserved_credits:{type:'number'},quoted_credits:{type:'number'}}},audio:{type:['object','null'],properties:{path:{type:'string'},content_type:{type:'string',const:'audio/mpeg'},bytes:{type:'integer'}}},error:{type:['object','null'],properties:{code:{type:'string'}}},replayed:{type:'boolean'},created_at:{type:'string',format:'date-time'}}},
}}};
export const voiceGuide=`# ConnectyHub Estúdio de Voz e Áudio AI

Base: https://www.connectyhub.com.br/api/v1/voice
Crie um projeto e uma chave em /dashboard/voz → Projetos e chaves API. O acesso exige conta ativa e saldo disponível para a operação; nenhum agente é obrigatório. Use Authorization: Bearer CHAVE_DE_VOZ. Não use chave WhatsApp, LLM ou do fornecedor.

## Propriedade
Cada chave pertence a um projeto. Trocar/revogar a chave não transfere os clones ou áudios para outro projeto. Confira project_id e billing_organization_id no catálogo e nos recibos. Todo ID direto passa pela mesma autorização; não envie organizationId no payload. Clones do projeto A não são visíveis ou utilizáveis no projeto B, mesmo na mesma conta. Vozes comuns são um catálogo autorizado separado. Apenas prévias públicas de vozes comuns têm URL pública; amostras, clones e áudios privados exigem autenticação.

## Texto para áudio
Consulte GET /models e GET /voices. POST /generations aceita text, voice_id, model_id opcional e voice_settings opcional (stability, similarity_boost, style:0–1; use_speaker_boost:boolean). Saída MP3 44,1 kHz / 128 kbps. Limite de 4.800 caracteres após normalização de espaços; 12 MB por áudio. Modelo indisponível não é substituído silenciosamente.

## Idempotência e recuperação
Envie Idempotency-Key ASCII de 1 a 128 caracteres. Mesma chave+mesmo corpo normalizado recuperam o mesmo recibo, inclusive após timeout sem ID. Corpo diferente:409. reserved/processing/uncertain não significam entrega concluída. GET /generations/{id} consulta e recupera mídia conhecida após 2 minutos, sem outra síntese. Sem recibo do fornecedor suficiente, uncertain conserva reserva e requer conciliação; não envie outra chave automaticamente. failed é terminal. completed comprova áudio persistido e liquidação. GET /generations/{id}/audio baixa o MP3 autenticado. A chave não vai na URL.

## Clonagem privada
POST /voices usa multipart/form-data: name(2–80), consent_accepted=true, files(1–5 arquivos de áudio, até 3 MB somados), remove_background_noise opcional. Idempotency-Key também obrigatório. Só envie voz sobre a qual tenha direitos e consentimento. O recibo liga clone.id/voice_id/generation_id ao projeto autenticado. verification_required depende de verificação no fornecedor antes do uso; não representa clone pronto. GET /voices/{id}, PATCH com{name}, DELETE gerenciam apenas clone próprio. GET /voices/{id}/samples e /voices/{id}/samples/{sample_id}/audio protegem todas as amostras. POST /voices/{id}/preview gera uma única prévia incluída; repetições recuperam o mesmo áudio, sem segundo débito ao cliente. Exclusão impede novas gerações com o clone; áudios já criados continuam privados no histórico.

## Créditos e limites
Tarifas são as mesmas do painel para a operação equivalente: criação de clone usa voice_clone; prévia incluída tem custo absorvido; geração avulsa usa text_to_speech. Não confundir com tarifa voice_reply_whatsapp. Mínimos e plano são aplicados pelo resolvedor existente. Uma tarifa 0 explicitamente cadastrada para clonagem é respeitada; tarifa ausente/inativa bloqueia. Cada operação reserva antes do fornecedor e liquida uma vez. Falha definitiva libera reserva; resultado incerto aguarda recuperação. 10 novas operações/minuto/carteira, 2 em andamento/carteira e limite mensal opcional por projeto. URLs e recibos não prometem retenção eterna; exporte áudios necessários.

## Erros
JSON error.code/message/request_id.401 chave;402 saldo;403 acesso;404 recurso ausente/privado;409 conflito/pendente;413 tamanho;422 parâmetros;429 capacidade;502 fornecedor;503 serviço/tarifa/conciliação. Nunca trate um HTTP 200 com status failed/uncertain como sucesso.

## Cobertura
Esta versão entrega catálogo autorizado, clonagem instantânea privada, gestão/amostras/prévia, TTS, recuperação/download e uso. Não oferece proxy irrestrito do fornecedor. Transcrição, limpeza, troca de voz, diálogo, desenho de voz, dicionários, dublagem, alinhamento e voz nativa têm contratos abaixo e ativação individual consultável em GET /capabilities. Música, efeitos sonoros, clonagem profissional e agentes de voz em tempo real não fazem parte deste contrato. A presença de uma rota documentada não comprova que a modalidade esteja habilitada para o projeto.
`+studioGuide;
