import {studioPaths,studioSchemas,studioGuide} from './studio-openapi';
const json=(schema:object)=>({'application/json':{schema}});
const ref=(name:string)=>({$ref:`#/components/schemas/${name}`});
const id={name:'id',in:'path',required:true,schema:{type:'string'},description:'ID da solicitação ou ID da voz do catálogo, conforme a rota.'};
const idem={name:'Idempotency-Key',in:'header',required:true,schema:{type:'string',minLength:1,maxLength:128,pattern:'^[!-~]+$'}};
const errors=Object.fromEntries([401,402,403,404,409,413,422,429,502,503].map(status=>[status,{description:'Consulte error.code; não use nova chave automaticamente após resultado incerto.',content:json(ref('Error'))}]));
const ok=(schema:object)=>({'200':{description:'Resultado; confira status antes de considerar a operação concluída.',content:json(schema)},...errors});
export const voiceOpenApiSpec={openapi:'3.1.0',info:{title:'ConnectyHub Estúdio de Voz e Áudio AI',version:'1.2.0',description:'Voz por projeto, com carteira ConnectyHub. Chave dedicada; clones privados e recibos idempotentes. Não é um proxy irrestrito da API do fornecedor.'},servers:[{url:'https://www.connectyhub.com.br/api/v1/voice'}],security:[{VoiceKey:[]}],externalDocs:{url:'https://www.connectyhub.com.br/docs/api#voz'},paths:{
 '/models':{get:{operationId:'voiceModels',summary:'Modelos e tarifas disponíveis',responses:ok({type:'object',properties:{project_id:{type:'string'},billing_organization_id:{type:'string'},models:{type:'array',items:{type:'object',properties:{model_id:{type:'string'},name:{type:'string'},available:{type:'boolean'},reason:{type:'string'},credits_per_character:{type:'number'},minimum_credits:{type:'number'}}}}}})}},
 '/voices':{get:{operationId:'voiceCatalog',summary:'Vozes comuns autorizadas e clones privados deste projeto',responses:ok({type:'object',properties:{project_id:{type:'string'},billing_organization_id:{type:'string'},partial:{type:'boolean'},voices:{type:'array',items:ref('Voice')}}})},post:{operationId:'createVoiceClone',summary:'Clonar voz com consentimento, no projeto autenticado',parameters:[idem],requestBody:{required:true,content:{'multipart/form-data':{schema:{type:'object',required:['name','consent_accepted','files'],additionalProperties:false,properties:{name:{type:'string',minLength:2,maxLength:80},consent_accepted:{type:'string',const:'true'},remove_background_noise:{type:'string',enum:['true','false']},files:{type:'array',minItems:1,maxItems:5,items:{type:'string',format:'binary'},description:'Áudio; soma até 3 MB.'}}}}}},responses:ok(ref('CloneResult'))}},
 '/voices/{id}':{get:{operationId:'getPrivateVoice',summary:'Consultar clone do próprio projeto',parameters:[id],responses:ok({type:'object',properties:{clone:ref('Clone')}})},patch:{operationId:'renamePrivateVoice',summary:'Renomear clone próprio',parameters:[id],requestBody:{required:true,content:json({type:'object',required:['name'],additionalProperties:false,properties:{name:{type:'string',minLength:2,maxLength:80}}})},responses:ok({type:'object',properties:{clone:ref('Clone')}})},delete:{operationId:'deletePrivateVoice',summary:'Excluir clone próprio; áudios históricos permanecem privados',parameters:[id],responses:ok({type:'object',properties:{deleted:{type:'boolean'}}})}},
 '/voices/{id}/samples':{get:{operationId:'listPrivateVoiceSamples',summary:'Listar amostras do clone próprio',parameters:[id],responses:ok({type:'object',properties:{samples:{type:'array',items:{type:'object',properties:{id:{type:'string'},name:{type:'string'},content_type:{type:'string'}}}}}})}},
 '/voices/{id}/samples/{sample_id}/audio':{get:{operationId:'downloadPrivateVoiceSample',summary:'Áudio da amostra, com autenticação',parameters:[id,{name:'sample_id',in:'path',required:true,schema:{type:'string'}}],responses:{200:{description:'Áudio privado',content:{'audio/mpeg':{schema:{type:'string',format:'binary'}}}},...errors}}},
 '/voices/{id}/preview':{post:{operationId:'previewPrivateVoice',summary:'Uma prévia incluída por clone; repetições recuperam o mesmo recibo',parameters:[id],responses:ok(ref('Generation'))}},
 '/generations':{post:{operationId:'generateVoice',summary:'Gerar ou recuperar áudio com a mesma chave e corpo',parameters:[idem],requestBody:{required:true,content:json(ref('VoiceInput'))},responses:{...ok(ref('Generation')),202:{description:'Reservada, processando ou incerta; consulte/reenvie a mesma chave.',content:json(ref('Generation'))}}},get:{operationId:'listVoiceGenerations',summary:'Últimas 50 solicitações deste projeto',responses:ok({type:'object',properties:{project_id:{type:'string'},billing_organization_id:{type:'string'},generations:{type:'array',items:ref('Generation')},limit:{type:'integer'}}})}},
 '/generations/stream':{post:{operationId:'streamVoice',summary:'Gerar em streaming: o áudio chega enquanto é produzido; reserva, persistência e débito como em /generations',parameters:[idem],requestBody:{required:true,content:json(ref('VoiceInput'))},responses:{200:{description:'Áudio em pedaços no formato pedido. X-Generation-Id identifica o recibo; X-Replayed=true quando a mesma chave já foi concluída.',content:{'audio/mpeg':{schema:{type:'string',format:'binary'}},'audio/pcm':{schema:{type:'string',format:'binary'}},'audio/basic':{schema:{type:'string',format:'binary'}},'audio/ogg':{schema:{type:'string',format:'binary'}}}},...errors}}},
 '/generations/{id}/alignment':{get:{operationId:'downloadVoiceAlignment',summary:'Marcação de tempo por caractere (gerações com with_timestamps)',parameters:[id],responses:ok({type:'object',properties:{alignment:{type:['object','null']},normalized_alignment:{type:['object','null']}}})}},
 '/usage':{get:{operationId:'voiceUsage',summary:'Uso do projeto e saldo disponível da carteira',parameters:[{name:'days',in:'query',schema:{type:'integer',minimum:1,maximum:90,default:30}}],responses:ok({type:'object',properties:{project_id:{type:'string'},days:{type:'integer'},usage:{type:'object'},wallet:{type:'object',properties:{balance_credits:{type:'number'},reserved_credits:{type:'number'},available_credits:{type:'number'}}},monthly_credit_limit:{type:['number','null']}}})}},
 '/generations/{id}':{get:{operationId:'getVoiceGeneration',summary:'Consultar recibo e recuperar áudio conhecido, sem nova síntese',parameters:[id],responses:ok(ref('Generation'))}},
 '/generations/{id}/audio':{get:{operationId:'downloadVoiceAudio',summary:'Baixar o áudio privado após liquidação concluída, no formato pedido',parameters:[id],responses:{200:{description:'Áudio autenticado, sem cache público',content:{'audio/mpeg':{schema:{type:'string',format:'binary'}},'audio/pcm':{schema:{type:'string',format:'binary'}},'audio/basic':{schema:{type:'string',format:'binary'}},'audio/ogg':{schema:{type:'string',format:'binary'}}}},...errors}}},
 ...studioPaths,
},components:{securitySchemes:{VoiceKey:{type:'http',scheme:'bearer',bearerFormat:'ch_voice_…'}},schemas:{
 ...studioSchemas,
 Error:{type:'object',properties:{error:{type:'object',required:['code','message'],properties:{code:{type:'string'},message:{type:'string'},request_id:{type:'string'}}}}},
 VoiceInput:{type:'object',additionalProperties:false,required:['text','voice_id'],properties:{dictionary_ids:{type:'array',maxItems:3,uniqueItems:true,items:{type:'string',format:'uuid'}},text:{type:'string',minLength:1,maxLength:4800,description:'Espaços normalizados antes da medição.'},voice_id:{type:'string'},model_id:{type:'string',description:'Opcional. Consulte GET /models para obter os identificadores compatíveis.'},voice_settings:{type:'object',additionalProperties:false,properties:{stability:{type:'number',minimum:0,maximum:1,default:.48},similarity_boost:{type:'number',minimum:0,maximum:1,default:.78},style:{type:'number',minimum:0,maximum:1,default:.22},use_speaker_boost:{type:'boolean',default:true},speed:{type:'number',minimum:0.7,maximum:1.2}}},language_code:{type:'string',pattern:'^[a-z]{2,3}$'},output_format:{type:'string',enum:['mp3_44100_128','mp3_44100_64','mp3_22050_32','pcm_16000','pcm_22050','pcm_24000','ulaw_8000','opus_48000_64'],default:'mp3_44100_128',description:'ulaw_8000 é o formato de telefonia; pcm é áudio bruto 16 bits.'},with_timestamps:{type:'boolean',description:'Somente em POST /generations: grava a marcação de tempo por caractere.'},seed:{type:'integer',minimum:0,maximum:4294967295,description:'Repete o mesmo resultado quando possível.'},previous_text:{type:'string',maxLength:1000,description:'Texto anterior, para continuidade entre trechos.'},next_text:{type:'string',maxLength:1000},apply_text_normalization:{type:'string',enum:['auto','on','off']}}},
 Voice:{type:'object',properties:{voice_id:{type:'string'},name:{type:'string'},kind:{type:'string',enum:['common','private','designed']},status:{type:'string'},preview_url:{type:['string','null']},language:{type:['string','null']},gender:{type:['string','null']},accent:{type:['string','null']},use_case:{type:['string','null']}}},
 Clone:{type:'object',properties:{id:{type:'string'},voice_id:{type:['string','null']},project_id:{type:'string'},generation_id:{type:'string'},name:{type:'string'},status:{type:'string',enum:['creating','ready','verification_required','uncertain','deleting','deleted','failed']},kind:{type:'string',const:'private'}}},
 CloneResult:{type:'object',properties:{clone:ref('Clone'),generation:ref('Generation'),billing_organization_id:{type:'string'},replayed:{type:'boolean'}}},
 Generation:{type:'object',required:['id','project_id','billing_organization_id','status','usage'],properties:{id:{type:'string',format:'uuid'},project_id:{type:'string',format:'uuid'},billing_organization_id:{type:'string',format:'uuid'},operation:{type:'string',enum:['text_to_speech','voice_clone','voice_clone_preview']},status:{type:'string',enum:['reserved','processing','uncertain','completed','failed']},voice_id:{type:'string'},model_id:{type:'string'},usage:{type:'object',properties:{characters:{type:'integer'},credits:{type:'number'},reserved_credits:{type:'number'},quoted_credits:{type:'number'}}},audio:{type:['object','null'],properties:{path:{type:'string'},content_type:{type:'string'},output_format:{type:'string'},bytes:{type:'integer'}}},alignment:{type:['object','null'],properties:{path:{type:'string'}}},error:{type:['object','null'],properties:{code:{type:'string'}}},replayed:{type:'boolean'},created_at:{type:'string',format:'date-time'}}},
}}};
export const voiceGuide=`# ConnectyHub Estúdio de Voz e Áudio AI

Base: https://www.connectyhub.com.br/api/v1/voice
Crie um projeto e uma chave em /dashboard/voz → Projetos e chaves API. O acesso exige conta ativa e saldo disponível para a operação; nenhum agente é obrigatório. Use Authorization: Bearer CHAVE_DE_VOZ. Não use chave WhatsApp, LLM ou do fornecedor.

## Propriedade
Cada chave pertence a um projeto. Trocar/revogar a chave não transfere os clones ou áudios para outro projeto. Confira project_id e billing_organization_id no catálogo e nos recibos. Todo ID direto passa pela mesma autorização; não envie organizationId no payload. Clones do projeto A não são visíveis ou utilizáveis no projeto B, mesmo na mesma conta. Vozes comuns são um catálogo autorizado separado. Apenas prévias públicas de vozes comuns têm URL pública; amostras, clones e áudios privados exigem autenticação.

## Texto para áudio
Consulte GET /models e GET /voices. Os modelos são eleven_multilingual_v2, eleven_v3, eleven_flash_v2_5 e eleven_turbo_v2_5, cada um com seu preço por caractere em GET /models. POST /generations aceita text, voice_id, model_id opcional, voice_settings opcional (stability, similarity_boost, style: 0–1; speed: 0,7–1,2; use_speaker_boost), language_code (pt, en...), output_format (mp3_44100_128 padrão, mp3_44100_64, mp3_22050_32, pcm_16000/22050/24000, ulaw_8000 para telefonia, opus_48000_64), seed, previous_text/next_text (continuidade entre trechos) e apply_text_normalization (auto, on, off). Limite de 4.800 caracteres por geração após normalização de espaços e 40 MB por áudio; textos maiores usam operation=long_tts em /operations. Modelo indisponível não é substituído silenciosamente.

## Streaming
POST /generations/stream recebe o mesmo corpo e Idempotency-Key e devolve o áudio em pedaços enquanto é produzido, ideal para atendimento e telefonia (use ulaw_8000). O cabeçalho X-Generation-Id traz o recibo. A reserva acontece antes, o áudio completo é guardado e o débito é único ao final, mesmo se a conexão cair. Repetir a mesma chave depois de concluído devolve o áudio guardado (X-Replayed: true). with_timestamps não se aplica ao streaming.

## Marcação de tempo
with_timestamps: true em POST /generations grava o alinhamento por caractere. GET /generations/{id}/alignment devolve alignment e normalized_alignment (caracteres, início e fim em segundos), útil para legendas e animação de boca. Sem custo adicional além da geração.

## Uso e saldo
GET /usage?days=30 devolve o uso do projeto (por dia, modelo, voz e operação) e o saldo disponível da carteira (available_credits), para acompanhar o gasto antes de enviar trabalhos grandes.

## Webhooks
Configure em /dashboard/voz → Projetos e chaves API → Ferramentas de desenvolvedor. Quando uma operação assíncrona (/operations: e-book, dublagem, transcrição...) termina, enviamos POST JSON com type voice.operation.completed ou voice.operation.failed e data (id, status, usage, result.path). Cabeçalho ConnectyHub-Signature: t=<segundos>,v1=<HMAC-SHA256 hex de "t.corpo" com o segredo do projeto>. Recuse eventos com t muito antigo. Responda 2xx; falhas são repetidas até 5 vezes com intervalo crescente. Somente URLs https públicas.

## Idempotência e recuperação
Envie Idempotency-Key ASCII de 1 a 128 caracteres. Mesma chave+mesmo corpo normalizado recuperam o mesmo recibo, inclusive após timeout sem ID. Corpo diferente:409. reserved/processing/uncertain não significam entrega concluída. GET /generations/{id} consulta e recupera mídia conhecida após 2 minutos, sem outra síntese. Sem recibo do fornecedor suficiente, uncertain conserva reserva e requer conciliação; não envie outra chave automaticamente. failed é terminal. completed comprova áudio persistido e liquidação. GET /generations/{id}/audio baixa o MP3 autenticado. A chave não vai na URL.

## Clonagem privada
POST /voices usa multipart/form-data: name(2–80), consent_accepted=true, files(1–5 arquivos de áudio, até 3 MB somados), remove_background_noise opcional. Idempotency-Key também obrigatório. Só envie voz sobre a qual tenha direitos e consentimento. O recibo liga clone.id/voice_id/generation_id ao projeto autenticado. verification_required depende de verificação no fornecedor antes do uso; não representa clone pronto. GET /voices/{id}, PATCH com{name}, DELETE gerenciam apenas clone próprio. GET /voices/{id}/samples e /voices/{id}/samples/{sample_id}/audio protegem todas as amostras. POST /voices/{id}/preview gera uma única prévia incluída; repetições recuperam o mesmo áudio, sem segundo débito ao cliente. Exclusão impede novas gerações com o clone; áudios já criados continuam privados no histórico.

## Créditos e limites
Tarifas são as mesmas do painel para a operação equivalente: criação de clone usa voice_clone; prévia incluída tem custo absorvido; geração avulsa usa text_to_speech. Não confundir com tarifa voice_reply_whatsapp. Mínimos e plano são aplicados pelo resolvedor existente. Uma tarifa 0 explicitamente cadastrada para clonagem é respeitada; tarifa ausente/inativa bloqueia. Cada operação reserva antes do fornecedor e liquida uma vez. Falha definitiva libera reserva; resultado incerto aguarda recuperação. 10 novas operações/minuto/carteira, 2 em andamento/carteira e limite mensal opcional por projeto. URLs e recibos não prometem retenção eterna; exporte áudios necessários.

## Erros
JSON error.code/message/request_id.401 chave;402 saldo;403 acesso;404 recurso ausente/privado;409 conflito/pendente;413 tamanho;422 parâmetros;429 capacidade;502 fornecedor;503 serviço/tarifa/conciliação. Nunca trate um HTTP 200 com status failed/uncertain como sucesso.

## Cobertura
Esta versão entrega catálogo autorizado, clonagem instantânea privada, gestão/amostras/prévia, TTS, recuperação/download e uso. Não oferece proxy irrestrito do fornecedor. Transcrição, limpeza, troca de voz, diálogo, desenho de voz, dicionários, dublagem, alinhamento e voz nativa têm contratos abaixo e ativação individual consultável em GET /capabilities. Consulte GET /capabilities para as modalidades disponíveis. A presença de uma rota documentada não comprova que a modalidade esteja habilitada para o projeto.
`+studioGuide;
