import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, Check, Code2, Layers3, MessageCircle, Network, PanelTop, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { PublicSiteHeader } from "@/components/seo/public-site-header";
import { ConnectyLogo } from "@/components/brand/connecty-logo";
import { JsonLd } from "@/components/seo/json-ld";
import { buildCanonicalUrl } from "@/lib/seo/site";
import styles from "./solutions.module.css";
const title="Software sob medida para sua empresa | ConnectyHub";
const description="Transforme sua ideia em uma plataforma, aplicativo ou sistema personalizado. Conheça o desenvolvimento de software ConnectyHub e agende uma reunião.";
export const metadata:Metadata={title,description,alternates:{canonical:"/solucoes-personalizadas"},openGraph:{title,description,url:"/solucoes-personalizadas",locale:"pt_BR",type:"website",images:["/opengraph-image"]},twitter:{card:"summary_large_image",title,description,images:["/opengraph-image"]},robots:{index:true,follow:true}};
const possibilities=[
  {icon:PanelTop,title:"Plataformas SaaS",text:"Transforme sua solução em um produto digital com contas, permissões, assinaturas e uma experiência própria."},
  {icon:Workflow,title:"Sistemas para sua operação",text:"Organize processos, equipes, documentos e decisões em um sistema que acompanha a forma como sua empresa trabalha."},
  {icon:Network,title:"Marketplaces e portais",text:"Conecte pessoas, serviços e oportunidades. Catálogos, reservas, áreas de membros e jornadas de compra integradas."},
  {icon:MessageCircle,title:"CRM e relacionamento",text:"Dê continuidade a cada conversa, da primeira mensagem ao acompanhamento do cliente, com contexto em cada etapa."},
  {icon:Sparkles,title:"Inteligência artificial",text:"Leitura de documentos, análise de conteúdo, assistentes e automações para ajudar sua equipe no trabalho do dia a dia."},
  {icon:Layers3,title:"Aplicativos e integrações",text:"Experiências para celular e conexões entre seus sistemas, canais de atendimento e ferramentas de gestão."},
];
const faq=[
  ["Minha ideia precisa estar pronta?","Não. Você pode começar com um problema, um processo que precisa melhorar ou uma ideia de produto. Na reunião, entendemos o objetivo e organizamos as possibilidades."],
  ["Vocês desenvolvem para qual tipo de negócio?","Trabalhamos com software sob medida para diferentes setores. Podemos construir plataformas, aplicativos, sistemas internos, portais e soluções com IA. O escopo e a viabilidade da sua ideia são definidos em conjunto."],
  ["Pode funcionar no celular e no computador?","Sim. Planejamos a experiência para os dispositivos que fazem parte da sua operação. A definição entre aplicação web responsiva, aplicativo e outras interfaces depende da jornada do projeto."],
  ["Consigo conectar ferramentas que já utilizo?","Avaliamos as integrações necessárias e as APIs disponíveis em cada ferramenta. Na descoberta, identificamos o que pode ser conectado e o que precisa ser desenvolvido."],
  ["Como começa o desenvolvimento?","Começa com uma conversa para entender sua empresa e sua ideia. Depois, definimos escopo, prioridades e a forma de validar as primeiras entregas. As etapas de implantação e evolução fazem parte desse planejamento."],
  ["Como agendo uma reunião?","Clique em Agendar uma reunião para conversar com a equipe no WhatsApp. Nossa agente aproveita as informações que você já compartilhou, entende brevemente a ideia e ajuda a encontrar um horário."],
];
import { MeetingLink } from "@/components/seo/meeting-link";
export default function Page(){return <div className={styles.page}>
  <PublicSiteHeader active="custom"/>
  <JsonLd id="custom-software-service" data={{"@context":"https://schema.org","@graph":[{"@type":"Service","@id":buildCanonicalUrl("/solucoes-personalizadas#servico"),name:"Desenvolvimento de software sob medida",description,serviceType:"Desenvolvimento de plataformas, aplicativos e sistemas personalizados",provider:{"@type":"Organization",name:"ConnectyHub",url:buildCanonicalUrl("/")},url:buildCanonicalUrl("/solucoes-personalizadas"),areaServed:{"@type":"Country",name:"Brasil"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"ConnectyHub",item:buildCanonicalUrl("/")},{"@type":"ListItem",position:2,name:"Soluções personalizadas",item:buildCanonicalUrl("/solucoes-personalizadas")}]}]}}/>
  <main>
    <section className={styles.hero}>
      <div className={styles.heroCopy}><p className={styles.eyebrow}><span/>Tecnologia com a sua assinatura</p><h1>Sua próxima<br/>grande ideia.<br/><em>Seu próprio software.</em></h1><p className={styles.intro}>Construímos plataformas, aplicativos e sistemas sob medida para transformar a maneira como seu negócio funciona.</p><div className={styles.actions}><MeetingLink className={styles.primary}>Agendar uma reunião<ArrowRight size={18}/></MeetingLink><a href="#possibilidades" className={styles.secondary}>Conheça as possibilidades<ArrowDown size={16}/></a></div><p className={styles.micro}><Check size={14}/>Da primeira conversa à evolução do produto.</p></div>
      <div className={styles.productScene} aria-label="Ilustração de uma plataforma personalizada">
        <div className={styles.orbit}/><div className={styles.productWindow}><div className={styles.windowBar}><span className={styles.dots}>● ● ●</span><span>O SEU PRÓXIMO PRODUTO</span><Code2 size={14}/></div><div className={styles.windowBody}><aside className={styles.mockSidebar}><div className={styles.mockLogo}><Layers3 size={19}/></div><PanelTop size={17}/><Workflow size={17}/><Network size={17}/><MessageCircle size={17}/></aside><div className={styles.mockContent}><div className={styles.mockTitle}><div><small>SUA OPERAÇÃO, CONECTADA</small><h2>Tudo faz parte.</h2></div><span className={styles.liveDot}/></div><div className={styles.mockTiles}><div><Workflow size={18}/><span>Processos</span><strong>Mais simples</strong></div><div><Sparkles size={18}/><span>Inteligência</span><strong>No dia a dia</strong></div></div><div className={styles.flow}><p>Uma jornada. Várias conexões.</p><div className={styles.flowSteps}><span>Ideia</span><ArrowRight size={14}/><span>Produto</span><ArrowRight size={14}/><span>Operação</span></div><div className={styles.flowBars}><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div className={styles.mockFooter}><ShieldCheck size={16}/>Projetado para o seu negócio<span>↗</span></div></div></div></div><div className={styles.floatingCard}><span><Sparkles size={20}/></span><div><strong>Uma nova possibilidade</strong><p>Sua ideia encontra a tecnologia.</p></div></div><p className={styles.illustrationLabel}>Interface ilustrativa · cada projeto tem sua identidade</p>
      </div>
    </section>
    <section className={styles.statement}><p>Sua empresa tem um jeito de funcionar.<br/><strong>Seu software também pode ter.</strong></p><span>Mais clareza para operar.<br/>Mais espaço para criar.</span></section>
    <section className={styles.section} id="possibilidades"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>O que podemos construir</p><h2>Imagine o que<br/><em>pode ser diferente.</em></h2></div><p>Um produto para seus clientes. Uma ferramenta para sua equipe. Uma nova forma de conectar tudo. Estas são algumas possibilidades para começar a conversa.</p></div><div className={styles.possibilities}>{possibilities.map(p=><article key={p.title}><p.icon size={23}/><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></section>
    <section className={styles.integration}><div><p className={styles.eyebrow}>Construído para se conectar</p><h2>Uma experiência própria.<br/><em>Um ecossistema por trás.</em></h2><p>Combinamos desenvolvimento de software com a estrutura ConnectyHub para conectar atendimento, dados, automações e inteligência artificial às necessidades do projeto.</p><MeetingLink className={styles.textLink}>Vamos conversar sobre sua ideia<ArrowRight size={18}/></MeetingLink></div><div className={styles.connectionMap}><div className={styles.connectionCore}><ConnectyLogo type="mark" tone="white" className="h-12 w-12"/><strong>Seu software</strong></div><div className={styles.connectionNodes}>{["Pessoas","WhatsApp","Inteligência artificial","Seus sistemas"].map(n=><span key={n}>{n}</span>)}</div><p>As integrações são definidas conforme o escopo e a disponibilidade das ferramentas.</p></div></section>
    <section className={styles.section} id="processo"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Como tiramos do papel</p><h2>Da conversa<br/><em>ao que vem depois.</em></h2></div><p>Você traz a visão do seu negócio. Nós ajudamos a transformar essa visão em uma experiência que as pessoas conseguem usar.</p></div><ol className={styles.steps}>{[["Entender","Uma reunião para conhecer sua empresa, a ideia e as pessoas que vão usar o sistema."],["Desenhar","Organizamos jornadas, prioridades e escopo para definir o que faz sentido construir primeiro."],["Construir e validar","Desenvolvemos as entregas e validamos os fluxos com você ao longo do projeto."],["Implantar e evoluir","Preparamos a entrada em operação e o caminho para as próximas melhorias."]].map(([h,p],i)=><li key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></li>)}</ol></section>
    <section className={styles.faq} id="perguntas"><div><p className={styles.eyebrow}>Antes da nossa conversa</p><h2>Ideias grandes.<br/><em>Respostas claras.</em></h2></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className={styles.finalCta}><p className={styles.eyebrow}>O próximo passo é uma conversa</p><h2>O que você<br/>quer <em>construir?</em></h2><p>Conte sua ideia. Vamos entender juntos como ela pode ganhar forma.</p><MeetingLink className={styles.primary}>Agendar uma reunião<ArrowRight size={18}/></MeetingLink><small>Atendimento pelo WhatsApp · ConnectyHub</small></section>
  </main>
  <footer className={styles.footer}><Link href="/" aria-label="ConnectyHub, página inicial"><ConnectyLogo type="full" tone="white" className="h-6 w-40"/></Link><p>Tecnologia que conecta ideias e negócios.</p><nav><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos</Link><Link href="/docs/ia">API de IA</Link></nav></footer>
  <div className={styles.mobileCta}><MeetingLink className={styles.primary}><MessageCircle size={18}/>Agendar uma reunião<ArrowRight size={16}/></MeetingLink></div>
</div>;}
