"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {AiOperations} from './ai-operations';
type Project={id:string;name:string;status:string;organization_id:string;organizations:{name:string}|null;ai_api_keys:{id:string;name:string;key_prefix:string;status:string;model_id:string|null}[]};
export function AdminAiConsole(){
 const [tab,setTab]=useState('operations'),[search,setSearch]=useState(''),[data,setData]=useState<{projects:Project[];truncated:boolean}|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch('/api/admin/ai-projects',{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error?.message??'Falha ao consultar os projetos.');if(!controller.signal.aborted){setData(d);setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[revision]);
 const projects=data?.projects.filter(p=>`${p.name} ${p.organizations?.name??''} ${p.id}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))??[];
 return <div className="mx-auto max-w-6xl space-y-6 text-slate-900">
  <header><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Operação da plataforma</p><h1 className="mt-2 text-3xl font-bold">API de AI</h1><p className="mt-2 text-sm leading-7 text-slate-600">Gerencie clientes, projetos e configuração comercial. A geração de conteúdo permanece no painel do cliente.</p></header>
  <nav aria-label="Administração da API de AI" className="flex flex-wrap gap-2 border-b border-slate-200">{[['operations','Operações e pendências'],['projects','Clientes, projetos e chaves'],['settings','Configuração comercial']].map(([value,label])=><button key={value} aria-current={tab===value?'page':undefined} onClick={()=>setTab(value)} className={`min-h-12 border-b-2 px-3 py-3 text-sm font-semibold ${tab===value?'border-blue-700 text-blue-800':'border-transparent text-slate-600'}`}>{label}</button>)}</nav>
  {tab==='operations'&&<AiOperations embedded/>}
  {tab==='projects'&&<section className="space-y-4"><div className="flex flex-wrap gap-3"><input aria-label="Buscar cliente ou projeto" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente ou projeto" className="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-300 px-3"/><button className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm" onClick={()=>{setData(null);setRevision(n=>n+1);}}>Atualizar</button></div>{error?<p role="alert">{error}</p>:!data?<p role="status">Carregando projetos…</p>:<>{data.truncated&&<p className="text-sm text-amber-800">Exibindo os 1.000 projetos mais recentes. A busca se aplica a essa lista.</p>}{!projects.length&&<p>Nenhum projeto encontrado.</p>}{projects.map(p=><article key={p.id} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">{p.organizations?.name??'Cliente'} · {p.name}</h2><p className="mt-2 text-sm text-slate-600">{p.status==='active'?'Ativo':'Pausado'}</p><p className="mt-1 break-all text-xs text-slate-500">Projeto: {p.id}</p><details className="mt-3"><summary className="cursor-pointer py-2 text-sm font-semibold text-blue-800">Chaves e modelos vinculados ({p.ai_api_keys.length})</summary>{p.ai_api_keys.map(k=><div key={k.id} className="mt-2 break-words rounded-xl bg-slate-50 p-3 text-sm"><p>{k.name} · {k.status==='active'?'Ativa':'Revogada'}</p><code className="break-all">{k.key_prefix}…</code><p className="mt-1 text-xs text-slate-600">Modelo: {k.model_id??'Seleção automática'}</p></div>)}<p className="mt-3 text-xs text-slate-500">Somente identificadores e prefixos. O segredo não é recuperável por esta tela.</p></details></article>)}</>}</section>}
  {tab==='settings'&&<section className="grid gap-4 sm:grid-cols-2">{[['/admin/financeiro','Tarifas, modelos e disponibilidade','Use o catálogo financeiro existente para preços, unidades, disponibilidade e custos.'],['/admin/clientes','Gestão de clientes','Acesse os controles administrativos das organizações.'],['/admin/maintenance','Configuração do serviço','Acesse a manutenção protegida dos provedores.'],['/admin/voz','Estúdio de Voz e Áudio','Acompanhe a operação de voz e áudio da plataforma.']].map(([href,title,copy])=><Link key={href} href={href} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-blue-800">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></Link>)}</section>}
 </div>;
}
