import Link from "next/link";
import { ArrowRight, FileJson, KeyRound, Sparkles } from "lucide-react";
import { aiChatExample, aiOpenApiSpec, aiResponseExample } from "@/lib/ai-api/openapi";
export const aiDocSections = [
  { id: "ia", label: "Começar com IA" },
  { id: "ia-models", label: "Identificação da API", method: "GET" },
  { id: "ia-chat", label: "Enviar uma solicitação", method: "POST" },
  { id: "ia-requests", label: "Consultar solicitação", method: "GET" },
  { id: "ia-creditos", label: "Como os créditos funcionam" },
  { id: "ia-falhas", label: "Erros e reenvios" },
] as const;
export type AiDocSection = typeof aiDocSections[number]["id"];
export function isAiDocSection(value:string):value is AiDocSection {return aiDocSections.some(section=>section.id===value);}
const base=aiOpenApiSpec.servers[0].url;
const card="rounded-xl border border-white/10 bg-white/[0.025] p-5";
const paragraph="text-sm leading-7 text-slate-300";
const link="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-emerald-200 hover:text-white";
const endpoints={
  "ia-models":{path:"/models",method:"GET",operation:aiOpenApiSpec.paths["/models"].get},
  "ia-chat":{path:"/chat/completions",method:"POST",operation:aiOpenApiSpec.paths["/chat/completions"].post},
  "ia-requests":{path:"/requests/{request_id}",method:"GET",operation:aiOpenApiSpec.paths["/requests/{request_id}"].get},
} as const;
export function AiDocsDownload(){return <a href="/docs/api/ia/openapi.json" download="connectyhub-ia-openapi.json" className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-emerald-300/25 bg-emerald-300/10 px-3 py-3 text-center text-sm font-bold text-emerald-100 hover:bg-emerald-300/20"><FileJson className="h-4 w-4 shrink-0"/>Baixar OpenAPI JSON · IA / LLM</a>;}
export function AiDocsSidePanel(){return <div className="space-y-5 rounded-xl border border-emerald-300/20 bg-slate-950/70 p-5"><h2 className="flex items-center gap-2 text-sm font-bold text-emerald-200"><Sparkles className="h-4 w-4"/>Conectar à API de IA</h2><p className={paragraph}>Crie o projeto, copie sua chave e configure este endereço no servidor do seu sistema.</p><Code code={`Base URL: ${base}\nAuthorization: Bearer SUA_CHAVE`}/><AiDocsDownload/><p className="text-xs leading-6 text-slate-400">Referência pública com exemplos, respostas e consumo em créditos. Sem login para consultar ou baixar.</p><Link href="/dashboard/api-ia" className={link}><KeyRound className="h-4 w-4"/>Criar projeto e chave<ArrowRight className="h-4 w-4"/></Link></div>;}
export function AiApiDocs({section}:{section:AiDocSection}) {
  const endpoint=section in endpoints?endpoints[section as keyof typeof endpoints]:null;
  return <article className="space-y-7"><header><p className="font-mono text-[11px] uppercase tracking-[0.2em] text-emerald-300">API de IA ConnectyHub</p><h2 className="mt-3 text-3xl font-black tracking-tight text-white sm:text-4xl">{endpoint?.operation.summary??(section==="ia-creditos"?"Tudo em créditos":section==="ia-falhas"?"Erros e reenvios":"Inteligência para seus projetos")}</h2><p className={`mt-4 ${paragraph}`}>{endpoint?.operation.description??"Conecte seu sistema à IA e acompanhe as solicitações e os créditos utilizados. A ConnectyHub cuida do processamento."}</p></header>
  {section==="ia"&&<>
    <section className={card}><h3 className="text-lg font-bold text-white">Pronto em três passos</h3><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm leading-7 text-slate-300"><li>Entre no <Link href="/dashboard/api-ia" className="text-emerald-200 underline">painel de IA</Link> e dê um nome ao seu projeto.</li><li>Copie a chave criada e guarde-a no servidor do seu sistema.</li><li>Envie uma mensagem para a API e acompanhe o uso em créditos.</li></ol><Code code={`Base URL: ${base}\nAuthorization: Bearer SUA_CHAVE`}/><p className={`mt-4 ${paragraph}`}>O projeto usa o saldo disponível da sua conta. Sua chave de IA é independente da chave WhatsApp.</p></section>
    <h3 className="text-lg font-bold text-white">Sua primeira solicitação</h3><Code code={curl()}/><p className="text-xs leading-6 text-slate-400">Exemplo Bash: configure CONNECTYHUB_AI_API_KEY no ambiente do servidor. Use uma Idempotency-Key própria para cada operação e preserve-a nos reenvios.</p>
    <div className="grid gap-3 sm:grid-cols-2"><a href="#ia-chat" className={`${card} ${link}`}>Ver mensagem e resposta<ArrowRight className="h-4 w-4"/></a><a href="#ia-creditos" className={`${card} ${link}`}>Acompanhar meus créditos<ArrowRight className="h-4 w-4"/></a></div><Compatibility/><AiDocsDownload/>
  </>}
  {endpoint&&<><div className="flex min-w-0 flex-wrap gap-3 rounded-lg border border-white/10 p-4"><strong className="font-mono text-xs text-emerald-200">{endpoint.method}</strong><code className="break-all text-sm">{endpoint.path}</code></div><Code code={section==="ia-chat"?curl():`curl '${base}${section==="ia-models"?"/models":`/requests/${aiResponseExample.connectyhub.request_id}`}' \\\n  -H "Authorization: Bearer $CONNECTYHUB_AI_API_KEY"`}/></>}
  {section==="ia-models"&&<><Code code={JSON.stringify({object:"list",data:[{id:"connectyhub-auto",object:"model",owned_by:"connectyhub"}]},null,2)}/><p className={paragraph}>Se a ferramenta de integração pedir um modelo, preencha connectyhub-auto. É a identificação da API ConnectyHub. Nas chamadas diretas, basta enviar messages.</p></>}
  {section==="ia-chat"&&<>
    <h3 className="text-lg font-bold text-white">O que enviar</h3><Rows rows={[["messages","Obrigatório: uma conversa com ao menos uma mensagem user. Use content para o texto; system pode orientar a resposta e assistant pode representar o histórico."],["model","Opcional. Use connectyhub-auto se a sua ferramenta exigir esse campo."],["stream","Opcional, false por padrão. true entrega SSE após a conclusão da solicitação."],["Idempotency-Key","Cabeçalho recomendado: identificador da operação, entre 1 e 128 caracteres ASCII imprimíveis sem espaços. Repita a mesma chave e corpo ao reenviar a operação."]]}/>
    <h3 className="text-lg font-bold text-white">Analisar uma imagem</h3><p className={paragraph}>Envie PNG, JPEG ou WebP como data URL base64 dentro do conteúdo de uma mensagem user. Endereços remotos não são aceitos.</p><Code code={JSON.stringify({messages:[{role:"user",content:[{type:"text",text:"Descreva a imagem."},{type:"image_url",image_url:{url:"data:image/png;base64,BASE64_DA_IMAGEM"}}]}]},null,2)}/>
    <h3 className="text-lg font-bold text-white">Resposta e créditos</h3><Code code={JSON.stringify(aiResponseExample,null,2)}/><Rows rows={[["choices[0].message.content","Texto da resposta."],["connectyhub.credits","Créditos utilizados nesta solicitação. O valor do exemplo é ilustrativo."],["connectyhub.request_id","UUID para consultar a solicitação. Também aparece no cabeçalho X-Request-Id."],["Idempotency-Replayed","Cabeçalho true quando a resposta foi recuperada sem nova execução."],["finish_reason","stop indica conclusão; length indica resposta parcial; content_filter indica que não há texto disponível."]]}/><Compatibility/>
  </>}
  {section==="ia-requests"&&<><Code code={JSON.stringify({id:aiResponseExample.connectyhub.request_id,status:"completed",charged_credits:1,reserved_credits:0,response:aiResponseExample,error_code:null,created_at:"2026-09-08T16:08:16.993Z"},null,2)}/><Rows rows={[["preparing / reserved / processing","Solicitação em andamento. Aguarde e consulte novamente."],["completed","Resposta disponível no campo response e créditos em charged_credits."],["uncertain","Em conferência. Não inicie outra operação equivalente."],["failed","Não concluída. Confira a causa antes de tentar novamente com uma nova identidade."]]}/><p className={paragraph}>reserved_credits informa créditos em processamento. Use o UUID de request_id, sem o prefixo chatcmpl-.</p></>}
  {section==="ia-creditos"&&<><section className={card}><h3 className="text-lg font-bold text-white">Um saldo para o seu ecossistema</h3><p className={`mt-3 ${paragraph}`}>Seus projetos, agentes e atendimentos usam a mesma carteira ConnectyHub. Cada atividade utiliza créditos conforme o trabalho realizado. Uma resposta curta e a análise de uma imagem podem ter consumos diferentes.</p><p className={`mt-3 ${paragraph}`}>Ao iniciar, uma parte do saldo fica em processamento. Quando a solicitação termina, o consumo é confirmado e a diferença fica disponível novamente. Falhas confirmadas são encerradas sem débito; solicitações em conferência mantêm o valor separado até a conclusão.</p><p className="mt-4 rounded-lg bg-emerald-300/10 p-4 text-sm leading-7 text-emerald-100">Exemplo ilustrativo: 1.000 créditos − uma atividade de 3 créditos = 997 créditos disponíveis.</p></section><Rows rows={[["Painel de uso","Veja créditos por dia, quantidade de solicitações, resultados e consumo por projeto."],["Filtros","Escolha um projeto ou todos os projetos e acompanhe os últimos 7, 30 ou 90 dias."],["Atividades","Confira data, projeto, resultado e créditos de cada solicitação."],["Adicionar créditos","Recarregue a carteira pelo painel. A recarga fica disponível após confirmação do pagamento."],["Acesso","Use com projeto ativo, acesso da conta válido e saldo disponível. A recarga e a renovação do contrato são operações diferentes."]]}/><Link className={link} href="/dashboard/api-ia">Abrir meu painel de uso<ArrowRight className="h-4 w-4"/></Link></>}
  {section==="ia-falhas"&&<><section className={card}><h3 className="text-lg font-bold text-white">Reenvie sem duplicar o uso</h3><p className={`mt-3 ${paragraph}`}>Uma Idempotency-Key identifica uma operação dentro do projeto. Se precisar reenviar, mantenha a mesma chave e o mesmo corpo. Um resultado concluído é recuperado sem nova execução ou débito. Sem esse cabeçalho, cada envio representa uma nova solicitação.</p><p className={`mt-3 ${paragraph}`}>Se a conexão cair, consulte GET /requests/UUID. Se não recebeu o UUID, reenvie a operação original com a mesma identidade. Uma solicitação uncertain deve aguardar conferência; uma solicitação failed exige conferir a causa antes de uma nova tentativa com outra chave.</p></section><Code code={JSON.stringify({error:{code:"request_in_progress",message:"Esta solicitação está sendo processada ou conferida.",request_id:aiResponseExample.connectyhub.request_id}},null,2)}/><p className={paragraph}>Na geração, error é um objeto com code e message. No catálogo e na consulta, error é uma mensagem de texto. request_id aparece quando a solicitação já foi registrada.</p></>}
  {(endpoint||section==="ia-falhas")&&<section className="space-y-4"><h3 className="text-lg font-bold text-white">Respostas HTTP</h3><Rows rows={Object.entries(endpoint?.operation.responses??aiOpenApiSpec.paths["/chat/completions"].post.responses).map(([status,response])=>[status,response.description])}/></section>}
  <footer className="border-t border-white/10 pt-5 text-xs leading-6 text-slate-400">API de IA ConnectyHub · <a className="text-emerald-200 underline" href="#whatsapp">API WhatsApp</a> · <a className="text-emerald-200 underline" href="/docs/api/ia/openapi.json" download>OpenAPI JSON</a></footer></article>;
}
function Compatibility(){return <section className={card}><h3 className="text-lg font-bold text-white">Integração simples</h3><p className={`mt-3 ${paragraph}`}>A API usa um subconjunto do formato Chat Completions. Envie os campos documentados. Ferramentas e saída com schema definido não estão disponíveis nesta versão. Documentos podem ser enviados como texto extraído; arquivos de áudio, vídeo e PDF não fazem parte deste contrato.</p><p className={`mt-3 ${paragraph}`}>Com stream=true, os eventos SSE chegam após a conclusão, com o texto, os créditos e data: [DONE]. Não é entrega incremental.</p></section>;}
function Rows({rows}:{rows:string[][]}){return <dl className="divide-y divide-white/10 overflow-hidden rounded-xl border border-white/10">{rows.map(([label,description])=><div key={label} className="grid gap-2 p-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,3fr)]"><dt className="break-words font-mono text-xs font-bold leading-6 text-emerald-200">{label}</dt><dd className="min-w-0 text-sm leading-7 text-slate-300">{description}</dd></div>)}</dl>;}
function Code({code}:{code:string}){return <pre className="mt-3 max-w-full overflow-x-auto rounded-lg border border-white/10 bg-black/50 p-4 font-mono text-xs leading-6 text-emerald-100"><code>{code}</code></pre>;}
function curl(){return `curl '${base}/chat/completions' \\\n  -H "Authorization: Bearer $CONNECTYHUB_AI_API_KEY" \\\n  -H 'Content-Type: application/json' \\\n  -H 'Idempotency-Key: pedido-123-resposta-1' \\\n  --data '${JSON.stringify(aiChatExample,null,2)}'`;}