"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Code2, Copy, KeyRound, Plus, RefreshCw } from "lucide-react";
import { CreditExplainer, formatPreciseCredits } from "./credit-explainer";
import {AiPlayground} from "./ai-playground";
type Project={id:string;name:string;status:string;monthly_credit_limit:number|null;requests_per_minute:number;max_output_tokens:number;ai_api_keys:Array<{id:string;name:string;key_prefix:string;status:string}>};
type Activity={id:string;project_id:string;status:string;model_id:string;charged_credits:number;reserved_credits:number;created_at:string;error_code:string|null;calculation:{input:number;output:number;rates:Array<{id:string;unit:string;units:number;price:number}>}};
const field="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm text-slate-900 focus:border-blue-500 focus:outline-2 focus:outline-blue-100";
const primary="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700 disabled:opacity-50";
export function AiConsole({admin=false}:{admin?:boolean}) {
  const [state,setState]=useState<{projects:Project[];wallet:{balance_credits:number;reserved_credits:number}|null;activity:Activity[]}|null>(null);
  const [notice,setNotice]=useState("");const [secret,setSecret]=useState("");const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const r=await fetch("/api/dashboard/ai");const data=await r.json();if(!r.ok)throw new Error(data.error);setState(data);},[]);
  useEffect(()=>{let alive=true;fetch("/api/dashboard/ai").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(alive)setState(d);}).catch(e=>{if(alive)setNotice(e.message);});return ()=>{alive=false;};},[]);
  async function action(body:Record<string,unknown>){setBusy(true);setNotice("");try{const r=await fetch("/api/dashboard/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);if(data.secret)setSecret(data.secret);await load();}catch(e){setNotice(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);}}
  return <div className="mx-auto max-w-6xl space-y-6 text-slate-900">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">Inteligência para seus projetos</p><h1 className="mt-2 text-3xl font-bold">API de IA</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Uma chave ConnectyHub. Seus projetos conectados à IA. O mesmo saldo que você já usa nos atendimentos.</p></div><Link className={primary} href="/docs/ia"><Code2 size={17}/>Documentação</Link></header>
    {notice&&<p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{notice}</p>}
    <div className="grid gap-3 sm:grid-cols-3">{[["Saldo disponível",Math.max(0,Number(state?.wallet?.balance_credits??0)-Number(state?.wallet?.reserved_credits??0))],["Reservado em chamadas",Number(state?.wallet?.reserved_credits??0)],["Projetos",state?.projects.length??0]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-3xl font-bold">{formatPreciseCredits(Number(value))}</p></div>)}</div>
    <CreditExplainer/>
    <AiPlayground/>
    <div className="flex flex-wrap gap-4 text-sm font-semibold"><Link className="text-blue-800 underline underline-offset-4" href="/dashboard/creditos">Comprar créditos e ver faturamento</Link>{admin&&<><Link className="text-blue-800 underline underline-offset-4" href="/admin/financeiro">Fornecedores e tarifas</Link><Link className="text-blue-800 underline underline-offset-4" href="/admin/api-ia/operacao">Consumo de clientes e conciliação</Link></>}</div>
    {secret&&<div className="space-y-3 rounded-2xl border border-emerald-300 bg-emerald-50 p-5"><h2 className="font-bold">Sua nova chave</h2><p className="text-sm">Copie agora. Ela aparece completa somente nesta criação. Use no servidor do seu projeto.</p><code className="block break-all rounded-lg bg-white p-3 text-xs">{secret}</code><button className={primary} onClick={()=>navigator.clipboard.writeText(secret).then(()=>setNotice("Chave copiada."))}><Copy size={16}/>Copiar chave</button><button className="ml-4 min-h-11 text-sm underline" onClick={()=>setSecret("")}>Fechar</button></div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Novo projeto</h2><form className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void action({action:"create_project",...Object.fromEntries(data)});}}>
      <label className="space-y-2 text-sm">Nome<input required name="name" maxLength={100} placeholder="Meu aplicativo" className={field}/></label><label className="space-y-2 text-sm">Teto mensal de créditos<input name="monthly_credit_limit" type="number" step="0.01" min="0.01" placeholder="Sem teto adicional" className={field}/></label><label className="space-y-2 text-sm">Chamadas por minuto<input name="requests_per_minute" type="number" min={1} max={300} defaultValue={30} className={field}/></label><label className="space-y-2 text-sm">Limite da resposta (tokens)<input name="max_output_tokens" type="number" min={1} max={8192} defaultValue={2048} className={field}/></label><button disabled={busy} className={primary}><Plus size={17}/>Criar projeto</button>
    </form><p className="mt-3 text-xs leading-5 text-slate-500">O teto protege o projeto e não cria saldo extra. Todas as chaves compartilham a carteira e os limites da conta.</p></section>
    <section className="space-y-3"><h2 className="text-lg font-bold">Projetos e chaves</h2>{state?.projects.length===0&&<p className="rounded-xl bg-white p-5 text-sm text-slate-600">Crie seu primeiro projeto para gerar uma chave.</p>}{state?.projects.map(p=><article key={p.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">{p.name}</h3><p className="mt-1 text-xs text-slate-500">{p.status==="active"?"Ativo":"Pausado"} · {p.requests_per_minute} chamadas/min · {p.monthly_credit_limit?`${formatPreciseCredits(Number(p.monthly_credit_limit))} créditos/mês`:"Usa o saldo da conta"}</p></div><div className="flex gap-2"><button disabled={busy} className={primary} onClick={()=>action({action:"create_key",projectId:p.id})}><KeyRound size={16}/>Nova chave</button><button disabled={busy} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm hover:bg-slate-100" onClick={()=>action({action:"toggle_project",projectId:p.id,status:p.status==="active"?"paused":"active"})}>{p.status==="active"?"Pausar":"Ativar"}</button></div></div><details className="mt-4 rounded-xl border border-slate-200 p-3"><summary className="min-h-11 cursor-pointer py-2 text-sm font-semibold text-blue-800">Editar limites do projeto</summary><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void action({action:"update_project",projectId:p.id,...Object.fromEntries(new FormData(e.currentTarget))});}}><label className="text-sm">Nome<input name="name" required defaultValue={p.name} className={field}/></label><label className="text-sm">Teto mensal de créditos<input name="monthly_credit_limit" type="number" min="0.01" step="0.01" defaultValue={p.monthly_credit_limit??""} placeholder="Sem teto adicional" className={field}/></label><label className="text-sm">Chamadas por minuto<input name="requests_per_minute" type="number" min={1} max={300} required defaultValue={p.requests_per_minute} className={field}/></label><label className="text-sm">Limite de saída (tokens)<input name="max_output_tokens" type="number" min={1} max={8192} required defaultValue={p.max_output_tokens} className={field}/></label><button disabled={busy} className={primary}>Salvar limites</button></form></details>{p.ai_api_keys.map(k=><div key={k.id} className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 px-3 py-2 text-xs"><code>{k.key_prefix}•••• · {k.status==="active"?"Ativa":"Revogada"}</code>{k.status==="active"&&<button disabled={busy} className="min-h-11 px-2 font-semibold text-red-700 hover:underline" onClick={()=>action({action:"revoke_key",projectId:p.id,keyId:k.id})}>Revogar</button>}</div>)}</article>)}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Atividades recentes</h2><button aria-label="Atualizar atividades" className="grid size-11 place-items-center rounded-xl hover:bg-slate-100" onClick={()=>load().catch(e=>setNotice(e.message))}><RefreshCw size={17}/></button></div>{state?.activity.length===0&&<p className="mt-4 text-sm text-slate-600">As chamadas vão aparecer aqui com o consumo e o cálculo.</p>}{state?.activity.map(a=><details key={a.id} className="mt-3 rounded-xl border border-slate-200 p-3 text-sm"><summary className="cursor-pointer"><span className="font-semibold">{state.projects.find(p=>p.id===a.project_id)?.name??"Projeto"}</span><span className="ml-3">{formatPreciseCredits(Number(a.charged_credits))} créditos</span><span className="ml-3 text-xs text-slate-500">{({completed:"Concluída",failed:"Falhou",uncertain:"Em conferência",preparing:"Preparando",reserved:"Reservada",processing:"Processando"} as Record<string,string>)[a.status]??a.status} · Ver cálculo</span></summary><div className="mt-3 space-y-2 text-xs leading-5 text-slate-600"><p>{new Date(a.created_at).toLocaleString("pt-BR")} · {a.model_id}</p><p>Conteúdo processado: {a.calculation.input} · Resposta e raciocínio: {a.calculation.output}</p>{a.calculation.rates.map((r,i)=><p key={i}>{r.unit==="input_token"?"Leitura":r.unit==="output_token"?"Produção":r.unit}: {r.units} × {formatPreciseCredits(Number(r.price))} crédito por unidade</p>)}<p className="break-all">Solicitação: {a.id}</p>{a.reserved_credits>0&&<p>Em reserva: {formatPreciseCredits(Number(a.reserved_credits))}. O saldo será conciliado antes de liberar ou debitar o valor.</p>}{a.error_code&&<p>Código: {a.error_code}</p>}</div></details>)}</section>
  </div>;
}
