"use client";
import {useEffect,useState,useCallback} from "react";
import Link from "next/link";
import {formatPreciseCredits} from "./credit-explainer";
type Row={id:string;status:string;model_id:string;reserved_credits:number;charged_credits:number;error_code:string;created_at:string;has_result:boolean;organizations:{name:string};ai_projects:{name:string};usage_events:{provider_cost:number;input_tokens:number;output_tokens:number}|null};
export function AiOperations(){
 const [rows,setRows]=useState<Row[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await fetch("/api/admin/ai-operations");const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.requests);},[]);
 useEffect(()=>{let alive=true;fetch("/api/admin/ai-operations").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(alive)setRows(d.requests);}).catch(e=>{if(alive)setNotice(e.message);});return ()=>{alive=false;};},[]);
 async function release(id:string,reason:string){setBusy(true);try{const r=await fetch("/api/admin/ai-operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:id,reason})});const d=await r.json();if(!r.ok)throw new Error(d.error);setNotice("Reserva liberada. O cliente não foi cobrado; conferência registrada.");await load();}catch(e){setNotice(e instanceof Error?e.message:"Falha ao conciliar.");}finally{setBusy(false);}}
 return <div className="mx-auto max-w-6xl space-y-5 text-slate-900"><h1 className="text-3xl font-bold">Operação da API de IA</h1><p className="text-sm text-slate-600">Últimas 200 chamadas ou até 200 pendências mais antigas. Custos internos são visíveis somente no admin. Resultados confirmados são conciliados automaticamente.</p><Link href="/admin/financeiro" className="inline-block min-h-11 text-blue-800 underline">Gerenciar fornecedores e tarifas</Link><button className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm" onClick={()=>fetch("/api/admin/ai-operations?pending=1").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.requests);}).catch(e=>setNotice(e.message))}>Somente pendências</button><button className="ml-3 min-h-11 text-sm text-blue-800 underline" onClick={()=>load().catch(e=>setNotice(e.message))}>Últimas chamadas</button>{notice&&<p role="status" className="rounded-xl bg-amber-50 p-4 text-amber-900">{notice}</p>}{rows.map(r=><article key={r.id} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold">{r.organizations?.name} · {r.ai_projects?.name}</h2><p className="text-sm">{r.status} · {new Date(r.created_at).toLocaleString("pt-BR")}</p></div><p className="text-sm">{r.model_id??"Preparação"} · Cobrado: {formatPreciseCredits(Number(r.charged_credits))} créditos · Reserva: {formatPreciseCredits(Number(r.reserved_credits))}</p><p className="text-xs text-slate-600">Custo estimado do fornecedor (R$): {r.usage_events?Number(r.usage_events.provider_cost).toFixed(8):"aguardando apuração"} · {r.error_code}</p><code className="block break-all text-xs">{r.id}</code>{r.status==="uncertain"&&!r.has_result&&<details><summary className="min-h-11 cursor-pointer py-2 text-sm font-semibold text-blue-800">Conferir e liberar reserva</summary><p className="text-sm leading-6">Use após verificar a ocorrência. Esta ação encerra a chamada sem débito ao cliente. Eventual custo sem confirmação fica com a ConnectyHub. A execução não será repetida.</p><form className="mt-3 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void release(r.id,String(new FormData(e.currentTarget).get("reason")));}}><input required name="reason" minLength={15} maxLength={2000} aria-label="Motivo da conciliação" placeholder="Descreva o que foi verificado" className="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-300 px-3"/><button disabled={busy} className="min-h-11 rounded-xl bg-blue-700 px-4 text-white hover:bg-blue-800 disabled:opacity-50">Liberar sem cobrança</button></form></details>}</article>)}{!rows.length&&<p>Nenhuma chamada registrada.</p>}</div>;
}
