"use client";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { AiUsage } from "@/lib/ai-api/usage";
import { formatPreciseCredits } from "./credit-explainer";

export function AiUsageCharts({ usage }: { usage: AiUsage }) {
  const daily = usage.daily.map(day => ({ ...day, label: `${day.date.slice(8)}/${day.date.slice(5,7)}` }));
  const card = "min-w-0 rounded-2xl border border-slate-200 bg-white p-5";
  return <div className="grid min-w-0 gap-5 lg:grid-cols-2">
    <section className={card} aria-label="Gráfico de créditos utilizados"><h2 className="font-bold text-slate-900">Créditos utilizados</h2><p className="mt-1 text-sm text-slate-500">Seu consumo por dia no período selecionado.</p><div className="mt-5 h-64 min-w-0"><ResponsiveContainer width="100%" height="100%"><AreaChart data={daily} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}><defs><linearGradient id="ai-credits-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={0.28}/><stop offset="100%" stopColor="#2563eb" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="label" minTickGap={28} tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis width={52} tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip formatter={value => [formatPreciseCredits(Number(value)), "Créditos"]}/><Area type="monotone" dataKey="credits" stroke="#2563eb" strokeWidth={2} fill="url(#ai-credits-fill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>{!usage.totals.requests&&<p className="mt-2 text-sm text-slate-500">Seu consumo aparecerá aqui após a primeira solicitação.</p>}</section>
    <section className={card} aria-label="Gráfico de solicitações"><h2 className="font-bold text-slate-900">Solicitações por dia</h2><p className="mt-1 text-sm text-slate-500">Acompanhe o volume de uso dos seus projetos.</p><div className="mt-5 h-64 min-w-0"><ResponsiveContainer width="100%" height="100%"><BarChart data={daily} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="label" minTickGap={28} tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis width={44} allowDecimals={false} tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip formatter={value => [Number(value).toLocaleString("pt-BR"), "Solicitações"]}/><Bar dataKey="requests" fill="#14b8a6" radius={[4,4,0,0]} maxBarSize={26} isAnimationActive={false}/></BarChart></ResponsiveContainer></div></section>
    <section className={card}><h2 className="font-bold text-slate-900">Resultado das solicitações</h2><p className="mt-1 text-sm text-slate-500">Veja o que foi concluído e o que precisa de atenção.</p><div className="mt-5 space-y-5">{[["Concluídas",usage.totals.completed,"bg-emerald-500"],["Não concluídas",usage.totals.failed,"bg-rose-400"],["Em andamento ou conferência",usage.totals.pending,"bg-amber-400"]].map(([label,value,color])=><div key={String(label)}><div className="mb-2 flex justify-between gap-3 text-sm"><span>{label}</span><strong>{Number(value).toLocaleString("pt-BR")}</strong></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${color}`} style={{width:`${usage.totals.requests?Number(value)/usage.totals.requests*100:0}%`}}/></div></div>)}</div></section>
    <section className={card}><h2 className="font-bold text-slate-900">Consumo por projeto</h2><p className="mt-1 text-sm text-slate-500">Distribuição dos créditos utilizados.</p><div className="mt-5 max-h-64 space-y-4 overflow-y-auto">{usage.projects.length ? usage.projects.map(project=><div key={project.id}><div className="mb-2 flex justify-between gap-3 text-sm"><span className="min-w-0 break-words">{project.name}</span><strong className="shrink-0">{formatPreciseCredits(Number(project.credits))} créditos</strong></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-500" style={{width:`${usage.totals.credits?Number(project.credits)/usage.totals.credits*100:0}%`}}/></div></div>):<p className="text-sm text-slate-500">Nenhum consumo neste período.</p>}</div></section>
    <details className={`${card} lg:col-span-2`}><summary className="cursor-pointer text-sm font-semibold text-blue-800">Ver dados dos gráficos</summary><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Uso diário em créditos e solicitações</caption><thead><tr>{["Data","Créditos","Solicitações","Concluídas","Não concluídas"].map(label=><th key={label} className="whitespace-nowrap p-3">{label}</th>)}</tr></thead><tbody>{daily.map(day=><tr key={day.date} className="border-t border-slate-100"><td className="p-3">{day.label}</td><td className="p-3">{formatPreciseCredits(Number(day.credits))}</td><td className="p-3">{day.requests}</td><td className="p-3">{day.completed}</td><td className="p-3">{day.failed}</td></tr>)}</tbody></table></div></details>
  </div>;
}
