'use client';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import type {OperationAudit,AuditOperation} from '@/lib/billing/operation-audit';
import {Panel} from './panel-primitives';
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:4});
const num=(v:number)=>v.toLocaleString('pt-BR',{maximumFractionDigits:6});
const units:Record<string,string>={input_token:'tokens de entrada',output_token:'tokens de saída',character:'caracteres',minute:'minutos',request:'operações',message:'mensagens',media:'mídias',megabyte:'MB',cached_input:'tokens em cache',search:'buscas'};
type GroupKey='provider'|'model'|'feature'|'organization'|'source';
export function BillingOperationAudit({data}:{data:OperationAudit}){
 const router=useRouter(),[search,setSearch]=useState(''),[provider,setProvider]=useState(''),[origin,setOrigin]=useState(''),[group,setGroup]=useState<GroupKey>('model'),[page,setPage]=useState(0);
 const rows=useMemo(()=>data.rows.filter(r=>(!provider||r.provider===provider)&&(!origin||r.source===origin)&&[r.organization,r.model,r.feature,r.agent,r.project,r.id].join(' ').toLowerCase().includes(search.toLowerCase())),[data.rows,provider,origin,search]);
 const totals=rows.reduce((t,r)=>({cost:t.cost+(r.cost??0),revenue:t.revenue+r.nominalRevenue,reserved:t.reserved+r.reserved,refund:t.refund+r.refund,negative:t.negative+(r.margin!==null&&r.margin<0?1:0),missing:t.missing+(!r.pending&&(r.cost===null||r.costBasis.startsWith('Zero'))?1:0)}),{cost:0,revenue:0,reserved:0,refund:0,negative:0,missing:0});
 const groups=new Map<string,{count:number;cost:number;revenue:number;pending:number;units:Map<string,number>}>();
 for(const r of rows){const name=r[group]||'Não informado',g=groups.get(name)??{count:0,cost:0,revenue:0,pending:0,units:new Map<string,number>()};g.count++;g.cost+=r.cost??0;g.revenue+=r.nominalRevenue;g.pending+=r.pending?1:0;for(const u of r.units)g.units.set(u.unit,(g.units.get(u.unit)??0)+u.quantity);groups.set(name,g);}
 const selectedPage=Math.min(page,Math.max(0,Math.ceil(rows.length/50)-1)),shown=rows.slice(selectedPage*50,selectedPage*50+50);
 const control='rounded-lg border border-slate-300 bg-transparent p-2 text-sm min-w-0';
 return <Panel title="Operações de IA e voz" eyebrow="consumo / carteira / margem estimada" className="mb-4" compact collapsible defaultOpen>
  <p className="mb-3 text-sm text-slate-500">Atualizado {new Date(data.at).toLocaleString('pt-BR')} · acompanha a atualização de 15s do Financeiro enquanto a aba estiver visível. Custos, reservas e lançamentos podem chegar em momentos diferentes.</p>
  <div className="mb-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-5">
   <label className="text-xs">Período<select aria-label="Período das operações" className={`${control} block w-full`} value={data.days} onChange={e=>{setPage(0);router.replace(`/admin/financeiro?usageDays=${e.target.value}`);}}>{[1,7,30].map(d=><option key={d} value={d}>{d===1?'Último dia':`Últimos ${d} dias`}</option>)}</select></label>
   <label className="text-xs">Fornecedor<select className={`${control} block w-full`} value={provider} onChange={e=>{setProvider(e.target.value);setPage(0);}}><option value="">Todos</option>{[...new Set(data.rows.map(r=>r.provider).filter(Boolean))].map(v=><option key={v}>{v}</option>)}</select></label>
   <label className="text-xs">Origem<select className={`${control} block w-full`} value={origin} onChange={e=>{setOrigin(e.target.value);setPage(0);}}><option value="">Todas</option>{[...new Set(data.rows.map(r=>r.source))].map(v=><option key={v}>{v}</option>)}</select></label>
   <label className="text-xs">Cliente, projeto, modelo ou recurso<input className={`${control} block w-full`} value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Filtrar operações"/></label>
   <label className="text-xs">Agrupar por<select className={`${control} block w-full`} value={group} onChange={e=>setGroup(e.target.value as GroupKey)}>{Object.entries({model:'Modelo',provider:'Fornecedor',feature:'Recurso',organization:'Cliente',source:'Origem'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
  </div>
  <div className="mb-3 grid grid-cols-2 gap-2 lg:grid-cols-5">{[['Custo registrado estimado',money(totals.cost)],['Receita nominal estimada',money(totals.revenue)],['Margem antes das despesas',money(totals.revenue-totals.cost)],['Créditos reservados',num(totals.reserved)],['Créditos estornados',num(totals.refund)]].map(([label,value])=><div key={label} className="rounded-lg border border-slate-200 p-3"><p className="text-xs text-slate-500">{label}</p><strong className="text-base">{value}</strong></div>)}</div>
  {(totals.negative>0||totals.missing>0)&&<p className="mb-3 rounded-lg bg-amber-100 p-3 text-sm text-amber-950">{totals.negative} operações com margem nominal negativa · {totals.missing} com custo ausente ou zero a conferir. Tarifas novas não recalculam os registros antigos.</p>}
  <details className="mb-3 text-sm text-slate-500"><summary className="cursor-pointer font-semibold">Como interpretar os valores e limites</summary><ul className="mt-2 list-disc space-y-1 pl-5">{data.warnings.map(w=><li key={w}>{w}</li>)}<li>Margem não é lucro líquido: faltam impostos, taxas de pagamento, infraestrutura e demais despesas efetivas. Não somamos novamente custos de orquestração ao custo de áudio.</li>{data.creditPackRange&&<li>Pacotes ativos rendem entre {money(data.creditPackRange.min)} e {money(data.creditPackRange.max)} por crédito. A origem de cada crédito consumido não está vinculada a cada operação.</li>}</ul></details>
  {data.truncated&&<p className="mb-2 font-semibold text-amber-700">Totais parciais: reduza o período. Máximo de 2.000 eventos recentes.</p>}
  <div className="mb-4 max-h-72 overflow-auto"><table className="w-full text-left text-xs"><thead><tr>{['Grupo','Operações / pendentes','Consumo (unidades separadas)','Custo','Receita nominal','Margem R$ / %'].map(v=><th className="p-2" key={v}>{v}</th>)}</tr></thead><tbody>{[...groups].map(([name,g])=><tr key={name} className="border-t border-slate-200"><td className="p-2 break-all">{name}</td><td className="p-2">{g.count} / {g.pending}</td><td className="p-2">{[...g.units].map(([u,q])=><div key={u}>{num(q)} {units[u]??u}</div>)}</td><td className="p-2 whitespace-nowrap">{money(g.cost)}</td><td className="p-2 whitespace-nowrap">{money(g.revenue)}</td><td className="p-2 whitespace-nowrap">{money(g.revenue-g.cost)} / {g.revenue>0?`${num((g.revenue-g.cost)/g.revenue*100)}%`:'—'}</td></tr>)}</tbody></table></div>
  <p className="mb-2 text-sm">{rows.length} operações no recorte · página {selectedPage+1} de {Math.max(1,Math.ceil(rows.length/50))}</p>
  <div className="max-h-[600px] overflow-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr>{['Data / cliente','Origem / modelo / recurso','Consumo e custo unitário','Carteira','Custo / margem','Snapshot'].map(v=><th className="p-2" key={v}>{v}</th>)}</tr></thead><tbody>{shown.map(r=><OperationRow key={r.id} row={r}/>)}</tbody></table></div>
  {!rows.length&&<p className="py-4 text-sm text-slate-500">Nenhuma operação carregada para este recorte. Confira avisos de consulta acima.</p>}
  <div className="mt-3 flex gap-2"><button className={control} disabled={selectedPage===0} onClick={()=>setPage(selectedPage-1)}>Anterior</button><button className={control} disabled={(selectedPage+1)*50>=rows.length} onClick={()=>setPage(selectedPage+1)}>Próxima</button></div>
 </Panel>;
}
function OperationRow({row:r}:{row:AuditOperation}){return <tr className="border-t border-slate-200 align-top">
 <td className="p-2">{new Date(r.at).toLocaleString('pt-BR')}<div className="font-semibold">{r.organization}</div><div>{r.status}</div></td>
 <td className="p-2 max-w-56 break-words">{r.source} · {r.provider}<div>{r.model}</div><div>{r.feature}</div>{r.project&&<div>Projeto: {r.project}</div>}{r.agent&&<div>Agente: {r.agent}</div>}</td>
 <td className="p-2">{r.units.length?r.units.map((u,i)=><div key={i}>{num(u.quantity)} {units[u.unit]??u.unit}{u.costPerThousand!==null&&<div className="text-slate-500">{money(u.costPerThousand)} / 1.000 {units[u.unit]??u.unit}</div>}</div>):'Unidade não registrada'}</td>
 <td className="p-2 whitespace-nowrap">Débito: {num(r.debit)} cr<div>Reserva: {num(r.reserved)} cr</div><div>Estorno: {num(r.refund)} cr</div><div>Liberado: {num(r.released)} cr</div>{!r.ledgerLinked&&<span className="text-amber-700">Sem movimento vinculado</span>}</td>
 <td className="p-2">{r.cost===null?'Pendente':money(r.cost)}<div className="text-slate-500">{r.costBasis}</div><div>Receita nominal: {money(r.nominalRevenue)}</div><div className={r.margin!==null&&r.margin<0?'text-red-700':''}>Margem: {r.margin===null?'—':money(r.margin)} {r.margin!==null&&r.nominalRevenue>0?`(${num(r.margin/r.nominalRevenue*100)}%)`:''}</div></td>
 <td className="p-2"><details><summary className="cursor-pointer">Tarifas / identificação</summary><p className="max-w-52 break-all">Operação: {r.id}</p><p>Câmbio: {r.fx?`R$${num(r.fx)}/USD`:'não registrado'}</p>{r.units.map((u,i)=><p className="max-w-52 break-all" key={i}>{u.unit}: {u.rateId??'sem ID'}{u.sourceRateId&&` · base ${u.sourceRateId}`}</p>)}</details></td>
 </tr>;}
