"use client";
import { useState,useEffect } from "react";
import { planFeatureDefinitions } from "@/lib/billing/plan-entitlements";
import type { CustomContract } from "@/lib/billing/custom-contracts";
const field="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm text-slate-900";
export function CustomContractEditor({organizations,initialOrganizationId}:{organizations:Array<{id:string;name:string}>;initialOrganizationId?:string}){
 const [org,setOrg]=useState(initialOrganizationId??"");const [contracts,setContracts]=useState<CustomContract[]>([]);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{if(org)fetch(`/api/admin/custom-contracts?organizationId=${org}`).then(r=>r.json()).then(d=>{if(d.error)setNotice(d.error);else setContracts(d.contracts??[]);});},[org]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice("");const d=new FormData(e.currentTarget),features:Record<string,boolean>={},resource_limits:Record<string,number>={};for(const key of Object.keys(planFeatureDefinitions)){const v=d.get(`feature:${key}`);if(v==="true"||v==="false")features[key]=v==="true";}for(const key of ["agent_limit","whatsapp_instance_limit","user_limit","organization_limit","storage_limit_bytes","storage_file_limit"]){const v=d.get(key);if(v!==null&&v!=="")resource_limits[key]=Number(v);}try{const r=await fetch("/api/admin/custom-contracts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:org,name:d.get("name"),base_plan_code:d.get("base_plan_code"),monthly_price_brl:d.get("monthly_price_brl"),included_credits:d.get("included_credits"),effective_at:new Date(String(d.get("effective_at"))).toISOString(),first_period_end:new Date(String(d.get("first_period_end"))).toISOString(),features,resource_limits})});const data=await r.json();if(!r.ok)throw new Error(data.error);setContracts(c=>[data.contract,...c]);setNotice("Condições salvas. A nova versão será usada nas próximas faturas elegíveis; o pagamento ativa os recursos e créditos.");}catch(error){setNotice(error instanceof Error?error.message:"Não foi possível salvar.");}finally{setBusy(false);}}
 return <div className="mx-auto max-w-5xl space-y-6 text-slate-900"><div><h1 className="text-3xl font-bold">Contratos personalizados</h1><p className="mt-3 text-sm leading-6 text-slate-600">Defina as condições individuais de cada cliente. O preço público dos planos permanece independente. Alterações não reescrevem faturas emitidas nem concedem créditos por edição.</p></div><label className="block text-sm font-semibold">Cliente<select value={org} onChange={e=>setOrg(e.target.value)} className={field}><option value="">Selecione a conta de cobrança</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{notice&&<p role="status" className="rounded-xl bg-blue-50 p-4 text-sm text-blue-900">{notice}</p>}
 {org&&<form onSubmit={save} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Nova versão das condições</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Nome do contrato<input required name="name" maxLength={120} placeholder="Plataforma da empresa" className={field}/></label><label className="text-sm">Base dos recursos<select name="base_plan_code" defaultValue="scale" className={field}><option value="starter">Start</option><option value="pro">Pro</option><option value="scale">Scale</option></select></label><label className="text-sm">Mensalidade (R$)<input name="monthly_price_brl" required type="number" min="0.01" step="0.01" className={field}/></label><label className="text-sm">Créditos por mês<input name="included_credits" required type="number" min={0} step="1" className={field}/></label><label className="text-sm">Início de vigência<input required type="datetime-local" name="effective_at" className={field}/></label><label className="text-sm">Próximo vencimento na contratação inicial<input required type="datetime-local" name="first_period_end" className={field}/></label></div><p className="text-xs leading-5 text-slate-500">Horários no fuso do seu dispositivo. Em renovações, o período corrente é preservado e o novo ciclo dura um mês. Serviços avulsos de desenvolvimento podem ser cadastrados separadamente em Produtos CH.</p><details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold">Recursos e limites específicos</summary><p className="mt-3 text-xs text-slate-600">Mantenha “Plano base” para herdar o recurso. IA está disponível em todos os planos; a API WhatsApp possui permissão própria.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.values(planFeatureDefinitions).map(f=><label key={f.code} className="text-sm">{f.name}<select name={`feature:${f.code}`} className={field}><option value="">Plano base</option><option value="true">Liberado</option><option value="false">Bloqueado</option></select></label>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["agent_limit","Agentes"],["whatsapp_instance_limit","WhatsApps"],["user_limit","Usuários"],["organization_limit","Empresas"],["storage_limit_bytes","Armazenamento (bytes)"],["storage_file_limit","Arquivos"]].map(([key,label])=><label className="text-sm" key={key}>{label}<input name={key} type="number" min={0} placeholder="Limite do plano base" className={field}/></label>)}</div></details><button disabled={busy} className="min-h-11 rounded-xl bg-blue-700 px-5 py-3 text-sm font-bold text-white hover:bg-blue-800 disabled:opacity-50">{busy?"Salvando…":"Salvar condições individuais"}</button></form>}
 <section className="space-y-3"><h2 className="text-lg font-bold">Histórico de condições</h2>{contracts.map(c=><article key={c.id} className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-semibold">{c.name} · versão {c.version}</h3><p className="mt-2 text-sm">{Number(c.monthly_price_brl).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}/mês · {Number(c.included_credits).toLocaleString("pt-BR")} créditos · base {c.base_plan_code}</p><p className="mt-1 text-xs text-slate-500">Vigência: {new Date(c.effective_at).toLocaleString("pt-BR")}</p></article>)}</section></div>;
}
