"use client";
import { defaultFoodComposition, readFoodComposition, validateFoodComposition, type FoodCompositionPolicy } from "@/lib/sales-catalog/food-composition";
const field = "mt-1 min-h-11 w-full rounded-lg border border-slate-600 bg-transparent px-2 text-sm";
const button = "min-h-11 text-xs font-semibold text-cyan-300";
const id = () => crypto.randomUUID();
export function FoodCompositionEditor({ value, onChange }: { value?: FoodCompositionPolicy; onChange: (value: FoodCompositionPolicy) => void }) {
  const policy = value ? readFoodComposition(value) : defaultFoodComposition();
  const update = (patch: Partial<FoodCompositionPolicy>) => onChange({ ...policy, ...patch });
  const error = validateFoodComposition(policy);
  return <section className="my-4 rounded-xl border border-slate-600 p-3 text-slate-200">
    <label className="flex min-h-11 items-center justify-between gap-3 text-sm font-semibold">Montagem de alimentos<input type="checkbox" checked={policy.enabled} onChange={event => update({ enabled: event.target.checked })}/></label>
    <p className="text-xs leading-5 text-slate-400">Configure tamanhos, sabores, bordas, adicionais e escolhas do combo. Cada unidade terá sua montagem e observação no pedido.</p>
    {policy.enabled ? <div className="mt-4 space-y-4">
      <label className="block text-xs">Preço da montagem<select className={field} value={policy.pricing} onChange={event => update({ pricing: event.target.value as FoodCompositionPolicy["pricing"] })}><option className="bg-slate-900" value="">Escolha a regra de preço</option><option className="bg-slate-900" value="highest">Maior preço entre os sabores</option><option className="bg-slate-900" value="weighted">Média proporcional às frações</option><option className="bg-slate-900" value="fixed">Preço fixo do tamanho ou combo</option></select></label>
      <label className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={policy.localOnly} onChange={event => update({ localOnly: event.target.checked })}/>Somente entrega regional ou retirada habilitadas na loja</label>
      <fieldset className="space-y-3 rounded-lg border border-slate-700 p-3"><legend className="px-1 text-sm font-semibold">Tamanhos e frações</legend>
        {policy.sizes.map((size, index) => { const change = (patch: Partial<typeof size>) => update({ sizes: policy.sizes.map((row, at) => at === index ? { ...row, ...patch } : row) }); return <div key={size.id} className="space-y-2 rounded-lg border border-slate-700 p-2">
          <div className="grid gap-2 sm:grid-cols-2"><label className="text-xs">Nome<input className={field} value={size.name} onChange={event => change({ name: event.target.value })}/></label><label className="text-xs">Preço fixo (R$)<input className={field} value={size.price} onChange={event => change({ price: event.target.value })}/></label></div>
          <div className="grid grid-cols-2 gap-2"><label className="text-xs">Frações iguais<input className={field} type="number" min={1} max={12} value={size.portions} onChange={event => change({ portions: Number(event.target.value) })}/></label><label className="text-xs">Máximo de sabores<input className={field} type="number" min={1} max={12} value={size.maxFlavors} onChange={event => change({ maxFlavors: Number(event.target.value) })}/></label></div>
          <label className="flex min-h-10 items-center gap-2 text-xs"><input type="checkbox" checked={size.active} onChange={event => change({ active: event.target.checked })}/>Disponível</label><button type="button" className={button} onClick={() => update({ sizes: policy.sizes.filter(row => row.id !== size.id) })}>Remover tamanho</button>
        </div>; })}<button type="button" className={button} onClick={() => update({ sizes: [...policy.sizes, { id: id(), name: "", price: "", portions: 1, maxFlavors: 1, active: true }] })}>Adicionar tamanho</button><p className="text-xs leading-5 text-slate-400">Quatro frações permitem inteiro, meio a meio ou quartos, dentro do limite de sabores. O preço fixo só é usado na regra de preço fixo; nos outros modos, cadastre o preço inteiro de cada sabor.</p>
      </fieldset>
      <fieldset className="space-y-3 rounded-lg border border-slate-700 p-3"><legend className="px-1 text-sm font-semibold">Sabores</legend>
        {policy.flavors.map((flavor, index) => { const change = (patch: Partial<typeof flavor>) => update({ flavors: policy.flavors.map((row, at) => at === index ? { ...row, ...patch } : row) }); return <div key={flavor.id} className="space-y-2 rounded-lg border border-slate-700 p-2"><label className="block text-xs">Nome do sabor<input className={field} value={flavor.name} onChange={event => change({ name: event.target.value })}/></label>
          {policy.pricing !== "fixed" ? <div className="grid grid-cols-2 gap-2">{policy.sizes.map(size => <label className="text-xs" key={size.id}>Preço inteiro — {size.name || "tamanho sem nome"}<input className={field} value={flavor.prices[size.id] ?? ""} onChange={event => change({ prices: { ...flavor.prices, [size.id]: event.target.value } })}/></label>)}</div> : null}
          <label className="flex min-h-10 items-center gap-2 text-xs"><input type="checkbox" checked={flavor.active} onChange={event => change({ active: event.target.checked })}/>Disponível</label>
          {policy.flavors.length > 1 ? <details className="text-xs"><summary className="min-h-8 cursor-pointer">Sabores que não podem ser combinados com este</summary>{policy.flavors.filter(other => other.id !== flavor.id).map(other => <label className="flex min-h-10 items-center gap-2" key={other.id}><input type="checkbox" checked={flavor.incompatibleWith.includes(other.id)} onChange={event => change({ incompatibleWith: event.target.checked ? [...flavor.incompatibleWith, other.id] : flavor.incompatibleWith.filter(value => value !== other.id) })}/>{other.name || "Sabor sem nome"}</label>)}</details> : null}
          <button type="button" className={button} onClick={() => update({ flavors: policy.flavors.filter(row => row.id !== flavor.id).map(row => ({ ...row, incompatibleWith: row.incompatibleWith.filter(value => value !== flavor.id) })) })}>Remover sabor</button>
        </div>; })}<button type="button" className={button} onClick={() => update({ flavors: [...policy.flavors, { id: id(), name: "", active: true, prices: {}, incompatibleWith: [] }] })}>Adicionar sabor</button>
      </fieldset>
      <fieldset className="space-y-3 rounded-lg border border-slate-700 p-3"><legend className="px-1 text-sm font-semibold">Bordas, adicionais e escolhas do combo</legend>
        {policy.groups.map((group, index) => { const change = (patch: Partial<typeof group>) => update({ groups: policy.groups.map((row, at) => at === index ? { ...row, ...patch } : row) }); return <div key={group.id} className="space-y-3 rounded-lg border border-slate-700 p-2"><label className="block text-xs">Nome do grupo<input className={field} value={group.name} onChange={event => change({ name: event.target.value })}/></label><label className="block text-xs">Aplicação e preço<select className={field} value={group.scope} onChange={event => change({ scope: event.target.value as typeof group.scope })}><option className="bg-slate-900" value="unit">Na unidade inteira, preço inteiro</option><option className="bg-slate-900" value="portion">Na fração escolhida, preço proporcional</option></select></label>
          <div className="grid grid-cols-2 gap-2">{(["min", "max"] as const).map(key => <label key={key} className="text-xs">{key === "min" ? "Mínimo de escolhas" : "Máximo de escolhas"}<input className={field} type="number" min={0} max={30} value={group[key]} onChange={event => change({ [key]: Number(event.target.value) })}/></label>)}</div>
          {group.options.map((option, at) => { const updateOption = (patch: Partial<typeof option>) => change({ options: group.options.map((row, i) => i === at ? { ...row, ...patch } : row) }); return <div key={option.id} className="rounded-lg border border-slate-700 p-2"><label className="block text-xs">Nome da opção<input className={field} value={option.name} onChange={event => updateOption({ name: event.target.value })}/></label><div className="grid grid-cols-2 gap-2"><label className="text-xs">Preço inteiro (R$)<input className={field} value={option.price} onChange={event => updateOption({ price: event.target.value })}/></label><label className="text-xs">Repetição máxima<input className={field} type="number" min={1} max={30} value={option.maxQuantity} onChange={event => updateOption({ maxQuantity: Number(event.target.value) })}/></label></div><label className="flex min-h-10 items-center gap-2 text-xs"><input type="checkbox" checked={option.active} onChange={event => updateOption({ active: event.target.checked })}/>Disponível</label><button type="button" className={button} onClick={() => change({ options: group.options.filter(row => row.id !== option.id) })}>Remover opção</button></div>; })}
          <div className="flex flex-wrap gap-4"><button type="button" className={button} onClick={() => change({ options: [...group.options, { id: id(), name: "", active: true, price: "", maxQuantity: 1 }] })}>Adicionar opção</button><button type="button" className={button} onClick={() => update({ groups: policy.groups.filter(row => row.id !== group.id) })}>Remover grupo</button></div>
        </div>; })}<button type="button" className={button} onClick={() => update({ groups: [...policy.groups, { id: id(), name: "", min: 0, max: 1, scope: "unit", options: [] }] })}>Adicionar grupo</button>
      </fieldset>
      <p className="text-xs leading-5 text-slate-400">Observações por unidade não geram acréscimo. Marque uma opção como indisponível quando não puder servi-la. A montagem usa o estoque do produto final. Cadastre aqui os tamanhos e sabores, sem múltiplas variações de estoque. O preço da montagem substitui o preço simples e a promoção do produto. Esta montagem controla disponibilidade do cardápio; não calcula estoque ou consumo de ingredientes.</p>
      {error ? <p role="status" className="text-xs text-amber-300">{error}</p> : null}
    </div> : null}
  </section>;
}
