"use client";

import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { Activity, ArrowLeft, ArrowUpRight, Database, GitBranch, LockKeyhole, Server } from "lucide-react";
import { DialogFrame } from "@/components/ui/dialog-frame";
import { actionLabels, blockedReason, eventLabels, healthLabels, jobActions, migrationRiskLabels, originLabels, projectHealth, stageLabels, stages, stale, type Detail, type Health, type InfraAction, type JobAction, type Migration, type MigrationExecution, type Overview, type ProjectConfiguration, type Telemetry } from "@/lib/infrastructure/model";

const panel = "rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
const button = "min-h-11 rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50";
const date = (v: string | null | undefined) => v ? new Date(v).toLocaleString("pt-BR") : "Não informado";
const value = (v: number | null | undefined) => v ?? "Não informado";
function Badge({ health }: { health: Health }) {
  const color = { healthy: "bg-emerald-50 text-emerald-800", warning: "bg-amber-50 text-amber-900", error: "bg-rose-50 text-rose-800", unknown: "bg-slate-100 text-slate-600" }[health];
  return <span className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-semibold ${color}`}><span aria-hidden className="h-1.5 w-1.5 rounded-full bg-current" />{healthLabels[health]}</span>;
}
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className={`${panel} min-w-0 space-y-4`}><h2 className="text-lg font-bold">{title}</h2>{children}</section>; }
function Fact({ name, children }: { name: string; children: ReactNode }) { return <div className="min-w-0"><dt className="text-xs text-slate-500">{name}</dt><dd className="mt-1 break-all text-sm font-medium">{children}</dd></div>; }
function Configuration({ config }: { config: ProjectConfiguration | undefined }) {
  if (!config) return null;
  const operation = config.missing.filter(item => /^INFRA_(MIGRATION_|PROJECT_DATABASE_|ADMIN_USER_|JOB_ADAPTERS)/.test(item));
  const observation = config.missing.filter(item => !operation.includes(item));
  return <div className="min-w-0 rounded-xl bg-slate-50 p-4 text-sm text-slate-800">
    <strong>{config.checked ? "Conexões de leitura configuradas" : "Leitura aguardando configuração"}</strong>
    <p className="mt-1 text-xs">{config.checked}/{config.total} serviços com configuração aceita. A saúde de cada conexão aparece abaixo. SQL: {config.sql.status === "ready" ? "configurado; exige confirmação" : "bloqueado até cadastrar conexão TLS e habilitar o executor"}.</p>
    {operation.length>0?<details className="mt-3 rounded-lg bg-amber-50 p-3 text-amber-950"><summary className="cursor-pointer font-semibold">SQL e jobs · {operation.length} configurações obrigatórias para executar</summary><p className="mt-2 text-xs">A leitura dos serviços já conectados continua funcionando. SQL fica bloqueado até cadastrar DSN/role TLS e habilitar o executor. Jobs ficam bloqueados até instalar e cadastrar o adaptador HTTPS com credencial do projeto.</p><ul className="mt-3 list-disc space-y-2 break-words pl-4 text-xs leading-5">{operation.map(item=><li key={item}>{item}</li>)}</ul></details>:null}
    {observation.length>0?<details className="mt-3"><summary className="cursor-pointer font-semibold">Observabilidade e inventário · {observation.length} complementos</summary><p className="mt-2 text-xs">Coletores, publicadores e cadastros complementares. Não impedem a leitura já conectada e não habilitam comandos de SQL/jobs.</p><ul className="mt-3 list-disc space-y-2 break-words pl-4 text-xs leading-5">{observation.map(item=><li key={item}>{item}</li>)}</ul></details>:null}
  </div>;
}
function Freshness({ telemetry }: { telemetry: Telemetry | null | undefined }) {
  return <p className={`text-xs ${stale(telemetry) ? "text-amber-800" : "text-slate-500"}`}>{!telemetry ? "Sem observação recente. Abra o projeto para conferir a configuração necessária por serviço." : `${stale(telemetry) ? "Telemetria desatualizada · " : "Observação · "}${date(telemetry.observed_at)} · ${telemetry.executor}`}</p>;
}

function usePolling<T>(url: string) {
  const [state, setState] = useState<{ url: string; data: T | null; error: string; updated: string | null }>({ url, data: null, error: "", updated: null });
  const [revision, setRevision] = useState(0);
  useEffect(() => {
    const controller = new AbortController();
    let timer: ReturnType<typeof setTimeout>;
    const read = async () => {
      try {
        const result = await fetch(url, { cache: "no-store", signal: AbortSignal.any([controller.signal, AbortSignal.timeout(15_000)]) });
        const data = await result.json();
        if (!result.ok) throw new Error(data.error ?? "Não foi possível atualizar.");
        if (!controller.signal.aborted) setState({ url, data, error: "", updated: new Date().toISOString() });
      } catch (e) {
        if (!controller.signal.aborted) setState(previous => ({ url, data: previous.url === url ? previous.data : null, updated: previous.url === url ? previous.updated : null, error: e instanceof Error ? e.message : "Falha ao atualizar." }));
      } finally { if (!controller.signal.aborted) timer = setTimeout(read, 5000); }
    };
    void read();
    return () => { controller.abort(); clearTimeout(timer); };
  }, [url, revision]);
  return { ...(state.url === url ? state : { data: null, error: "", updated: null }), refresh: () => setRevision(n => n + 1) };
}

export function InfrastructureInventory() {
  const { data, error, updated, refresh } = usePolling<Overview>("/api/admin/infrastructure");
  return <main className="mx-auto max-w-7xl space-y-6 text-slate-900">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Admin OS / Sistema</p><h1 className="mt-2 text-3xl font-bold">Infraestrutura</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Aplicações, dados e deploys em um cockpit por empresa. Acompanhe a publicação real na VPS e a saúde dos serviços.</p></div><button className={button} onClick={refresh}>Atualizar</button></header>
    <div className="flex flex-wrap gap-3 text-xs text-slate-500"><span className="flex items-center gap-2"><Activity size={14} />Polling a cada 5 segundos</span><span>Última consulta: {date(updated)}</span><span>Horários no fuso do navegador</span></div>
    {error && <p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error} {data && "Exibindo a última leitura; conexão interrompida."}</p>}
    <div className="grid gap-4 md:grid-cols-3">{[[Server, "Inventário", "Empresa, projeto e ambiente"], [GitBranch, "Deploy VPS", "Etapas, container e healthcheck"], [LockKeyhole, "Controle protegido", "Confirmação e auditoria"]].map(([Icon, title, text]) => { const I = Icon as typeof Server; return <div key={String(title)} className={`${panel} flex items-center gap-4`}><I className="shrink-0 text-blue-700" size={24} /><div><p className="font-semibold">{String(title)}</p><p className="mt-1 text-xs text-slate-500">{String(text)}</p></div></div>; })}</div>
    {!data && !error && <p role="status">Carregando inventário…</p>}
    {data && <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{data.projects.map(project => {
      const telemetry = data.telemetry.find(t => t.project_id === project.id);
      return <article key={project.id} className={`${panel} space-y-5`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-500">{project.company} · {project.environment}</p><h2 className="mt-1 text-xl font-bold">{project.name}</h2></div>{telemetry ? <Badge health={error ? "unknown" : projectHealth(telemetry)} /> : <span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-900">Leitura bloqueada</span>}</div>
        <p className="w-fit rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-800">{project.topology === "unknown" ? "Origem a confirmar" : originLabels[project.topology]}</p>
        <dl className="grid gap-3 sm:grid-cols-2"><Fact name="App / API">{project.app}</Fact><Fact name="Supabase">{project.supabase}</Fact><Fact name="Inngest">{project.inngest}</Fact><Fact name="Worker">{project.worker}</Fact><Fact name="Storage">{project.storage}</Fact><Fact name="Acesso">{data.canOperate ? "Admin infra · ações condicionadas à configuração" : "Leitura administrativa · ações restritas"}</Fact></dl>
        <Configuration config={data.configuration?.[project.id]} /><Freshness telemetry={telemetry} /><Link className="flex min-h-11 items-center justify-between rounded-xl bg-blue-700 px-4 py-3 text-sm font-semibold text-white" href={`/admin/infrastructure/${project.id}`}>Abrir operação <ArrowUpRight size={17} /></Link>
      </article>;
    })}</div>}
    <p className="text-xs leading-6 text-slate-500">Saúde coletada no servidor a cada 30 s enquanto o painel está aberto. Cada projeto tem configuração e permissões próprias; execução SQL depende dos requisitos mostrados na aba Migrations. <Link className="font-semibold text-blue-700 underline" href="/admin/maintenance">Configurar administradores e coletores no cofre de Infraestrutura</Link>.</p>
  </main>;
}

export function InfrastructureProject({ projectId }: { projectId: string }) {
  const [selected, setSelected] = useState("");
  const [tab, setTab] = useState("deploys");
  const [catalog, setCatalog] = useState<Migration[] | null>(null);
  const [execution, setExecution] = useState<MigrationExecution | null>(null);
  const [history, setHistory] = useState<{ applied: string[] | null; reason: string | null } | null>(null);
  const [catalogRevision, setCatalogRevision] = useState(0);
  const [reviewed, setReviewed] = useState(false);
  const [draft, setDraft] = useState({ version: "", name: "", sql: "" });
  const [draftResult, setDraftResult] = useState("");
  const [preparing, setPreparing] = useState(false);
  const [catalogError, setCatalogError] = useState("");
  const [migrationFilter, setMigrationFilter] = useState("");
  const [pending, setPending] = useState<{ action: InfraAction; target: string; checksum?: string; revision?: string | null } | null>(null);
  const [confirmation, setConfirmation] = useState("");
  const [result, setResult] = useState("");
  const [sending, setSending] = useState(false);
  const base = `/api/admin/infrastructure/${encodeURIComponent(projectId)}`;
  const { data, error, updated, refresh } = usePolling<Detail>(`${base}${selected ? `?deploy=${encodeURIComponent(selected)}` : ""}`);
  useEffect(() => {
    const controller = new AbortController();
    fetch(`${base}/migrations`, { signal: controller.signal, cache: "no-store" }).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error); setCatalog(d.migrations); setExecution(d.execution); setHistory(d.history); setCatalogError(""); }).catch(e => { if (!controller.signal.aborted) setCatalogError(e.message); });
    return () => controller.abort();
  }, [base, catalogRevision]);
  function prepare(action: InfraAction, target: string, checksum?: string) { setPending({ action, target, checksum, ...(jobActions.includes(action as JobAction) ? { revision: data?.jobs.revision } : {}) }); setConfirmation(""); setResult(""); setReviewed(false); }
  async function submit() {
    if (!pending) return;
    setSending(true);
    try {
      const response = await fetch(`${base}/actions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...pending, confirmation, ...(pending.action === "migration_apply" ? { riskAccepted: reviewed ? pending.checksum : "" } : {}) }) });
      const body = await response.json();
      setResult(body.error ?? body.message ?? "Solicitação registrada.");
      refresh(); setCatalogRevision(n => n + 1);
    } catch { setResult("Falha de conexão. Consulte a auditoria antes de repetir."); } finally { setSending(false); }
  }
  const telemetry = data?.telemetry && !stale(data.telemetry) ? data.telemetry : data?.live?.telemetry ?? data?.telemetry;
  const snapshot = telemetry?.payload;
  const observedHealth = (h?: Health): Health => error || stale(telemetry) ? "unknown" : h ?? "unknown";
  const deployment = data?.deployments.find(d => d.id === data.selectedDeployId);
  const jobs = data?.jobs.status === "ready" ? data.jobs.snapshot : snapshot?.inngest;
  const jobRequirement = `Configurar INFRA_JOB_ADAPTERS_JSON.${projectId}.url e .token no servidor e instalar o adaptador autenticado no host. Para telemetria sem comandos, usar scripts/infra-report.mjs com escopo telemetry em INFRA_INGEST_KEYS_JSON.`;
  const reporterRequirement = `No publicador do host: INFRA_REPORT_URL, INFRA_REPORT_PROJECT=${projectId}, INFRA_REPORT_TOKEN. No Admin OS: INFRA_INGEST_KEYS_JSON com hash do token e escopo por projeto. Enviar eventos com scripts/infra-report.mjs.`;
  const actionButton = (action: InfraAction, target: string, checksum?: string) => {
    const isJob = jobActions.includes(action as JobAction);
    const available = action === "migration_apply" ? execution?.status === "ready" : isJob && data?.jobs.status === "ready" && data.jobs.actions.includes(action as JobAction);
    return <button className={button} disabled={!data?.canOperate || !available} title={!data?.canOperate ? "Configure INFRA_ADMIN_USER_IDS para operar." : !available ? isJob ? data?.jobs.reason : action === "migration_apply" ? execution?.missing.join("; ") : blockedReason : "Revisar alvo e confirmar execução auditada"} onClick={() => prepare(action, target, checksum)}>{actionLabels[action]}{!available ? " · bloqueado" : ""}</button>;
  };
  return <main className="mx-auto max-w-7xl space-y-6 text-slate-900">
    <Link href="/admin/infrastructure" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-blue-700"><ArrowLeft size={16} />Todos os projetos</Link>
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-700">{data?.project.company ?? projectId} / {data?.project.environment ?? "Operações"}</p><h1 className="mt-2 text-3xl font-bold">{data?.project.name ?? "Operação do projeto"}</h1><p className="mt-2 text-sm text-slate-600">{data?.project.topology && data.project.topology !== "unknown" ? originLabels[data.project.topology] : "Origem a confirmar"} · {data?.canOperate ? "Admin infra" : "Leitura administrativa"}</p></div><div className="flex flex-wrap items-center gap-3"><Badge health={observedHealth(projectHealth(telemetry))} /><button className={button} onClick={refresh}>Atualizar</button></div></header>
    <div className="space-y-2"><p className="text-xs text-slate-500">Atualização a cada 5 s · Última consulta: {date(updated)} · Fuso do navegador</p><Freshness telemetry={telemetry} /></div>
    {error && <p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error} {data && "Última leitura preservada; conexão interrompida."}</p>}
    {!data && !error && <p role="status">Carregando operação…</p>}
    {data && <>
      <Configuration config={data.configuration} />
      <Link className="inline-flex min-h-11 items-center text-sm font-semibold text-blue-700 underline" href="/admin/maintenance">Configurar administradores e coletores no cofre de Infraestrutura</Link>
      <p className="text-xs leading-6 text-slate-500">Controle interno do Admin OS. Organização: {data.project.organization_id ?? "vínculo ainda não cadastrado"}. A camada cliente permanece indisponível nesta entrega; comandos exigem administrador da plataforma e allowlist infra.</p>
      {data.permissionReason && <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{data.permissionReason}</p>}
      <Section title="Verificação ao vivo dos serviços"><p className="text-xs text-slate-500">Coleta no servidor a cada 30 s com o painel aberto. Storage verifica a API Supabase; R2, deploy/container e execução de workers requerem observação específica do host.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{data.live?.checks.map(check => <div key={check.service} className="min-w-0 rounded-xl bg-slate-50 p-3"><p className="mb-2 text-sm font-semibold">{check.service}</p><Badge health={error || Date.parse(updated ?? "") - Date.parse(check.checkedAt) > 120000 ? "unknown" : check.health} /><p className="mt-2 break-words text-xs leading-5 text-slate-600">{check.reason.replace("<projeto>", projectId)}</p><p className="mt-2 text-xs text-slate-400">{date(check.checkedAt)}</p></div>)}</div></Section>
      {projectId === "betel" && <p className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-900">Betel: o app é publicado na VPS em <strong>app-production</strong>. A Vercel atua como proxy. Push GitHub e deploy do proxy não comprovam atualização do app.</p>}
      <nav aria-label="Operação do projeto" className="flex flex-wrap gap-2 border-b border-slate-200">{[["deploys", "Deploy VPS / App"], ["supabase", "Supabase / Storage"], ["inngest", "Inngest / Worker"], ["migrations", "Migrations"], ["audit", "Auditoria"]].map(([id, label]) => <button key={id} onClick={() => setTab(id)} aria-current={tab === id ? "page" : undefined} className={`min-h-12 border-b-2 px-3 text-sm font-semibold ${tab === id ? "border-blue-700 text-blue-800" : "border-transparent text-slate-500"}`}>{label}</button>)}</nav>
      {tab === "deploys" && <div className="grid items-start gap-5 xl:grid-cols-[1fr_2fr]">
        <Section title="App em execução"><dl className="grid gap-4"><Fact name="Versão observada">{snapshot?.version ?? "Não informada"}</Fact><Fact name="Imagem observada">{snapshot?.image ?? "Não informada"}</Fact><Fact name="Container">{snapshot?.container ?? "Não informado"}</Fact><Fact name="Healthcheck"><Badge health={observedHealth(snapshot?.services.app)} /></Fact><Fact name="Rollback disponível">{snapshot?.rollbackAvailable == null ? "Não informado" : snapshot.rollbackAvailable ? "Informado pelo coletor; execução bloqueada" : "Não"}</Fact></dl><h3 className="text-sm font-bold">Logs recentes do app</h3>{!snapshot?.appLogs?.length ? <p className="text-xs text-slate-500">Nenhum log estruturado informado.</p> : <ol className="max-h-60 space-y-2 overflow-auto rounded-xl bg-slate-50 p-3 text-xs">{snapshot.appLogs.map((log, i) => <li key={i}>{date(log.at)} · {eventLabels[log.code] ?? ({ process_started: "Processo iniciado", process_stopped: "Processo parado", request_failed: "Falha de requisição" } as Record<string, string>)[log.code]}</li>)}</ol>}{actionButton("app_rollback", data.project.app.replace(/[^a-zA-Z0-9_.-]/g, "-"))}</Section>
        <div className="order-first min-w-0 space-y-5 xl:order-none"><Section title="Deploy VPS"><p className="text-sm leading-6 text-slate-600">Progresso informado pelo script de publicação. Esta tela acompanha eventos; não inicia deploys.</p>
          <label className="block text-xs font-semibold text-slate-600">Histórico de publicações<select value={selected} onChange={e => setSelected(e.target.value)} className="mt-2 min-h-11 w-full min-w-0 rounded-xl border border-slate-300 bg-white p-3 text-sm"><option value="">Acompanhar publicação mais recente</option>{data.deployments.map(d => <option key={d.id} value={d.id}>{date(d.started_at)} · {originLabels[d.origin]} · {stageLabels[d.stage]}</option>)}</select></label>
          {data.truncated && <p className="text-xs text-amber-800">50 publicações recentes. Histórico completo preservado no banco.</p>}
          {!deployment ? <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Nenhum deploy registrado. {reporterRequirement} Escopo necessário: deploy. Token configurado não comprova envio; o histórico só aparece após o primeiro evento aceito.</p> : <>
            <div className="flex flex-wrap gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-800">{originLabels[deployment.origin]}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{stageLabels[deployment.stage]}</span></div>
            {!deployment.finished_at && Date.parse(updated ?? "") - Date.parse(deployment.updated_at) > 120_000 && <p role="status" className="text-sm text-amber-800">Sem progresso há mais de dois minutos. O resultado do deploy é desconhecido; confira o executor.</p>}
            <ol className="grid grid-cols-2 gap-2 sm:grid-cols-5">{stages.map(s => <li key={s} className={`rounded-lg border p-3 text-xs ${deployment.stage === s ? "border-blue-500 bg-blue-50 font-bold text-blue-900" : "border-slate-200 text-slate-500"}`} aria-current={deployment.stage === s ? "step" : undefined}>{stageLabels[s]}</li>)}</ol>
            <dl className="grid gap-4 sm:grid-cols-2"><Fact name="App afetado">{deployment.app}</Fact><Fact name="Executor autenticado">{deployment.executor}</Fact><Fact name="Imagem anterior">{deployment.current_image}</Fact><Fact name="Nova imagem">{deployment.new_image}</Fact><Fact name="Início / fim">{date(deployment.started_at)} / {date(deployment.finished_at)}</Fact><Fact name="Container / healthcheck informado">{deployment.container} · {healthLabels[deployment.health]}</Fact></dl>
            <h3 className="text-sm font-bold">Logs resumidos · últimos 100 eventos</h3><ol className="max-h-80 space-y-2 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-200">{data.events.map(e => <li className="break-words leading-6" key={e.sequence}><span className="text-slate-400">#{e.sequence} · {date(e.created_at)}</span><br />{stageLabels[e.stage]} — {eventLabels[e.code] ?? "Evento registrado"}</li>)}</ol>
          </>}
        </Section></div>
      </div>}
      {tab === "supabase" && <div className="grid gap-5 lg:grid-cols-2"><Section title="Supabase · saúde e conexão"><p className="text-xs leading-5 text-amber-900">Storage: o healthcheck verifica disponibilidade da API. Contagem de buckets e uso em bytes ainda não são coletados. R2 exige adaptador de métricas específico no servidor; credenciais R2 existentes não habilitam esta leitura automaticamente.</p><dl className="grid grid-cols-2 gap-5">{[["api", "API"], ["auth", "Auth"], ["rest", "REST"], ["database", "Conexão ao banco"], ["storage", "Storage"], ["app", "App"]].map(([key, label]) => <Fact key={key} name={label}><Badge health={observedHealth(snapshot?.services[key as keyof typeof snapshot.services])} /></Fact>)}</dl><p className="text-xs text-slate-500">Destino declarado: {data.project.supabase} · Storage: {data.project.storage}</p></Section><Section title="Tabelas críticas e permissões">{!snapshot?.tables.length ? <p className="text-sm text-slate-500">Leitura de tabelas pendente. {projectId === "connectyhub" ? "Conferir migration 0151, RPC infra_database_status e SUPABASE_SECRET_KEY." : `Conectar coletor do banco de ${projectId} ao receptor /api/infrastructure/${projectId}/events com escopo telemetry; enviar tables com RLS/permissões observadas.`}</p> : snapshot.tables.map(t => <div className="space-y-2 rounded-xl bg-slate-50 p-3" key={t.name}><p className="break-all text-sm font-semibold">{t.name}</p><Badge health={observedHealth(t.health)} /><p className="text-xs text-slate-600">RLS: {t.rls === "enabled" ? "Habilitado" : t.rls === "disabled" ? "Desabilitado" : "Não informado"} · Permissões: {t.permissions === "verified" ? "Verificadas" : t.permissions === "warning" ? "Atenção" : "Não informadas"}</p></div>)}</Section></div>}
      {tab === "inngest" && <div className="space-y-5"><Section title="Inngest e workers"><p className={`rounded-xl p-3 text-sm ${data.jobs.status === "ready" ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-900"}`}>{data.jobs.reason}</p><div className="flex flex-wrap gap-3"><Badge health={observedHealth(snapshot?.services.inngest)} /><Badge health={observedHealth(snapshot?.services.worker)} /></div><dl className="grid grid-cols-2 gap-5 sm:grid-cols-5"><Fact name="Falhas">{value(jobs?.failures)}</Fact><Fact name="Retries">{value(jobs?.retries)}</Fact><Fact name="Fila">{value(jobs?.queued)}</Fact><Fact name="Atraso (s)">{value(jobs?.delaySeconds)}</Fact><Fact name="Workers conectados">{value(jobs?.workers)}</Fact></dl><p className="text-xs text-slate-500">Fonte: {data.jobs.status === "ready" ? `adaptador autenticado · ${date(data.jobs.observedAt)}` : "snapshot do host, quando disponível"}. Ausência não equivale a zero.</p></Section><div className="grid gap-5 lg:grid-cols-2"><Section title="Funções / jobs">{!jobs?.functions.length && <p className="text-sm text-slate-500">Lista de funções pendente. {jobRequirement}</p>}{jobs?.functions.map(f => <div key={f.id} className="space-y-3 rounded-xl bg-slate-50 p-4"><p className="break-all text-sm font-semibold">{f.id} · {f.status === "active" ? "Ativa" : f.status === "paused" ? "Pausada" : "Não informado"}</p><div className="flex flex-wrap gap-2">{actionButton("inngest_pause", f.id)}{actionButton("inngest_resume", f.id)}</div></div>)}</Section><Section title="Últimos eventos e falhas">{!jobs?.events.length && <p className="text-sm text-slate-500">Últimas execuções indisponíveis. {jobRequirement}</p>}{jobs?.events.map(e => <div key={e.id} className="space-y-3 rounded-xl bg-slate-50 p-4"><p className="break-all text-sm font-semibold">{e.id}</p><p className="text-xs text-slate-500">{e.status} · {e.retries} retries</p><div className="flex flex-wrap gap-2">{actionButton("inngest_retry", e.id)}{actionButton("inngest_resend", e.id)}</div></div>)}</Section></div><p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Ações só são liberadas para capacidades declaradas pelo adaptador. Pausa/retomada valida o estado da função; reenvio/reprocessamento exige execução falha. O servidor revalida projeto, alvo e revisão antes do comando. Resultado incerto exige conferir o recibo no host.</p></div>}
      {tab === "migrations" && <Section title="Migrations versionadas"><p className="text-sm leading-6 text-slate-600">O catálogo é versionado. A pré-validação identifica comandos e riscos; sintaxe e dependências são conferidas pelo PostgreSQL na execução transacional. Revise o SQL e o backup antes de confirmar.</p>{execution && <div className={`rounded-xl p-4 text-sm ${execution.status === "ready" ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-900"}`}><strong>{execution.status === "ready" ? "Executor configurado" : "Ação preparada · execução bloqueada"}</strong><p className="mt-1">{execution.status === "ready" ? "Ainda exige confirmação forte e auditoria." : `Faltam: ${execution.missing.join(", ")}`}</p></div>}{catalogError && <p role="alert" className="text-sm text-rose-800">{catalogError}</p>}{!catalog && !catalogError && <p>Carregando catálogo…</p>}{catalog?.length === 0 && <p className="text-sm text-slate-500">Catálogo deste projeto ainda não conectado. Nenhuma migration é presumida aplicada.</p>}
        <details className="rounded-xl border border-blue-200 p-4"><summary className="cursor-pointer text-sm font-semibold">Preparar nova migration SQL</summary><p className="my-3 text-xs text-slate-500">Salva uma versão imutável no projeto selecionado. Preparar não executa SQL. Não inclua credenciais ou dados pessoais.</p><div className="grid gap-3 sm:grid-cols-2"><input aria-label="Versão da migration" placeholder="Versão (ex.: 202609170001)" className={button} value={draft.version} onChange={e => setDraft({ ...draft, version: e.target.value })} /><input aria-label="Nome da migration" placeholder="Nome_sem_espacos" className={button} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></div><textarea aria-label="SQL da migration" rows={8} className="my-3 w-full rounded-xl border border-slate-300 p-3 font-mono text-xs" value={draft.sql} onChange={e => setDraft({ ...draft, sql: e.target.value })} /><button className={button} disabled={!data.canOperate || preparing || !draft.sql.trim()} onClick={async () => { setPreparing(true); setDraftResult(""); try { const r = await fetch(base + "/migrations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const body = await r.json(); setDraftResult(body.error ?? body.message); if (r.ok) { setDraft({ version: "", name: "", sql: "" }); setCatalogRevision(n => n + 1); refresh(); } } catch { setDraftResult("Falha de conexão. Confira o catálogo antes de repetir."); } finally { setPreparing(false); } }}>{preparing ? "Preparando…" : "Pré-validar e salvar versão"}</button>{draftResult && <p role="status" className="mt-3 text-sm">{draftResult}</p>}</details><p className="text-xs text-slate-600">{history?.reason ?? "Histórico consultado no banco de destino."}</p>
        <input aria-label="Filtrar migrations" placeholder="Filtrar por versão ou nome" value={migrationFilter} onChange={e => setMigrationFilter(e.target.value)} className="min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm" />
        {catalog?.filter(m => `${m.version} ${m.name}`.toLowerCase().includes(migrationFilter.toLowerCase())).map(m => <details key={m.version} className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer break-all text-sm font-semibold"><Database className="mr-2 inline" size={14} />{m.version} · {m.name}<span className="ml-3 text-xs font-normal text-slate-500">{!history?.applied ? "Aplicação não verificada" : history.applied.includes(m.version) ? "Aplicada (histórico do banco)" : "Pendente (ausente no histórico)"}</span></summary><div className="my-3 flex flex-wrap gap-2 text-xs"><span className={`rounded-full px-3 py-1 font-semibold ${m.risk.level === "destructive" ? "bg-rose-100 text-rose-800" : m.risk.level === "review" ? "bg-amber-100 text-amber-900" : "bg-emerald-100 text-emerald-800"}`}>{migrationRiskLabels[m.risk.level]}</span><span className="rounded-full bg-slate-100 px-3 py-1">{m.risk.transactional ? "Transação possível" : "Fora de transação"}</span></div>{m.risk.reasons.length > 0 && <ul className="mb-3 list-disc pl-5 text-xs text-amber-900">{m.risk.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul>}<p className="break-all text-xs text-slate-500">SHA-256: {m.checksum}</p><pre className="my-3 max-h-80 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-200">{m.sql}</pre>{m.blockers?.map(reason => <p key={reason} className="my-2 text-xs text-amber-900">{reason}</p>)}{!history?.applied?.includes(m.version) && !m.blockers?.length && actionButton("migration_apply", m.version, m.checksum)}</details>)}
      </Section>}
      {tab === "audit" && <Section title="Auditoria operacional"><p className="text-xs text-slate-500">100 registros recentes; snapshots periódicos ficam no banco. Tentativas sem projeto válido têm auditoria global, consultável pelo serviço.</p>{!data.audit.length && <p className="text-sm text-slate-500">Nenhuma ação registrada.</p>}{data.audit.map(a => <details key={a.id} className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer break-words text-sm"><strong>{a.action}</strong> · {a.result === "running" ? "Iniciada · aguarda confirmação de resultado" : a.result} · {date(a.created_at)}</summary><p className="mt-3 break-all text-xs text-slate-600">Usuário/executor: {a.actor} · Alvo: {a.target ?? "Não se aplica"} · Motivo: {a.reason}</p><pre className="mt-3 max-h-60 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify({ antes: a.before_state, depois: a.after_state }, null, 2)}</pre></details>)}</Section>}
    </>}
    {pending && <DialogFrame onClose={() => !sending && setPending(null)} aria-labelledby="infra-confirm-title" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-xl space-y-4 rounded-2xl bg-white p-6 text-slate-900"><h2 id="infra-confirm-title" className="text-xl font-bold">{actionLabels[pending.action]}</h2><p className="break-all text-sm">Projeto: <strong>{projectId}</strong> · Alvo: <strong>{pending.target}</strong></p><p className="text-sm leading-6 text-amber-900">{pending.action === "migration_apply" ? "Esta ação pode alterar dados e estruturas. Revise o SQL, providencie backup e confirme o projeto. A execução e o resultado serão auditados." : pending.action === "app_rollback" ? blockedReason : "Ação operacional de jobs: confirme o projeto e o alvo. O adaptador validará a revisão e registrará um recibo idempotente. Reprocessar pode repetir efeitos de negócio; revise a falha antes de confirmar."}</p><label className="block text-sm">Para confirmar, digite <code className="break-all font-semibold">{`${projectId}:${pending.action}:${pending.target}`}</code><input className="mt-3 min-h-11 w-full rounded-xl border border-slate-300 px-3" value={confirmation} onChange={e => setConfirmation(e.target.value)} autoComplete="off" /></label>{pending.action === "migration_apply" && <label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} /><span>Revisei o SQL e os riscos desta versão. SHA-256: <code className="break-all text-xs">{pending.checksum}</code></span></label>}{result && <p role="status" className="text-sm leading-6 text-blue-800">{result}</p>}<div className="flex flex-wrap justify-end gap-3"><button className={button} disabled={sending} onClick={() => setPending(null)}>Fechar</button><button className={button} disabled={sending || !!result || (pending.action === "migration_apply" && !reviewed) || confirmation !== `${projectId}:${pending.action}:${pending.target}`} onClick={submit}>{sending ? "Executando…" : pending.action === "migration_apply" ? "Confirmar execução" : "Confirmar solicitação"}</button></div></div></DialogFrame>}
  </main>;
}
