'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Rate={unit:string;providerCostPerUnit:number;connectyPricePerUnit:number;minimumChargeCredits:number};
type Capability={operation:string;model_id:string;name:string;enabled:boolean;ready:boolean;confirmed_at:string|null;cost_evidence:string|null;rate_hash:string;rates:Rate[]};
type Catalog={capabilities:Capability[];runtime_enabled:boolean;uploads_enabled:boolean};
const button='min-h-11 rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold disabled:opacity-50';
async function read(r:Response){const b=await r.json();if(!r.ok)throw new Error(b.error?.message??'Operação indisponível.');return b;}
export function StudioAdminControls(){
 const [data,setData]=useState<Catalog|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[evidence,setEvidence]=useState<Record<string,string>>({});
 const refresh=async()=>setData(await fetch('/api/admin/voice/capabilities').then(read));
 useEffect(()=>{let active=true;fetch('/api/admin/voice/capabilities').then(read).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[]);
 async function save(c:Capability,enabled:boolean){setBusy(true);setMessage('');try{
  await fetch('/api/admin/voice/capabilities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:c.operation,model_id:c.model_id,enabled,cost_evidence:evidence[c.operation+c.model_id]??c.cost_evidence,rate_hash:c.rate_hash})}).then(read);await refresh();setMessage('Disponibilidade atualizada. Tarifas existentes preservadas.');
 }catch(e){setMessage(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
 return <details className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-semibold">Disponibilidade e custos das modalidades do Estúdio</summary><p className="mt-3 text-sm leading-6 text-slate-600">Cadastre as tarifas no <Link className="text-blue-800 underline" href="/admin/financeiro">catálogo financeiro</Link>, confira o custo aplicável à conta do fornecedor e libere cada modalidade. Alterar a tarifa exige nova conferência. Planos com tarifa específica precisam de validação correspondente.</p>{message&&<p role="status" className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{message}</p>}{data&&<><p className="mt-3 text-sm text-slate-500">Execução: {data.runtime_enabled?'habilitada':'aguardando implantação/ativação'} · Arquivos: {data.uploads_enabled?'habilitados':'aguardando implantação/ativação'}</p><div className="mt-4 space-y-4">{data.capabilities.map(c=>{const key=c.operation+c.model_id;return <article key={key} className="min-w-0 space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{c.name}</h3><span className="text-sm">{c.enabled?'Liberada no cadastro':'Desativada'}</span></div><p className="break-all text-xs text-slate-500">{c.model_id}</p>{c.rates.map((r,i)=><p key={i} className="text-sm">{r.unit}: custo estimado R$ {r.providerCostPerUnit} · {r.connectyPricePerUnit} créditos · mínimo {r.minimumChargeCredits}</p>)}{!c.ready&&<p className="text-sm text-amber-800">Tarifa ou unidade ainda não está pronta para confirmação.</p>}<label className="block text-sm">Evidência do custo aplicável<textarea className="mt-1 min-h-20 w-full rounded-xl border border-slate-300 p-3" maxLength={2000} value={evidence[key]??c.cost_evidence??''} onChange={e=>setEvidence(v=>({...v,[key]:e.target.value}))} placeholder="Referência e data da tabela/contrato conferido. Não inclua credenciais ou dados pessoais."/></label><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!c.ready} onClick={()=>save(c,true)}>Confirmar tarifas e liberar</button><button className={button} disabled={busy||!c.enabled} onClick={()=>save(c,false)}>Desativar modalidade</button></div></article>;})}</div></>}</details>;
}
