'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Download,RefreshCw,Upload,Plus,Trash2} from 'lucide-react';
type Voice={voice_id:string;name:string;status:string};
type Capability={operation:string;name:string;model_id:string;requires_audio:boolean;available:boolean;reason:string};
type Catalog={capabilities:Capability[];gemini_voices:Voice[];uploads_available:boolean};
type Asset={id:string;name:string;size_bytes:number;status:string;duration_seconds:number|null};
type Resource={id:string;kind:string;name:string;description?:string};
type Receipt={id:string;operation:string;status:string;result_state?:string;usage:{credits:number;reserved_credits:number};result:{content_type:string}|null;error:{code:string}|null;created_at:string};
type Quote={credits:number;reservation_only:boolean};
type Rule={type:'alias'|'phoneme';string_to_replace:string;alias:string;phoneme:string;alphabet:'ipa'|'cmu-arpabet'};
const field='mt-1 min-h-11 w-full min-w-0 rounded-xl border border-slate-300 bg-white p-3 text-sm text-slate-900 focus:outline-2 focus:outline-blue-500';
const button='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-800 disabled:opacity-50';
const secondary='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50';
const states:Record<string,string>={pending:'Aguardando envio',ready:'Pronto',processing:'Processando',reserved:'Na fila',uncertain:'Em conferência',completed:'Concluído',failed:'Não concluído',deleted:'Excluído',deleting:'Excluindo'};
const count=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:4});
async function read<T>(r:Response):Promise<T>{const data=await r.json();if(!r.ok)throw new Error(data.error?.message??'Não foi possível concluir a solicitação.');return data as T;}
const blankRule=():Rule=>({type:'alias',string_to_replace:'',alias:'',phoneme:'',alphabet:'ipa'});
export function StudioTools({project,voices,onChanged}:{project:string;voices:Voice[];onChanged:()=>Promise<void>}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[assets,setAssets]=useState<Asset[]>([]),[resources,setResources]=useState<Resource[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]);
 const [operation,setOperation]=useState('transcription'),[model,setModel]=useState(''),[asset,setAsset]=useState(''),[voice,setVoice]=useState(''),[text,setText]=useState(''),[language,setLanguage]=useState(''),[diarize,setDiarize]=useState(false);
 const [description,setDescription]=useState(''),[sample,setSample]=useState(''),[name,setName]=useState(''),[preview,setPreview]=useState(''),[parent,setParent]=useState(''),[dictionary,setDictionary]=useState('');
 const [turns,setTurns]=useState([{text:'',voice_id:''},{text:'',voice_id:''}]),[rules,setRules]=useState<Rule[]>([blankRule()]);
 const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[quote,setQuote]=useState<{body:string;value:Quote}|null>(null),[media,setMedia]=useState<{url:string;mime:string;name:string;text?:string}|null>(null);
 const idem=useRef<{body:string;key:string}|null>(null);
 const endpoint=useCallback((path:string)=>`/api/dashboard/voice/${path}${path.includes('?')?'&':'?'}project=${encodeURIComponent(project)}`,[project]);
 const load=useCallback(async()=>{
  const c=await fetch(endpoint('capabilities')).then(read<Catalog>);
  const [a,r,h]=await Promise.all([c.uploads_available?fetch(endpoint('assets')).then(read<{assets:Asset[]}>):{assets:[]},fetch(endpoint('resources')).then(read<{resources:Resource[]}>),fetch(endpoint('operations')).then(read<{operations:Receipt[]}>)]);
  return {c,a,r,h};
 },[endpoint]);
 const apply=useCallback(({c,a,r,h}:Awaited<ReturnType<typeof load>>)=>{setCatalog(c);setAssets(a.assets);setResources(r.resources);setReceipts(h.operations);},[]);
 const refresh=async()=>{apply(await load());await onChanged();};
 useEffect(()=>{let active=true;load().then(d=>{if(active)apply(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[load,apply]);
 useEffect(()=>()=>{if(media)URL.revokeObjectURL(media.url);},[media]);
 const choices=catalog?.capabilities.filter(c=>c.operation===operation)??[],chosen=choices.find(c=>c.model_id===model)??choices[0];
 const body=JSON.stringify({operation,...(chosen?{model_id:chosen.model_id}:{}),...(chosen?.requires_audio?{asset_id:asset}:{}),
  ...(operation==='transcription'?{...(language?{language}:{}),diarize}:{}),...(operation==='dubbing'?{target_language:language}:{}),
  ...(['voice_change','gemini_tts'].includes(operation)?{voice_id:voice}:{}),...(['gemini_tts','forced_alignment'].includes(operation)?{text}:{}),
  ...(operation==='dialogue'?{turns,...(dictionary?{dictionary_ids:[dictionary]}:{})}:{}),...(operation==='voice_design'?{description,sample_text:sample}:{}),
  ...(operation==='voice_design_save'?{preview_id:preview,name,description}:{}),
  ...(operation==='dictionary_create'?{name,...(parent?{parent_dictionary_id:parent}:{}),rules:rules.map(r=>r.type==='alias'?{type:r.type,string_to_replace:r.string_to_replace,alias:r.alias}:{type:r.type,string_to_replace:r.string_to_replace,phoneme:r.phoneme,alphabet:r.alphabet})}:{}),
 });
 const currentQuote=quote?.body===body?quote.value:null;
 async function act(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();}catch(error){setMessage(error instanceof Error?error.message:'Falha na operação.');}finally{setBusy(false);}}
 async function openResult(path:string,filename:string){
  const r=await fetch(endpoint(path));if(!r.ok){await read(r);return;}const blob=await r.blob(),mime=r.headers.get('content-type')??blob.type;
  const content=/json|text/.test(mime)?await blob.text():undefined;
  setMedia({url:URL.createObjectURL(blob),mime,name:filename,text:content});
 }
 async function upload(){
  if(!file)return;if(file.size>20_000_000)throw new Error('Envie um arquivo de até 20 MB.');
  const mime=file.type==='audio/x-wav'?'audio/wav':file.type;
  const created=await fetch(endpoint('assets'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name.slice(0,100),size_bytes:file.size,mime_type:mime})}).then(read<Asset&{upload:{url:string;access_key:string}}>);
  setAsset(created.id);setAssets(a=>[created,...a]);
  try{const r=await fetch(created.upload.url,{method:'PUT',headers:{Authorization:`Bearer ${created.upload.access_key}`,'Content-Type':mime},body:file});if(!r.ok)throw new Error('Envio não confirmado. Atualize os arquivos antes de reenviar.');}
  finally{await refresh();}
  setFile(null);setMessage('Arquivo enviado. Aguarde o estado Pronto para utilizá-lo.');
 }
 const voiceOptions=(items:Voice[])=><><option value="">Selecione uma voz</option>{items.filter(v=>v.status==='ready'||operation==='gemini_tts').map(v=><option key={v.voice_id} value={v.voice_id}>{v.name}</option>)}</>;
 return <section className="min-w-0 space-y-5 rounded-2xl border border-slate-200 bg-white p-5" aria-label="Ferramentas de áudio">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Mais ferramentas de voz e áudio</h2><p className="mt-2 text-sm text-slate-600">Escolha uma ferramenta e confira os créditos antes de começar.</p></div><button className={secondary} disabled={busy} onClick={()=>act(refresh)}><RefreshCw size={16}/>Atualizar</button></div>
  {message&&<p role="status" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{message}</p>}
  {!catalog?<p className="text-sm text-slate-500">Carregando ferramentas…</p>:<>
   <div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]">
    <nav aria-label="Escolher ferramenta de áudio" className="grid grid-cols-2 content-start gap-2 lg:grid-cols-1">{Array.from(new Map(catalog.capabilities.map(c=>[c.operation,c])).values()).map(c=><button key={c.operation} disabled={busy} aria-pressed={operation===c.operation} onClick={()=>{setOperation(c.operation);setModel('');setVoice('');setLanguage('');setQuote(null);setMessage('');}} className={`min-h-12 min-w-0 rounded-xl border p-3 text-left text-sm ${operation===c.operation?'border-blue-500 bg-blue-50 font-semibold text-blue-900':'border-slate-200 text-slate-600 hover:bg-slate-50'}`}>{c.name}</button>)}</nav>
    <div className="min-w-0 space-y-4"><h3 className="text-lg font-semibold">{chosen?.name}</h3>
     {!chosen?.available&&<p className="rounded-xl bg-slate-100 p-3 text-sm text-slate-600">{chosen?.reason??'Ainda indisponível'}. Aguarde a liberação desta ferramenta para sua conta.</p>}
     <fieldset disabled={busy} className="min-w-0 space-y-4">
      {choices.length>1&&<label className="block text-sm">Modelo<select className={field} value={chosen?.model_id??''} onChange={e=>setModel(e.target.value)}>{choices.map(c=><option key={c.model_id} value={c.model_id}>{c.model_id}{c.available?'':' · indisponível'}</option>)}</select></label>}
      {chosen?.requires_audio&&<label className="block text-sm">Áudio do projeto<select className={field} value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Selecione um arquivo pronto</option>{assets.filter(a=>a.status==='ready').map(a=><option key={a.id} value={a.id}>{a.name} · {count(a.duration_seconds??0)} s</option>)}</select></label>}
      {['voice_change','gemini_tts'].includes(operation)&&<label className="block text-sm">Voz<select className={field} value={voice} onChange={e=>setVoice(e.target.value)}>{voiceOptions(operation==='gemini_tts'?catalog.gemini_voices:voices)}</select></label>}
      {['transcription','dubbing'].includes(operation)&&<label className="block text-sm">{operation==='dubbing'?'Idioma de destino':'Idioma do áudio'}<select className={field} value={language} onChange={e=>setLanguage(e.target.value)}><option value="">{operation==='transcription'?'Detectar automaticamente':'Selecione o idioma'}</option>{[['pt','Português'],['en','Inglês'],['es','Espanhol'],['fr','Francês'],['de','Alemão'],['it','Italiano'],['ja','Japonês']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}
      {operation==='transcription'&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={diarize} onChange={e=>setDiarize(e.target.checked)}/>Identificar falantes</label>}
      {['gemini_tts','forced_alignment'].includes(operation)&&<label className="block text-sm">{operation==='forced_alignment'?'Texto correspondente ao áudio':'Texto para gerar fala'}<textarea className={`${field} min-h-40`} maxLength={4800} value={text} onChange={e=>setText(e.target.value)}/><span className="text-xs text-slate-500">{text.length}/4.800 caracteres</span></label>}
      {operation==='dialogue'&&<label className="block text-sm">Dicionário de pronúncia (opcional)<select className={field} value={dictionary} onChange={e=>setDictionary(e.target.value)}><option value="">Sem dicionário</option>{resources.filter(r=>r.kind==='dictionary').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}
      {operation==='dialogue'&&<div className="space-y-3">{turns.map((turn,i)=><div className="rounded-xl border border-slate-200 p-3" key={i}><div className="flex items-end gap-2"><label className="min-w-0 flex-1 text-sm">Voz da fala {i+1}<select className={field} value={turn.voice_id} onChange={e=>setTurns(t=>t.map((v,j)=>j===i?{...v,voice_id:e.target.value}:v))}>{voiceOptions(voices)}</select></label><button className={secondary} aria-label={`Remover fala ${i+1}`} disabled={turns.length===1} onClick={()=>setTurns(t=>t.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div><label className="mt-3 block text-sm">Texto da fala {i+1}<textarea className={field} maxLength={2000} value={turn.text} onChange={e=>setTurns(t=>t.map((v,j)=>j===i?{...v,text:e.target.value}:v))}/></label></div>)}<p className="text-xs text-slate-500">{turns.reduce((n,t)=>n+t.text.length,0)}/2.000 caracteres no total · até 10 vozes</p><button className={secondary} disabled={turns.length>=50} onClick={()=>setTurns(t=>[...t,{text:'',voice_id:''}])}><Plus size={16}/>Adicionar fala</button></div>}
      {['voice_design','voice_design_save'].includes(operation)&&<label className="block text-sm">Descrição da voz<textarea className={field} minLength={20} maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descreva o tom, o ritmo e as características da voz."/><span className="text-xs text-slate-500">De 20 a 1.000 caracteres</span></label>}
      {operation==='voice_design'&&<label className="block text-sm">Texto das prévias<textarea className={`${field} min-h-32`} minLength={100} maxLength={1000} value={sample} onChange={e=>setSample(e.target.value)}/><span className="text-xs text-slate-500">De 100 a 1.000 caracteres. O mesmo texto será usado nas prévias.</span></label>}
      {['voice_design_save','dictionary_create'].includes(operation)&&<label className="block text-sm">Nome<input className={field} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>}
      {operation==='voice_design_save'&&<label className="block text-sm">Prévia escolhida<select className={field} value={preview} onChange={e=>{setPreview(e.target.value);setDescription(resources.find(r=>r.id===e.target.value)?.description??'');}}><option value="">Selecione uma prévia deste projeto</option>{resources.filter(r=>r.kind==='voice_preview').map(r=><option key={r.id} value={r.id}>{r.name} · {r.id.slice(0,8)}</option>)}</select></label>}
      {operation==='dictionary_create'&&<div className="space-y-3"><label className="block text-sm">Versão anterior (opcional)<select className={field} value={parent} onChange={e=>setParent(e.target.value)}><option value="">Novo dicionário</option>{resources.filter(r=>r.kind==='dictionary').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><span className="text-xs text-slate-500">As regras abaixo formam uma versão completa e independente.</span></label>{rules.map((rule,i)=><div className="space-y-2 rounded-xl border border-slate-200 p-3" key={i}><div className="flex items-end gap-2"><label className="min-w-0 flex-1 text-sm">Expressão {i+1}<input className={field} maxLength={100} value={rule.string_to_replace} onChange={e=>setRules(rs=>rs.map((r,j)=>j===i?{...r,string_to_replace:e.target.value}:r))}/></label><button className={secondary} aria-label={`Remover regra ${i+1}`} disabled={rules.length===1} onClick={()=>setRules(rs=>rs.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div><label className="block text-sm">Tipo de pronúncia<select className={field} value={rule.type} onChange={e=>setRules(rs=>rs.map((r,j)=>j===i?{...r,type:e.target.value as Rule['type']}:r))}><option value="alias">Substituição por texto</option><option value="phoneme">Fonema</option></select></label>{rule.type==='alias'?<label className="block text-sm">Pronunciar como<input className={field} maxLength={200} value={rule.alias} onChange={e=>setRules(rs=>rs.map((r,j)=>j===i?{...r,alias:e.target.value}:r))}/></label>:<><label className="block text-sm">Alfabeto<select className={field} value={rule.alphabet} onChange={e=>setRules(rs=>rs.map((r,j)=>j===i?{...r,alphabet:e.target.value as Rule['alphabet']}:r))}><option value="ipa">IPA</option><option value="cmu-arpabet">CMU Arpabet</option></select></label><label className="block text-sm">Fonema<input className={field} maxLength={200} value={rule.phoneme} onChange={e=>setRules(rs=>rs.map((r,j)=>j===i?{...r,phoneme:e.target.value}:r))}/></label></>}</div>)}<button className={secondary} disabled={rules.length>=100} onClick={()=>setRules(rs=>[...rs,blankRule()])}><Plus size={16}/>Adicionar regra</button></div>}
     </fieldset>
     <div className="flex flex-wrap items-center gap-3"><button className={secondary} disabled={busy||!chosen?.available} onClick={()=>act(async()=>{const value=await fetch(endpoint('operations/quote'),{method:'POST',headers:{'Content-Type':'application/json'},body}).then(read<Quote>);setQuote({body,value});})}>Consultar créditos</button>{currentQuote&&<span className="text-sm font-medium text-blue-900">{currentQuote.reservation_only?'Reserva máxima':'Custo'}: {count(currentQuote.credits)} créditos</span>}</div>
     {currentQuote?.reservation_only&&<p className="text-xs leading-5 text-slate-500">O débito final usa os tokens informados pelo serviço; a diferença da reserva é liberada após a confirmação.</p>}
     <button className={button} disabled={busy||!chosen?.available||!currentQuote} onClick={()=>act(async()=>{if(idem.current?.body!==body)idem.current={body,key:crypto.randomUUID()};const r=await fetch(endpoint('operations'),{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idem.current.key,'X-Max-Credits':String(currentQuote!.credits)},body}).then(read<Receipt>);setMessage(`Solicitação ${r.id}: ${states[r.status]??r.status}. Acompanhe abaixo.`);await refresh();})}>{busy?'Aguarde…':'Iniciar / consultar mesma solicitação'}</button>
     <p className="text-xs leading-5 text-slate-500">Repetir a mesma solicitação recupera o recibo existente. Altere os parâmetros para criar outra operação. Evite reenviar operações em conferência.</p>
    </div>
   </div>
   <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold">Arquivos deste projeto</summary><p className="mt-3 text-sm text-slate-500">Áudios de até 20 MB e 30 minutos. O armazenamento usa a capacidade do seu plano.</p><div className="mt-3 flex flex-wrap items-center gap-3"><input aria-label="Arquivo de áudio" type="file" accept="audio/wav,audio/mpeg,audio/mp4,audio/aac,audio/ogg,audio/flac,audio/webm" disabled={busy||!catalog.uploads_available} className="w-full min-w-0 text-sm sm:flex-1" onChange={e=>setFile(e.target.files?.[0]??null)}/><button className={button} disabled={busy||!file||!catalog.uploads_available} onClick={()=>act(upload)}><Upload size={16}/>Enviar arquivo</button></div>{!catalog.uploads_available&&<p className="mt-2 text-sm text-slate-500">Envio ainda indisponível.</p>}<ul className="mt-4 space-y-2">{assets.filter(a=>a.status!=='deleted').map(a=><li key={a.id} className="flex flex-wrap items-center gap-3 rounded-lg bg-slate-50 p-3 text-sm"><span className="min-w-0 flex-1 break-words">{a.name}<span className="block text-xs text-slate-500">{states[a.status]??a.status} · {count(a.size_bytes/1_000_000)} MB{a.duration_seconds!==null?` · ${count(a.duration_seconds)} s`:''}</span></span><button className={secondary} disabled={busy||a.status==='processing'} onClick={()=>act(async()=>{if(!window.confirm(`Excluir o arquivo ${a.name}?`))return;await fetch(endpoint(`assets/${a.id}`),{method:'DELETE'}).then(read);await refresh();})}>Excluir</button></li>)}</ul></details>
   <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold">Prévias, vozes e dicionários</summary><ul className="mt-4 space-y-3">{resources.map(r=><li key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-50 p-3 text-sm"><span>{r.name}<span className="block text-xs text-slate-500">{r.kind==='voice_preview'?'Prévia':r.kind==='voice'?'Voz privada':'Dicionário'} · {r.id.slice(0,8)}</span></span>{r.kind==='voice_preview'&&<button className={secondary} disabled={busy} onClick={()=>act(()=>openResult(`resources/${r.id}/audio`,'previa.mp3'))}>Ouvir prévia</button>}</li>)}{!resources.length&&<li className="text-sm text-slate-500">Nenhum recurso criado neste projeto.</li>}</ul></details>
   <div><h3 className="font-semibold">Solicitações recentes</h3><div className="mt-3 space-y-3">{receipts.map(r=><article className="rounded-xl border border-slate-200 p-4" key={r.id}><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{catalog.capabilities.find(c=>c.operation===r.operation)?.name??r.operation}</strong><span className="text-sm text-slate-600">{states[r.status]??r.status}</span></div><p className="mt-2 break-all text-xs text-slate-500">{r.id} · {new Date(r.created_at).toLocaleString('pt-BR')}</p><p className="mt-2 text-sm">{count(r.usage.credits)} créditos usados · {count(r.usage.reserved_credits)} reservados</p>{r.error&&<p className="mt-2 text-xs text-amber-800">{r.status==='uncertain'?'Estamos conferindo o resultado. Evite reenviar.':'A operação não foi concluída.'} Referência: {r.error.code}</p>}{r.result&&<div className="mt-3 flex flex-wrap gap-2"><button className={secondary} disabled={busy} onClick={()=>act(()=>openResult(`operations/${r.id}/result`,r.result?.content_type==='audio/wav'?'resultado.wav':r.result?.content_type==='audio/mpeg'?'resultado.mp3':'resultado.json'))}><Download size={16}/>Abrir resultado</button>{['transcription','forced_alignment'].includes(r.operation)&&(['srt','vtt'] as const).map(format=><button className={secondary} disabled={busy} key={format} onClick={()=>act(()=>openResult(`operations/${r.id}/result?format=${format}`,`legendas.${format}`))}>{format.toUpperCase()}</button>)}</div>}{r.status==='completed'&&r.result_state!=='deleted'&&<button className={`${secondary} mt-3`} disabled={busy} onClick={()=>act(async()=>{if(!window.confirm('Excluir o resultado e suas prévias? O recibo e os créditos usados serão mantidos.'))return;await fetch(endpoint(`operations/${r.id}/result`),{method:'DELETE'}).then(read);setMedia(null);await refresh();})}>Excluir resultado</button>}{r.result_state==='deleted'&&<p className="mt-2 text-xs text-slate-500">Resultado excluído. Recibo preservado.</p>}</article>)}{!receipts.length&&<p className="text-sm text-slate-500">Nenhuma solicitação destas ferramentas neste projeto.</p>}</div></div>
   {media&&<section aria-label="Resultado selecionado" className="min-w-0 rounded-xl bg-blue-50 p-4"><h3 className="font-semibold">Resultado selecionado</h3>{media.mime.startsWith('audio/')?<audio controls src={media.url} className="mt-3 w-full"/>:<pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-words text-xs">{media.text}</pre>}<a className={`${secondary} mt-3`} href={media.url} download={media.name}><Download size={16}/>Baixar {media.name}</a></section>}
  </>}
 </section>;
}
