import {voiceGuide,voiceOpenApiSpec} from '@/lib/voice-api/openapi';
export function VoiceApiDocs(){return <article className="space-y-6"><header><p className="text-xs uppercase tracking-widest text-violet-300">Estúdio de Voz e Áudio AI</p><h1 className="mt-3 text-3xl font-bold">Vozes privadas, áudio e créditos</h1><p className="mt-3 text-sm leading-7 text-slate-400">Use o mesmo projeto no Estúdio e na integração. Nenhuma chave de fornecedor fica no seu aplicativo.</p><div className="mt-4 flex flex-wrap gap-4 text-sm text-violet-200"><a href="/docs/api/voz/openapi.json" download="connectyhub-voz-openapi.json" className="underline">Baixar OpenAPI de Voz (JSON)</a><a href="/docs/api/voz/guide.md" download="connectyhub-voz.md" className="underline">Baixar guia (Markdown)</a><a href="/dashboard/voz" className="underline">Abrir Estúdio</a></div><p className="mt-3 text-sm leading-7 text-slate-400">Para integrar em outro aplicativo ou chat de programação, baixe e envie os dois arquivos: o JSON descreve os endpoints e seus parâmetros; o guia explica autenticação, créditos e uso do Estúdio.</p></header>
 <section className="rounded-xl border border-white/10 p-5"><h2 className="font-semibold">Primeira geração</h2><pre className="mt-4 overflow-x-auto text-xs leading-6 text-slate-300">{`curl https://www.connectyhub.com.br/api/v1/voice/generations \\\n  -H "Authorization: Bearer $CONNECTYHUB_VOICE_KEY" \\\n  -H "Idempotency-Key: pedido-voz-001" \\\n  -H "Content-Type: application/json" \\\n  -d '{"voice_id":"ID_DO_CATALOGO","text":"Olá! Como posso ajudar?"}'`}</pre></section>
 {voiceGuide.split('## ').slice(1).map(section=>{const [heading,...body]=section.split('\n');return <section key={heading} className="rounded-xl border border-white/10 p-5"><h2 className="text-lg font-semibold">{heading}</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-300">{body.join('\n').trim()}</p></section>;})}
 <section className="rounded-xl border border-white/10 p-5"><h2 className="mb-3 text-lg font-semibold">Referência de endpoints</h2>{Object.entries(voiceOpenApiSpec.paths).flatMap(([path,methods])=>Object.entries(methods).map(([method,operation])=><div key={method+path} className="border-t border-white/10 py-3"><p className="break-all font-mono text-xs"><strong className="mr-2 text-violet-300">{method.toUpperCase()}</strong>{path}</p><p className="mt-1 text-sm text-slate-400">{operation.summary}</p></div>))}</section>
 <section className="rounded-xl border border-white/10 p-5"><h2 className="font-semibold">Clonar e baixar com autorização</h2><pre className="mt-4 overflow-x-auto text-xs leading-6 text-slate-300">{`curl https://www.connectyhub.com.br/api/v1/voice/voices \\\n  -H "Authorization: Bearer $CONNECTYHUB_VOICE_KEY" \\\n  -H "Idempotency-Key: meu-clone-001" \\\n  -F "name=Minha voz" -F "consent_accepted=true" -F "files=@amostra.mp3"

curl https://www.connectyhub.com.br/api/v1/voice/generations/ID/audio \\\n  -H "Authorization: Bearer $CONNECTYHUB_VOICE_KEY" --output voz.mp3`}</pre></section>
 </article>;}
