'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
type Project={id:string;name:string;status:string;monthly_credit_limit:number|null;voice_api_keys:{id:string;name:string;key_prefix:string;status:string}[]};
type Voice={voice_id:string;name:string;kind:string;status:string;preview_url:string|null};
type Model={model_id:string;name:string;available:boolean;credits_per_character?:number;minimum_credits?:number};
type Summary={requests:number;completed:number;failed:number;pending:number;credits:number;reserved_credits:number;characters:number;daily:{day:string;requests:number;credits:number}[];models:{model_id:string;requests:number;credits:number}[];operations:{operation:string;requests:number;credits:number}[];voices:{voice_id:string;requests:number;credits:number}[];accounts?:{organization_id:string;name:string;requests:number;credits:number;estimated_cost:number;errors:number}[];estimated_provider_cost?:number;effective_provider_cost?:number|null;credit_value_brl?:number;estimated_margin_brl?:number};
type Receipt={id:string;status:string;usage:{credits:number;reserved_credits:number};audio:{path:string}|null};
type History={id:string;project_id:string;operation:string;status:string;charged_credits:number;reserved_credits:number;created_at:string;error_code:string|null};
const number=(n:unknown)=>Number(n??0).toLocaleString('pt-BR',{maximumFractionDigits:6});
async function readResponse(r:Response){const data=await r.json();if(!r.ok)throw new Error(data.error?.message??'Não foi possível concluir.');return data;}
const field='w-full rounded-xl border border-white/15 bg-[#111827] p-3 text-sm text-slate-100';
const button='rounded-xl bg-emerald-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40';
const box='rounded-2xl border border-white/10 bg-white/[0.025] p-5';
const base='/api/dashboard/voice';
export function VoiceConsole({admin=false}:{admin?:boolean}){
 const [tab,setTab]=useState(admin?'Gestão':'Estúdio'),[days,setDays]=useState('30'),[data,setData]=useState<{projects?:Project[];wallet?:{balance_credits:number;reserved_credits:number};summary:Summary;history?:History[]}|null>(null);
 const [cloning,setCloning]=useState<{available:boolean;credits?:number}>({available:false});
 const [project,setProject]=useState(''),[voices,setVoices]=useState<Voice[]>([]),[models,setModels]=useState<Model[]>([]),[voice,setVoice]=useState(''),[model,setModel]=useState('eleven_multilingual_v2'),[text,setText]=useState('');
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[secret,setSecret]=useState(''),[audio,setAudio]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null),[name,setName]=useState(''),[cloneName,setCloneName]=useState(''),[files,setFiles]=useState<File[]>([]),[consent,setConsent]=useState(false);
 const idempotency=useRef<{body:string;key:string}|null>(null),cloneIdem=useRef<string|null>(null);
 const refresh=useCallback(async()=>{const r=await fetch(`/api/${admin?'admin':'dashboard'}/voice?days=${days}`);const next=await readResponse(r);setData(next);if(!admin)setProject(p=>next.projects?.some((item:Project)=>item.id===p)?p:next.projects?.[0]?.id??'');},[admin,days]);
 useEffect(()=>{let active=true;fetch(`/api/${admin?'admin':'dashboard'}/voice?days=${days}`).then(readResponse).then(next=>{if(!active)return;setData(next);if(!admin)setProject(p=>next.projects?.some((item:Project)=>item.id===p)?p:next.projects?.[0]?.id??'');}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[admin,days]);
 const endpoint=(path:string,p=project)=>`${base}/${path}?project=${encodeURIComponent(p)}`;
 const loadCatalog=useCallback(async()=>{if(!project)return;const [v,m]=await Promise.all([fetch(`${base}/voices?project=${project}`).then(readResponse),fetch(`${base}/models?project=${project}`).then(readResponse)]);setVoices(v.voices);setModels(m.models);setCloning(m.cloning??{available:false});setVoice(current=>v.voices.some((item:Voice)=>item.voice_id===current)?current:v.voices.find((item:Voice)=>item.status==='ready')?.voice_id??'');},[project]);
 useEffect(()=>{if(!project)return;let active=true;Promise.all([fetch(`${base}/voices?project=${project}`).then(readResponse),fetch(`${base}/models?project=${project}`).then(readResponse)]).then(([v,m])=>{if(!active)return;setVoices(v.voices);setModels(m.models);setCloning(m.cloning??{available:false});setVoice(current=>v.voices.some((item:Voice)=>item.voice_id===current)?current:v.voices.find((item:Voice)=>item.status==='ready')?.voice_id??'');}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[project]);
 useEffect(()=>()=>{if(audio)URL.revokeObjectURL(audio);},[audio]);
 async function act(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Falha na operação.');}finally{setBusy(false);}}
 async function manage(body:Record<string,unknown>){const result=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(readResponse);if(result.secret)setSecret(result.secret);await refresh();return result;}
 async function play(r:Receipt,p=project){setReceipt(r);if(r.status!=='completed'||!r.audio){setMessage(`Solicitação ${r.id}: ${r.status}. Consulte novamente para recuperar; evite uma nova geração.`);return;}
  const response=await fetch(endpoint(`generations/${r.id}/audio`,p));if(!response.ok){await readResponse(response);return;}const blob=await response.blob();setAudio(URL.createObjectURL(blob));}
 const selected=models.find(m=>m.model_id===model),chars=text.replace(/\s+/g,' ').trim().length;
 const estimate=selected?.available?Math.max(selected.minimum_credits??0,chars*(selected.credits_per_character??0)):null;
 const summary=data?.summary;
 return <div className="mx-auto max-w-7xl space-y-6 rounded-3xl bg-[#0a111f] p-4 text-slate-100 md:p-8">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-emerald-300">ConnectyHub Voz</p><h1 className="mt-2 text-3xl font-semibold">{admin?'Operação de voz':'Dê voz às suas ideias'}</h1><p className="mt-2 text-sm text-slate-400">{admin?'Consumo e saúde do Estúdio e da API, por cliente.':'Estúdio, clones privados e API com os créditos da sua conta.'}</p></div><Link href="/docs/api#voz" className="text-sm text-emerald-300 underline">Documentação da API</Link></header>
  <div className="flex flex-wrap items-center gap-3">{!admin&&['Estúdio','API','Gestão'].map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-full px-5 py-2 text-sm ${tab===t?'bg-white text-slate-950':'bg-white/5 text-slate-300'}`}>{t}</button>)}<button className="ml-auto text-sm text-slate-300 underline" onClick={()=>act(refresh)} disabled={busy}>Atualizar</button></div>
  {message&&<p role="status" className="rounded-xl border border-amber-300/25 bg-amber-300/5 p-4 text-sm text-amber-200">{message}</p>}
  {!admin&&<div className="flex flex-wrap items-center gap-4"><label className="min-w-56 flex-1 text-sm">Projeto<select aria-label="Projeto de Voz" disabled={busy} className={`${field} mt-1`} value={project} onChange={e=>{setProject(e.target.value);setReceipt(null);setAudio('');}}>{!data?.projects?.length&&<option value="">Crie seu primeiro projeto na aba API</option>}{data?.projects?.map(p=><option key={p.id} value={p.id}>{p.name}{p.status!=='active'?' · pausado':''}</option>)}</select></label><p className="text-sm text-slate-400">Saldo disponível <strong className="block text-xl text-white">{number(Number(data?.wallet?.balance_credits??0)-Number(data?.wallet?.reserved_credits??0))} créditos</strong></p></div>}
  {tab==='Estúdio'&&!admin&&<div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]">
   <section className={box}><h2 className="mb-4 text-lg font-semibold">Gerar áudio</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Voz<select className={`${field} mt-1`} value={voice} onChange={e=>setVoice(e.target.value)}>{voices.filter(v=>v.status==='ready').map(v=><option key={v.voice_id} value={v.voice_id}>{v.name}{v.kind==='private'?' · privada':''}</option>)}</select></label><label className="text-sm">Modelo<select className={`${field} mt-1`} value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m.model_id} value={m.model_id} disabled={!m.available}>{m.name}{!m.available?' · tarifa indisponível':''}</option>)}</select></label></div>
    <label className="mt-4 block text-sm">Seu texto<textarea className={`${field} mt-1 min-h-48`} value={text} maxLength={4800} onChange={e=>setText(e.target.value)} placeholder="Escreva o que você quer transformar em voz."/></label><div className="mt-3 flex flex-wrap justify-between gap-3 text-sm text-slate-400"><span>{chars}/4800 caracteres</span><span>{chars&&estimate!==null?`Estimativa: ${number(estimate)} créditos`:'Escolha uma voz e escreva seu texto'}</span></div>
    <button className={`${button} mt-5`} disabled={busy||!project||!voice||!chars||!selected?.available} onClick={()=>act(async()=>{const body=JSON.stringify({text,voice_id:voice,model_id:model});const identity=project+body;if(idempotency.current?.body!==identity)idempotency.current={body:identity,key:crypto.randomUUID()};const result=await fetch(endpoint('generations'),{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotency.current.key},body}).then(readResponse);await play(result);await refresh();})}>{busy?'Processando…':'Gerar / recuperar áudio'}</button>
    {receipt&&<div className="mt-5 text-sm text-slate-400"><p>Estado: {receipt.status} · Débito: {number(receipt.usage.credits)} créditos</p><button className="mt-2 text-emerald-300 underline" onClick={()=>act(async()=>play(await fetch(endpoint(`generations/${receipt.id}`)).then(readResponse)))}>Consultar solicitação</button></div>}
    {audio&&<div className="mt-5"><audio controls src={audio} className="w-full"/><a download="connectyhub-voz.mp3" href={audio} className="mt-3 inline-block text-sm text-emerald-300 underline">Baixar MP3</a></div>}
   </section>
   <section className={box}><h2 className="text-lg font-semibold">Sua voz, privada</h2><p className="mt-2 text-sm text-slate-400">O clone pertence ao projeto selecionado. Outros clientes e projetos não têm acesso.</p><p className="mt-2 text-sm text-emerald-300">{cloning.available?`Criação: ${number(cloning.credits)} créditos · uma prévia incluída`:'Tarifa de clonagem indisponível'}</p><label className="mt-4 block text-sm">Nome<input className={`${field} mt-1`} value={cloneName} maxLength={80} onChange={e=>{setCloneName(e.target.value);cloneIdem.current=null;}}/></label><label className="mt-4 block text-sm">Amostras de áudio<input type="file" accept="audio/*,video/mp4" multiple className="mt-2 block w-full text-sm" onChange={e=>{setFiles(Array.from(e.target.files??[]));cloneIdem.current=null;}}/></label><p className="mt-2 text-xs text-slate-400">De 1 a 5 arquivos; até 3 MB no total.</p><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Tenho direito e consentimento para clonar esta voz.</label><button className={`${button} mt-5`} disabled={busy||!project||!cloning.available||!consent||!files.length||cloneName.trim().length<2} onClick={()=>act(async()=>{cloneIdem.current??=crypto.randomUUID();const form=new FormData();form.set('name',cloneName);form.set('consent_accepted','true');files.forEach(f=>form.append('files',f));const result=await fetch(endpoint('voices'),{method:'POST',headers:{'Idempotency-Key':cloneIdem.current},body:form}).then(readResponse);setMessage(`Clone: ${result.clone?.status??result.generation?.status}. ${result.generation?`Débito: ${number(result.generation.usage.credits)} créditos.`:''}`);await loadCatalog();await refresh();})}>Criar / recuperar clone</button>
    <div className="mt-6 space-y-3">{voices.filter(v=>v.kind==='private').map(v=><div className="rounded-xl bg-white/5 p-3" key={v.voice_id}><p className="text-sm font-medium">{v.name}</p><p className="text-xs text-slate-400">{v.status}</p><div className="mt-2 flex gap-3 text-xs"><button disabled={busy||v.status!=='ready'} className="text-emerald-300 underline" onClick={()=>act(async()=>{await play(await fetch(endpoint(`voices/${v.voice_id}/preview`),{method:'POST'}).then(readResponse));await refresh();})}>Prévia incluída</button><button disabled={busy} className="text-slate-300 underline" onClick={()=>act(async()=>{const next=window.prompt('Novo nome da voz',v.name);if(!next)return;await fetch(endpoint(`voices/${v.voice_id}`),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:next})}).then(readResponse);await loadCatalog();})}>Renomear</button><button disabled={busy} className="text-rose-300 underline" onClick={()=>act(async()=>{if(!window.confirm(`Excluir o clone ${v.name}?`))return;await fetch(endpoint(`voices/${v.voice_id}`),{method:'DELETE'}).then(readResponse);await loadCatalog();})}>Excluir</button></div></div>)}</div>
   </section>
  </div>}
  {tab==='API'&&!admin&&<div className="space-y-5"><section className={box}><h2 className="font-semibold">Projetos e chaves</h2><p className="mt-2 text-sm text-slate-400">Cada projeto tem seus próprios clones, áudios e recibos. A chave aparece uma única vez; trocá-la preserva os dados do projeto.</p><div className="mt-4 flex gap-3"><input className={field} placeholder="Nome do novo projeto" value={name} onChange={e=>setName(e.target.value)}/><button className={button} disabled={busy||!name.trim()} onClick={()=>act(async()=>{await manage({action:'create_project',name});setName('');})}>Criar</button></div>
   {secret&&<div className="mt-4 rounded-xl border border-amber-200/30 p-4"><p className="text-sm">Guarde esta chave. Ela não será exibida novamente.</p><code className="mt-2 block break-all text-sm">{secret}</code><button className="mt-3 text-sm underline" onClick={()=>navigator.clipboard.writeText(secret)}>Copiar</button><button className="ml-4 text-sm underline" onClick={()=>setSecret('')}>Ocultar</button></div>}
   {data?.projects?.map(p=><article key={p.id} className="mt-5 border-t border-white/10 pt-4"><div className="flex flex-wrap items-center gap-3"><h3 className="font-medium">{p.name}</h3><span className="text-xs text-slate-400">{p.status} · Limite mensal: {p.monthly_credit_limit?`${number(p.monthly_credit_limit)} créditos`:'sem limite por projeto'}</span><button className="text-xs text-emerald-300 underline" disabled={busy} onClick={()=>act(async()=>{await manage({action:'create_key',project_id:p.id,name:'Chave de Voz'});})}>Nova chave</button><button className="text-xs underline" disabled={busy} onClick={()=>act(async()=>{const raw=window.prompt('Limite mensal em créditos (vazio = sem limite)',p.monthly_credit_limit?.toString()??'');if(raw===null)return;await manage({action:'update_project',project_id:p.id,status:p.status,monthly_credit_limit:raw.trim()?Number(raw):null});})}>Definir limite</button><button className="text-xs underline" disabled={busy} onClick={()=>act(async()=>{await manage({action:'update_project',project_id:p.id,status:p.status==='active'?'paused':'active',monthly_credit_limit:p.monthly_credit_limit});})}>{p.status==='active'?'Pausar':'Ativar'}</button></div><code className="text-xs text-slate-500">{p.id}</code>{p.voice_api_keys.map(k=><div key={k.id} className="mt-3 flex items-center gap-3 text-sm"><span>{k.name}</span><code>{k.key_prefix}…</code><span className="text-slate-400">{k.status}</span>{k.status==='active'&&<button className="text-xs text-rose-300 underline" onClick={()=>act(async()=>{if(!window.confirm('Revogar esta chave?'))return;await manage({action:'revoke_key',project_id:p.id,key_id:k.id});})}>Revogar</button>}</div>)}</article>)}
  </section><section className={box}><h2 className="font-semibold">Comece pela API</h2><p className="mt-2 text-sm text-slate-400">Consulte as vozes antes de gerar. Use a mesma Idempotency-Key para recuperar uma tentativa após timeout.</p><pre className="mt-4 overflow-x-auto rounded-xl bg-black/30 p-4 text-xs">{'curl https://www.connectyhub.com.br/api/v1/voice/voices \\\n  -H "Authorization: Bearer $CONNECTYHUB_VOICE_KEY"'}</pre><Link href="/docs/api#voz" className="mt-3 inline-block text-sm text-emerald-300 underline">Clonagem, geração, download e exemplos completos →</Link></section></div>}
  {tab==='Gestão'&&<section className="space-y-5"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Uso do Estúdio e da API</h2><select aria-label="Período de uso" className={`${field} max-w-44`} value={days} onChange={e=>setDays(e.target.value)}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option></select></div>
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Solicitações',summary?.requests],['Concluídas',summary?.completed],['Créditos debitados',summary?.credits],['Falhas / pendentes',`${number(summary?.failed)} / ${number(summary?.pending)}`]].map(([label,value])=><div className={box} key={String(label)}><p className="text-sm text-slate-400">{label}</p><strong className="mt-2 block text-2xl">{typeof value==='string'?value:number(value)}</strong></div>)}</div>
   <div className={box}><h3 className="font-medium">Créditos por dia · UTC</h3>{!summary?.daily.length?<p className="mt-6 text-sm text-slate-400">Nenhuma operação registrada neste período.</p>:<div className="mt-4 flex h-44 items-end gap-1" role="img" aria-label="Consumo diário em créditos">{summary.daily.map(d=><div key={d.day} title={`${d.day}: ${number(d.credits)} créditos; ${d.requests} solicitações`} className="flex h-full min-w-0 flex-1 items-end"><div className="w-full rounded-t bg-emerald-400" style={{height:`${Math.max(0,Number(d.credits)/Math.max(1,...summary.daily.map(v=>Number(v.credits)))*100)}%`}}/></div>)}</div>}<p className="mt-3 text-xs text-slate-500">Valores derivados dos recibos reais. Passe o cursor nas barras para ver o dia.</p></div>
   <div className="grid gap-5 lg:grid-cols-3">{[['Modelos',summary?.models?.map(v=>({label:v.model_id,...v}))],['Operações',summary?.operations?.map(v=>({label:v.operation,...v}))],['Vozes',summary?.voices?.map(v=>({label:v.voice_id,...v}))]].map(([label,rows])=><div className={box} key={String(label)}><h3 className="font-medium">{String(label)}</h3>{(rows as {label:string;requests:number;credits:number}[]|undefined)?.map(row=><div key={row.label} className="mt-3 text-sm"><p className="break-all text-slate-300">{row.label}</p><p className="text-xs text-slate-500">{row.requests} solicitações · {number(row.credits)} créditos</p></div>)}</div>)}</div>
   {admin&&summary&&<><div className="grid gap-3 md:grid-cols-3">{[['Custo estimado do fornecedor (R$)',summary.estimated_provider_cost],['Valor equivalente dos créditos (R$)',summary.credit_value_brl],['Margem estimada (R$)',summary.estimated_margin_brl]].map(([label,value])=><div className={box} key={String(label)}><p className="text-sm text-slate-400">{label}</p><strong className="text-xl">{number(value)}</strong></div>)}</div><p className="text-xs text-slate-400">Custos estimados pelas tarifas configuradas. Custo efetivo conciliado: {summary.effective_provider_cost==null?'ainda não disponível':number(summary.effective_provider_cost)}. Valor de créditos consumidos não equivale a receita recebida neste período.</p><div className={`${box} overflow-x-auto`}><table className="w-full text-left text-sm"><thead><tr><th>Cliente</th><th>Operações</th><th>Créditos</th><th>Falhas/pendências</th></tr></thead><tbody>{summary.accounts?.map(a=><tr key={a.organization_id} className="border-t border-white/10"><td className="py-3">{a.name}</td><td>{a.requests}</td><td>{number(a.credits)}</td><td>{a.errors}</td></tr>)}</tbody></table></div></>}
   {!admin&&<div className={`${box} overflow-x-auto`}><h3 className="mb-4 font-medium">Últimas 50 solicitações</h3><table className="w-full text-left text-sm"><thead><tr><th>Data</th><th>Operação</th><th>Estado</th><th>Créditos</th><th>Erro</th></tr></thead><tbody>{data?.history?.map(r=><tr key={r.id} className="border-t border-white/10"><td className="py-3">{new Date(r.created_at).toLocaleString('pt-BR')}</td><td>{r.operation}</td><td>{r.status}</td><td>{number(r.charged_credits)}</td><td>{r.error_code??'—'}</td></tr>)}</tbody></table></div>}
  </section>}
 </div>;
}
