'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Code2,ArrowRight,RefreshCw,Plus,KeyRound} from 'lucide-react';
import {CreditExplainer} from './credit-explainer';
import {VoiceUsageCharts} from './voice-usage-charts';
type Project={id:string;name:string;status:string;monthly_credit_limit:number|null;voice_api_keys:{id:string;name:string;key_prefix:string;status:string}[]};
type Voice={voice_id:string;name:string;kind:string;status:string;preview_url:string|null};
type Model={model_id:string;name:string;available:boolean;credits_per_character?:number;minimum_credits?:number};
type Summary={requests:number;completed:number;failed:number;pending:number;credits:number;reserved_credits:number;characters:number;daily:{day:string;requests:number;credits:number}[];models:{model_id:string;requests:number;credits:number}[];operations:{operation:string;requests:number;credits:number}[];voices:{voice_id:string;requests:number;credits:number}[];accounts?:{organization_id:string;name:string;requests:number;credits:number;estimated_cost:number;errors:number}[];estimated_provider_cost?:number;effective_provider_cost?:number|null;credit_value_brl?:number;estimated_margin_brl?:number};
type Receipt={id:string;status:string;usage:{credits:number;reserved_credits:number};audio:{path:string}|null};
type History={id:string;project_id:string;operation:string;status:string;charged_credits:number;reserved_credits:number;created_at:string;error_code:string|null};
const number=(n:unknown)=>Number(n??0).toLocaleString('pt-BR',{maximumFractionDigits:6});
async function readResponse(r:Response){const data=await r.json();if(!r.ok)throw new Error(data.error?.message??'Não foi possível concluir.');return data;}
const field='min-h-11 w-full min-w-0 rounded-xl border border-slate-300 bg-white p-3 text-sm text-slate-900 focus:outline-2 focus:outline-blue-500';
const button='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-800 disabled:opacity-50';
const box='min-w-0 rounded-2xl border border-slate-200 bg-white p-5';
const statusLabels:Record<string,string>={active:'Ativo',paused:'Pausado',ready:'Pronta para usar',revoked:'Revogada',completed:'Concluída',failed:'Não concluída',reserved:'Em andamento',processing:'Em andamento',uncertain:'Em conferência',verification_required:'Aguardando verificação'};
const operationLabels:Record<string,string>={text_to_speech:'Geração de áudio',voice_clone:'Clonagem de voz',voice_clone_preview:'Prévia de voz'};
const base='/api/dashboard/voice';
export function VoiceConsole({admin=false}:{admin?:boolean}){
 const [tab,setTab]=useState('Gestão'),[days,setDays]=useState('30'),[data,setData]=useState<{projects?:Project[];wallet?:{balance_credits:number;reserved_credits:number};summary:Summary;history?:History[]}|null>(null);
 const [catalogProject,setCatalogProject]=useState('');
 const [cloning,setCloning]=useState<{available:boolean;credits?:number}>({available:false});
 const [project,setProject]=useState(''),[voices,setVoices]=useState<Voice[]>([]),[models,setModels]=useState<Model[]>([]),[voice,setVoice]=useState(''),[model,setModel]=useState('eleven_multilingual_v2'),[text,setText]=useState('');
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[secret,setSecret]=useState(''),[audio,setAudio]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null),[name,setName]=useState(''),[cloneName,setCloneName]=useState(''),[files,setFiles]=useState<File[]>([]),[consent,setConsent]=useState(false);
 const idempotency=useRef<{body:string;key:string}|null>(null),cloneIdem=useRef<string|null>(null);
 const refresh=useCallback(async()=>{const r=await fetch(`/api/${admin?'admin':'dashboard'}/voice?days=${days}`);const next=await readResponse(r);setData(next);if(!admin)setProject(p=>next.projects?.some((item:Project)=>item.id===p)?p:next.projects?.[0]?.id??'');},[admin,days]);
 useEffect(()=>{let active=true;fetch(`/api/${admin?'admin':'dashboard'}/voice?days=${days}`).then(readResponse).then(next=>{if(!active)return;setData(next);if(!admin)setProject(p=>next.projects?.some((item:Project)=>item.id===p)?p:next.projects?.[0]?.id??'');}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[admin,days]);
 const endpoint=(path:string,p=project)=>`${base}/${path}?project=${encodeURIComponent(p)}`;
 const loadCatalog=useCallback(async()=>{if(!project)return;const [v,m]=await Promise.all([fetch(`${base}/voices?project=${project}`).then(readResponse),fetch(`${base}/models?project=${project}`).then(readResponse)]);setVoices(v.voices);setModels(m.models);setCloning(m.cloning??{available:false});setCatalogProject(project);setVoice(current=>v.voices.some((item:Voice)=>item.voice_id===current)?current:v.voices.find((item:Voice)=>item.status==='ready')?.voice_id??'');},[project]);
 useEffect(()=>{if(!project)return;let active=true;Promise.all([fetch(`${base}/voices?project=${project}`).then(readResponse),fetch(`${base}/models?project=${project}`).then(readResponse)]).then(([v,m])=>{if(!active)return;setVoices(v.voices);setModels(m.models);setCloning(m.cloning??{available:false});setCatalogProject(project);setVoice(current=>v.voices.some((item:Voice)=>item.voice_id===current)?current:v.voices.find((item:Voice)=>item.status==='ready')?.voice_id??'');}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[project]);
 useEffect(()=>()=>{if(audio)URL.revokeObjectURL(audio);},[audio]);
 async function act(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Falha na operação.');}finally{setBusy(false);}}
 async function manage(body:Record<string,unknown>){const result=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(readResponse);if(result.secret)setSecret(result.secret);await refresh();return result;}
 async function play(r:Receipt,p=project){setReceipt(r);if(r.status!=='completed'||!r.audio){setMessage(`Solicitação ${r.id}: ${r.status}. Consulte novamente para recuperar; evite uma nova geração.`);return;}
  const response=await fetch(endpoint(`generations/${r.id}/audio`,p));if(!response.ok){await readResponse(response);return;}const blob=await response.blob();setAudio(URL.createObjectURL(blob));}
 const selected=models.find(m=>m.model_id===model),chars=text.replace(/\s+/g,' ').trim().length;
 const estimate=selected?.available?Math.max(selected.minimum_credits??0,chars*(selected.credits_per_character??0)):null;
 const summary=data?.summary;
 const catalogReady=!!project&&catalogProject===project;
 return <div className="mx-auto min-w-0 max-w-6xl space-y-6 text-slate-900">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">{admin?'Operação da plataforma':'Seus projetos conectados'}</p><h1 className="mt-2 text-3xl font-bold">API de Voz</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-600">{admin?'Acompanhe o consumo, os custos e os resultados de voz por cliente.':'Crie áudios no Estúdio ou conecte seu aplicativo. Gerencie vozes privadas e acompanhe tudo em créditos ConnectyHub.'}</p></div><Link href="/docs/api#voz" className={button}><Code2 size={17}/>Documentação</Link></header>
  {!admin&&<div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="min-w-0"><p className="text-sm text-slate-600">Saldo disponível da conta</p><p className="mt-1 break-words text-3xl font-bold tracking-tight text-blue-900">{data?number(Math.max(0,Number(data.wallet?.balance_credits??0)-Number(data.wallet?.reserved_credits??0))):'…'}<span className="ml-2 text-sm font-medium">créditos</span></p><p className="mt-2 text-xs leading-6 text-slate-600">O mesmo saldo para seus projetos e atendimentos.{data&&Number(data.wallet?.reserved_credits)>0?` ${number(data.wallet?.reserved_credits)} créditos em processamento.`:''}</p></div><Link href="/dashboard/creditos" className={button}>Adicionar créditos<ArrowRight size={16}/></Link></div>}
  {!admin&&<nav aria-label="Painel da API de Voz" className="grid grid-cols-3 gap-1 border-b border-slate-200 sm:flex">{[['Gestão','Painel de uso'],['API','Projetos e chaves'],['Estúdio','Estúdio de Voz']].map(([value,label])=><button key={value} aria-current={tab===value?'page':undefined} onClick={()=>setTab(value)} className={`min-h-12 min-w-0 border-b-2 px-2 py-3 text-xs font-semibold sm:px-4 sm:text-sm ${tab===value?'border-blue-700 text-blue-800':'border-transparent text-slate-500 hover:text-slate-900'}`}>{label}</button>)}</nav>}
  {message&&<p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{message}</p>}
  <div className="flex flex-wrap items-end gap-3">
   {!admin&&tab==='Estúdio'&&<label className="min-w-0 flex-1 text-sm font-medium">Projeto<select aria-label="Projeto de Voz" disabled={busy||!data} className={`${field} mt-2`} value={project} onChange={e=>{setProject(e.target.value);setReceipt(null);setAudio('');}}>{!data?.projects?.length&&<option value="">{data?'Crie seu primeiro projeto':'Carregando projetos…'}</option>}{data?.projects?.map(p=><option key={p.id} value={p.id}>{p.name}{p.status!=='active'?' · pausado':''}</option>)}</select></label>}
   {tab==='Gestão'&&<><div className="min-w-40 flex-1"><h2 className="font-bold">Uso do Estúdio e da API</h2><p className="mt-1 text-sm text-slate-500">{admin?'Todos os clientes · período selecionado':'Todos os projetos da sua conta · período selecionado'}</p></div><label className="text-sm font-medium">Período<select aria-label="Período de uso" className={`${field} mt-2`} value={days} onChange={e=>{setData(null);setDays(e.target.value);}}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option></select></label></>}
   <button aria-label="Atualizar API de Voz" className="ml-auto grid size-11 shrink-0 place-items-center rounded-xl border border-slate-300 bg-white hover:bg-slate-50 disabled:opacity-50" onClick={()=>act(refresh)} disabled={busy}><RefreshCw size={17} className={busy?'animate-spin':''}/></button>
  </div>
  {!data?<p role="status" className="py-12 text-center text-sm text-slate-500">{message?'Não foi possível carregar os dados. Tente atualizar.':'Carregando sua API de Voz…'}</p>:<>
  {!admin&&!data.projects?.length&&<div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-dashed border-blue-300 bg-white p-6"><div><h2 className="font-bold">Conecte seu primeiro projeto</h2><p className="mt-2 text-sm text-slate-600">Organize as vozes, os áudios e as chaves do seu aplicativo em um projeto.</p></div><button className={button} onClick={()=>setTab('API')}><Plus size={16}/>Criar meu projeto</button></div>}
  {!admin&&tab==='Estúdio'&&project&&!catalogReady&&<p role="status" className="text-sm text-slate-500">Carregando vozes e modelos do projeto…</p>}
  {tab==='Estúdio'&&!admin&&<div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]">
   <section className={box}><h2 className="mb-4 text-lg font-bold">Estúdio de Voz</h2><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Voz<select className={`${field} mt-1`} disabled={!catalogReady||busy} value={voice} onChange={e=>setVoice(e.target.value)}>{voices.filter(v=>catalogReady&&v.status==='ready').map(v=><option key={v.voice_id} value={v.voice_id}>{v.name}{v.kind==='private'?' · privada':''}</option>)}</select></label><label className="text-sm">Modelo<select className={`${field} mt-1`} disabled={!catalogReady||busy} value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m.model_id} value={m.model_id} disabled={!m.available}>{m.name}{!m.available?' · tarifa indisponível':''}</option>)}</select></label></div>
    <label className="mt-4 block text-sm">Seu texto<textarea className={`${field} mt-1 min-h-48`} value={text} maxLength={4800} onChange={e=>setText(e.target.value)} placeholder="Escreva o que você quer transformar em voz."/></label><div className="mt-3 flex flex-wrap justify-between gap-3 text-sm text-slate-500"><span>{chars}/4800 caracteres</span><span>{chars&&estimate!==null?`Estimativa: ${number(estimate)} créditos`:'Escolha uma voz e escreva seu texto'}</span></div>
    <button className={`${button} mt-5`} disabled={busy||!catalogReady||!project||!voice||!chars||!selected?.available} onClick={()=>act(async()=>{const body=JSON.stringify({text,voice_id:voice,model_id:model});const identity=project+body;if(idempotency.current?.body!==identity)idempotency.current={body:identity,key:crypto.randomUUID()};const result=await fetch(endpoint('generations'),{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotency.current.key},body}).then(readResponse);await play(result);await refresh();})}>{busy?'Processando…':'Gerar / recuperar áudio'}</button>
    {receipt&&<div className="mt-5 text-sm text-slate-500"><p>Estado: {statusLabels[receipt.status]??receipt.status} · Débito: {number(receipt.usage.credits)} créditos</p><button className="mt-2 text-blue-800 underline" onClick={()=>act(async()=>play(await fetch(endpoint(`generations/${receipt.id}`)).then(readResponse)))}>Consultar solicitação</button></div>}
    {audio&&<div className="mt-5"><audio controls src={audio} className="w-full"/><a download="connectyhub-voz.mp3" href={audio} className="mt-3 inline-block text-sm text-blue-800 underline">Baixar MP3</a></div>}
   </section>
   <section className={box}><h2 className="text-lg font-bold">Suas vozes privadas</h2><p className="mt-2 text-sm text-slate-500">O clone pertence ao projeto selecionado. Outros clientes e projetos não têm acesso.</p><p className="mt-2 text-sm text-blue-800">{!catalogReady?'Selecione um projeto para consultar a tarifa.':cloning.available?`Criação: ${number(cloning.credits)} créditos · uma prévia incluída`:'Tarifa de clonagem indisponível'}</p><label className="mt-4 block text-sm">Nome<input className={`${field} mt-1`} value={cloneName} maxLength={80} onChange={e=>{setCloneName(e.target.value);cloneIdem.current=null;}}/></label><label className="mt-4 block text-sm">Amostras de áudio<input type="file" accept="audio/*,video/mp4" multiple className="mt-2 block w-full text-sm" onChange={e=>{setFiles(Array.from(e.target.files??[]));cloneIdem.current=null;}}/></label><p className="mt-2 text-xs text-slate-500">De 1 a 5 arquivos; até 3 MB no total.</p><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Tenho direito e consentimento para clonar esta voz.</label><button className={`${button} mt-5`} disabled={busy||!catalogReady||!project||!cloning.available||!consent||!files.length||cloneName.trim().length<2} onClick={()=>act(async()=>{cloneIdem.current??=crypto.randomUUID();const form=new FormData();form.set('name',cloneName);form.set('consent_accepted','true');files.forEach(f=>form.append('files',f));const result=await fetch(endpoint('voices'),{method:'POST',headers:{'Idempotency-Key':cloneIdem.current},body:form}).then(readResponse);setMessage(`Clone: ${result.clone?.status??result.generation?.status}. ${result.generation?`Débito: ${number(result.generation.usage.credits)} créditos.`:''}`);await loadCatalog();await refresh();})}>Criar / recuperar clone</button>
    <div className="mt-6 space-y-3">{voices.filter(v=>catalogReady&&v.kind==='private').map(v=><div className="rounded-xl bg-slate-50 p-3" key={v.voice_id}><p className="text-sm font-medium">{v.name}</p><p className="text-xs text-slate-500">{statusLabels[v.status]??'Em conferência'}</p><div className="mt-2 flex flex-wrap gap-3 text-xs [&>button]:min-h-11"><button disabled={busy||v.status!=='ready'} className="text-blue-800 underline" onClick={()=>act(async()=>{await play(await fetch(endpoint(`voices/${v.voice_id}/preview`),{method:'POST'}).then(readResponse));await refresh();})}>Prévia incluída</button><button disabled={busy} className="text-slate-700 underline" onClick={()=>act(async()=>{const next=window.prompt('Novo nome da voz',v.name);if(!next)return;await fetch(endpoint(`voices/${v.voice_id}`),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:next})}).then(readResponse);await loadCatalog();})}>Renomear</button><button disabled={busy} className="text-red-700 underline" onClick={()=>act(async()=>{if(!window.confirm(`Excluir o clone ${v.name}?`))return;await fetch(endpoint(`voices/${v.voice_id}`),{method:'DELETE'}).then(readResponse);await loadCatalog();})}>Excluir</button></div></div>)}</div>
   </section>
  </div>}
  {tab==='API'&&!admin&&<div className="space-y-5"><section className={box}><h2 className="font-semibold">Projetos e chaves</h2><p className="mt-2 text-sm text-slate-500">Cada projeto tem seus próprios clones, áudios e recibos. A chave aparece uma única vez; trocá-la preserva os dados do projeto.</p><div className="mt-4 flex flex-wrap items-end gap-3"><input aria-label="Nome do novo projeto" maxLength={100} className={`${field} flex-1`} placeholder="Nome do novo projeto" value={name} onChange={e=>setName(e.target.value)}/><button className={button} disabled={busy||!name.trim()} onClick={()=>act(async()=>{await manage({action:'create_project',name});setName('');})}><Plus size={16}/>Criar projeto</button></div>
   {secret&&<div className="mt-4 rounded-xl border border-emerald-300 bg-emerald-50 p-4"><p className="text-sm">Guarde esta chave. Ela não será exibida novamente.</p><code className="mt-2 block break-all text-sm">{secret}</code><button className="mt-3 text-sm underline" onClick={()=>navigator.clipboard.writeText(secret)}>Copiar</button><button className="ml-4 text-sm underline" onClick={()=>setSecret('')}>Ocultar</button></div>}
   {data?.projects?.map(p=><article key={p.id} className="mt-5 rounded-2xl border border-slate-200 p-5"><div className="flex flex-wrap items-center gap-3"><h3 className="font-medium">{p.name}</h3><span className="text-xs text-slate-500">{statusLabels[p.status]??p.status} · Limite mensal: {p.monthly_credit_limit?`${number(p.monthly_credit_limit)} créditos`:'sem limite por projeto'}</span><button className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 px-3 text-sm font-semibold text-blue-800" disabled={busy} onClick={()=>act(async()=>{await manage({action:'create_key',project_id:p.id,name:'Chave de Voz'});})}><KeyRound size={14} className="mr-1 inline"/>Nova chave</button><button className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm" disabled={busy} onClick={()=>act(async()=>{const raw=window.prompt('Limite mensal em créditos (vazio = sem limite)',p.monthly_credit_limit?.toString()??'');if(raw===null)return;await manage({action:'update_project',project_id:p.id,status:p.status,monthly_credit_limit:raw.trim()?Number(raw):null});})}>Definir limite</button><button className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm" disabled={busy} onClick={()=>act(async()=>{await manage({action:'update_project',project_id:p.id,status:p.status==='active'?'paused':'active',monthly_credit_limit:p.monthly_credit_limit});})}>{p.status==='active'?'Pausar':'Ativar'}</button></div><code className="break-all text-xs text-slate-500">{p.id}</code>{p.voice_api_keys.map(k=><div key={k.id} className="mt-3 flex flex-wrap items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm"><span>{k.name}</span><code>{k.key_prefix}…</code><span className="text-slate-500">{k.status==='active'?'Ativa':'Revogada'}</span>{k.status==='active'&&<button className="min-h-11 px-2 text-sm font-semibold text-red-700" disabled={busy} onClick={()=>act(async()=>{if(!window.confirm('Revogar esta chave?'))return;await manage({action:'revoke_key',project_id:p.id,key_id:k.id});})}>Revogar</button>}</div>)}</article>)}
  </section><section className={box}><h2 className="font-semibold">Comece pela API</h2><p className="mt-2 text-sm text-slate-500">Consulte as vozes antes de gerar. Use a mesma Idempotency-Key para recuperar uma tentativa após timeout.</p><pre className="mt-4 overflow-x-auto rounded-xl bg-slate-50 p-4 text-xs">{'curl https://www.connectyhub.com.br/api/v1/voice/voices \\\n  -H "Authorization: Bearer $CONNECTYHUB_VOICE_KEY"'}</pre><Link href="/docs/api#voz" className="mt-3 inline-block text-sm text-blue-800 underline">Clonagem, geração, download e exemplos completos →</Link></section></div>}
  {tab==='Gestão'&&summary&&<section className="space-y-5">
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Solicitações',summary?.requests],['Concluídas',summary?.completed],['Créditos debitados',summary?.credits],['Falhas / pendentes',`${number(summary?.failed)} / ${number(summary?.pending)}`]].map(([label,value])=><div className={box} key={String(label)}><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-2xl">{typeof value==='string'?value:number(value)}</strong></div>)}</div>
   <VoiceUsageCharts daily={summary.daily}/>
   <p className="text-xs leading-6 text-slate-500">Os gráficos usam recibos reais, agrupados em UTC. Atualize para acompanhar novas solicitações.</p>
   <div className="grid gap-5 lg:grid-cols-3">{[['Modelos',summary?.models?.map(v=>({label:v.model_id,...v}))],['Operações',summary?.operations?.map(v=>({label:operationLabels[v.operation]??v.operation,...v}))],['Vozes',summary?.voices?.map(v=>({label:voices.find(voice=>voice.voice_id===v.voice_id)?.name??v.voice_id,...v}))]].map(([label,rows])=><div className={box} key={String(label)}><h3 className="font-bold">{String(label)}</h3>{!(rows as unknown[]|undefined)?.length&&<p className="mt-4 text-sm text-slate-500">Nenhum consumo neste período.</p>}{(rows as {label:string;requests:number;credits:number}[]|undefined)?.map(row=><div key={row.label} className="mt-3 text-sm"><p className="break-all text-slate-700">{row.label}</p><p className="text-xs text-slate-500">{row.requests} solicitações · {number(row.credits)} créditos</p></div>)}</div>)}</div>
   {admin&&summary&&<><div className="grid gap-3 md:grid-cols-3">{[['Custo estimado do fornecedor (R$)',summary.estimated_provider_cost],['Valor equivalente dos créditos (R$)',summary.credit_value_brl],['Margem estimada (R$)',summary.estimated_margin_brl]].map(([label,value])=><div className={box} key={String(label)}><p className="text-sm text-slate-500">{label}</p><strong className="text-xl">{number(value)}</strong></div>)}</div><p className="text-xs text-slate-500">Custos estimados pelas tarifas configuradas. Custo efetivo conciliado: {summary.effective_provider_cost==null?'ainda não disponível':number(summary.effective_provider_cost)}. Valor de créditos consumidos não equivale a receita recebida neste período.</p><div className={`${box} overflow-x-auto`}><table className="w-full text-left text-sm"><thead><tr><th>Cliente</th><th>Operações</th><th>Créditos</th><th>Falhas/pendências</th></tr></thead><tbody>{summary.accounts?.map(a=><tr key={a.organization_id} className="border-t border-slate-200"><td className="py-3">{a.name}</td><td>{a.requests}</td><td>{number(a.credits)}</td><td>{a.errors}</td></tr>)}</tbody></table></div></>}
   {!admin&&<section className={box}><h3 className="text-lg font-bold">Atividades recentes</h3><p className="mt-1 text-sm text-slate-500">Até 50 solicitações mais recentes do período selecionado.</p>{!data.history?.length&&<p className="mt-5 text-sm text-slate-500">Nenhuma solicitação neste período.</p>}{data.history?.map(r=><details key={r.id} className="mt-3 rounded-xl border border-slate-200 p-4 text-sm"><summary className="cursor-pointer leading-7"><strong>{data.projects?.find(p=>p.id===r.project_id)?.name??'Projeto'}</strong><span className="ml-3">{number(r.charged_credits)} créditos</span><span className="ml-3 text-slate-500">{statusLabels[r.status]??'Em conferência'}</span></summary><div className="mt-3 space-y-2 text-xs leading-6 text-slate-500"><p>{new Date(r.created_at).toLocaleString('pt-BR')} · {operationLabels[r.operation]??r.operation}</p><p className="break-all">Solicitação: {r.id}</p>{Number(r.reserved_credits)>0&&<p>{number(r.reserved_credits)} créditos em processamento.</p>}{r.error_code&&<p className="break-words text-amber-800">Código de erro: {r.error_code}</p>}</div></details>)}</section>}

  </section>}
  </>}
  {!admin&&<CreditExplainer/>}
 </div>;
}
