import {describe,it,expect} from 'vitest';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {diskStore,digest,copyObjects} from '../services/managed-objects/disk-store.mjs';
import {signObjectCapability,verifyObjectCapability} from '../services/managed-objects/protocol.mjs';
import {objectServer} from '../services/managed-objects/server.mjs';
const a='30000000-0000-4000-8000-000000000001',b='30000000-0000-4000-8000-000000000002',file='40000000-0000-4000-8000-000000000001';const secret='fictional-local-signing-secret-for-objects';
async function fixture(){const path=await mkdtemp(join(tmpdir(),'managed-object-test-'));return {path,store:await diskStore(join(path,'source')),async close(){const target=resolve(path);if(!target.startsWith(resolve(tmpdir())+sep)||!target.split(sep).at(-1)?.startsWith('managed-object-test-'))throw Error('Unexpected test path');await rm(target,{recursive:true,force:true});}};}
describe('private object adapter',()=>{
 it('binds capability to exact object, method, content and expiration',()=>{const now=Date.now(),claim={project:a,object:file,method:'PUT',bytes:3,sha256:digest(Buffer.from('abc')),expires:now+30000};const token=signObjectCapability(claim,secret,now);expect(verifyObjectCapability(token,secret,'PUT',`/objects/${a}/${file}`,now)).toEqual(claim);for(const [method,path]of [['GET',`/objects/${a}/${file}`],['PUT',`/objects/${b}/${file}`]])expect(()=>verifyObjectCapability(token,secret,method,path,now)).toThrow();expect(()=>verifyObjectCapability(token,secret,'PUT',`/objects/${a}/${file}`,now+60000)).toThrow();expect(()=>verifyObjectCapability(token+'x',secret,'PUT',`/objects/${a}/${file}`,now)).toThrow();});
 it('keeps immutable bytes, denies traversal and prevents resurrection after deletion',async()=>{const f=await fixture();try{const bytes=Buffer.from('private');await f.store.put(a,file,bytes,digest(bytes));await f.store.put(a,file,bytes,digest(bytes));expect(await f.store.get(a,file,digest(bytes),bytes.length)).toEqual(bytes);await expect(f.store.get(b,file,digest(bytes),bytes.length)).rejects.toThrow();await expect(f.store.put('../escape',file,bytes,digest(bytes))).rejects.toThrow();await expect(f.store.put(a,file,Buffer.from('other'),digest(Buffer.from('other')))).rejects.toThrow();await f.store.delete(a,file);await f.store.delete(a,file);await expect(f.store.put(a,file,bytes,digest(bytes))).rejects.toThrow('object_deleted');await expect(f.store.get(a,file,digest(bytes),bytes.length)).rejects.toThrow();}finally{await f.close();}});
 it('restores into another root, verifies checksums and keeps deletion tombstones',async()=>{const f=await fixture();try{const bytes=Buffer.from('restorable');await f.store.put(a,file,bytes,digest(bytes));await f.store.delete(b,file);const target=await diskStore(join(f.path,'restored'));const manifest=await copyObjects(f.store,target);expect(manifest).toHaveLength(2);expect(await target.get(a,file,digest(bytes),bytes.length)).toEqual(bytes);await expect(target.put(b,file,bytes,digest(bytes))).rejects.toThrow();const path=join(f.path,'restored',a,file,'content');expect(await readFile(path)).toEqual(bytes);await writeFile(path,'corrupted');await expect(target.get(a,file,digest(bytes),bytes.length)).rejects.toThrow('integrity_mismatch');}finally{await f.close();}});
 it('enforces scoped capabilities over real HTTP without exposing storage paths',async()=>{const f=await fixture();const server=objectServer(f.store,secret);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();if(!address||typeof address==='string')throw Error('Bad address');const base=`http://127.0.0.1:${address.port}`;const bytes=Buffer.from('http-private'),claim={project:a,object:file,bytes:bytes.length,sha256:digest(bytes),expires:Date.now()+30000};const url=base+`/objects/${a}/${file}`;try{const put=signObjectCapability({...claim,method:'PUT'},secret);expect((await fetch(url,{method:'PUT',headers:{Authorization:`Bearer ${put}`},body:bytes})).status).toBe(200);expect((await fetch(url,{headers:{Authorization:`Bearer ${put}`}})).status).toBe(403);const get=signObjectCapability({...claim,method:'GET'},secret);expect(await(await fetch(url,{headers:{Authorization:`Bearer ${get}`}})).text()).toBe('http-private');expect((await fetch(base+`/objects/${b}/${file}`,{headers:{Authorization:`Bearer ${get}`}})).status).toBe(403);}finally{await new Promise<void>(r=>server.close(()=>r()));await f.close();}});
});
