import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {managedDatabaseFixture,ids} from './helpers/managed-database';
const file='50000000-0000-4000-8000-000000000001',other='50000000-0000-4000-8000-000000000002',sha='a'.repeat(64);
async function fixture(){const f=await managedDatabaseFixture();await f.db.exec(readFileSync('supabase/migrations/0151_managed_objects.sql','utf8'));return f;}
const reserve=(f:Awaited<ReturnType<typeof fixture>>,user=ids.a,project=ids.pA,key=file,bytes=7)=>f.as(user,'select managed_object_reserve($1,$2,$3,$4,$5) result',[project,key,'file.txt',bytes,sha]);
describe('private object catalog authorization and recovery states',()=>{
 it('keeps client scope and reserves shared quota even before transport completes',async()=>{const f=await fixture();try{await f.db.query('update managed_projects set storage_limit_bytes=10 where id=$1',[ids.pA]);await reserve(f);expect((await reserve(f)).rows[0].result).toMatchObject({status:'pending'});await expect(reserve(f,ids.b,ids.pA)).rejects.toThrow();expect((await f.as(ids.b,'select * from managed_objects')).rows).toEqual([]);await expect(reserve(f,ids.viewer)).rejects.toThrow();await expect(reserve(f,ids.a,ids.pA,other,4)).rejects.toThrow('storage_limit');await expect(f.as(ids.a,"select managed_put_file($1,'legacy','YWJjZA==')",[ids.pA])).rejects.toThrow('storage_limit');}finally{await f.db.close();}},30000);
 it('only backend completes; retry settles once; deleting keeps quota until confirmation',async()=>{const f=await fixture();try{await reserve(f);await expect(f.as(ids.a,'select managed_object_complete($1,$2,false)',[ids.pA,file])).rejects.toThrow();for(let i=0;i<2;i++)await f.service('select managed_object_complete($1,$2,false)',[ids.pA,file]);expect((await f.db.query("select * from managed_usage where operation_id=$1 and unit='stored_bytes'",[file])).rows).toHaveLength(1);await f.as(ids.a,'select managed_object_delete_begin($1,$2)',[ids.pA,file]);await expect(reserve(f)).rejects.toThrow('object_conflict');expect((await f.service('select managed_object_complete($1,$2,false) done',[ids.pA,file])).rows[0].done).toBe(false);for(let i=0;i<2;i++)await f.service('select managed_object_complete($1,$2,true)',[ids.pA,file]);expect((await f.db.query("select * from managed_usage where operation_id=$1 and unit='released_bytes'",[file])).rows).toHaveLength(1);await expect(reserve(f)).rejects.toThrow('object_conflict');}finally{await f.db.close();}},30000);
 it('retains pending reservation when access is revoked; another client cannot finalize',async()=>{const f=await fixture();try{await reserve(f);await f.db.query('delete from organization_members where user_id=$1',[ids.a]);await expect(reserve(f)).rejects.toThrow();await expect(f.as(ids.b,'select managed_object_delete_begin($1,$2)',[ids.pA,file])).rejects.toThrow();expect((await f.db.query('select status from managed_objects where id=$1',[file])).rows[0]).toEqual({status:'pending'});}finally{await f.db.close();}},30000);
});
