import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {whatsappTrackingOrigin} from '../src/lib/whatsapp/tracking-origin';
import {resolveOwnedOutboundLink} from '../src/lib/whatsapp/resolve-outbound-link';
import type {SupabaseClient} from '@supabase/supabase-js';
const mocks=vi.hoisted(()=>({auth:vi.fn()}));
vi.mock('@/lib/connectyhub-api/gateway',()=>({authenticateGatewayRequest:mocks.auth,formatGatewayError:()=>({status:401,body:{error:'unauthorized'}})}));
import {GET,HEAD} from '../src/app/api/v1/links/[id]/resolve/route';
const id='10000000-0000-4000-8000-000000000001',org='org-betel',destination='https://betel.example/item?sig=exact%2Fbytes#details';
function database(owner=org,target=destination){const rpc=vi.fn(async()=>({data:target,error:null}));let matches=true;const q={select:()=>q,eq:(key:string,value:string)=>{if(key==='organization_id'&&value!==owner)matches=false;return q;},maybeSingle:async()=>({data:matches?{target_url:target}:null,error:null})};const client={rpc,from:()=>q} as unknown as SupabaseClient;return {client,rpc};}
beforeEach(()=>vi.clearAllMocks());afterEach(()=>vi.unstubAllEnvs());
it('changes only the server-configured organization origin',()=>{const config=JSON.stringify({[org]:'https://betel-leil-es.vercel.app'});expect(whatsappTrackingOrigin(org,'https://www.connectyhub.com.br',config)).toBe('https://betel-leil-es.vercel.app');expect(whatsappTrackingOrigin('other','https://www.connectyhub.com.br',config)).toBe('https://www.connectyhub.com.br');});
it.each(['http://evil.example','https://user:secret@evil.example','https://evil.example/path','https://evil.example/?x=1','https://localhost','https://127.0.0.1','https://evil.example:8443'])('rejects unsafe configured origin %s',origin=>{expect(()=>whatsappTrackingOrigin(org,'https://app.example',JSON.stringify({[org]:origin}))).toThrow();});
it('does not resolve or count another organization link',async()=>{const db=database('other');await expect(resolveOwnedOutboundLink(db.client,org,id,true)).rejects.toMatchObject({status:404});expect(db.rpc).not.toHaveBeenCalled();});
it.each(['javascript:alert(1)','https://user:secret@example.com','https://betel.example/w/'+id])('rejects unsafe destination before recording a click: %s',async target=>{const db=database(org,target);await expect(resolveOwnedOutboundLink(db.client,org,id,true)).rejects.toMatchObject({status:503});expect(db.rpc).not.toHaveBeenCalled();});
it('GET resolves stored destination and counts once, ignoring query overrides',async()=>{const db=database();mocks.auth.mockResolvedValue({client:db.client,apiClient:{organization_id:org}});const request=new Request(`https://ch.example/api/v1/links/${id}/resolve?target=https://evil.example`,{headers:{'user-agent':'Mozilla/5.0'}});const response=await GET(request,{params:Promise.resolve({id})});expect(response.status).toBe(200);expect(await response.json()).toEqual({ok:true,destination});expect(db.rpc).toHaveBeenCalledExactlyOnceWith('record_whatsapp_outbound_click',{p_link:id});expect(mocks.auth).toHaveBeenCalledWith(request,['instances:read']);expect(response.headers.get('cache-control')).toBe('private, no-store');});
it('HEAD and bot previews do not count clicks',async()=>{const db=database();mocks.auth.mockResolvedValue({client:db.client,apiClient:{organization_id:org}});const context={params:Promise.resolve({id})};const response=await HEAD(new Request('https://ch.example'),context);expect(response.status).toBe(302);expect(response.headers.get('location')).toBe(destination);expect(await response.text()).toBe('');await GET(new Request('https://ch.example',{headers:{'user-agent':'WhatsApp'}}),context);await GET(new Request('https://ch.example',{headers:{'sec-purpose':'prefetch'}}),context);expect(db.rpc).not.toHaveBeenCalled();});
it('rejects missing authentication without accessing links',async()=>{const db=database();mocks.auth.mockRejectedValue(Error('missing auth'));expect((await GET(new Request('https://ch.example'),{params:Promise.resolve({id})})).status).toBe(401);expect(db.rpc).not.toHaveBeenCalled();});
