import type { LucideIcon } from "lucide-react";
import {
  Apple,
  BadgeCheck,
  BadgeDollarSign,
  BadgePercent,
  Baby,
  Bath,
  Bed,
  Beef,
  Bike,
  BookOpen,
  Box,
  Boxes,
  BriefcaseBusiness,
  CakeSlice,
  CalendarDays,
  Camera,
  Car,
  CircleDollarSign,
  Coffee,
  CreditCard,
  CupSoda,
  Dumbbell,
  Flower,
  Gamepad2,
  Gem,
  Glasses,
  GraduationCap,
  Gift,
  Hammer,
  HeartPulse,
  Headphones,
  Home,
  Hospital,
  Lamp,
  Landmark,
  Laptop,
  Layers3,
  Leaf,
  MapPin,
  MonitorSmartphone,
  Music,
  Package,
  PackageCheck,
  Paintbrush,
  Palette,
  Percent,
  Pill,
  Pizza,
  Plane,
  QrCode,
  ReceiptText,
  Salad,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  SprayCan,
  Stethoscope,
  Store,
  Syringe,
  Tag,
  TicketPercent,
  Truck,
  Utensils,
  WalletCards,
  Watch,
  Wine,
  Wrench,
} from "lucide-react";
import {
  defaultSalesCatalogCategoryIconId,
  normalizeSalesCatalogCategoryIconId,
  type SalesCatalogCategoryIconId,
} from "@/lib/sales-catalog/category-icons";

const salesCatalogCategoryIconGlyphs: Record<SalesCatalogCategoryIconId, LucideIcon> = {
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  store: Store,
  package: Package,
  box: Box,
  boxes: Boxes,
  "package-check": PackageCheck,
  layers: Layers3,
  pill: Pill,
  syringe: Syringe,
  stethoscope: Stethoscope,
  hospital: Hospital,
  dumbbell: Dumbbell,
  shirt: Shirt,
  watch: Watch,
  glasses: Glasses,
  baby: Baby,
  home: Home,
  sofa: Sofa,
  bed: Bed,
  bath: Bath,
  lamp: Lamp,
  gift: Gift,
  sparkles: Sparkles,
  flower: Flower,
  leaf: Leaf,
  gem: Gem,
  scissors: Scissors,
  "spray-can": SprayCan,
  tag: Tag,
  "ticket-percent": TicketPercent,
  percent: Percent,
  "badge-percent": BadgePercent,
  "heart-pulse": HeartPulse,
  monitor: MonitorSmartphone,
  smartphone: Smartphone,
  laptop: Laptop,
  headphones: Headphones,
  camera: Camera,
  music: Music,
  gamepad: Gamepad2,
  basket: ShoppingBasket,
  utensils: Utensils,
  apple: Apple,
  coffee: Coffee,
  cake: CakeSlice,
  pizza: Pizza,
  beef: Beef,
  "cup-soda": CupSoda,
  wine: Wine,
  salad: Salad,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  briefcase: BriefcaseBusiness,
  calendar: CalendarDays,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  car: Car,
  bike: Bike,
  plane: Plane,
  truck: Truck,
  "wallet-cards": WalletCards,
  "credit-card": CreditCard,
  "qr-code": QrCode,
  landmark: Landmark,
  "map-pin": MapPin,
  "circle-dollar": CircleDollarSign,
  "badge-dollar": BadgeDollarSign,
  receipt: ReceiptText,
  palette: Palette,
  "badge-check": BadgeCheck,
};

export function SalesCatalogCategoryIconGlyph({
  className,
  id,
}: {
  className?: string;
  id: string | null | undefined;
}) {
  const normalizedId = normalizeSalesCatalogCategoryIconId(id) ?? defaultSalesCatalogCategoryIconId;
  const Icon = salesCatalogCategoryIconGlyphs[normalizedId];

  return <Icon className={className} />;
}
