'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import type {SourceConnection,SourceRow} from '@portal/lib/connected-source';
import type {ManagedProject} from '@/lib/managed-projects/contracts';

const date=(value:unknown)=>value?new Date(String(value)).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Não informado';
function Table({rows,columns}:{rows:SourceRow[];columns:[string,string][]}){
 if(!rows.length)return <p>Nenhum registro encontrado nesta consulta e neste escopo.</p>;
 return <div style={{overflowX:'auto'}}><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)}>{columns.map(([key])=><td key={key}>{key.endsWith('_at')?date(row[key]):row[key]===null||row[key]===undefined?'Não informado':typeof row[key]==='boolean'?(row[key]?'Sim':'Não'):String(row[key])}</td>)}</tr>)}</tbody></table></div>;
}
export function ConnectedProject({connection,projects,path}:{connection:SourceConnection;projects:ManagedProject[];path:string[]}){
 const router=useRouter(),s=connection.snapshot,area=path[2]??'banco',tab=path[3]??'overview';
 const stale=!connection.collected_at||Date.now()-Date.parse(connection.collected_at)>180000;
 const base=`/infraestrutura/projetos/${connection.project_id}`;
 return <main className="portal-shell" style={{maxWidth:1440}}>
  <nav><Link href="/infraestrutura">ConnectyHub · Projetos</Link><Link href="/infraestrutura/vps">Infraestrutura global</Link><Link href="/conta">Minha conta</Link></nav>
  <div className="portal-card"><span className="portal-badge">PROJETO REAL · CONSULTA EM LEITURA</span><h1>ConnectyHub</h1>
   <label>Selecionar projeto<select aria-label="Selecionar projeto" value={connection.project_id} onChange={e=>router.push(`/infraestrutura/projetos/${e.target.value}/banco`)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <p>Fonte: Supabase da VPS · organização <strong>{connection.source_name}</strong> · {connection.source_organization_id}.</p>
   <p>Última coleta: {date(connection.collected_at)}. Atualização automática a cada minuto. Os serviços e dados permanecem nos destinos atuais.</p>
   {(stale||connection.collection_status!=='ok')&&<p role="alert" className="portal-alert">{connection.collection_status==='failed'?'A última coleta falhou.':'A coleta está pendente ou desatualizada.'} Os valores anteriores não comprovam o estado atual.</p>}
   <button onClick={()=>router.refresh()}>Atualizar visualização</button>
  </div>
  <nav style={{flexWrap:'wrap'}} aria-label="Recursos conectados"><Link href={`${base}/banco`}>Visão geral</Link><Link href={`${base}/banco/tabelas`}>Banco</Link><Link href={`${base}/banco/arquivos`}>Arquivos</Link><Link href={`${base}/banco/consumo`}>Consumo e créditos</Link><Link href={`${base}/automacoes`}>Automações</Link></nav>
  {!s?<section className="portal-card"><h2>Aguardando primeira coleta</h2><p>A conexão só será apresentada como verificada após receber dados da origem.</p></section>:<>
   {area==='automacoes'?<section className="portal-card"><h2>Automações da ConnectyHub</h2><p>O Inngest produtivo continua no serviço existente. Este portal ainda não consulta execuções nem controla esse motor. Nenhuma automação foi migrada ou disparada por esta conexão.</p><p>O cadastro abaixo foi consultado no Supabase: agentes da organização interna e agentes globais da plataforma. Cadastro e estado configurado não comprovam execução ou entrega.</p><Table rows={s.agents} columns={[["name","Agente"],["scope","Escopo"],["sector_name","Setor"],["status","Estado cadastrado"],["updated_at","Atualizado em"]]}/><p>Até 100 agentes. <a href="https://inngest.connectyhub.com.br" target="_blank" rel="noreferrer">Abrir Inngest existente</a> exige o acesso próprio desse serviço.</p></section>
   :tab==='tabelas'?<section className="portal-card"><h2>Banco produtivo existente</h2><p>Inventário global de estrutura, sem conteúdo das tabelas. Tamanho: {Number(s.database.bytes).toLocaleString('pt-BR')} bytes. {s.database.table_count} tabelas nos esquemas public/auth/storage. Até 400 exibidas.</p><p>Linhas estimadas são estatísticas do PostgreSQL, não contagens exatas. Não há editor SQL nem comandos de escrita nesta conexão.</p><Table rows={s.database.tables} columns={[["schema","Esquema"],["name","Tabela"],["estimated_rows","Linhas estimadas"],["bytes","Bytes com índices"]]}/></section>
   :tab==='arquivos'?<section className="portal-card"><h2>Arquivos e armazenamento</h2><p>{s.counts.files} registros da organização interna em lead_files e studio_assets; até 50 metadados recentes. Conteúdo, nomes pessoais, URLs privadas e chaves de objetos não são copiados nem expostos.</p><Table rows={s.files} columns={[["id","Registro"],["source","Tabela de origem"],["kind","Tipo"],["mime_type","Formato"],["bytes","Bytes"],["created_at","Criado em"]]}/><h3>Contabilidade de armazenamento da organização</h3>{s.storage_accounting?<Table rows={[s.storage_accounting]} columns={[["used_bytes","Bytes contabilizados"],["billable_file_count","Arquivos contabilizados"],["last_recalculated_at","Último recálculo na origem"]]}/>:<p>Contabilidade não encontrada; ausência não significa consumo zero.</p>}<h3>Buckets do Supabase · inventário global</h3><Table rows={s.buckets} columns={[["name","Bucket"],["public","Público"]]}/><p>Lista administrativa de até 50 buckets; não inclui inventário direto do R2, prova de existência física ou download dos objetos.</p></section>
   :tab==='consumo'?<section className="portal-card"><h2>Consumo e créditos · organização interna</h2><p>Últimos 30 dias até a coleta. Fonte: usage_events, agrupado por moeda, modo de cobrança e estado. Custos são os valores registrados na aplicação, não faturas conciliadas do fornecedor. Créditos e moeda são unidades diferentes. No modo internal_shadow, os créditos são uma referência de consumo interno, sem débito ao cliente. Estes registros, sozinhos, não comprovam cobrança na carteira.</p><Table rows={s.consumption} columns={[["currency","Moeda"],["billing_mode","Modo"],["status","Estado"],["events","Eventos"],["recorded_provider_cost","Custo registrado"],["missing_cost_events","Sem custo informado"],["recorded_credits","Créditos registrados"],["input_tokens","Tokens entrada"],["output_tokens","Tokens saída"]]}/><h3>Carteira própria da organização interna</h3>{s.wallet?<Table rows={[s.wallet]} columns={[["balance_credits","Saldo em créditos"],["reserved_credits","Reservado"],["updated_at","Atualizado na origem"]]}/>:<p>Não há carteira própria registrada nesta consulta. Não inferimos saldo zero nem usamos a carteira de outra empresa.</p>}<p>Valores apresentados sem alterar tarifas, reservas, saldos ou débitos. Não incluem consumo de outras organizações, prévias de voz em organização separada, Contabo ou Vercel.</p></section>
   :<section className="portal-card"><h2>Conexão verificada</h2><p>Aplicação: <a href="https://www.connectyhub.com.br">www.connectyhub.com.br</a>. Banco/Auth/Storage: Supabase existente na VPS. A administração global vê somente a seleção de dados descrita abaixo.</p><div className="portal-grid">{[['Tabelas · banco global',s.database.table_count],['Leads · organização interna',s.counts.leads],['Arquivos registrados · organização interna',s.counts.files],['Eventos de uso · organização interna · 30 dias',s.counts.usage_events_30d]].map(([label,value])=><div className="portal-card" key={String(label)}><p>{label}</p><strong style={{fontSize:28}}>{value}</strong></div>)}</div><h3>Projetos de API da organização interna</h3><Table rows={s.resources} columns={[["name","Projeto"],["kind","API"],["status","Estado"]]}/><p>Até 100 projetos. Nenhuma chave de API é transmitida ao navegador. Os cadastros QA da homologação permanecem separados.</p></section>}
  </>}
 </main>;
}
