"use client";
import { deliveryMoneyCents } from "@/lib/sales-catalog/local-delivery";
const money = (cents: number) => (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
import { foodLineQuote, foodUnitSummary, readFoodUnitSelections, type FoodCompositionPolicy, type FoodUnitSelection } from "@/lib/sales-catalog/food-composition";
const field = "mt-1 min-h-11 w-full min-w-0 rounded-lg border border-slate-300 bg-white px-2 text-sm text-slate-950";
export function FoodUnitEditor({ policy, quantity, value, onChange, unitStartIndex = 0 }: { unitStartIndex?: number; policy: FoodCompositionPolicy; quantity: number; value?: FoodUnitSelection[]; onChange: (value: FoodUnitSelection[]) => void }) {
  const stored = readFoodUnitSelections(value), units = Array.from({ length: quantity }, (_, at) => stored[at] ?? { sizeId: "", flavors: [], options: [], note: "" });
  const quote = foodLineQuote({ foodComposition: policy, priceCents: null }, quantity, value);
  return <div className="col-span-2 min-w-0 space-y-3 border-t border-slate-200 pt-3">
    <p className="text-xs text-slate-600">{policy.pricing === "highest" ? "Preço pelo maior valor dos sabores escolhidos." : policy.pricing === "weighted" ? "Preço proporcional às frações de cada sabor." : "Preço fixo do tamanho ou combo."} Adicionais são somados conforme as escolhas.</p>
    {units.map((unit, index) => { const change = (patch: Partial<FoodUnitSelection>) => onChange(units.map((row, at) => at === index ? { ...row, ...patch } : row)); const size = policy.sizes.find(size => size.id === unit.sizeId); return <fieldset key={index} className="space-y-3 rounded-lg border border-slate-200 p-3"><legend className="px-1 text-sm font-semibold">Unidade {unitStartIndex + index + 1}</legend>
      <label className="block text-xs font-medium">Tamanho<select className={field} value={unit.sizeId} onChange={event => change({ sizeId: event.target.value, flavors: [], options: [] })}><option value="">Escolha o tamanho</option>{policy.sizes.filter(size => size.active).map(size => <option value={size.id} key={size.id}>{size.name}</option>)}</select></label>
      {size && policy.flavors.length ? <div className="space-y-2"><p className="text-xs text-slate-600">Complete {size.portions} fração(ões), com até {size.maxFlavors} sabor(es).</p>{unit.flavors.map((flavor, at) => <div key={at} className="grid grid-cols-[minmax(0,1fr)_70px] gap-2"><label className="text-xs">Sabor<select className={field} value={flavor.flavorId} onChange={event => change({ flavors: unit.flavors.map((row, i) => i === at ? { ...row, flavorId: event.target.value } : row), options: unit.options.filter(option => !option.flavorId) })}><option value="">Escolha</option>{policy.flavors.filter(flavor => flavor.active).map(flavor => <option key={flavor.id} value={flavor.id}>{flavor.name}</option>)}</select></label><label className="text-xs">Frações<input className={field} type="number" min={1} max={size.portions} value={Number.isFinite(flavor.portions) ? flavor.portions : ""} onChange={event => change({ flavors: unit.flavors.map((row, i) => i === at ? { ...row, portions: Number(event.target.value) } : row) })}/></label><button type="button" className="min-h-10 text-left text-xs text-rose-700" onClick={() => change({ flavors: unit.flavors.filter((_, i) => i !== at), options: unit.options.filter(option => option.flavorId !== flavor.flavorId) })}>Remover sabor</button></div>)}{unit.flavors.length < size.maxFlavors ? <button type="button" className="min-h-11 text-xs font-semibold text-blue-700" onClick={() => change({ flavors: [...unit.flavors, { flavorId: "", portions: 1 }] })}>Adicionar sabor</button> : null}</div> : null}
      {size ? policy.groups.map(group => <fieldset key={group.id} className="space-y-2 border-t border-slate-200 pt-2"><legend className="text-xs font-semibold">{group.name}</legend><p className="text-xs text-slate-500">De {group.min} a {group.max} escolha(s) {group.scope === "unit" ? "por unidade" : "por fração de sabor"}.</p>{(group.scope === "unit" ? [null] : unit.flavors.map(flavor => flavor.flavorId).filter(Boolean)).map(target => <div className="space-y-2" key={target ?? "unit"}>{target ? <p className="text-xs font-medium">Em {policy.flavors.find(flavor => flavor.id === target)?.name}</p> : null}{group.options.filter(option => option.active).map(option => { const chosen = unit.options.find(row => row.groupId === group.id && row.optionId === option.id && (row.flavorId ?? null) === target); return <label key={option.id} className="flex min-h-11 items-center justify-between gap-2 text-xs"><span className="min-w-0">{option.name}<span className="block text-slate-500">{money(Math.round((deliveryMoneyCents(option.price) ?? 0) * (chosen?.quantity || 1) * (target ? (unit.flavors.find(flavor => flavor.flavorId === target)?.portions ?? 0) : size.portions) / size.portions))} {chosen?.quantity ? `por ${chosen.quantity} adicional(is)` : "por adicional"}</span></span><input aria-label={`Quantidade de ${option.name}${target ? ` em ${policy.flavors.find(flavor => flavor.id === target)?.name}` : ""}`} type="number" min={0} max={option.maxQuantity} value={chosen?.quantity ?? 0} className={`${field.replace("w-full", "w-20")} shrink-0`} onChange={event => { const count = Number(event.target.value); const rest = unit.options.filter(row => !(row.groupId === group.id && row.optionId === option.id && (row.flavorId ?? null) === target)); change({ options: count > 0 ? [...rest, { groupId: group.id, optionId: option.id, quantity: count, flavorId: target }] : rest }); }}/></label>; })}</div>)}</fieldset>) : null}
      <label className="block text-xs font-medium">Observação desta unidade (sem acréscimo)<textarea className={`${field} min-h-20 py-2`} maxLength={500} value={unit.note} onChange={event => change({ note: event.target.value })}/></label>
    </fieldset>; })}
    {quote.error ? <p role="status" className="text-xs text-amber-800">{quote.error}</p> : <p className="whitespace-pre-line text-xs leading-5 text-slate-700">{quote.snapshot?.units.map((unit, index) => foodUnitSummary(unit, unitStartIndex + index)).join("\n")}</p>}
  </div>;
}
