import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm,lstat,readdir,symlink,unlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createRequire} from 'node:module';
import {createServer} from 'node:net';
import {prepare,marker,removeOwnedChild,sourceManifest,rolesSql,baseSql,seedSql,ids,hash,repo} from './lib.mjs';
import {composeEnvironment,validateConfig,command,migrations,preflight,validateOwnedContainers,validateRuntimeBounds,validDeadline} from './runner.mjs';
const require=createRequire(import.meta.url),yaml=require('yaml');
async function fixture(fn){const parent=await mkdtemp(join(tmpdir(),'managed-rehearsal-tests-'));try{return await fn(parent);}finally{assert.ok(resolve(parent).startsWith(resolve(tmpdir())));await rm(parent,{recursive:true,force:true});}}
test('fresh fixtures have exclusive secrets, no production endpoints, matching source hashes',()=>fixture(async parent=>{const a=await prepare(parent),b=await prepare(parent);assert.notEqual(a.id,b.id);assert.notEqual(await readFile(join(a.root,'secrets/object-key'),'utf8'),await readFile(join(b.root,'secrets/object-key'),'utf8'));assert.equal((await marker(a.root)).id,a.id);assert.deepEqual(JSON.parse(await readFile(join(a.root,'source-manifest.json'))),await sourceManifest());const env=await readFile(join(a.root,'inputs/auth.env'),'utf8');assert.match(env,/@database:5432\/managed_rehearsal/);assert.doesNotMatch(env,/connectyhub\.com|supabase\.co/);assert.match(composeEnvironment(a),/REHEARSAL_IMAGE=/);assert.match(await rolesSql(a.root),/NOINHERIT/);}));
test('cleanup rejects traversal, wrong ownership marker and symlinks',()=>fixture(async parent=>{const m=await prepare(parent);await assert.rejects(removeOwnedChild(m.root,'../'),/Non-disposable/);const outside=join(parent,'outside.txt');await writeFile(outside,'keep');const link=join(m.root,'data/link');try{await symlink(parent,link,process.platform==='win32'?'junction':'dir');await assert.rejects(removeOwnedChild(m.root,'data'),/Symlink/);await unlink(link);}catch(e){if(e.code!=='EPERM')throw e;}await removeOwnedChild(m.root,'data');assert.equal(await readFile(outside,'utf8'),'keep');await writeFile(join(m.root,'manifest.json'),JSON.stringify({...m,id:'00000000-0000-4000-8000-000000000000'}));await assert.rejects(marker(m.root),/ownership/);}));
function normalized(m){const source=yaml.parse(require('fs').readFileSync(join(repo,'services/managed-rehearsal/compose.review.yml'),'utf8'),{merge:true});source.name=m.project;for(const s of Object.values(source.services)){s.mem_limit=parseInt(s.mem_limit)*1024*1024;s.memswap_limit=parseInt(s.memswap_limit)*1024*1024;s.networks=Array.isArray(s.networks)?Object.fromEntries(s.networks.map(x=>[x,{}])):s.networks;if(s.build)s.build.context=repo;for(const v of s.volumes??[])v.source=m.root+'/data/test';}for(const s of Object.values(source.secrets))s.file=m.root+'/secrets/test';return source;}
test('Compose envelope counts executor and refuses public ports/foreign mounts',()=>{const m={root:'/fixture/managed',project:'fixture'};const c=normalized(m);assert.deepEqual(validateConfig(c,m),{containers:9,container_memory_bytes:2415919104,container_cpus:2.75,host_supervisor_reserve_MiB:256,host_supervisor_cgroup_limit:false});c.services.rest.ports=[{published:'1234'}];assert.throws(()=>validateConfig(c,m),/Exposure/);delete c.services.rest.ports;c.services.objects.volumes[0].source='/production';assert.throws(()=>validateConfig(c,m),/Foreign/);});
test('command deadline and output bounds end local child processes',async()=>{await assert.rejects(command(process.execPath,['-e','setInterval(()=>{},1000)'],{timeout:150}),/deadline/);await assert.rejects(command(process.execPath,['-e',"process.stdout.write('a'.repeat(10000))"],{maxBytes:10}),/bound/);});
test('cleanup scope and watchdog cannot expand to foreign resources or indefinite time',()=>{const m={root:resolve('fixture'),project:'fixture',id:'id'},c={Config:{Labels:{'com.docker.compose.project':'fixture','com.docker.compose.project.config_files':join(repo,'services/managed-rehearsal/compose.review.yml'),'com.docker.compose.service':'executor'}},Mounts:[{Type:'bind',Source:join(m.root,'evidence')}],HostConfig:{PortBindings:{},Memory:512*1024*1024,MemorySwap:512*1024*1024,NanoCpus:500000000,ReadonlyRootfs:true}};validateOwnedContainers([c],m);validateRuntimeBounds(c);c.Mounts[0].Source=resolve('foreign');assert.throws(()=>validateOwnedContainers([c],m),/Foreign container mount/);c.HostConfig.Memory=0;assert.throws(()=>validateRuntimeBounds(c),/memory/);validDeadline({id:'id',deadline:1000+45*60000},m,1000);assert.throws(()=>validDeadline({id:'id',deadline:1000+47*60000},m,1000),/deadline/);assert.throws(()=>validDeadline({id:'other',deadline:2000},m,1000),/deadline/);});
test('Windows preflight refuses execution before Docker access',{skip:process.platform==='linux'},async()=>{await assert.rejects(preflight('/unused'),/Linux amd64/);});
test('real isolated PostgreSQL: bootstrap and migrations replay, hashes and RLS roles', {skip:!process.env.REHEARSAL_PG_BIN,timeout:120000},()=>fixture(async parent=>{
 const m=await prepare(parent),bin=process.env.REHEARSAL_PG_BIN,exe=n=>join(bin,n+(process.platform==='win32'?'.exe':'')),data=join(m.root,'data/postgres');let started=false;
 const listener=createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));
 const envPassword=await readFile(join(m.root,'secrets/database-password'),'utf8');
 try{
  // This disposable PostgreSQL trusts only its loopback test clients, and is never production.
  await command(exe('initdb'),['-D',data,'-U','postgres','--auth=trust','--no-locale','--encoding=UTF8'],{timeout:30000});
  started=true;await command(exe('pg_ctl'),['start','-D',data,'-l',join(m.root,'evidence/postgres.log'),'-o',`-h 127.0.0.1 -p ${port} -c shared_buffers=32MB -c max_connections=10`],{timeout:30000,exitOnly:true});
  const sql=(text,db='managed_rehearsal')=>command(exe('psql'),['-X','-h','127.0.0.1','-p',String(port),'-U','postgres','-d',db,'-v','ON_ERROR_STOP=1','-q','-t','-A'],{input:text});
  await sql('CREATE DATABASE managed_rehearsal;','postgres');await sql(await rolesSql(m.root));await sql(await rolesSql(m.root));assert.equal((await sql('SELECT count(*) FROM rehearsal_meta.owner')).trim(),'1');
  assert.equal((await sql("SELECT rolsuper FROM pg_roles WHERE rolname='authenticator'")).trim(),'f');assert.equal((await sql("SELECT rolinherit FROM pg_roles WHERE rolname='authenticator'")).trim(),'f');
  await sql('SET ROLE supabase_auth_admin; CREATE TABLE auth.users(id uuid PRIMARY KEY,email text); RESET ROLE;');
  const dc=async(_args,options)=>sql(options.input);await migrations(m,dc);await migrations(m,dc);assert.equal((await sql('SELECT count(*) FROM rehearsal_meta.migrations')).trim(),'4');
  const users={admin:'20000000-0000-4000-8000-000000000001',productAdmin:'20000000-0000-4000-8000-000000000002',a:'20000000-0000-4000-8000-000000000003',b:'20000000-0000-4000-8000-000000000004'};
  await writeFile(join(m.root,'evidence/users.json'),JSON.stringify(users));for(const [k,id]of Object.entries(users))await sql(`INSERT INTO auth.users VALUES('${id}','${k.toLowerCase()}@managed-fixture.example');`);
  await sql(await seedSql(m.root));await sql(await seedSql(m.root));assert.equal((await sql('SELECT count(*) FROM managed_workers')).trim(),'2');
  assert.equal((await sql(`SET ROLE authenticated; SELECT set_config('request.jwt.claims','{"sub":"${users.a}"}',false); SELECT count(*) FROM managed_projects;`)).trim().split('\n').at(-1),'1');
  await sql("UPDATE rehearsal_meta.migrations SET sha256='tampered' WHERE name='0150_managed_projects.sql';");await assert.rejects(migrations(m,dc),/migration changed/);
 }finally{if(started)await command(exe('pg_ctl'),['stop','-D',data,'-m','fast'],{timeout:30000});}
}));
