// Local Linux Docker socket only. Never discovers or connects to SSH/VPS/remote Docker.
import {spawn} from 'node:child_process';
import {readFile,writeFile,statfs,lstat,readdir,realpath,open,mkdir,cp,chown} from 'node:fs/promises';
import {join,dirname,resolve,sep} from 'node:path';
import {setTimeout as pause} from 'node:timers/promises';
import {cpus} from 'node:os';
import {fileURLToPath} from 'node:url';
import {here,repo,assert,hash,json,marker,prepare,noSymlink,treeSafe,removeOwnedChild,rolesSql,baseSql,seedSql,uuid,ids,sourceManifest,fileManifest} from './lib.mjs';
const composeFile=join(here,'compose.review.yml');
const activeCommands=new Set();
const cleanEnv=()=>({PATH:process.env.PATH,HOME:process.env.HOME,LANG:'C.UTF-8',COMPOSE_PARALLEL_LIMIT:'1'});
export async function command(file,args,{input,timeout=60000,outputFile,maxBytes=2*1024*1024,exitOnly=false,env={}}={}){
 return new Promise((resolveResult,reject)=>{const p=spawn(file,args,{env:{...cleanEnv(),...env},stdio:['pipe','pipe','pipe'],windowsHide:true});activeCommands.add(p);let chunks=[],length=0,errors=[],errorBytes=0,done=false,fileHandle;
  const timer=setTimeout(()=>{p.kill('SIGKILL');finish(Error('Command deadline exceeded'));},timeout);
  async function finish(error,result){if(done)return;done=true;activeCommands.delete(p);clearTimeout(timer);if(fileHandle)await fileHandle.close();error?reject(error):resolveResult(result);}
  // Never echo command arguments, SQL, DSNs or untrusted raw service errors.
  p.on('error',()=>finish(Error(`Required command unavailable: ${file}`)));
  p.stdout.on('data',chunk=>{length+=chunk.length;if(length>maxBytes){p.kill('SIGKILL');return finish(Error('Command output bound exceeded'));}chunks.push(chunk);});
  p.stderr.on('data',chunk=>{errorBytes+=chunk.length;if(errorBytes<8192)errors.push(chunk);});
  p.on(exitOnly?'exit':'close',async code=>{if(done)return;if(exitOnly){p.stdout.destroy();p.stderr.destroy();}if(code!==0)return finish(Error(`Command failed: ${file} (exit ${code})`));const bytes=Buffer.concat(chunks);if(outputFile){try{fileHandle=await open(outputFile,'wx',0o600);await fileHandle.writeFile(bytes);await fileHandle.sync();await finish(null,'');}catch{await finish(Error('Private output write failed'));}}else await finish(null,bytes.toString());});
  p.stdin.on('error',()=>{});p.stdin.end(input);
 });
}
export function composeEnvironment(m,restored=false){const p=v=>{v=v.replaceAll('\\','/');assert(!/[\r\n"'$]/.test(v),'Unsafe env file path');return `"${v}"`;};return Object.entries({REHEARSAL_SOURCE_ROOT:repo,REHEARSAL_IMAGE:`connectyhub-managed-rehearsal:${m.id}`,REHEARSAL_DATA_ROOT:join(m.root,restored?'restore':'data'),REHEARSAL_SECRET_ROOT:join(m.root,'secrets'),REHEARSAL_AUTH_ENV_FILE:join(m.root,'inputs/auth.env'),REHEARSAL_REST_ENV_FILE:join(m.root,'inputs/rest.env'),REHEARSAL_EVIDENCE_ROOT:join(m.root,'evidence')}).map(([k,v])=>`${k}=${p(v)}`).join('\n')+'\n';}
function docker(args,options){return command('docker',['--host','unix:///var/run/docker.sock',...args],options);}
function context(m){const prefix=['compose','--project-name',m.project,'--file',composeFile,'--env-file',join(m.root,'inputs/compose.env'),'--profile','rehearsal','--profile','tools','--profile','pressure'];return {dc:(args,opts)=>docker([...prefix,...args],opts),prefix};}
export function validateConfig(config,m){assert(config.name===m.project,'Compose project mismatch');let memory=0,cpu=0;const allowed=new Set(['database','auth','rest','managed-gateway','worker','telemetry-gateway','objects','executor','objects-pressure']);
 for(const [name,s]of Object.entries(config.services)){assert(allowed.delete(name),'Unexpected service');assert(!s.ports?.length&&!s.network_mode&&!s.privileged,'Exposure forbidden');assert(s.read_only&&s.restart==='no','Runtime protection missing');assert(s.platform==='linux/amd64','Architecture mismatch');assert(s.cap_drop?.includes('ALL')&&s.security_opt?.includes('no-new-privileges:true'),'Privilege hardening missing');assert(Object.keys(s.networks).join(',')==='isolated','Unexpected service network');assert(s.mem_limit===s.memswap_limit,'Swap bound missing');memory+=Number(s.mem_limit);cpu+=Number(s.cpus);
  if(s.build)assert(resolve(s.build.context)===repo&&s.build.dockerfile==='services/managed-rehearsal/Dockerfile','Foreign build context');else assert(/@sha256:[a-f0-9]{64}$/.test(s.image),'Image is not pinned');
  for(const v of s.volumes??[])assert(v.type==='bind'&&resolve(v.source).startsWith(resolve(m.root)+sep)&&v.bind?.create_host_path===false,'Foreign writable path');
 }
 assert(allowed.size===0&&memory===2415919104&&Math.abs(cpu-2.75)<.001,'Resource envelope changed');assert(config.networks.isolated.internal&&!config.networks.isolated.external,'Network not isolated');assert(Object.keys(config.networks).length===1,'Unexpected network');for(const s of Object.values(config.secrets??{}))assert(resolve(s.file).startsWith(resolve(m.root,'secrets')+sep),'Foreign secret');return {containers:9,container_memory_bytes:memory,container_cpus:cpu,host_supervisor_reserve_MiB:256,host_supervisor_cgroup_limit:false};
}
async function ownedResources(m){const list=(await docker(['ps','-aq','--filter',`label=com.docker.compose.project=${m.project}`])).trim().split(/\s+/).filter(Boolean);if(!list.length)return [];
 const containers=JSON.parse(await docker(['inspect',...list]));validateOwnedContainers(containers,m);return containers;
}
export function validateOwnedContainers(containers,m){for(const c of containers){const labels=c.Config.Labels??{};assert(labels['com.docker.compose.project']===m.project&&labels['com.docker.compose.project.config_files']===composeFile,'Foreign container ownership');assert(c.Mounts.every(x=>(x.Type==='bind'&&resolve(x.Source).startsWith(resolve(m.root)+sep))||(x.Type==='tmpfs'&&['/data/objects','/tmp','/var/run/postgresql'].includes(x.Destination))),'Foreign container mount');assert(!Object.values(c.HostConfig.PortBindings??{}).some(x=>x?.length),'Published port detected');}}
export function validateRuntimeBounds(c){const service=c.Config.Labels['com.docker.compose.service'],memory=({database:512,auth:256,rest:128,'managed-gateway':128,worker:128,'telemetry-gateway':128,objects:256,executor:512,'objects-pressure':256})[service];assert(memory,'Unexpected runtime service');assert(c.HostConfig.Memory===memory*1024*1024&&c.HostConfig.MemorySwap===c.HostConfig.Memory,'Container memory/swap limit not applied');assert(c.HostConfig.NanoCpus===(['database','executor'].includes(service)?500000000:250000000),'Container CPU limit not applied');assert(c.HostConfig.ReadonlyRootfs===true,'Container rootfs is writable');}
export function validDeadline(state,m,now=Date.now()){assert(state.id===m.id&&state.deadline>now&&state.deadline<=now+46*60*1000,'Invalid watchdog deadline');}
export async function cleanup(root){const m=await marker(root);const state=await json(join(root,'run-state.json'));assert(state.id===m.id&&state.project===m.project,'Invalid runtime scope');await ownedResources(m);const networks=(await docker(['network','ls','-q','--filter',`label=com.docker.compose.project=${m.project}`])).trim().split(/\s+/).filter(Boolean);if(networks.length){for(const n of JSON.parse(await docker(['network','inspect',...networks])))assert(n.Internal&&n.Labels?.['com.docker.compose.project']===m.project,'Foreign network');}
 await context(m).dc(['down','--timeout','10'],{timeout:60000});assert((await ownedResources(m)).length===0,'Containers remain');assert(!(await docker(['network','ls','-q','--filter',`label=com.docker.compose.project=${m.project}`])).trim(),'Network remains');await writeFile(join(root,'stopped.json'),JSON.stringify({id:m.id,at:new Date().toISOString(),containers_remaining:0}));await writeFile(join(root,'watchdog-cancel.json'),JSON.stringify({id:m.id}));
}
async function runtimeFiles(m){await writeFile(join(m.root,'inputs/compose.env'),composeEnvironment(m),{mode:0o600});}
async function capacity(root,maxUsed=.5){const fs=await statfs(root),size=Number(fs.blocks)*Number(fs.bsize),free=Number(fs.bavail)*Number(fs.bsize);assert(size>=1024**3&&size<=4*1024**3,'Require dedicated filesystem of 1–4 GiB; no quota inferred from YAML');assert(free>size*(1-maxUsed),'Dedicated data filesystem lacks free space');return {hard_bound:'dedicated filesystem capacity',capacity_bytes:size,available_bytes:free};}
async function cpuSample(){const a=cpus().map(x=>x.times);await pause(1000);const b=cpus().map(x=>x.times);let idle=0,total=0;for(let i=0;i<a.length;i++){idle+=b[i].idle-a[i].idle;for(const k of Object.keys(a[i]))total+=b[i][k]-a[i][k];}return total?100*(1-idle/total):0;}
export async function preflight(root,{baselineSeconds=300}={}){assert(process.platform==='linux'&&process.arch==='x64','Execution requires Linux amd64; local preparation remains allowed elsewhere');assert(process.getuid()===0,'Root supervisor required for isolated UID mounts and local Docker socket; do not sudo individual fragments');const m=await marker(root);assert(Date.now()/1000<m.expires-3600,'Fixture credentials expire too soon: prepare a new instance');assert(JSON.stringify(await json(join(root,'source-manifest.json')))===JSON.stringify(await sourceManifest()),'Reviewed source changed after prepare; create a new instance');await runtimeFiles(m);await treeSafe(root);
 const mount=JSON.parse(await command('findmnt',['--json','--target',dirname(root),'--output','TARGET,FSTYPE'])).filesystems?.[0];assert(mount&&resolve(mount.target)===dirname(root)&&['ext4','xfs'].includes(mount.fstype),'Parent must already be a dedicated ext4/xfs mount; runner never creates one');assert((await readdir(dirname(root))).every(n=>n===root.split('/').at(-1)||n==='lost+found'),'Dedicated mount contains unrelated data');const quota=await capacity(root);
 for(const [path,uid]of [['data/postgres',70],['restore/postgres',70],['data/objects',1000],['restore/objects',1000],['evidence',1000]]){const s=await lstat(join(root,path));assert(s.uid===uid&&(s.mode&0o777)===0o700,`Wrong ownership/mode for ${path}`);}
 for(const path of ['data/postgres','restore/postgres','data/objects','restore/objects','backup'])assert((await readdir(join(root,path))).length===0,'Preflight requires empty new fixture directories');
 assert(((await lstat(root)).mode&0o777)===0o700,'Private root must be 0700');for(const f of await readdir(join(root,'secrets')))assert(((await lstat(join(root,'secrets',f))).mode&0o777)===0o444,'Secret must be container-readable behind private parent');
 await docker(['compose','version','--short']);const info=JSON.parse(await docker(['info','--format','{{json .}}']));assert(info.OSType==='linux'&&info.NCPU>=4&&!info.SecurityOptions?.some(x=>x.includes('rootless')),'Require existing rootful Linux Docker with >=4 CPUs');assert(info.CgroupVersion==='2','Require cgroup v2 for predictable accounting');const imageFs=await statfs(info.DockerRootDir);assert(Number(imageFs.bavail)*Number(imageFs.bsize)>=8*1024**3,'Docker image filesystem requires >=8 GiB free');
 assert(!(await docker(['ps','-aq'])).trim(),'Execution requires a dedicated Docker daemon without other containers; never production');assert((await ownedResources(m)).length===0,'Rehearsal already has containers');const cfg=JSON.parse(await context(m).dc(['config','--format','json']));const budget=validateConfig(cfg,m);
 let maximumCPU=0;for(let elapsed=0;elapsed<baselineSeconds;elapsed++){const cpu=await cpuSample();maximumCPU=Math.max(maximumCPU,cpu);const mem=await readFile('/proc/meminfo','utf8');const available=Number(/MemAvailable:\s+(\d+)/.exec(mem)?.[1])*1024;assert(available>=4*1024**3,'Host memory below 4 GiB available');assert(cpu<70,'Host CPU baseline at or above 70%');}
 const result={at:new Date().toISOString(),quota,budget,maximum_CPU_percent:maximumCPU,baseline_seconds:baselineSeconds,compose_validated:true,linux_execution_tests:false};await writeFile(join(root,'evidence/preflight.json'),JSON.stringify(result,null,2),{mode:0o600});return result;
}
export async function migrations(m,dc){const sql=(input)=>dc(['exec','-T','database','psql','-X','-U','postgres','-d','managed_rehearsal','-v','ON_ERROR_STOP=1','-q','-t','-A'],{input,maxBytes:1024*1024});await sql(baseSql);
 for(const name of ['0150_managed_projects.sql','0151_managed_objects.sql','0152_managed_inngest_bindings.sql','0153_managed_persistent_alerts.sql']){const source=await readFile(join(repo,'supabase/migrations',name),'utf8'),sha=hash(source);const prior=(await sql(`SELECT sha256 FROM rehearsal_meta.migrations WHERE name='${name}';`)).trim();if(prior){assert(prior===sha,'Applied migration changed');continue;}await sql(`BEGIN; SELECT pg_advisory_xact_lock(724619); SET search_path=public;\n${source}\nINSERT INTO rehearsal_meta.migrations VALUES('${name}','${sha}'); COMMIT;`);}
}
async function waitDB(dc){for(let i=0;i<60;i++){try{await dc(['exec','-T','database','pg_isready','-U','postgres','-d','managed_rehearsal']);return;}catch{}await pause(1000);}throw Error('Database readiness deadline');}
async function run(root){const m=await marker(root);assert(!await exists(join(root,'run-state.json')),'Instance already used; prepare a fresh one');await preflight(root);const {dc}=context(m);
 // Pull/build happens only in this explicit run mode, before any service starts.
 await dc(['pull','database','auth','rest'],{timeout:600000,maxBytes:1024*1024});await dc(['build','executor'],{timeout:600000,maxBytes:1024*1024});
 const state={id:m.id,project:m.project,deadline:Date.now()+45*60*1000,phase:'starting'};await writeFile(join(root,'run-state.json'),JSON.stringify(state),{mode:0o600,flag:'wx'});
 const watch=spawn(process.execPath,['--max-old-space-size=64',fileURLToPath(import.meta.url),'watchdog','--root',root],{detached:true,stdio:'ignore',env:cleanEnv()});watch.unref();let watchdogReady=false;for(let i=0;i<20;i++){if(await exists(join(root,'watchdog-ready.json'))){watchdogReady=true;break;}await pause(100);}assert(watchdogReady,'Independent deadline watchdog did not start');
 let monitorError;const controller=new AbortController();const monitorPromise=(async()=>{while(!controller.signal.aborted){try{await capacity(root,.75);const memory=Number(/MemAvailable:\s+(\d+)/.exec(await readFile('/proc/meminfo','utf8'))?.[1])*1024;assert(memory>2*1024**3,'Host memory pressure');assert(Date.now()<state.deadline,'Runtime deadline');for(const c of await ownedResources(m)){validateRuntimeBounds(c);assert(!c.State.OOMKilled,'Container OOM');}}catch(e){monitorError=e;for(const p of activeCommands)p.kill('SIGTERM');break;}await pause(5000,undefined,{signal:controller.signal}).catch(()=>{});}})();
 const step=async fn=>{if(monitorError)throw monitorError;await fn();if(monitorError)throw monitorError;};
 const sql=input=>dc(['exec','-T','database','psql','-X','-U','postgres','-d','managed_rehearsal','-v','ON_ERROR_STOP=1','-q','-t','-A'],{input,maxBytes:1024*1024});
 const harness=p=>dc(['run','--rm','--no-deps','executor','node','rehearsal/harness.mjs',p],{timeout:180000,maxBytes:1024*1024});
 const stopSignal=()=>{monitorError=Error('Supervisor interrupted');controller.abort();for(const p of activeCommands)p.kill('SIGTERM');};process.once('SIGTERM',stopSignal);process.once('SIGINT',stopSignal);
 try{
  await step(async()=>{await dc(['up','-d','--no-build','database']);await waitDB(dc);await sql(await rolesSql(root));await sql(await rolesSql(root));await dc(['up','-d','--no-build','auth']);await harness('users');await migrations(m,dc);await migrations(m,dc);await sql(await seedSql(root));await sql(await seedSql(root));});
  await step(async()=>{await dc(['up','-d','--no-build','rest','managed-gateway','telemetry-gateway','objects']);await harness('exercise');await dc(['stop','objects']);await dc(['up','-d','--no-build','objects-pressure']);const space=JSON.parse(await dc(['exec','-T','objects-pressure','node','-e',"require('node:fs').statfs('/data/objects',(e,s)=>{if(e)process.exit(1);console.log(JSON.stringify({capacity:s.bsize*s.blocks}))})"]));assert(space.capacity===1048576,'Pressure tmpfs size not applied');await writeFile(join(root,'evidence/pressure-filesystem.json'),JSON.stringify(space));await harness('pressure');await dc(['stop','objects-pressure']);await dc(['up','-d','--no-build','objects']);});
  await step(async()=>{const lease=await json(join(root,'evidence/lease.json'));await sql(`UPDATE managed_jobs SET lease_until=now()-interval '1 second' WHERE id='${uuid(lease.id)}' AND project_id='${ids.pA}';`);await harness('expired');await dc(['up','-d','--no-build','worker']);await harness('worker');await dc(['stop','worker']);await harness('load');});
  await step(async()=>{const u=await json(join(root,'evidence/users.json'));await sql(`DELETE FROM organization_members WHERE user_id='${uuid(u.a)}'; UPDATE managed_workers SET enabled=false WHERE project_id='${ids.pA}';`);await harness('revoked');await sql(`INSERT INTO organization_members VALUES('${ids.orgA}','${uuid(u.a)}','member') ON CONFLICT DO NOTHING; UPDATE managed_workers SET enabled=true WHERE project_id='${ids.pA}';`);});
  await step(async()=>{await dc(['stop','worker','auth','rest','managed-gateway','telemetry-gateway','objects']);await dc(['exec','-T','database','pg_dump','-U','postgres','-d','managed_rehearsal','-Fc'],{outputFile:join(root,'backup/database.dump'),maxBytes:64*1024*1024});await treeSafe(join(root,'data/objects'));await cp(join(root,'data/objects'),join(root,'restore/objects'),{recursive:true,errorOnExist:true,force:false,preserveTimestamps:true});await restoreOwnership(join(root,'restore/objects'));await writeFile(join(root,'backup/manifest.json'),JSON.stringify({database_sha256:hash(await readFile(join(root,'backup/database.dump'))),method:'writers stopped; logical PG dump + private objects',objects:await fileManifest(join(root,'data/objects')),id:m.id}));assert(JSON.stringify(await fileManifest(join(root,'restore/objects')))===JSON.stringify((await json(join(root,'backup/manifest.json'))).objects),'Object copy checksum mismatch');await dc(['down','--timeout','10']);await writeFile(join(root,'inputs/compose.env'),composeEnvironment(m,true),{mode:0o600});await dc(['up','-d','--no-build','database']);await waitDB(dc);await sql(await rolesSql(root,{restore:true}));const dump=await readFile(join(root,'backup/database.dump'));assert(hash(dump)===(await json(join(root,'backup/manifest.json'))).database_sha256,'Dump checksum mismatch');await dc(['exec','-T','database','pg_restore','-U','postgres','-d','managed_rehearsal','--clean','--if-exists','--exit-on-error','--single-transaction'],{input:dump,maxBytes:1024*1024});await dc(['up','-d','--no-build','auth','rest','managed-gateway','telemetry-gateway','objects']);await harness('restored');});
  await writeFile(join(root,'evidence/summary.json'),JSON.stringify({passed:true,id:m.id,finished:new Date().toISOString(),production_mutations:0,linux_executed:true,inngest:'excluded; automatic review block remains'},null,2));
 }finally{controller.abort();await monitorPromise;process.removeListener('SIGTERM',stopSignal);process.removeListener('SIGINT',stopSignal);await cleanup(root);await writeFile(join(root,'watchdog-cancel.json'),JSON.stringify({id:m.id}));}
}
async function restoreOwnership(path){await noSymlink(path);await chown(path,1000,1000);for(const entry of await readdir(path,{withFileTypes:true})){assert(!entry.isSymbolicLink(),'Unsafe restore entry');const child=join(path,entry.name);if(entry.isDirectory())await restoreOwnership(child);else await chown(child,1000,1000);}}
async function exists(path){try{await lstat(path);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}}
async function watchdog(root){const m=await marker(root),s=await json(join(root,'run-state.json'));validDeadline(s,m);await writeFile(join(root,'watchdog-ready.json'),JSON.stringify({id:m.id}),{mode:0o600});while(Date.now()<s.deadline){if(await exists(join(root,'watchdog-cancel.json')))return;await pause(1000);}await cleanup(root);}
export async function main(args){const mode=args[0],get=k=>args[args.indexOf(k)+1];if(mode==='prepare'){const m=await prepare(get('--parent'));await runtimeFiles(m);console.log(JSON.stringify({prepared_root:m.root,expires:m.expires,credentials:'private files only',linux_execution:false}));return;}
 assert(args.includes('--root'),'Explicit root required');const root=resolve(get('--root'));await marker(root);
 if(mode==='preflight')console.log(JSON.stringify(await preflight(root)));
 else if(mode==='run'){assert(args.includes('--reviewed'),'Review package and host before --reviewed');await run(root);console.log(JSON.stringify({finished:true,evidence:join(root,'evidence')}));}
 else if(mode==='stop')await cleanup(root);
 else if(mode==='watchdog')await watchdog(root);
 else if(mode==='purge'){assert(args.includes('--discard-fictional-data'),'Explicit disposable data flag required');assert((await json(join(root,'stopped.json'))).containers_remaining===0,'Stop and verify runtime first');assert((await ownedResources(await marker(root))).length===0,'Containers still exist');for(const child of ['data','restore','backup','secrets','inputs'])await removeOwnedChild(root,child);console.log(JSON.stringify({purged:'only owned fixture children',evidence_preserved:true}));}
 else throw Error('Mode must be prepare, preflight, run, stop or purge');
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main(process.argv.slice(2)).catch(e=>{console.error(JSON.stringify({passed:false,error:e.message}));process.exitCode=1;});
