'use client';
import Link from 'next/link';
import {EngineMetadata} from './engine-metadata';
import {useState,useRef,useEffect,type FormEvent,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import {Database,Workflow,LayoutGrid,Table2,Folder,Users,Activity,Settings,Server,Search,ChevronRight,ArrowUpRight,RefreshCw,Plus,Clock,ShieldCheck} from 'lucide-react';
import type {ManagedProject,ProjectSnapshot,Row,HostSample,AlertSettings} from '@/lib/managed-projects/contracts';
import {evaluateAlerts,networkRate} from '@/lib/managed-projects/contracts';
import styles from './portal.module.css';
const base='/infraestrutura';
const statusLabels:Record<string,string>={pending:'Pendente',ready:'Disponível',deleting:'Excluindo',deleted:'Excluído',draft:'Rascunho',active:'Ativo',paused:'Pausado',queued:'Na fila',running:'Executando',succeeded:'Concluído',failed:'Falhou',uncertain:'Resultado incerto'};
const metricLabels:Record<string,string>={cpu:'CPU',memory:'Memória',disk:'Disco'};
const alertEventLabels:Record<string,string>={opened:'Aberto',recovered:'Recuperado',reminder:'Persistente'};
const fmt=(n:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(n);
const date=(v:unknown)=>v?new Date(String(v)).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
export type PortalProps={admin:boolean;userId:string;projects:ManagedProject[];companies?:{id:string;name:string}[];snapshot?:ProjectSnapshot;path:string[];samples?:HostSample[];settings?:AlertSettings;alertEvents?:Row[];alertStates?:Row[];pilot?:boolean;homologation?:boolean};
export function ManagedPortal(props:PortalProps){
 const router=useRouter();const {admin,projects,snapshot,path}=props;const p=snapshot?.project;
 const area=path[0]==='vps'?'vps':path[2]??'banco';const tab=path[3]??'overview';
 const [search,setSearch]=useState('');const [company,setCompany]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [dialog,setDialog]=useState<string|null>(null);const [editing,setEditing]=useState<Row|null>(null);
 const canWrite=p?.status==='active'&&(admin||snapshot?.members.some(m=>m.user_id===props.userId&&m.role==='operator'));
 const uploadIds=useRef(new Map<string,string>());
 const objectRows=snapshot?.objects?.filter(o=>o.status!=='deleted')??[];
 async function action(body:Row,endpoint=p?`/api/managed-projects/${p.id}`:'/api/managed-projects'){
  setBusy(true);setMessage('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error??'Não foi possível concluir.');setDialog(null);setMessage('Alteração concluída.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}
 }
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget));
  if(dialog==='project')void action({...d,concurrency_limit:1});
  if(dialog==='record'){try{void action({action:editing?'record.update':'record.create',id:editing?.id,collection:d.collection,data:JSON.parse(String(d.data))});}catch{setMessage('Informe um objeto JSON válido.');}}
  if(dialog==='resource')void action({action:'resource.link',...d});
  if(dialog==='member')void action({action:'member.put',...d});
  if(dialog==='limits')void action({action:'project.update',status:d.status,concurrency_limit:Number(d.concurrency_limit),queue_limit:Number(d.queue_limit),storage_limit_bytes:Number(d.storage_limit_bytes)});
  if(dialog==='alerts')void action(Object.fromEntries(Object.entries(d).map(([k,v])=>[k,Number(v)])),'/api/managed-infrastructure');
 }
 const href=(section:string,sub='')=>`${base}/projetos/${p?.id}/${section}${sub?`/${sub}`:''}`;
 const nav=p?[{id:'banco',label:'Banco',icon:Database},{id:'automacoes',label:'Automações',icon:Workflow},{id:'configuracoes',label:'Configurações',icon:Settings}]:[];
 const sections=area==='banco'?[['overview','Visão geral',LayoutGrid],['tabelas','Editor de tabelas',Table2],['arquivos','Arquivos',Folder],['auth','Acessos',Users],['logs','Logs',Activity]] as const:[['overview','Visão geral',LayoutGrid],['apps','Apps',LayoutGrid],['functions','Functions',Workflow],['runs','Runs',Activity],['events','Events',Clock]] as const;
 const filtered=projects.filter(pr=>(!company||pr.organization_id===company)&&`${pr.name} ${pr.organization_id} ${pr.slug}`.toLowerCase().includes(search.toLowerCase()));
 const queue=snapshot?.jobs.filter(j=>['queued','running'].includes(String(j.status))).length??0;
 const successes=snapshot?.jobs.filter(j=>j.status==='succeeded').length??0;
 return <div className={styles.portal}>
  <header className={styles.header}><Link href={base} className={styles.brand}><span className={styles.brandMark}>C</span> ConnectyHub</Link><span className={styles.divider}>/</span><Link href={base}>Projetos</Link>{p&&<><ChevronRight size={13}/><select aria-label="Selecionar projeto" value={p.id} onChange={e=>router.push(`${base}/projetos/${e.target.value}/banco`)}>{projects.map(pr=><option key={pr.id} value={pr.id}>{pr.name}</option>)}</select></>}<span className={styles.environment}>{props.pilot?'PILOTO LOCAL':props.homologation?'HOMOLOGAÇÃO':'GERENCIADO'}</span><div className={styles.headerEnd}><ShieldCheck size={15}/>{admin?'Administração de infraestrutura':'Acesso por projeto'}{props.homologation&&admin&&<Link href="/clientes">Clientes</Link>}<Link href={props.homologation?"/conta":"/dashboard"} title={props.homologation?"Minha conta":"Voltar ao produto"}><ArrowUpRight size={16}/></Link></div></header>
  {props.pilot&&<div className={styles.notice}>Ambiente isolado · dados fictícios · nenhum serviço de produção conectado</div>}
  <div className={styles.frame}><aside className={styles.rail}><Link href={base} title="Projetos" aria-label="Projetos"><LayoutGrid size={19}/></Link>{nav.map(n=><Link key={n.id} href={href(n.id)} aria-label={n.label} title={n.label} className={area===n.id?styles.current:''}><n.icon size={19}/></Link>)}{admin&&<Link href={`${base}/vps`} aria-label="Infraestrutura global" title="Infraestrutura global" className={area==='vps'?styles.current:''}><Server size={19}/></Link>}</aside>
  {p&&area!=='configuracoes'&&<aside className={styles.sidebar}><h2>{area==='banco'?'Banco':'Automações'}</h2><div className={styles.eyebrow}>{p.name}</div><nav>{sections.map(([slug,text,Icon])=><Link key={slug} href={href(area,slug==='overview'?'':slug)} className={tab===slug?styles.selected:''}><Icon size={15}/>{text}</Link>)}</nav><div className={styles.sidebarFoot}>Projeto gerenciado<br/><span>Dados e permissões isolados</span></div></aside>}
  <main className={styles.main}>
   <div className={styles.toolbar}><span>{p?`${p.name} / ${area==='banco'?'Banco':area==='automacoes'?'Automações':'Configurações'}`:area==='vps'?'Infraestrutura / Visão global':'Organizações / Projetos'}</span><button onClick={()=>router.refresh()} aria-label="Atualizar"><RefreshCw size={14}/>Atualizar</button></div>
   {message&&<div role="status" className={styles.notice}>{message}</div>}
   {!p&&area!=='vps'&&<section className={styles.content}><div className={styles.titleRow}><div><h1>Projetos</h1><p>Banco e automações dos projetos {admin?'da infraestrutura':'aos quais você tem acesso'}.</p></div>{admin&&<button className={styles.primary} onClick={()=>setDialog('project')}><Plus size={15}/>Novo projeto</button>}</div><div className={styles.search}><Search size={15}/><input aria-label="Buscar projeto" placeholder="Buscar nome, empresa ou identificador..." value={search} onChange={e=>setSearch(e.target.value)}/><span>{filtered.length} projetos</span></div><label className={styles.inline}>Empresa <select aria-label="Selecionar empresa" value={company} onChange={e=>setCompany(e.target.value)}><option value="">Todas as empresas permitidas</option>{props.companies?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className={styles.projectGrid} style={{marginTop:20}}>{filtered.map(pr=><Link key={pr.id} href={`${base}/projetos/${pr.id}/banco`} className={styles.projectCard}><div className={styles.titleRow}><Database size={22}/><Badge status={pr.status}/></div><h2>{pr.name}</h2><p>{pr.slug}</p><small>{props.companies?.find(c=>c.id===pr.organization_id)?.name??"Empresa vinculada"}</small><footer><span>Banco · Automações</span><ArrowUpRight size={16}/></footer></Link>)}</div>{!filtered.length&&<Empty title="Nenhum projeto encontrado" detail={admin?'Cadastre um projeto em rascunho para iniciar a configuração.':'Solicite ao responsável o vínculo com um projeto existente.'}/>}</section>}
   {p&&snapshot&&<section className={styles.content}>{snapshot.truncated&&<div className={styles.notice}>Mostrando até 200 registros recentes por seção. Indicadores abaixo representam esta amostra.</div>}<div className={styles.titleRow}><div><h1>{tab==='overview'?p.name:tab==='tabelas'?'Editor de tabelas':tab==='arquivos'?'Arquivos':tab==='auth'?'Acessos ao projeto':tab==='logs'?'Logs':tab==='runs'?'Runs':tab==='functions'?'Functions':tab==='apps'?'Apps':tab==='events'?'Events':'Configurações'}</h1><p>{area==='banco'?'Banco de dados do projeto':area==='automacoes'?'Execuções, filas e resultados de negócio':'Membros e limites do projeto gerenciado'}</p></div><Badge status={p.status}/></div>
   {p&&area==='automacoes'&&<EngineMetadata projectId={p.id}/>}
   {tab==='overview'&&area!=='configuracoes'&&<><div className={styles.overview}><div><div className={styles.overviewInfo}><Stat label="ESTADO" value={statusLabels[p.status]}/><Stat label="CONCORRÊNCIA" value={String(p.concurrency_limit)}/><Stat label="ARMAZENAMENTO" value={`${fmt([...snapshot.files,...objectRows].reduce((n,f)=>n+Number(f.bytes),0)/1024)} KB`}/><Stat label="RESULTADO" value={`${successes} execuções concluídas`}/></div></div><div className={styles.topology}><div className={styles.node}><Database size={20}/><strong>{p.name}</strong><small>{area==='banco'?'Banco gerenciado':'Worker de diagnóstico'}</small><footer>Projeto isolado · {p.slug}</footer></div></div></div><div className={styles.stats}><Stat label="Registros" value={String(snapshot.records.length)}/><Stat label="Arquivos" value={String(snapshot.files.length+objectRows.length)}/><Stat label="Fila / limite" value={`${queue} / ${p.queue_limit}`}/><Stat label="Falhas / incertas" value={String(snapshot.jobs.filter(j=>['failed','uncertain'].includes(String(j.status))).length)}/></div><h2>Atividade recente</h2><Grid rows={snapshot.logs.slice(0,8)} columns={[['code','Evento'],['job_id','Execução'],['created_at','Horário']]}/><p className={styles.muted}>As métricas representam o projeto. Custo de fornecedor e cobrança não são inferidos destas contagens.</p></>}
   {tab==='tabelas'&&<><div className={styles.titleRow}><span className={styles.pill}>Registros · JSON</span>{canWrite&&<button className={styles.primary} onClick={()=>{setEditing(null);setDialog('record');}}><Plus size={14}/>Inserir registro</button>}</div><Grid rows={snapshot.records} columns={[['id','ID'],['collection','Coleção'],['data','Dados'],['created_at','Criado em']]} action={canWrite?row=><div className={styles.inline}><button onClick={()=>{setEditing(row);setDialog('record');}}>Editar</button><button disabled={busy} onClick={()=>void action({action:'record.delete',id:row.id})}>Excluir</button></div>:undefined}/><p className={styles.muted}>Este editor trabalha com coleções do projeto. SQL global e alterações de estrutura não estão disponíveis ao cliente.</p></>}
   {tab==='arquivos'&&<><div className={styles.titleRow}><span className={styles.pill}>Privado · {fmt(p.storage_limit_bytes/1024/1024)} MB de limite</span>{canWrite&&<label className={styles.upload}>{busy?'Enviando...':'Enviar arquivo'}<input type="file" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>1048576){setMessage('Limite de 1 MB por arquivo nesta etapa.');return;}try{const buffer=await file.arrayBuffer();const bytes=new Uint8Array(buffer);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),b=>b.toString(16).padStart(2,'0')).join('');const key=`${p.id}/${file.name}/${hash}`;const existing=objectRows.find(row=>row.name===file.name&&row.sha256===hash&&['pending','ready'].includes(String(row.status)));const id=String(existing?.id??uploadIds.current.get(key)??crypto.randomUUID());uploadIds.current.set(key,id);let binary='';for(const b of bytes)binary+=String.fromCharCode(b);await action({action:'put',name:file.name,base64:btoa(binary)},`/api/managed-projects/${p.id}/objects/${id}`);}catch{setMessage('Nao foi possivel ler o arquivo. Tente novamente.');}}}/></label>}</div><Grid rows={objectRows} columns={[['name','Nome'],['bytes','Bytes'],['status','Estado'],['created_at','Enviado em']]} action={row=><div className={styles.inline}>{row.status==='ready'&&<a href={`/api/managed-projects/${p.id}/objects/${row.id}`} download>Baixar</a>}{canWrite&&<button disabled={busy} onClick={()=>void action({action:'delete'},`/api/managed-projects/${p.id}/objects/${row.id}`)}>{row.status==='deleting'?'Concluir exclusão':'Excluir'}</button>}</div>}/><p className={styles.muted}>Objetos privados fora do banco · até 1 MB por envio nesta etapa. Estados pendentes mantêm a reserva de espaço até confirmação ou exclusão.</p><h2>Arquivos anteriores do piloto</h2><Grid rows={snapshot.files} columns={[['name','Nome'],['bytes','Bytes'],['created_at','Enviado em']]} action={row=><div className={styles.inline}><a href={`/api/managed-projects/${p.id}/files/${row.id}`} download>Baixar</a>{canWrite&&<button disabled={busy} onClick={()=>void action({action:'file.delete',id:row.id})}>Excluir</button>}</div>}/><p className={styles.muted}>Arquivos anteriores permanecem no banco; o novo envio usa o serviço privado de objetos.</p></>}
   {(tab==='auth'||area==='configuracoes')&&<><div className={styles.titleRow}><h2>Membros</h2>{admin&&<button onClick={()=>setDialog('member')}>Vincular usuário existente</button>}</div><Grid rows={snapshot.members} columns={[['user_id','Usuário'],['role','Papel']]} action={admin?row=><button disabled={busy} onClick={()=>void action({action:'member.delete',user_id:row.user_id})}>Revogar</button>:undefined}/><p className={styles.muted}>O vínculo usa a conta existente e exige participação na empresa. Não cria senha ou usuário novo.</p>{admin&&<div className={styles.inline}><button onClick={()=>setDialog('limits')}>Configurar estado e limites</button>{!props.homologation&&<button onClick={()=>setDialog('resource')}>Vincular projeto de API</button>}</div>}<h2 style={{marginTop:24}}>Recursos vinculados</h2><Grid rows={snapshot.resources} columns={[["ai_project_id","Projeto de IA"],["voice_project_id","Projeto de Voz"]]} action={admin?row=><button disabled={busy} onClick={()=>void action({action:'resource.unlink',id:row.id})}>Desvincular</button>:undefined}/><div className={styles.stats}><Stat label="Concorrência" value={String(p.concurrency_limit)}/><Stat label="Limite de fila" value={String(p.queue_limit)}/><Stat label="Armazenamento" value={`${fmt(p.storage_limit_bytes/1024/1024)} MB`}/></div></>}
   {tab==='logs'&&<Grid rows={snapshot.logs} columns={[['code','Evento'],['job_id','Execução'],['created_at','Horário']]}/>}
   {tab==='apps'&&<div className={styles.projectGrid}><div className={styles.projectCard}><Workflow size={22}/><h2>Diagnóstico do projeto</h2><p>Aplicativo de diagnóstico</p><footer>1 função · sem chamadas pagas</footer></div></div>}
   {tab==='functions'&&<Grid rows={[{name:'diagnostic.ping',trigger:'Solicitação autenticada',execution:'Worker persistente',effects:'Sem efeitos externos'}]} columns={[['name','Função'],['trigger','Gatilho'],['execution','Execução'],['effects','Efeitos']]}/>}
   {(tab==='runs'||tab==='events')&&<><div className={styles.titleRow}><div className={styles.search}><Search size={14}/><input aria-label="Filtrar execuções" placeholder="Filtrar ID ou estado..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{canWrite&&<button className={styles.primary} disabled={busy} onClick={()=>void action({action:'job.create',idempotency_key:crypto.randomUUID()})}>Executar diagnóstico</button>}</div><Grid rows={snapshot.jobs.filter(j=>`${j.id} ${j.status}`.toLowerCase().includes(search.toLowerCase()))} columns={[['status','Status'],['id','Run ID'],['kind','Função'],['created_at','Na fila em'],['finished_at','Concluída em'],['result_code','Resultado']]} action={row=><details><summary>Detalhes</summary><pre>{JSON.stringify(row,null,2)}</pre></details>}/><p className={styles.muted}>Somente diagnósticos deste ambiente. Inngest não está integrado a este portal.</p></>}
   </section>}
   {area==='vps'&&admin&&<section className={styles.content}><div className={styles.titleRow}><div><h1>Infraestrutura</h1><p>Visão global da VPS · acesso exclusivo da infraestrutura</p></div><button onClick={()=>setDialog('alerts')}>Configurar alertas</button></div><HostDashboard samples={props.samples??[]} settings={props.settings!} alertEvents={props.alertEvents} alertStates={props.alertStates}/></section>}
  </main></div>
  {dialog&&<Modal close={()=>setDialog(null)}><div className={styles.titleRow}><h2>{dialog==='project'?'Novo projeto':dialog==='record'?'Inserir registro':dialog==='member'?'Vincular usuário':dialog==='alerts'?'Alertas da infraestrutura':dialog==='resource'?'Vincular projeto de API':'Limites do projeto'}</h2><button onClick={()=>setDialog(null)} aria-label="Fechar">×</button></div><form onSubmit={submit}>
   {dialog==='project'&&<><Field name="name" label="Nome do projeto"/><Field name="slug" label="Identificador"/><label>Empresa<select name="organization_id" required>{props.companies?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p>O cadastro começa em rascunho. Nenhuma stack ou cobrança será criada.</p></>}
   {dialog==='record'&&<><Field name="collection" label="Coleção" value={String(editing?.collection??"notes")}/><label>Dados JSON<textarea name="data" defaultValue={editing?JSON.stringify(editing.data,null,2):'{\n  "text": ""\n}'} required rows={7}/></label></>}
   {dialog==='resource'&&<><label>Tipo<select name="kind"><option value="ai">API de IA</option><option value="voice">API de Voz</option></select></label><Field name="resource_id" label="ID do projeto de API existente"/><p>O recurso deve pertencer à mesma empresa. A carteira e as tarifas permanecem no serviço original.</p></>}
   {dialog==='member'&&<><Field name="user_id" label="ID do usuário existente"/><label>Papel<select name="role"><option value="viewer">Leitura</option><option value="operator">Operação</option></select></label></>}
   {dialog==='limits'&&p&&<><label>Estado<select name="status" defaultValue={p.status}>{Object.entries(statusLabels).filter(([state])=>['draft','active','paused'].includes(state)).map(([s,l])=><option key={s} value={s}>{l}</option>)}</select></label><Field name="concurrency_limit" label="Concorrência" value={p.concurrency_limit} type="number"/><Field name="queue_limit" label="Limite da fila" value={p.queue_limit} type="number"/><Field name="storage_limit_bytes" label="Armazenamento (bytes)" value={p.storage_limit_bytes} type="number"/></>}
   {dialog==='alerts'&&props.settings&&<>{Object.entries(props.settings).filter(([k])=>k!=='id').map(([key,value])=><Field key={key} name={key} label={key==='stale_seconds'?'Coleta desatualizada após (segundos)':key==='cpu_percent'?'CPU (%)':key==='memory_percent'?'Memória (%)':'Disco (%)'} value={value} type="number"/>)}</>}
   {message&&<p role="alert">{message}</p>}<button className={styles.primary} type="submit" disabled={busy}>{busy?'Salvando...':'Salvar'}</button></form></Modal>}
 </div>;
}
function Field({name,label,value,type='text'}:{name:string;label:string;value?:string|number;type?:string}){return <label>{label}<input name={name} defaultValue={value} type={type} required/></label>;}
function Stat({label,value}:{label:string;value:string}){return <div className={styles.stat}><small>{label}</small><strong>{value}</strong></div>;}
function Badge({status}:{status:string}){return <span className={`${styles.badge} ${['active','succeeded'].includes(status)?styles.good:styles.neutral}`}><span/>{statusLabels[status]??status}</span>;}
function Empty({title='Nenhum registro',detail='A atividade deste projeto aparecerá aqui.'}:{title?:string;detail?:string}){return <div className={styles.empty}><Database size={25}/><h3>{title}</h3><p>{detail}</p></div>;}
function Grid({rows,columns,action}:{rows:Row[];columns:[string,string][];action?:(row:Row)=>ReactNode}){if(!rows.length)return <Empty/>;return <div className={styles.tableWrap}><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}{action&&<th>Ações</th>}</tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??row.user_id??i)}>{columns.map(([key])=><td key={key}>{key==='status'?<Badge status={String(row[key])}/>:key.endsWith('_at')?date(row[key]):row[key]===null?'—':typeof row[key]==='object'?<code>{JSON.stringify(row[key])}</code>:String(row[key]??'—')}</td>)}{action&&<td>{action(row)}</td>}</tr>)}</tbody></table></div>;}
function HostDashboard({samples,settings,alertEvents=[],alertStates=[]}:{samples:HostSample[];settings:AlertSettings;alertEvents?:Row[];alertStates?:Row[]}){const sorted=[...samples].sort((a,b)=>Date.parse(b.measured_at)-Date.parse(a.measured_at));const s=sorted[0];const rate=sorted[1]&&s?networkRate(sorted[1],s):null;const alerts=evaluateAlerts(s,settings);return <><div className={styles.notice}>{alerts.length?alerts.join(' '):'Última amostra dentro dos limites configurados.'}</div>{s?<><div className={styles.stats}><Stat label="CPU" value={s.cpu_percent===null?'Sem amostra':`${fmt(s.cpu_percent)}%`}/><Stat label="Memória em uso" value={`${fmt((1-s.memory_available/s.memory_total)*100)}%`}/><Stat label="Disco em uso" value={`${fmt(s.disk_used/s.disk_total*100)}%`}/><Stat label="Rede de entrada" value={rate?.rx!=null?`${fmt(rate.rx/1024)} KB/s`:'Sem intervalo válido'}/></div><div className={styles.chart}><div className={styles.titleRow}><h2>CPU · amostras recentes</h2><small>Última coleta: {date(s.measured_at)}</small></div><div className={styles.bars}>{[...sorted].reverse().map(x=><div key={x.measured_at} title={`${date(x.measured_at)}: ${x.cpu_percent??'sem dado'}%`} style={{height:`${x.cpu_percent??0}%`}}/>)}</div></div><h2>Serviços</h2><Grid rows={s.services} columns={[['name','Serviço'],['status','Estado']]}/></>:<Empty title="Aguardando coleta" detail="O coletor ainda não enviou amostras a este ambiente."/>}<h2>Alertas persistidos</h2><Grid rows={alertStates.map(s=>({...s,metric:metricLabels[String(s.metric)]??s.metric,status:s.last_value===null?'Sem amostra':s.active?'Alerta':'Normal'}))} columns={[['metric','Métrica'],['status','Estado'],['bad_samples','Amostras consecutivas'],['last_sample_at','Última amostra']]}/><h2>Histórico de alertas</h2><Grid rows={alertEvents.map(e=>({...e,metric:metricLabels[String(e.metric)]??e.metric,event:alertEventLabels[String(e.event)]??e.event}))} columns={[['metric','Métrica'],['event','Transição'],['value','Valor (%)'],['measured_at','Horário']]}/><p className={styles.muted}>Valores medidos no host; não representam custo ou CPU individual de cliente. Alertas nesta fase aparecem no painel, sem envio externo.</p></>;}
function Modal({children,close}:{children:ReactNode;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const dialog=ref.current;dialog?.showModal();return()=>{dialog?.close();previous?.focus();};},[]);return <dialog ref={ref} className={styles.dialog} aria-label="Configurar projeto" onCancel={close}>{children}</dialog>;}
