export type UazapiAuthMode = "admin" | "instance";
export type UazapiMethod = "GET" | "POST" | "PUT" | "DELETE";
export type UazapiRisk = "standard" | "sensitive" | "danger";

export type UazapiOperation = {
  operationId: string;
  method: UazapiMethod;
  path: string;
  auth: UazapiAuthMode;
  category: string;
  title: string;
  risk?: UazapiRisk;
  samplePayload?: Record<string, unknown>;
  sampleQuery?: Record<string, string>;
};

export const uazapiOperations = [
  {
    operationId: "createInstance",
    method: "POST",
    path: "/instance/create",
    auth: "admin",
    category: "Instancias",
    title: "Criar instancia",
    samplePayload: { name: "connectyhub-cliente-001", adminField01: "workspace_cli_001" },
  },
  {
    operationId: "listAllInstances",
    method: "GET",
    path: "/instance/all",
    auth: "admin",
    category: "Instancias",
    title: "Listar todas as instancias",
    risk: "sensitive",
  },
  {
    operationId: "connectInstance",
    method: "POST",
    path: "/instance/connect",
    auth: "instance",
    category: "Instancias",
    title: "Conectar instancia com QR code ou codigo",
    samplePayload: { browser: "auto", systemName: "ConnectyHub" },
  },
  {
    operationId: "disconnectInstance",
    method: "POST",
    path: "/instance/disconnect",
    auth: "instance",
    category: "Instancias",
    title: "Desconectar instancia",
    risk: "sensitive",
  },
  {
    operationId: "resetInstance",
    method: "POST",
    path: "/instance/reset",
    auth: "instance",
    category: "Instancias",
    title: "Resetar instancia",
    risk: "sensitive",
  },
  {
    operationId: "getInstanceStatus",
    method: "GET",
    path: "/instance/status",
    auth: "instance",
    category: "Instancias",
    title: "Ver status da instancia",
  },
  {
    operationId: "getWAMessageLimits",
    method: "GET",
    path: "/instance/wa_messages_limits",
    auth: "instance",
    category: "Instancias",
    title: "Consultar limites de novas conversas",
  },
  {
    operationId: "updateFieldsMap",
    method: "POST",
    path: "/instance/updateFieldsMap",
    auth: "instance",
    category: "Instancias",
    title: "Atualizar mapa de campos",
  },
  {
    operationId: "updateInstanceName",
    method: "POST",
    path: "/instance/updateInstanceName",
    auth: "instance",
    category: "Instancias",
    title: "Atualizar nome da instancia",
    samplePayload: { name: "Loja Principal" },
  },
  {
    operationId: "updateAdminFields",
    method: "POST",
    path: "/instance/updateAdminFields",
    auth: "admin",
    category: "Instancias",
    title: "Atualizar campos administrativos",
    risk: "sensitive",
  },
  {
    operationId: "getProxyConfig",
    method: "GET",
    path: "/instance/proxy",
    auth: "instance",
    category: "Instancias",
    title: "Ver proxy da instancia",
  },
  {
    operationId: "updateProxyConfig",
    method: "POST",
    path: "/instance/proxy",
    auth: "instance",
    category: "Instancias",
    title: "Atualizar proxy da instancia",
    risk: "sensitive",
  },
  {
    operationId: "listRegionCities",
    method: "GET",
    path: "/proxy-managed/cities",
    auth: "instance",
    category: "Instancias",
    title: "Listar cidades de proxy regional",
    sampleQuery: { country: "br", state: "sp", search: "campinas" },
  },
  {
    operationId: "updateProfileName",
    method: "POST",
    path: "/profile/name",
    auth: "instance",
    category: "Perfil",
    title: "Atualizar nome do perfil",
    samplePayload: { name: "Minha Loja" },
  },
  {
    operationId: "updateProfileImage",
    method: "POST",
    path: "/profile/image",
    auth: "instance",
    category: "Perfil",
    title: "Atualizar imagem do perfil",
    samplePayload: { image: "https://exemplo.com/avatar.jpg" },
  },
  {
    operationId: "deleteInstance",
    method: "DELETE",
    path: "/instance",
    auth: "instance",
    category: "Instancias",
    title: "Excluir instancia",
    risk: "danger",
  },
  {
    operationId: "getInstancePrivacy",
    method: "GET",
    path: "/instance/privacy",
    auth: "instance",
    category: "Instancias",
    title: "Ver privacidade",
  },
  {
    operationId: "setPrivacySetting",
    method: "POST",
    path: "/instance/privacy",
    auth: "instance",
    category: "Instancias",
    title: "Atualizar privacidade",
  },
  {
    operationId: "updateInstancePresence",
    method: "POST",
    path: "/instance/presence",
    auth: "instance",
    category: "Instancias",
    title: "Atualizar presenca da instancia",
    samplePayload: { presence: "available" },
  },
  {
    operationId: "sendText",
    method: "POST",
    path: "/send/text",
    auth: "instance",
    category: "Envio",
    title: "Enviar texto",
    samplePayload: {
      number: "5511999999999",
      text: "Ola {{name}}, aqui e a ConnectyHub.",
      linkPreview: true,
      track_source: "connectyhub",
      track_id: "lead_001",
    },
  },
  {
    operationId: "sendMedia",
    method: "POST",
    path: "/send/media",
    auth: "instance",
    category: "Envio",
    title: "Enviar midia",
    samplePayload: { number: "5511999999999", type: "image", file: "https://exemplo.com/foto.jpg", text: "Veja isso" },
  },
  {
    operationId: "sendContact",
    method: "POST",
    path: "/send/contact",
    auth: "instance",
    category: "Envio",
    title: "Enviar contato",
  },
  {
    operationId: "sendLocation",
    method: "POST",
    path: "/send/location",
    auth: "instance",
    category: "Envio",
    title: "Enviar localizacao",
  },
  {
    operationId: "sendPresence",
    method: "POST",
    path: "/message/presence",
    auth: "instance",
    category: "Mensagens",
    title: "Enviar presenca no chat",
    samplePayload: { number: "5511999999999", presence: "composing" },
  },
  {
    operationId: "sendStatus",
    method: "POST",
    path: "/send/status",
    auth: "instance",
    category: "Envio",
    title: "Enviar status",
    samplePayload: { type: "text", text: "Oferta de hoje", backgroundColor: 4 },
  },
  {
    operationId: "sendMenu",
    method: "POST",
    path: "/send/menu",
    auth: "instance",
    category: "Envio",
    title: "Enviar menu interativo",
    samplePayload: {
      number: "5511999999999",
      type: "button",
      text: "Escolha uma opcao",
      choices: ["Comprar|comprar", "Falar com humano|humano"],
    },
  },
  {
    operationId: "sendCarousel",
    method: "POST",
    path: "/send/carousel",
    auth: "instance",
    category: "Envio",
    title: "Enviar carrossel",
    samplePayload: {
      number: "5511999999999",
      text: "Produtos em destaque",
      carousel: [{ text: "Produto A", image: "https://exemplo.com/a.jpg", buttons: [{ id: "comprar_a", text: "Comprar", type: "REPLY" }] }],
    },
  },
  {
    operationId: "sendLocationButton",
    method: "POST",
    path: "/send/location-button",
    auth: "instance",
    category: "Envio",
    title: "Enviar botao de localizacao",
  },
  {
    operationId: "sendRequestPayment",
    method: "POST",
    path: "/send/request-payment",
    auth: "instance",
    category: "Pagamentos",
    title: "Solicitar pagamento",
    samplePayload: {
      number: "5511999999999",
      title: "Detalhes do pedido",
      text: "Pedido pronto para pagamento",
      itemName: "Plano Pro",
      amount: 199.9,
      pixKey: "123e4567-e89b-12d3-a456-426614174000",
      pixType: "EVP",
    },
  },
  {
    operationId: "sendPixButton",
    method: "POST",
    path: "/send/pix-button",
    auth: "instance",
    category: "Pagamentos",
    title: "Enviar botao PIX",
    samplePayload: { number: "5511999999999", pixType: "EVP", pixKey: "123e4567-e89b-12d3-a456-426614174000", pixName: "Loja Exemplo" },
  },
  {
    operationId: "getAsyncQueueStatus",
    method: "GET",
    path: "/message/async",
    auth: "instance",
    category: "Mensagens",
    title: "Ver fila assincrona",
  },
  {
    operationId: "clearAsyncQueue",
    method: "DELETE",
    path: "/message/async",
    auth: "instance",
    category: "Mensagens",
    title: "Limpar fila assincrona",
    risk: "danger",
  },
  {
    operationId: "downloadMessage",
    method: "POST",
    path: "/message/download",
    auth: "instance",
    category: "Mensagens",
    title: "Baixar midia da mensagem",
    samplePayload: { id: "7EB0F01D7244B421048F0706368376E0", transcribe: true, return_link: true },
  },
  {
    operationId: "findMessages",
    method: "POST",
    path: "/message/find",
    auth: "instance",
    category: "Mensagens",
    title: "Buscar mensagens",
    samplePayload: { chatid: "5511999999999@s.whatsapp.net", limit: 20, offset: 0 },
  },
  {
    operationId: "requestHistorySync",
    method: "POST",
    path: "/message/history-sync",
    auth: "instance",
    category: "Mensagens",
    title: "Solicitar historico do chat",
    samplePayload: { number: "5511999999999@s.whatsapp.net", mode: "history", count: 20 },
  },
  {
    operationId: "markMessageRead",
    method: "POST",
    path: "/message/markread",
    auth: "instance",
    category: "Mensagens",
    title: "Marcar mensagem como lida",
  },
  {
    operationId: "reactToMessage",
    method: "POST",
    path: "/message/react",
    auth: "instance",
    category: "Mensagens",
    title: "Reagir a mensagem",
  },
  {
    operationId: "deleteMessage",
    method: "POST",
    path: "/message/delete",
    auth: "instance",
    category: "Mensagens",
    title: "Apagar mensagem",
    risk: "danger",
  },
  {
    operationId: "editMessage",
    method: "POST",
    path: "/message/edit",
    auth: "instance",
    category: "Mensagens",
    title: "Editar mensagem",
  },
  {
    operationId: "pinMessage",
    method: "POST",
    path: "/message/pin",
    auth: "instance",
    category: "Mensagens",
    title: "Fixar mensagem",
  },
  {
    operationId: "createGroup",
    method: "POST",
    path: "/group/create",
    auth: "instance",
    category: "Grupos",
    title: "Criar grupo",
  },
  {
    operationId: "getGroupInfo",
    method: "POST",
    path: "/group/info",
    auth: "instance",
    category: "Grupos",
    title: "Ver dados do grupo",
  },
  {
    operationId: "getGroupInviteInfo",
    method: "POST",
    path: "/group/inviteInfo",
    auth: "instance",
    category: "Grupos",
    title: "Ver convite de grupo",
  },
  {
    operationId: "joinGroup",
    method: "POST",
    path: "/group/join",
    auth: "instance",
    category: "Grupos",
    title: "Entrar em grupo",
  },
  {
    operationId: "leaveGroup",
    method: "POST",
    path: "/group/leave",
    auth: "instance",
    category: "Grupos",
    title: "Sair de grupo",
    risk: "sensitive",
  },
  {
    operationId: "listGroups",
    method: "GET",
    path: "/group/list",
    auth: "instance",
    category: "Grupos",
    title: "Listar grupos",
  },
  {
    operationId: "refreshGroups",
    method: "POST",
    path: "/group/list",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar lista de grupos",
  },
  {
    operationId: "resetGroupInviteCode",
    method: "POST",
    path: "/group/resetInviteCode",
    auth: "instance",
    category: "Grupos",
    title: "Resetar convite do grupo",
    risk: "sensitive",
  },
  {
    operationId: "updateGroupAnnounce",
    method: "POST",
    path: "/group/updateAnnounce",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar modo anuncio",
  },
  {
    operationId: "updateGroupJoinApproval",
    method: "POST",
    path: "/group/updateJoinApproval",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar aprovacao de entrada",
  },
  {
    operationId: "updateGroupMemberAddMode",
    method: "POST",
    path: "/group/updateMemberAddMode",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar permissao de adicionar membros",
  },
  {
    operationId: "updateGroupDescription",
    method: "POST",
    path: "/group/updateDescription",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar descricao do grupo",
  },
  {
    operationId: "updateGroupEphemeral",
    method: "POST",
    path: "/group/ephemeral",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar mensagens temporarias do grupo",
  },
  {
    operationId: "updateGroupImage",
    method: "POST",
    path: "/group/updateImage",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar imagem do grupo",
  },
  {
    operationId: "updateGroupLocked",
    method: "POST",
    path: "/group/updateLocked",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar bloqueio do grupo",
  },
  {
    operationId: "updateGroupName",
    method: "POST",
    path: "/group/updateName",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar nome do grupo",
  },
  {
    operationId: "updateGroupParticipants",
    method: "POST",
    path: "/group/updateParticipants",
    auth: "instance",
    category: "Grupos",
    title: "Atualizar participantes",
  },
  {
    operationId: "createCommunity",
    method: "POST",
    path: "/community/create",
    auth: "instance",
    category: "Comunidades",
    title: "Criar comunidade",
  },
  {
    operationId: "editCommunityGroups",
    method: "POST",
    path: "/community/editgroups",
    auth: "instance",
    category: "Comunidades",
    title: "Editar grupos da comunidade",
  },
  {
    operationId: "createNewsletter",
    method: "POST",
    path: "/newsletter/create",
    auth: "instance",
    category: "Canais",
    title: "Criar canal/newsletter",
  },
  {
    operationId: "listNewsletters",
    method: "GET",
    path: "/newsletter/list",
    auth: "instance",
    category: "Canais",
    title: "Listar canais/newsletters",
  },
  {
    operationId: "getNewsletterInfo",
    method: "POST",
    path: "/newsletter/info",
    auth: "instance",
    category: "Canais",
    title: "Ver canal/newsletter",
  },
  {
    operationId: "getNewsletterInfoWithInvite",
    method: "POST",
    path: "/newsletter/link",
    auth: "instance",
    category: "Canais",
    title: "Ver canal por convite",
  },
  {
    operationId: "subscribeNewsletterLiveUpdates",
    method: "POST",
    path: "/newsletter/subscribe",
    auth: "instance",
    category: "Canais",
    title: "Assinar atualizacoes do canal",
  },
  {
    operationId: "getNewsletterMessages",
    method: "POST",
    path: "/newsletter/messages",
    auth: "instance",
    category: "Canais",
    title: "Buscar mensagens do canal",
  },
  {
    operationId: "editNewsletterMessage",
    method: "POST",
    path: "/newsletter/messages/edit",
    auth: "instance",
    category: "Canais",
    title: "Editar mensagem do canal",
  },
  {
    operationId: "deleteNewsletterMessage",
    method: "POST",
    path: "/newsletter/messages/delete",
    auth: "instance",
    category: "Canais",
    title: "Apagar mensagem do canal",
    risk: "danger",
  },
  {
    operationId: "getNewsletterMessageUpdates",
    method: "POST",
    path: "/newsletter/updates",
    auth: "instance",
    category: "Canais",
    title: "Ver atualizacoes de mensagem do canal",
  },
  {
    operationId: "markNewsletterViewed",
    method: "POST",
    path: "/newsletter/viewed",
    auth: "instance",
    category: "Canais",
    title: "Marcar canal como visto",
  },
  {
    operationId: "reactNewsletterMessage",
    method: "POST",
    path: "/newsletter/reaction",
    auth: "instance",
    category: "Canais",
    title: "Reagir a mensagem do canal",
  },
  {
    operationId: "followNewsletter",
    method: "POST",
    path: "/newsletter/follow",
    auth: "instance",
    category: "Canais",
    title: "Seguir canal",
  },
  {
    operationId: "unfollowNewsletter",
    method: "POST",
    path: "/newsletter/unfollow",
    auth: "instance",
    category: "Canais",
    title: "Deixar de seguir canal",
  },
  {
    operationId: "muteNewsletter",
    method: "POST",
    path: "/newsletter/mute",
    auth: "instance",
    category: "Canais",
    title: "Silenciar canal",
  },
  {
    operationId: "unmuteNewsletter",
    method: "POST",
    path: "/newsletter/unmute",
    auth: "instance",
    category: "Canais",
    title: "Remover silencio do canal",
  },
  {
    operationId: "deleteNewsletter",
    method: "POST",
    path: "/newsletter/delete",
    auth: "instance",
    category: "Canais",
    title: "Excluir canal",
    risk: "danger",
  },
  {
    operationId: "updateNewsletterPicture",
    method: "POST",
    path: "/newsletter/picture",
    auth: "instance",
    category: "Canais",
    title: "Atualizar imagem do canal",
  },
  {
    operationId: "updateNewsletterName",
    method: "POST",
    path: "/newsletter/name",
    auth: "instance",
    category: "Canais",
    title: "Atualizar nome do canal",
  },
  {
    operationId: "updateNewsletterDescription",
    method: "POST",
    path: "/newsletter/description",
    auth: "instance",
    category: "Canais",
    title: "Atualizar descricao do canal",
  },
  {
    operationId: "updateNewsletterSettings",
    method: "POST",
    path: "/newsletter/settings",
    auth: "instance",
    category: "Canais",
    title: "Atualizar configuracoes do canal",
  },
  {
    operationId: "searchNewsletterDirectory",
    method: "POST",
    path: "/newsletter/search",
    auth: "instance",
    category: "Canais",
    title: "Pesquisar diretorio de canais",
  },
  {
    operationId: "inviteNewsletterAdmin",
    method: "POST",
    path: "/newsletter/admin/invite",
    auth: "instance",
    category: "Canais",
    title: "Convidar admin do canal",
  },
  {
    operationId: "acceptNewsletterAdminInvite",
    method: "POST",
    path: "/newsletter/admin/accept",
    auth: "instance",
    category: "Canais",
    title: "Aceitar convite de admin",
  },
  {
    operationId: "removeNewsletterAdmin",
    method: "POST",
    path: "/newsletter/admin/remove",
    auth: "instance",
    category: "Canais",
    title: "Remover admin do canal",
  },
  {
    operationId: "revokeNewsletterAdminInvite",
    method: "POST",
    path: "/newsletter/admin/revoke",
    auth: "instance",
    category: "Canais",
    title: "Revogar convite de admin",
  },
  {
    operationId: "transferNewsletterOwnership",
    method: "POST",
    path: "/newsletter/owner/transfer",
    auth: "instance",
    category: "Canais",
    title: "Transferir dono do canal",
    risk: "danger",
  },
  {
    operationId: "findChats",
    method: "POST",
    path: "/chat/find",
    auth: "instance",
    category: "Chats",
    title: "Buscar chats",
    samplePayload: { operator: "AND", sort: "-wa_lastMsgTimestamp", limit: 20, offset: 0 },
  },
  {
    operationId: "getChatDetails",
    method: "POST",
    path: "/chat/details",
    auth: "instance",
    category: "Chats",
    title: "Detalhes do chat",
  },
  {
    operationId: "checkChat",
    method: "POST",
    path: "/chat/check",
    auth: "instance",
    category: "Chats",
    title: "Checar chat/numero",
  },
  {
    operationId: "markChatRead",
    method: "POST",
    path: "/chat/read",
    auth: "instance",
    category: "Chats",
    title: "Marcar chat como lido",
  },
  {
    operationId: "archiveChat",
    method: "POST",
    path: "/chat/archive",
    auth: "instance",
    category: "Chats",
    title: "Arquivar chat",
  },
  {
    operationId: "pinChat",
    method: "POST",
    path: "/chat/pin",
    auth: "instance",
    category: "Chats",
    title: "Fixar chat",
  },
  {
    operationId: "muteChat",
    method: "POST",
    path: "/chat/mute",
    auth: "instance",
    category: "Chats",
    title: "Silenciar chat",
  },
  {
    operationId: "blockChat",
    method: "POST",
    path: "/chat/block",
    auth: "instance",
    category: "Chats",
    title: "Bloquear chat",
    risk: "sensitive",
  },
  {
    operationId: "deleteChat",
    method: "POST",
    path: "/chat/delete",
    auth: "instance",
    category: "Chats",
    title: "Apagar chat",
    risk: "danger",
  },
  {
    operationId: "getBlocklist",
    method: "GET",
    path: "/chat/blocklist",
    auth: "instance",
    category: "Chats",
    title: "Ver bloqueados",
  },
  {
    operationId: "setChatLabels",
    method: "POST",
    path: "/chat/labels",
    auth: "instance",
    category: "Chats",
    title: "Definir etiquetas do chat",
  },
  {
    operationId: "getChatNotes",
    method: "POST",
    path: "/chat/notes",
    auth: "instance",
    category: "Chats",
    title: "Ver notas do chat",
  },
  {
    operationId: "editChatNotes",
    method: "POST",
    path: "/chat/notes/edit",
    auth: "instance",
    category: "Chats",
    title: "Editar notas do chat",
  },
  {
    operationId: "refreshChatNotes",
    method: "POST",
    path: "/chat/notes/refresh",
    auth: "instance",
    category: "Chats",
    title: "Atualizar notas do chat",
  },
  {
    operationId: "editLead",
    method: "POST",
    path: "/chat/editLead",
    auth: "instance",
    category: "Chats",
    title: "Editar lead do chat",
  },
  {
    operationId: "updateChatEphemeral",
    method: "POST",
    path: "/chat/ephemeral",
    auth: "instance",
    category: "Chats",
    title: "Atualizar mensagens temporarias",
  },
  {
    operationId: "addContact",
    method: "POST",
    path: "/contact/add",
    auth: "instance",
    category: "Contatos",
    title: "Adicionar contato",
  },
  {
    operationId: "removeContact",
    method: "POST",
    path: "/contact/remove",
    auth: "instance",
    category: "Contatos",
    title: "Remover contato",
    risk: "sensitive",
  },
  {
    operationId: "checkContacts",
    method: "GET",
    path: "/contacts",
    auth: "instance",
    category: "Contatos",
    title: "Checar contatos",
  },
  {
    operationId: "listContacts",
    method: "POST",
    path: "/contacts/list",
    auth: "instance",
    category: "Contatos",
    title: "Listar contatos",
    samplePayload: { limit: 100, offset: 0, contactScope: "all" },
  },
  {
    operationId: "listLabels",
    method: "GET",
    path: "/labels",
    auth: "instance",
    category: "Etiquetas",
    title: "Listar etiquetas",
  },
  {
    operationId: "refreshLabels",
    method: "POST",
    path: "/labels/refresh",
    auth: "instance",
    category: "Etiquetas",
    title: "Atualizar etiquetas",
  },
  {
    operationId: "editLabel",
    method: "POST",
    path: "/label/edit",
    auth: "instance",
    category: "Etiquetas",
    title: "Editar etiqueta",
  },
  {
    operationId: "listQuickReplies",
    method: "GET",
    path: "/quickreply/showall",
    auth: "instance",
    category: "Respostas rapidas",
    title: "Listar respostas rapidas",
  },
  {
    operationId: "editQuickReply",
    method: "POST",
    path: "/quickreply/edit",
    auth: "instance",
    category: "Respostas rapidas",
    title: "Editar resposta rapida",
  },
  {
    operationId: "getWebhook",
    method: "GET",
    path: "/webhook",
    auth: "instance",
    category: "Webhooks",
    title: "Ver webhook da instancia",
  },
  {
    operationId: "updateWebhook",
    method: "POST",
    path: "/webhook",
    auth: "instance",
    category: "Webhooks",
    title: "Configurar webhook da instancia",
    samplePayload: {
      url: "https://seu-dominio.com/api/webhooks/uazapi",
      events: ["messages", "connection", "history", "messages_update"],
      excludeMessages: ["wasSentByApi"],
    },
  },
  {
    operationId: "getWebhookErrors",
    method: "GET",
    path: "/webhook/errors",
    auth: "instance",
    category: "Webhooks",
    title: "Ver erros do webhook",
  },
  {
    operationId: "getGlobalWebhook",
    method: "GET",
    path: "/globalwebhook",
    auth: "admin",
    category: "Webhooks",
    title: "Ver webhook global",
    risk: "sensitive",
  },
  {
    operationId: "updateGlobalWebhook",
    method: "POST",
    path: "/globalwebhook",
    auth: "admin",
    category: "Webhooks",
    title: "Configurar webhook global",
    risk: "sensitive",
  },
  {
    operationId: "getGlobalWebhookErrors",
    method: "GET",
    path: "/globalwebhook/errors",
    auth: "admin",
    category: "Webhooks",
    title: "Ver erros do webhook global",
    risk: "sensitive",
  },
  {
    operationId: "subscribeSSE",
    method: "GET",
    path: "/sse",
    auth: "instance",
    category: "Webhooks",
    title: "Assinar SSE da instancia",
  },
  {
    operationId: "getChatwootConfig",
    method: "GET",
    path: "/chatwoot/config",
    auth: "instance",
    category: "Integracoes",
    title: "Ver Chatwoot",
  },
  {
    operationId: "updateChatwootConfig",
    method: "PUT",
    path: "/chatwoot/config",
    auth: "instance",
    category: "Integracoes",
    title: "Configurar Chatwoot",
  },
  {
    operationId: "makeCall",
    method: "POST",
    path: "/call/make",
    auth: "instance",
    category: "Chamadas",
    title: "Fazer chamada",
    risk: "sensitive",
  },
  {
    operationId: "rejectCall",
    method: "POST",
    path: "/call/reject",
    auth: "instance",
    category: "Chamadas",
    title: "Recusar chamada",
  },
  {
    operationId: "sendSimpleCampaign",
    method: "POST",
    path: "/sender/simple",
    auth: "instance",
    category: "Campanhas",
    title: "Enviar campanha simples",
    risk: "sensitive",
  },
  {
    operationId: "sendAdvancedCampaign",
    method: "POST",
    path: "/sender/advanced",
    auth: "instance",
    category: "Campanhas",
    title: "Enviar campanha avancada",
    risk: "sensitive",
  },
  {
    operationId: "editCampaign",
    method: "POST",
    path: "/sender/edit",
    auth: "instance",
    category: "Campanhas",
    title: "Editar campanha",
  },
  {
    operationId: "clearDoneCampaigns",
    method: "POST",
    path: "/sender/cleardone",
    auth: "instance",
    category: "Campanhas",
    title: "Limpar campanhas concluidas",
  },
  {
    operationId: "clearAllCampaigns",
    method: "DELETE",
    path: "/sender/clearall",
    auth: "instance",
    category: "Campanhas",
    title: "Limpar todas as campanhas",
    risk: "danger",
  },
  {
    operationId: "listCampaignFolders",
    method: "GET",
    path: "/sender/listfolders",
    auth: "instance",
    category: "Campanhas",
    title: "Listar pastas de campanhas",
  },
  {
    operationId: "listCampaignMessages",
    method: "POST",
    path: "/sender/listmessages",
    auth: "instance",
    category: "Campanhas",
    title: "Listar mensagens de campanha",
  },
  {
    operationId: "getBusinessProfile",
    method: "POST",
    path: "/business/get/profile",
    auth: "instance",
    category: "Business",
    title: "Ver perfil comercial",
  },
  {
    operationId: "getBusinessCategories",
    method: "GET",
    path: "/business/get/categories",
    auth: "instance",
    category: "Business",
    title: "Ver categorias comerciais",
  },
  {
    operationId: "updateBusinessProfile",
    method: "POST",
    path: "/business/update/profile",
    auth: "instance",
    category: "Business",
    title: "Atualizar perfil comercial",
  },
  {
    operationId: "getCatalog",
    method: "POST",
    path: "/business/catalog/list",
    auth: "instance",
    category: "Business",
    title: "Listar catalogo comercial",
  },
  {
    operationId: "getCatalogItem",
    method: "POST",
    path: "/business/catalog/info",
    auth: "instance",
    category: "Business",
    title: "Ver produto do catalogo",
  },
  {
    operationId: "deleteCatalogItem",
    method: "POST",
    path: "/business/catalog/delete",
    auth: "instance",
    category: "Business",
    title: "Excluir produto do catalogo",
    risk: "danger",
  },
  {
    operationId: "showCatalogItem",
    method: "POST",
    path: "/business/catalog/show",
    auth: "instance",
    category: "Business",
    title: "Mostrar produto no catalogo",
  },
  {
    operationId: "hideCatalogItem",
    method: "POST",
    path: "/business/catalog/hide",
    auth: "instance",
    category: "Business",
    title: "Ocultar produto no catalogo",
  },
  {
    operationId: "restartAdminApplication",
    method: "POST",
    path: "/admin/restart",
    auth: "admin",
    category: "Administracao",
    title: "Reiniciar aplicacao Uazapi",
    risk: "danger",
  },
  {
    operationId: "rotateAdminToken",
    method: "POST",
    path: "/admin/token/rotate",
    auth: "admin",
    category: "Administracao",
    title: "Rotacionar admin token",
    risk: "danger",
  },
] as const satisfies readonly UazapiOperation[];

export type UazapiOperationId = (typeof uazapiOperations)[number]["operationId"];

export const uazapiOperationsById = Object.fromEntries(
  uazapiOperations.map((operation) => [operation.operationId, operation]),
) as Record<UazapiOperationId, UazapiOperation>;

export function getUazapiOperation(operationId: string) {
  return uazapiOperationsById[operationId as UazapiOperationId] ?? null;
}

export function getUazapiCategories() {
  return Array.from(new Set(uazapiOperations.map((operation) => operation.category))).sort();
}
