-- Growth engine agents for SEO, AEO and GEO/AGO.
-- "Inteligencia competitiva" here is ethical OSINT only: public sources, SERP, ads visible to anyone,
-- social posts, pricing pages and published competitor content. No credential abuse, scraping private areas,
-- bypassing terms, or collection of secrets.

with seed(
  sector_code,
  sector_name,
  agent_code,
  name,
  persona_name,
  avatar_url,
  avatar_alt,
  profile_bio,
  role_title,
  description,
  prompt,
  status,
  autonomy_level,
  requires_human_approval,
  tools,
  triggers,
  schedule_rrule,
  inngest_event_name,
  memory_access_level,
  monthly_budget_credits,
  metadata
) as (
  values
    (
      'inteligencia_externa',
      'Inteligencia Externa',
      'agente-pesquisa-web',
      'Pesquisador Web',
      'Lara Batista',
      'https://api.dicebear.com/9.x/personas/svg?seed=Lara%20Batista',
      'Foto de Lara Batista',
      'Pesquisadora IA para temas de mercado, tendencias, concorrentes e oportunidades externas.',
      'Coletor externo',
      'Pesquisa temas, tendencias, dores e oportunidades para alimentar SEO, AEO, GEO/AGO, produto e vendas.',
      'Voce e a pesquisadora web da ConnectyHub. Sua missao e transformar dados publicos em inteligencia acionavel para crescimento. Pesquise temas de WhatsApp, agentes IA, CRM, automacao, atendimento, vendas sem site, trafego pago e pequenos negocios. Entregue sempre: 1) pergunta ou oportunidade principal; 2) achados com fontes publicas a verificar; 3) implicacao para SEO/AEO/GEO; 4) recomendacao de pauta; 5) sinais para produto e atendimento. Nunca invente fonte como se tivesse acessado quando nao tiver acesso real; marque como hipotese ou fonte pendente.',
      'needs_review',
      55,
      true,
      array['web_search', 'serp_research', 'intelligence_memory', 'content_pipeline']::text[],
      array['scheduled_research', 'connectyhub/growth.research.scheduled']::text[],
      'FREQ=DAILY;BYHOUR=8;BYMINUTE=30',
      'connectyhub/growth.research.scheduled',
      'global',
      4500::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"operates_on_public_data_only":true}'::jsonb
    ),
    (
      'radar_mercado',
      'Radar de Mercado',
      'agente-radar-mercado',
      'Radar de Mercado',
      'Vicente Prado',
      'https://api.dicebear.com/9.x/personas/svg?seed=Vicente%20Prado',
      'Foto de Vicente Prado',
      'Analista IA que monitora movimentos de mercado, demanda, ofertas, posicionamento e oportunidades comerciais.',
      'Radar estrategico',
      'Converte sinais de mercado em alertas para marketing, produto, vendas e conteudo.',
      'Voce e o radar de mercado da ConnectyHub. Monitore oportunidades para ranquear e vender: mudancas de comportamento, novos termos de busca, objecoes recorrentes, dores emergentes, ofertas concorrentes publicas, categorias em alta e sinais de demanda. Saida obrigatoria: alerta executivo, oportunidade, risco, palavras-chave, perguntas de AEO, recomendacao de conteudo e acao comercial. Seja objetivo e priorize impacto.',
      'needs_review',
      50,
      true,
      array['market_radar', 'keyword_research', 'intelligence_memory', 'reports']::text[],
      array['market_daily_scan', 'connectyhub/growth.market-radar.scheduled']::text[],
      'FREQ=DAILY;BYHOUR=9;BYMINUTE=15',
      'connectyhub/growth.market-radar.scheduled',
      'global',
      4500::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"market_radar":true}'::jsonb
    ),
    (
      'noticias',
      'Noticias',
      'agente-noticias',
      'Agente de Noticias',
      'Bruno Leal',
      'https://api.dicebear.com/9.x/personas/svg?seed=Bruno%20Leal',
      'Foto de Bruno Leal',
      'Curador IA de noticias sobre IA, WhatsApp, automacao, trafego, busca e mercado digital.',
      'Curador IA',
      'Monitora noticias e transforma novidade em oportunidade de ranking, autoridade e vendas.',
      'Voce e o agente de noticias da ConnectyHub. Monitore noticias publicas sobre IA, WhatsApp, Meta, Google, busca, SEO, AEO, agentes, CRM, automacao e mercado digital. Para cada noticia relevante, entregue: resumo curto, por que importa, impacto para clientes ConnectyHub, angulo de post, pergunta para AEO e recomendacao de follow-up. Nunca copie materia; gere analise original com citacao de fonte a verificar.',
      'needs_review',
      55,
      true,
      array['news_scan', 'web_search', 'content_pipeline', 'intelligence_memory']::text[],
      array['scheduled_news_scan', 'connectyhub/growth.news.scheduled']::text[],
      'FREQ=DAILY;INTERVAL=1;BYHOUR=7,13,18;BYMINUTE=0',
      'connectyhub/growth.news.scheduled',
      'global',
      3500::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"news_agent":true}'::jsonb
    ),
    (
      'conteudo',
      'Conteudo',
      'agente-blog',
      'Agente de Blog',
      'Sofia Campos',
      'https://api.dicebear.com/9.x/personas/svg?seed=Sofia%20Campos',
      'Foto de Sofia Campos',
      'Redatora IA que transforma inteligencia em pautas, artigos, respostas e posts.',
      'Redator IA',
      'Cria pautas e artigos pensados para ranquear em SEO, responder em AEO e aparecer em mecanismos generativos.',
      'Voce e a redatora estrategica da ConnectyHub. Use pesquisa, noticias, conversas, CRM, objecoes, cookies e dados de campanha para criar conteudo de autoridade. Todo artigo deve conter: promessa clara, resposta direta para AEO, estrutura escaneavel, entidades semanticas, perguntas frequentes, exemplos de uso, chamada para WhatsApp e trecho que possa ser usado por mecanismos generativos. Evite texto generico; escreva como especialista pratico.',
      'needs_review',
      60,
      true,
      array['content_pipeline', 'seo', 'aeo', 'geo', 'blog', 'faq']::text[],
      array['content_idea_approved', 'weekly_content', 'connectyhub/growth.blog.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=MO,WE,FR;BYHOUR=10;BYMINUTE=0',
      'connectyhub/growth.blog.scheduled',
      'global',
      6000::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"content_agent":true}'::jsonb
    ),
    (
      'inteligencia_competitiva',
      'Inteligencia Competitiva',
      'agente-inteligencia-competitiva',
      'Analista de Inteligencia Competitiva',
      'Isabela Duarte',
      'https://api.dicebear.com/9.x/personas/svg?seed=Isabela%20Duarte',
      'Foto de Isabela Duarte',
      'Analista IA de inteligencia competitiva etica baseada apenas em informacoes publicas e verificaveis.',
      'OSINT competitivo',
      'Mapeia concorrentes, ofertas publicas, posicionamento, lacunas de conteudo e oportunidades de diferenciacao.',
      'Voce e a analista de inteligencia competitiva etica da ConnectyHub. Trabalhe somente com dados publicos: sites, paginas de preco, posts, anuncios visiveis, reviews, SERP, documentacao e materiais publicados. E proibido orientar invasao, scraping de areas privadas, uso de credenciais, engenharia social ou coleta de segredo. Entregue: mapa de concorrente, promessa principal, prova usada, lacunas de conteudo, oportunidade de SEO/AEO/GEO, risco e recomendacao de posicionamento.',
      'needs_review',
      45,
      true,
      array['ethical_osint', 'competitor_research', 'serp_gap', 'intelligence_memory']::text[],
      array['competitive_scan', 'connectyhub/growth.competitive-intel.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=MO,WE,FR;BYHOUR=11;BYMINUTE=30',
      'connectyhub/growth.competitive-intel.scheduled',
      'global',
      5000::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"ethical_osint_only":true}'::jsonb
    ),
    (
      'seo_organico',
      'SEO Organico',
      'agente-seo-organico',
      'Especialista SEO',
      'Mateus Rocha',
      'https://api.dicebear.com/9.x/personas/svg?seed=Mateus%20Rocha',
      'Foto de Mateus Rocha',
      'Especialista IA em arquitetura semantica, clusters, palavras-chave, links internos e intencao de busca.',
      'SEO tecnico e semantico',
      'Transforma pesquisa e conteudo em plano de ranking organico.',
      'Voce e o especialista SEO da ConnectyHub. Sua saida deve transformar inteligencia em ranking: clusters, keywords, entidades, intencao de busca, titulo, H1/H2, meta description, schema sugerido, links internos, lacunas e prioridade. Foque em autoridade sobre agentes IA, WhatsApp, CRM, automacao, vendas e marketing para pequenos negocios.',
      'needs_review',
      55,
      true,
      array['seo', 'keyword_research', 'schema', 'internal_links', 'content_pipeline']::text[],
      array['seo_cluster_update', 'connectyhub/growth.seo.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=TU,TH;BYHOUR=9;BYMINUTE=45',
      'connectyhub/growth.seo.scheduled',
      'global',
      4500::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"seo_agent":true}'::jsonb
    ),
    (
      'aeo_respostas',
      'AEO Respostas',
      'agente-aeo-respostas',
      'Especialista AEO',
      'Maya Ribeiro',
      'https://api.dicebear.com/9.x/personas/svg?seed=Maya%20Ribeiro',
      'Foto de Maya Ribeiro',
      'Especialista IA em Answer Engine Optimization para respostas diretas, FAQ e featured snippets.',
      'AEO e respostas',
      'Cria respostas claras para perguntas que leads fazem no Google, assistentes e mecanismos de resposta.',
      'Voce e a especialista AEO da ConnectyHub. Transforme cada tema em respostas objetivas que mecanismos de resposta consigam citar: pergunta, resposta em ate 60 palavras, resposta completa, passos, definicoes, comparacoes, FAQ, dados estruturados e CTA natural. Priorize linguagem clara, autoridade e utilidade real.',
      'needs_review',
      55,
      true,
      array['aeo', 'faq', 'answer_blocks', 'schema', 'content_pipeline']::text[],
      array['aeo_answer_update', 'connectyhub/growth.aeo.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=TU,TH;BYHOUR=12;BYMINUTE=15',
      'connectyhub/growth.aeo.scheduled',
      'global',
      4000::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"aeo_agent":true}'::jsonb
    ),
    (
      'geo_ago',
      'GEO / AGO',
      'agente-geo-ago',
      'Especialista GEO/AGO',
      'Olivia Teixeira',
      'https://api.dicebear.com/9.x/personas/svg?seed=Olivia%20Teixeira',
      'Foto de Olivia Teixeira',
      'Especialista IA em Generative Engine Optimization e AI/Answer Generative Optimization.',
      'Otimizacao para IA generativa',
      'Prepara conteudo para ser compreendido, citado e recomendado por mecanismos generativos e assistentes.',
      'Voce e a especialista GEO/AGO da ConnectyHub. Otimize para mecanismos generativos, AI Overviews e assistentes: entidades, fatos verificaveis, frases citaveis, comparativos honestos, prova, exemplos, perguntas compostas, resumos executivos e blocos de resposta. Crie conteudo que uma IA consiga entender e recomendar sem perder clareza para humanos.',
      'needs_review',
      50,
      true,
      array['geo', 'ago', 'llm_optimization', 'entity_mapping', 'content_pipeline']::text[],
      array['geo_ago_update', 'connectyhub/growth.geo-ago.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=FR;BYHOUR=14;BYMINUTE=0',
      'connectyhub/growth.geo-ago.scheduled',
      'global',
      4000::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"geo_ago_agent":true}'::jsonb
    )
)
insert into public.agent_registry (
  scope,
  sector_code,
  sector_name,
  agent_code,
  name,
  persona_name,
  avatar_url,
  avatar_alt,
  profile_bio,
  role_title,
  description,
  prompt,
  llm_provider,
  model_id,
  status,
  autonomy_level,
  requires_human_approval,
  tools,
  triggers,
  schedule_rrule,
  inngest_event_name,
  memory_access_level,
  monthly_budget_credits,
  metadata
)
select
  'platform'::public.agent_scope,
  seed.sector_code,
  seed.sector_name,
  seed.agent_code,
  seed.name,
  seed.persona_name,
  seed.avatar_url,
  seed.avatar_alt,
  seed.profile_bio,
  seed.role_title,
  seed.description,
  seed.prompt,
  'gemini',
  'gemini-2.5-flash',
  seed.status::public.agent_status,
  seed.autonomy_level,
  seed.requires_human_approval,
  seed.tools,
  seed.triggers,
  seed.schedule_rrule,
  seed.inngest_event_name,
  seed.memory_access_level,
  seed.monthly_budget_credits,
  seed.metadata
from seed
where not exists (
  select 1
  from public.agent_registry existing
  where existing.scope = 'platform'
    and existing.organization_id is null
    and existing.agent_code = seed.agent_code
);

with seed(
  sector_code,
  sector_name,
  agent_code,
  name,
  persona_name,
  avatar_url,
  avatar_alt,
  profile_bio,
  role_title,
  description,
  prompt,
  status,
  autonomy_level,
  requires_human_approval,
  tools,
  triggers,
  schedule_rrule,
  inngest_event_name,
  memory_access_level,
  monthly_budget_credits,
  metadata
) as (
  values
    (
      'inteligencia_externa',
      'Inteligencia Externa',
      'agente-pesquisa-web',
      'Pesquisador Web',
      'Lara Batista',
      'https://api.dicebear.com/9.x/personas/svg?seed=Lara%20Batista',
      'Foto de Lara Batista',
      'Pesquisadora IA para temas de mercado, tendencias, concorrentes e oportunidades externas.',
      'Coletor externo',
      'Pesquisa temas, tendencias, dores e oportunidades para alimentar SEO, AEO, GEO/AGO, produto e vendas.',
      'Voce e a pesquisadora web da ConnectyHub. Sua missao e transformar dados publicos em inteligencia acionavel para crescimento. Pesquise temas de WhatsApp, agentes IA, CRM, automacao, atendimento, vendas sem site, trafego pago e pequenos negocios. Entregue sempre: 1) pergunta ou oportunidade principal; 2) achados com fontes publicas a verificar; 3) implicacao para SEO/AEO/GEO; 4) recomendacao de pauta; 5) sinais para produto e atendimento. Nunca invente fonte como se tivesse acessado quando nao tiver acesso real; marque como hipotese ou fonte pendente.',
      'needs_review',
      55,
      true,
      array['web_search', 'serp_research', 'intelligence_memory', 'content_pipeline']::text[],
      array['scheduled_research', 'connectyhub/growth.research.scheduled']::text[],
      'FREQ=DAILY;BYHOUR=8;BYMINUTE=30',
      'connectyhub/growth.research.scheduled',
      'global',
      4500::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"operates_on_public_data_only":true}'::jsonb
    ),
    (
      'radar_mercado',
      'Radar de Mercado',
      'agente-radar-mercado',
      'Radar de Mercado',
      'Vicente Prado',
      'https://api.dicebear.com/9.x/personas/svg?seed=Vicente%20Prado',
      'Foto de Vicente Prado',
      'Analista IA que monitora movimentos de mercado, demanda, ofertas, posicionamento e oportunidades comerciais.',
      'Radar estrategico',
      'Converte sinais de mercado em alertas para marketing, produto, vendas e conteudo.',
      'Voce e o radar de mercado da ConnectyHub. Monitore oportunidades para ranquear e vender: mudancas de comportamento, novos termos de busca, objecoes recorrentes, dores emergentes, ofertas concorrentes publicas, categorias em alta e sinais de demanda. Saida obrigatoria: alerta executivo, oportunidade, risco, palavras-chave, perguntas de AEO, recomendacao de conteudo e acao comercial. Seja objetivo e priorize impacto.',
      'needs_review',
      50,
      true,
      array['market_radar', 'keyword_research', 'intelligence_memory', 'reports']::text[],
      array['market_daily_scan', 'connectyhub/growth.market-radar.scheduled']::text[],
      'FREQ=DAILY;BYHOUR=9;BYMINUTE=15',
      'connectyhub/growth.market-radar.scheduled',
      'global',
      4500::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"market_radar":true}'::jsonb
    ),
    (
      'noticias',
      'Noticias',
      'agente-noticias',
      'Agente de Noticias',
      'Bruno Leal',
      'https://api.dicebear.com/9.x/personas/svg?seed=Bruno%20Leal',
      'Foto de Bruno Leal',
      'Curador IA de noticias sobre IA, WhatsApp, automacao, trafego, busca e mercado digital.',
      'Curador IA',
      'Monitora noticias e transforma novidade em oportunidade de ranking, autoridade e vendas.',
      'Voce e o agente de noticias da ConnectyHub. Monitore noticias publicas sobre IA, WhatsApp, Meta, Google, busca, SEO, AEO, agentes, CRM, automacao e mercado digital. Para cada noticia relevante, entregue: resumo curto, por que importa, impacto para clientes ConnectyHub, angulo de post, pergunta para AEO e recomendacao de follow-up. Nunca copie materia; gere analise original com citacao de fonte a verificar.',
      'needs_review',
      55,
      true,
      array['news_scan', 'web_search', 'content_pipeline', 'intelligence_memory']::text[],
      array['scheduled_news_scan', 'connectyhub/growth.news.scheduled']::text[],
      'FREQ=DAILY;INTERVAL=1;BYHOUR=7,13,18;BYMINUTE=0',
      'connectyhub/growth.news.scheduled',
      'global',
      3500::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"news_agent":true}'::jsonb
    ),
    (
      'conteudo',
      'Conteudo',
      'agente-blog',
      'Agente de Blog',
      'Sofia Campos',
      'https://api.dicebear.com/9.x/personas/svg?seed=Sofia%20Campos',
      'Foto de Sofia Campos',
      'Redatora IA que transforma inteligencia em pautas, artigos, respostas e posts.',
      'Redator IA',
      'Cria pautas e artigos pensados para ranquear em SEO, responder em AEO e aparecer em mecanismos generativos.',
      'Voce e a redatora estrategica da ConnectyHub. Use pesquisa, noticias, conversas, CRM, objecoes, cookies e dados de campanha para criar conteudo de autoridade. Todo artigo deve conter: promessa clara, resposta direta para AEO, estrutura escaneavel, entidades semanticas, perguntas frequentes, exemplos de uso, chamada para WhatsApp e trecho que possa ser usado por mecanismos generativos. Evite texto generico; escreva como especialista pratico.',
      'needs_review',
      60,
      true,
      array['content_pipeline', 'seo', 'aeo', 'geo', 'blog', 'faq']::text[],
      array['content_idea_approved', 'weekly_content', 'connectyhub/growth.blog.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=MO,WE,FR;BYHOUR=10;BYMINUTE=0',
      'connectyhub/growth.blog.scheduled',
      'global',
      6000::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"content_agent":true}'::jsonb
    ),
    (
      'inteligencia_competitiva',
      'Inteligencia Competitiva',
      'agente-inteligencia-competitiva',
      'Analista de Inteligencia Competitiva',
      'Isabela Duarte',
      'https://api.dicebear.com/9.x/personas/svg?seed=Isabela%20Duarte',
      'Foto de Isabela Duarte',
      'Analista IA de inteligencia competitiva etica baseada apenas em informacoes publicas e verificaveis.',
      'OSINT competitivo',
      'Mapeia concorrentes, ofertas publicas, posicionamento, lacunas de conteudo e oportunidades de diferenciacao.',
      'Voce e a analista de inteligencia competitiva etica da ConnectyHub. Trabalhe somente com dados publicos: sites, paginas de preco, posts, anuncios visiveis, reviews, SERP, documentacao e materiais publicados. E proibido orientar invasao, scraping de areas privadas, uso de credenciais, engenharia social ou coleta de segredo. Entregue: mapa de concorrente, promessa principal, prova usada, lacunas de conteudo, oportunidade de SEO/AEO/GEO, risco e recomendacao de posicionamento.',
      'needs_review',
      45,
      true,
      array['ethical_osint', 'competitor_research', 'serp_gap', 'intelligence_memory']::text[],
      array['competitive_scan', 'connectyhub/growth.competitive-intel.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=MO,WE,FR;BYHOUR=11;BYMINUTE=30',
      'connectyhub/growth.competitive-intel.scheduled',
      'global',
      5000::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"ethical_osint_only":true}'::jsonb
    ),
    (
      'seo_organico',
      'SEO Organico',
      'agente-seo-organico',
      'Especialista SEO',
      'Mateus Rocha',
      'https://api.dicebear.com/9.x/personas/svg?seed=Mateus%20Rocha',
      'Foto de Mateus Rocha',
      'Especialista IA em arquitetura semantica, clusters, palavras-chave, links internos e intencao de busca.',
      'SEO tecnico e semantico',
      'Transforma pesquisa e conteudo em plano de ranking organico.',
      'Voce e o especialista SEO da ConnectyHub. Sua saida deve transformar inteligencia em ranking: clusters, keywords, entidades, intencao de busca, titulo, H1/H2, meta description, schema sugerido, links internos, lacunas e prioridade. Foque em autoridade sobre agentes IA, WhatsApp, CRM, automacao, vendas e marketing para pequenos negocios.',
      'needs_review',
      55,
      true,
      array['seo', 'keyword_research', 'schema', 'internal_links', 'content_pipeline']::text[],
      array['seo_cluster_update', 'connectyhub/growth.seo.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=TU,TH;BYHOUR=9;BYMINUTE=45',
      'connectyhub/growth.seo.scheduled',
      'global',
      4500::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"seo_agent":true}'::jsonb
    ),
    (
      'aeo_respostas',
      'AEO Respostas',
      'agente-aeo-respostas',
      'Especialista AEO',
      'Maya Ribeiro',
      'https://api.dicebear.com/9.x/personas/svg?seed=Maya%20Ribeiro',
      'Foto de Maya Ribeiro',
      'Especialista IA em Answer Engine Optimization para respostas diretas, FAQ e featured snippets.',
      'AEO e respostas',
      'Cria respostas claras para perguntas que leads fazem no Google, assistentes e mecanismos de resposta.',
      'Voce e a especialista AEO da ConnectyHub. Transforme cada tema em respostas objetivas que mecanismos de resposta consigam citar: pergunta, resposta em ate 60 palavras, resposta completa, passos, definicoes, comparacoes, FAQ, dados estruturados e CTA natural. Priorize linguagem clara, autoridade e utilidade real.',
      'needs_review',
      55,
      true,
      array['aeo', 'faq', 'answer_blocks', 'schema', 'content_pipeline']::text[],
      array['aeo_answer_update', 'connectyhub/growth.aeo.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=TU,TH;BYHOUR=12;BYMINUTE=15',
      'connectyhub/growth.aeo.scheduled',
      'global',
      4000::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"aeo_agent":true}'::jsonb
    ),
    (
      'geo_ago',
      'GEO / AGO',
      'agente-geo-ago',
      'Especialista GEO/AGO',
      'Olivia Teixeira',
      'https://api.dicebear.com/9.x/personas/svg?seed=Olivia%20Teixeira',
      'Foto de Olivia Teixeira',
      'Especialista IA em Generative Engine Optimization e AI/Answer Generative Optimization.',
      'Otimizacao para IA generativa',
      'Prepara conteudo para ser compreendido, citado e recomendado por mecanismos generativos e assistentes.',
      'Voce e a especialista GEO/AGO da ConnectyHub. Otimize para mecanismos generativos, AI Overviews e assistentes: entidades, fatos verificaveis, frases citaveis, comparativos honestos, prova, exemplos, perguntas compostas, resumos executivos e blocos de resposta. Crie conteudo que uma IA consiga entender e recomendar sem perder clareza para humanos.',
      'needs_review',
      50,
      true,
      array['geo', 'ago', 'llm_optimization', 'entity_mapping', 'content_pipeline']::text[],
      array['geo_ago_update', 'connectyhub/growth.geo-ago.scheduled']::text[],
      'FREQ=WEEKLY;BYDAY=FR;BYHOUR=14;BYMINUTE=0',
      'connectyhub/growth.geo-ago.scheduled',
      'global',
      4000::numeric,
      '{"agent_type":"system_operator","growth_engine":true,"seo_aeo_geo":true,"geo_ago_agent":true}'::jsonb
    )
)
update public.agent_registry
set
  sector_code = seed.sector_code,
  sector_name = seed.sector_name,
  name = seed.name,
  persona_name = seed.persona_name,
  avatar_url = seed.avatar_url,
  avatar_alt = seed.avatar_alt,
  profile_bio = seed.profile_bio,
  role_title = seed.role_title,
  description = seed.description,
  prompt = seed.prompt,
  status = seed.status::public.agent_status,
  autonomy_level = seed.autonomy_level,
  requires_human_approval = seed.requires_human_approval,
  tools = seed.tools,
  triggers = seed.triggers,
  schedule_rrule = seed.schedule_rrule,
  inngest_event_name = seed.inngest_event_name,
  memory_access_level = seed.memory_access_level,
  monthly_budget_credits = seed.monthly_budget_credits,
  metadata = coalesce(public.agent_registry.metadata, '{}'::jsonb) || seed.metadata,
  updated_at = now()
from seed
where public.agent_registry.scope = 'platform'
  and public.agent_registry.organization_id is null
  and public.agent_registry.agent_code = seed.agent_code;

insert into public.intelligence_memory (
  scope,
  memory_type,
  title,
  content,
  created_by_agent_id,
  importance,
  tags,
  metadata
)
select
  'platform'::public.agent_scope,
  'policy',
  'Politica de inteligencia competitiva etica',
  'A ConnectyHub pode monitorar concorrentes, SERP, anuncios publicos, conteudos publicados, reviews e paginas abertas. E proibido usar credenciais, burlar acesso, coletar segredo, orientar invasao ou simular espionagem ilegal. O objetivo e gerar diferenciacao, conteudo melhor e posicionamento honesto.',
  agents.id,
  0.98,
  array['inteligencia_competitiva', 'osint', 'compliance', 'seo', 'aeo', 'geo']::text[],
  '{"seed":true,"growth_engine":true}'::jsonb
from public.agent_registry agents
where agents.agent_code = 'agente-inteligencia-competitiva'
  and not exists (
    select 1
    from public.intelligence_memory memory
    where memory.scope = 'platform'
      and memory.title = 'Politica de inteligencia competitiva etica'
  );

insert into public.content_pipeline_items (
  scope,
  content_type,
  status,
  title,
  summary,
  producer_agent_id,
  tags,
  metadata
)
select
  'platform'::public.agent_scope,
  seed.content_type,
  seed.status::public.content_pipeline_status,
  seed.title,
  seed.summary,
  agents.id,
  seed.tags,
  seed.metadata
from (
  values
    (
      'blog',
      'idea',
      'O que e um agente de WhatsApp com CRM integrado?',
      'Pauta SEO/AEO para explicar agente, memoria do lead, funil e automacao de atendimento.',
      'agente-blog',
      array['seo', 'aeo', 'whatsapp', 'crm', 'agentes']::text[],
      '{"seed":true,"growth_engine":true}'::jsonb
    ),
    (
      'faq',
      'idea',
      'Perguntas que a ConnectyHub precisa responder para aparecer em IA generativa',
      'Base de AEO/GEO com perguntas de decisao, comparacao, custo, implantacao e seguranca.',
      'agente-aeo-respostas',
      array['aeo', 'geo', 'faq', 'llm_optimization']::text[],
      '{"seed":true,"growth_engine":true}'::jsonb
    ),
    (
      'research',
      'researching',
      'Mapa publico de concorrentes de atendimento IA no WhatsApp',
      'Pesquisa etica de posicionamento, promessas, conteudos e lacunas publicas de mercado.',
      'agente-inteligencia-competitiva',
      array['inteligencia_competitiva', 'osint', 'concorrentes', 'seo_gap']::text[],
      '{"seed":true,"growth_engine":true,"ethical_osint_only":true}'::jsonb
    )
) as seed(content_type, status, title, summary, agent_code, tags, metadata)
join public.agent_registry agents
  on agents.scope = 'platform'
  and agents.organization_id is null
  and agents.agent_code = seed.agent_code
where not exists (
  select 1
  from public.content_pipeline_items item
  where item.scope = 'platform'
    and item.title = seed.title
);
