-- Paid plan lifecycle automations.
-- Adds WhatsApp messages for manual plan actions, paid renewals and low credits.

insert into public.platform_automation_flows (
  flow_key,
  name,
  description,
  event_type,
  audience_type,
  conditions,
  trigger_config,
  message_template,
  delay_minutes,
  cooldown_minutes,
  max_sends_per_contact,
  priority,
  labels,
  metadata
)
values
  (
    'manual_plan_activated',
    'Plano ativado manualmente',
    'Confirma para o cliente que o admin liberou um plano manualmente.',
    'manual_plan_activated',
    'paid_users',
    '{"plan_codes":["starter","pro","scale"]}'::jsonb,
    '{"kind":"admin_manual_plan","action":"activated"}'::jsonb,
    '{cliente}, seu plano {plano} foi ativado manualmente pela equipe ConnectyHub com {creditos} creditos. Ele fica valido ate {data_vencimento}. Boas vendas.',
    0,
    60,
    0,
    62,
    array['billing','manual','paid'],
    '{"seed":"0053_paid_billing_lifecycle_automations","goal":"confirm_manual_plan_activation"}'::jsonb
  ),
  (
    'manual_plan_renewed',
    'Plano renovado manualmente',
    'Confirma para o cliente que o admin renovou um ciclo pago manualmente.',
    'manual_plan_renewed',
    'paid_users',
    '{"plan_codes":["starter","pro","scale"]}'::jsonb,
    '{"kind":"admin_manual_plan","action":"renewed"}'::jsonb,
    '{cliente}, seu plano {plano} foi renovado manualmente pela equipe ConnectyHub. O novo ciclo vence em {data_vencimento} e seus creditos disponiveis sao {creditos_restantes}.',
    0,
    60,
    0,
    63,
    array['billing','manual','paid'],
    '{"seed":"0053_paid_billing_lifecycle_automations","goal":"confirm_manual_plan_renewal"}'::jsonb
  ),
  (
    'paid_plan_three_days_remaining',
    'Plano faltando 3 dias',
    'Avisa cliente pago tres dias antes do vencimento do ciclo atual.',
    'paid_plan_three_days_remaining',
    'paid_users',
    '{"plan_codes":["starter","pro","scale"]}'::jsonb,
    '{"kind":"paid_plan_deadline","days_remaining":3}'::jsonb,
    '{cliente}, seu plano {plano} vence em 3 dias, em {data_vencimento}. Voce ainda tem {creditos_restantes} creditos. Renove antes do vencimento para manter seus agentes atendendo sem pausa.',
    0,
    1440,
    1,
    64,
    array['billing','renewal','paid'],
    '{"seed":"0053_paid_billing_lifecycle_automations","goal":"renew_before_deadline"}'::jsonb
  ),
  (
    'paid_plan_one_day_remaining',
    'Plano faltando 1 dia',
    'Avisa cliente pago no ultimo dia antes do vencimento do ciclo atual.',
    'paid_plan_one_day_remaining',
    'paid_users',
    '{"plan_codes":["starter","pro","scale"]}'::jsonb,
    '{"kind":"paid_plan_deadline","days_remaining":1}'::jsonb,
    '{cliente}, seu plano {plano} vence em 1 dia, em {data_vencimento}. Para evitar pausa nos atendimentos automaticos, renove pelo painel.',
    0,
    1440,
    1,
    66,
    array['billing','renewal','paid'],
    '{"seed":"0053_paid_billing_lifecycle_automations","goal":"last_day_renewal"}'::jsonb
  ),
  (
    'paid_plan_expired',
    'Plano vencido',
    'Avisa cliente pago quando o ciclo venceu e os recursos pagos foram pausados.',
    'paid_plan_expired',
    'paid_users',
    '{"plan_codes":["starter","pro","scale"]}'::jsonb,
    '{"kind":"paid_plan_expired"}'::jsonb,
    '{cliente}, seu plano {plano} venceu em {data_vencimento}. Seus dados continuam salvos, mas recursos pagos ficam pausados ate a renovacao.',
    0,
    1440,
    2,
    68,
    array['billing','renewal','paid'],
    '{"seed":"0053_paid_billing_lifecycle_automations","goal":"recover_expired_paid_plan"}'::jsonb
  ),
  (
    'paid_low_credits_20',
    'Creditos abaixo de 20%',
    'Avisa cliente pago quando o saldo chega a vinte por cento ou menos do ciclo.',
    'paid_low_credits_20',
    'paid_users',
    '{"plan_codes":["starter","pro","scale"],"max_credit_percent":20}'::jsonb,
    '{"kind":"paid_credit_threshold","threshold_percent":20}'::jsonb,
    '{cliente}, seus creditos ConnectyHub chegaram a {percentual_creditos}% do ciclo. Restam {creditos_restantes}. Recarregue agora para seus agentes nao pararem no meio dos atendimentos.',
    0,
    1440,
    1,
    72,
    array['billing','credits','paid'],
    '{"seed":"0053_paid_billing_lifecycle_automations","goal":"prevent_credit_stop"}'::jsonb
  ),
  (
    'paid_low_credits_10',
    'Creditos abaixo de 10%',
    'Avisa cliente pago quando o saldo chega a dez por cento ou menos do ciclo.',
    'paid_low_credits_10',
    'paid_users',
    '{"plan_codes":["starter","pro","scale"],"max_credit_percent":10}'::jsonb,
    '{"kind":"paid_credit_threshold","threshold_percent":10}'::jsonb,
    '{cliente}, alerta importante: restam apenas {creditos_restantes} creditos ({percentual_creditos}% do ciclo). Recarregue pelo painel para manter IA, voz e WhatsApp ativos.',
    0,
    1440,
    1,
    74,
    array['billing','credits','paid'],
    '{"seed":"0053_paid_billing_lifecycle_automations","goal":"recover_low_credit_balance"}'::jsonb
  ),
  (
    'paid_no_credits',
    'Plano sem creditos',
    'Avisa cliente pago quando o saldo fica zerado.',
    'paid_no_credits',
    'paid_users',
    '{"plan_codes":["starter","pro","scale"],"max_balance_credits":0}'::jsonb,
    '{"kind":"paid_wallet_empty"}'::jsonb,
    '{cliente}, seus creditos acabaram. Seus agentes e recursos com custo ficam pausados ate uma recarga ou renovacao do plano.',
    0,
    720,
    2,
    76,
    array['billing','credits','paid'],
    '{"seed":"0053_paid_billing_lifecycle_automations","goal":"recover_empty_paid_wallet"}'::jsonb
  )
on conflict (flow_key) do update
set
  name = excluded.name,
  description = excluded.description,
  event_type = excluded.event_type,
  audience_type = excluded.audience_type,
  conditions = excluded.conditions,
  trigger_config = excluded.trigger_config,
  message_template = excluded.message_template,
  delay_minutes = excluded.delay_minutes,
  cooldown_minutes = excluded.cooldown_minutes,
  max_sends_per_contact = excluded.max_sends_per_contact,
  priority = excluded.priority,
  labels = excluded.labels,
  metadata = public.platform_automation_flows.metadata || excluded.metadata,
  updated_at = now();
