-- Keep internal ConnectyHub agents able to generate WhatsApp audio and media.
-- The internal organization uses plan_code='internal', so it needs an explicit
-- billing plan row for storage entitlement lookups.

insert into public.billing_plans (
  plan_code,
  name,
  short_description,
  status,
  sort_order,
  highlighted,
  monthly_price_brl,
  included_credits,
  overage_credit_price_brl,
  auto_recharge_min_credits,
  overage_limit_credits,
  trial_days,
  agent_limit,
  whatsapp_instance_limit,
  user_limit,
  module_codes,
  metadata,
  storage_limit_bytes,
  storage_file_limit,
  storage_image_max_bytes,
  storage_video_max_bytes,
  storage_file_max_bytes
) values (
  'internal',
  'ConnectyHub Interno',
  'Plano operacional interno da ConnectyHub para agentes, testes e automacoes da propria plataforma.',
  'active',
  999,
  false,
  0,
  0,
  0,
  0,
  0,
  0,
  null,
  null,
  null,
  array[
    'whatsapp_agent',
    'sales_catalog',
    'crm_basic',
    'automations',
    'voice_ai',
    'api_whatsapp',
    'reports',
    'team_users',
    'internal_ops'
  ]::text[],
  jsonb_build_object(
    'seed', 'internal_storage_voice_audio_fix',
    'editable', false,
    'internal', true,
    'storage_policy_version', 'storage_limits_v1',
    'storage_limit_label', '20 GB'
  ),
  20 * 1024::bigint * 1024 * 1024,
  10000,
  20 * 1024::bigint * 1024 * 1024,
  250 * 1024::bigint * 1024 * 1024,
  250 * 1024::bigint * 1024 * 1024
)
on conflict (plan_code) do update
set
  name = excluded.name,
  short_description = excluded.short_description,
  status = excluded.status,
  sort_order = excluded.sort_order,
  highlighted = excluded.highlighted,
  monthly_price_brl = excluded.monthly_price_brl,
  included_credits = excluded.included_credits,
  overage_credit_price_brl = excluded.overage_credit_price_brl,
  auto_recharge_min_credits = excluded.auto_recharge_min_credits,
  overage_limit_credits = excluded.overage_limit_credits,
  trial_days = excluded.trial_days,
  agent_limit = excluded.agent_limit,
  whatsapp_instance_limit = excluded.whatsapp_instance_limit,
  user_limit = excluded.user_limit,
  module_codes = excluded.module_codes,
  metadata = public.billing_plans.metadata || excluded.metadata,
  storage_limit_bytes = excluded.storage_limit_bytes,
  storage_file_limit = excluded.storage_file_limit,
  storage_image_max_bytes = excluded.storage_image_max_bytes,
  storage_video_max_bytes = excluded.storage_video_max_bytes,
  storage_file_max_bytes = excluded.storage_file_max_bytes,
  updated_at = now();
