-- Public model bindings are separate from private provider routing and billing.
create table public.ai_public_models (
 id text primary key, provider_model_id text not null unique,
 name text not null, family text not null, profile text not null, consumption text not null,
 recommended boolean not null default false, capabilities jsonb not null default '[]',
 enabled boolean not null default false, metadata jsonb not null default '{}',
 updated_at timestamptz not null default now()
);
alter table public.ai_public_models enable row level security;
revoke all on public.ai_public_models from public,anon,authenticated;
grant all on public.ai_public_models to service_role;
alter table public.ai_api_keys add column model_id text references public.ai_public_models(id);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-2.5','gemini-2.5-flash','Flash 2.5','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('pro-2.5','gemini-2.5-pro','Pro 2.5','text','Raciocínio, código e tarefas complexas, priorizando profundidade.','Maior conforme a tarefa',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-2.5-preview-tts','gemini-2.5-flash-preview-tts','Flash 2.5 Preview Voz','voice','Geração de fala a partir de texto.','Conforme o conteúdo processado',false,'["audio_output"]'::jsonb,false,'{"methods": ["countTokens", "generateContent"], "verified_at": "2026-09-10", "input_capacity": 8192, "output_capacity": 16384}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('pro-2.5-preview-tts','gemini-2.5-pro-preview-tts','Pro 2.5 Preview Voz','voice','Geração de fala a partir de texto.','Maior conforme a tarefa',false,'["audio_output", "batch"]'::jsonb,false,'{"methods": ["countTokens", "generateContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 8192, "output_capacity": 16384}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('open-4-26b-a4b-it','gemma-4-26b-a4b-it','Open 4 26B A4B It','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 262144, "output_capacity": 32768}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('open-4-31b-it','gemma-4-31b-it','Open 4 31B It','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 262144, "output_capacity": 32768}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-latest','gemini-flash-latest','Flash Latest','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-lite-latest','gemini-flash-lite-latest','Flash Lite Latest','text','Tarefas simples e alto volume, priorizando economia e rapidez.','Econômico',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('pro-latest','gemini-pro-latest','Pro Latest','text','Raciocínio, código e tarefas complexas, priorizando profundidade.','Maior conforme a tarefa',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-lite-2.5','gemini-2.5-flash-lite','Flash Lite 2.5','text','Tarefas simples e alto volume, priorizando economia e rapidez.','Econômico',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-2.5-image','gemini-2.5-flash-image','Flash 2.5 Image','image','Criação e edição de imagens.','Maior conforme a tarefa',false,'["image_output", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 32768, "output_capacity": 32768}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3-preview','gemini-3-flash-preview','Flash 3 Preview','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('pro-3.1-preview','gemini-3.1-pro-preview','Pro 3.1 Preview','text','Raciocínio, código e tarefas complexas, priorizando profundidade.','Maior conforme a tarefa',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('pro-3.1-preview-customtools','gemini-3.1-pro-preview-customtools','Pro 3.1 Preview Customtools','text','Raciocínio, código e tarefas complexas, priorizando profundidade.','Maior conforme a tarefa',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-lite-3.1-preview','gemini-3.1-flash-lite-preview','Flash Lite 3.1 Preview','text','Tarefas simples e alto volume, priorizando economia e rapidez.','Econômico',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-lite-3.1','gemini-3.1-flash-lite','Flash Lite 3.1','text','Tarefas simples e alto volume, priorizando economia e rapidez.','Econômico',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('pro-3-image-preview','gemini-3-pro-image-preview','Pro 3 Image Preview','image','Criação e edição de imagens.','Maior conforme a tarefa',false,'["image_output", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 32768}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('pro-3-image','gemini-3-pro-image','Pro 3 Image','image','Criação e edição de imagens.','Maior conforme a tarefa',false,'["image_output", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 32768}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('image-pro-preview','nano-banana-pro-preview','Image Pro Preview','image','Criação e edição de imagens.','Maior conforme a tarefa',false,'["image_output", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 32768}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3.1-image-preview','gemini-3.1-flash-image-preview','Flash 3.1 Image Preview','image','Criação e edição de imagens.','Maior conforme a tarefa',false,'["image_output", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 65536, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3.1-image','gemini-3.1-flash-image','Flash 3.1 Image','image','Criação e edição de imagens.','Maior conforme a tarefa',false,'["image_output", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 65536, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-lite-3.1-image','gemini-3.1-flash-lite-image','Flash Lite 3.1 Image','image','Criação e edição de imagens.','Econômico',false,'["image_output", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 65536, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3.5','gemini-3.5-flash','Flash 3.5','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',true,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "code_execution", "web_search", "url_context", "maps", "cache", "batch"]'::jsonb,true,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-lite-3.5','gemini-3.5-flash-lite','Flash Lite 3.5','text','Tarefas simples e alto volume, priorizando economia e rapidez.','Econômico',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('omni-flash-preview','gemini-omni-flash-preview','Omni Flash Preview','video','Criação e transformação de vídeos.','Maior conforme a tarefa',false,'["video_output"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('omni-1.1-flash','gemini-omni-1.1-flash','Omni 1.1 Flash','video','Criação e transformação de vídeos.','Maior conforme a tarefa',false,'["video_output"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('3.5-transcribe','gemini-3.5-transcribe','3.5 Transcribe','transcription','Transcrição de áudio para texto.','Conforme o conteúdo processado',false,'["audio_input"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 98304, "output_capacity": 32768}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3.6','gemini-3.6-flash','Flash 3.6','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "code_execution", "web_search", "url_context", "maps", "cache", "batch"]'::jsonb,true,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3.7','gemini-3.7-flash','Flash 3.7','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "code_execution", "web_search", "url_context", "maps", "cache", "batch"]'::jsonb,true,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3.8','gemini-3.8-flash','Flash 3.8','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "code_execution", "web_search", "url_context", "maps", "cache", "batch"]'::jsonb,true,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('music-3-clip-preview','lyria-3-clip-preview','Music 3 Clip Preview','music','Composição musical.','Maior conforme a tarefa',false,'["music"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('music-3-pro-preview','lyria-3-pro-preview','Music 3 Pro Preview','music','Composição musical.','Maior conforme a tarefa',false,'["music"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('music-3.5','lyria-3.5','Music 3.5','music','Composição musical.','Maior conforme a tarefa',false,'["music"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3.1-tts-preview','gemini-3.1-flash-tts-preview','Flash 3.1 Voz Preview','voice','Geração de fala a partir de texto.','Conforme o conteúdo processado',false,'["audio_output", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 8192, "output_capacity": 16384}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('robotics-er-2-preview','gemini-robotics-er-2-preview','Robotics Er 2 Preview','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions", "cache", "batch"]'::jsonb,false,'{"methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('2.5-computer-use-preview-10-2025','gemini-2.5-computer-use-preview-10-2025','2.5 Computer Use Preview 10 2025','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat", "image_input", "audio_input", "video_input", "pdf_input", "structured_output", "functions"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('antigravity-preview-05-2026','antigravity-preview-05-2026','Antigravity Preview 05 2026','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('deep-research-max-preview-04-2026','deep-research-max-preview-04-2026','Deep Research Max Preview 04 2026','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('deep-research-preview-04-2026','deep-research-preview-04-2026','Deep Research Preview 04 2026','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('deep-research-pro-preview-12-2025','deep-research-pro-preview-12-2025','Deep Research Pro Preview 12 2025','text','Raciocínio, código e tarefas complexas, priorizando profundidade.','Maior conforme a tarefa',false,'["chat"]'::jsonb,false,'{"methods": ["generateContent", "countTokens"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('embedding-001','gemini-embedding-001','Embedding 001','embeddings','Representações numéricas para busca e comparação.','Conforme o conteúdo processado',false,'["embeddings"]'::jsonb,false,'{"methods": ["embedContent", "countTextTokens", "countTokens", "asyncBatchEmbedContent"], "verified_at": "2026-09-10", "input_capacity": 2048, "output_capacity": 1}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('embedding-2-preview','gemini-embedding-2-preview','Embedding 2 Preview','embeddings','Representações numéricas para busca e comparação.','Conforme o conteúdo processado',false,'["embeddings"]'::jsonb,false,'{"methods": ["embedContent", "countTextTokens", "countTokens", "asyncBatchEmbedContent"], "verified_at": "2026-09-10", "input_capacity": 8192, "output_capacity": 1}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('embedding-2','gemini-embedding-2','Embedding 2','embeddings','Representações numéricas para busca e comparação.','Conforme o conteúdo processado',false,'["embeddings"]'::jsonb,false,'{"methods": ["embedContent", "countTextTokens", "countTokens", "asyncBatchEmbedContent"], "verified_at": "2026-09-10", "input_capacity": 8192, "output_capacity": 1}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('aqa','aqa','Aqa','text','Conversas, análise e tarefas de linguagem.','Conforme o conteúdo processado',false,'["chat"]'::jsonb,false,'{"methods": ["generateAnswer"], "verified_at": "2026-09-10", "input_capacity": 7168, "output_capacity": 1024}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('video-3.1-generate-preview','veo-3.1-generate-preview','Video 3.1 Generate Preview','video','Criação e transformação de vídeos.','Maior conforme a tarefa',false,'["video_output"]'::jsonb,false,'{"methods": ["predictLongRunning"], "verified_at": "2026-09-10", "input_capacity": 480, "output_capacity": 8192}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('video-3.1-fast-generate-preview','veo-3.1-fast-generate-preview','Video 3.1 Fast Generate Preview','video','Criação e transformação de vídeos.','Maior conforme a tarefa',false,'["video_output"]'::jsonb,false,'{"methods": ["predictLongRunning"], "verified_at": "2026-09-10", "input_capacity": 480, "output_capacity": 8192}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('video-3.1-lite-generate-preview','veo-3.1-lite-generate-preview','Video 3.1 Lite Generate Preview','video','Criação e transformação de vídeos.','Econômico',false,'["video_output"]'::jsonb,false,'{"methods": ["predictLongRunning"], "verified_at": "2026-09-10", "input_capacity": 480, "output_capacity": 8192}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('3.5-transcribe-live','gemini-3.5-transcribe-live','3.5 Transcribe Live','live','Interação contínua em tempo real.','Maior conforme a tarefa',false,'["live"]'::jsonb,false,'{"methods": ["bidiGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-2.5-native-audio-latest','gemini-2.5-flash-native-audio-latest','Flash 2.5 Native Audio Latest','live','Interação contínua em tempo real.','Maior conforme a tarefa',false,'["live"]'::jsonb,false,'{"methods": ["countTokens", "bidiGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 8192}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-2.5-native-audio-preview-09-2025','gemini-2.5-flash-native-audio-preview-09-2025','Flash 2.5 Native Audio Preview 09 2025','live','Interação contínua em tempo real.','Maior conforme a tarefa',false,'["live"]'::jsonb,false,'{"methods": ["countTokens", "bidiGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 8192}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-2.5-native-audio-preview-12-2025','gemini-2.5-flash-native-audio-preview-12-2025','Flash 2.5 Native Audio Preview 12 2025','live','Interação contínua em tempo real.','Maior conforme a tarefa',false,'["live"]'::jsonb,false,'{"methods": ["countTokens", "bidiGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 8192}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('flash-3.1-live-preview','gemini-3.1-flash-live-preview','Flash 3.1 Live Preview','live','Interação contínua em tempo real.','Maior conforme a tarefa',false,'["live"]'::jsonb,false,'{"methods": ["bidiGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('robotics-er-2-streaming-preview','gemini-robotics-er-2-streaming-preview','Robotics Er 2 Streaming Preview','live','Interação contínua em tempo real.','Maior conforme a tarefa',false,'["live"]'::jsonb,false,'{"methods": ["bidiGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 131072, "output_capacity": 65536}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('3.5-live-translate-preview','gemini-3.5-live-translate-preview','3.5 Live Translate Preview','live','Interação contínua em tempo real.','Maior conforme a tarefa',false,'["live"]'::jsonb,false,'{"methods": ["bidiGenerateContent"], "verified_at": "2026-09-10", "input_capacity": 16384, "output_capacity": 32768}'::jsonb);
insert into public.ai_public_models(id,provider_model_id,name,family,profile,consumption,recommended,capabilities,enabled,metadata) values ('music-realtime-exp','lyria-realtime-exp','Music Realtime Exp','live','Interação contínua em tempo real.','Maior conforme a tarefa',false,'["live"]'::jsonb,false,'{"methods": ["bidiGenerateMusic"], "verified_at": "2026-09-10", "input_capacity": 1048576, "output_capacity": 65536}'::jsonb);

create function public.create_ai_project_with_model_key(p_org uuid,p_name text,p_hash text,p_prefix text,p_model text) returns uuid
language plpgsql security definer set search_path=public as $$
declare created_project uuid;
begin
 if not exists(select 1 from public.ai_public_models where id=p_model and enabled) then raise exception 'ai_model_unavailable'; end if;
 created_project:=public.create_ai_project_with_key(p_org,p_name,p_hash,p_prefix);
 update public.ai_api_keys set model_id=p_model where project_id=created_project;
 return created_project;
end $$;
revoke all on function public.create_ai_project_with_model_key(uuid,text,text,text,text) from public,anon,authenticated;
grant execute on function public.create_ai_project_with_model_key(uuid,text,text,text,text) to service_role;

-- Preserve existing pricing. New text models follow the established FX guardrail
-- (6 BRL/USD), markup (4) and 0.01 BRL per credit, with official standard prices.
do $migration$
declare cc uuid; feature uuid; mid uuid; item record; price record;
begin
 select id into cc from public.provider_cost_centers where provider='gemini';
 select id into feature from public.provider_features where cost_center_id=cc and feature_code='external_ai';
 if cc is null or feature is null then raise exception 'EXTERNAL_AI_BILLING_REQUIRED'; end if;
 for item in select * from (values
 ('gemini-3.5-flash',1.50::numeric,9.00::numeric,null::timestamptz),
 ('gemini-3.5-flash-lite',0.30::numeric,2.50::numeric,null::timestamptz),
 ('gemini-3.1-pro-preview',2.00::numeric,12.00::numeric,null::timestamptz),
 ('gemini-3.1-pro-preview-customtools',2.00::numeric,12.00::numeric,null::timestamptz),
 ('gemini-3.7-flash',0.75::numeric,3.75::numeric,'2027-01-01T00:00:00Z'::timestamptz),
 ('gemini-3.8-flash',0.75::numeric,3.75::numeric,'2027-01-01T00:00:00Z'::timestamptz)
 ) as model(name,input_usd,output_usd,expires) loop
 insert into public.provider_models(cost_center_id,provider_model_id,display_name,feature_code,supports_billing,enabled,input_unit,output_unit,metadata)
 values(cc,item.name,item.name,'external_ai',true,true,'input_token','output_token','{"external_ai_available":true,"verified_at":"2026-09-10"}')
 on conflict(cost_center_id,provider_model_id) do update set metadata=provider_models.metadata||excluded.metadata returning id into mid;
 for price in select * from (values ('input_token',item.input_usd),('output_token',item.output_usd)) as rate(unit,usd) loop
 insert into public.billing_rates(cost_center_id,feature_id,model_id,unit,provider_cost_per_unit,connecty_price_per_unit,margin_multiplier,minimum_charge_credits,currency,effective_from,effective_to,active,metadata)
 values(cc,feature,mid,price.unit::public.billing_unit,price.usd*6/1000000,price.usd*2400/1000000,4,1,'BRL',now(),item.expires,true,
 jsonb_build_object('pricing_source','https://ai.google.dev/gemini-api/docs/pricing','verified_at','2026-09-10','usd_fx_guardrail',6,'markup',4));
 if item.expires is not null then
 insert into public.billing_rates(cost_center_id,feature_id,model_id,unit,provider_cost_per_unit,connecty_price_per_unit,margin_multiplier,minimum_charge_credits,currency,effective_from,active,metadata)
 values(cc,feature,mid,price.unit::public.billing_unit,price.usd*12/1000000,price.usd*4800/1000000,4,1,'BRL',item.expires,true,
 jsonb_build_object('pricing_source','https://ai.google.dev/gemini-api/docs/pricing','verified_at','2026-09-10','usd_fx_guardrail',6,'markup',4));
 end if;
 end loop;
 end loop;
end $migration$;

-- Text embeddings have no generated-text charge. Multimodal vectors remain gated.
do $migration$
declare cc uuid; feature uuid; mid uuid; item record;
begin
 select id into cc from provider_cost_centers where provider='gemini';
 select id into feature from provider_features where cost_center_id=cc and feature_code='external_ai';
 for item in select * from (values ('gemini-embedding-001',0.15::numeric),('gemini-embedding-2',0.20::numeric),('gemini-embedding-2-preview',0.20::numeric)) as t(name,usd) loop
  insert into provider_models(cost_center_id,provider_model_id,display_name,feature_code,supports_billing,enabled,input_unit,output_unit,metadata)
  values(cc,item.name,item.name,'external_ai',true,true,'input_token','output_token','{"external_ai_available":true,"verified_at":"2026-09-10"}')
  on conflict(cost_center_id,provider_model_id) do update set metadata=provider_models.metadata||excluded.metadata returning id into mid;
  insert into billing_rates(cost_center_id,feature_id,model_id,unit,provider_cost_per_unit,connecty_price_per_unit,margin_multiplier,minimum_charge_credits,currency,effective_from,active,metadata)
  values(cc,feature,mid,'input_token',item.usd*6/1000000,item.usd*2400/1000000,4,1,'BRL',now(),true,'{"pricing_source":"https://ai.google.dev/gemini-api/docs/pricing","verified_at":"2026-09-10","modality":"text"}');
 end loop;
end $migration$;
update ai_public_models set enabled=true where id in ('flash-lite-3.5','embedding-001','embedding-2','embedding-2-preview');

create function public.guard_ai_key_model() returns trigger language plpgsql set search_path=public as $$
begin
 if old.model_id is not null and new.model_id is distinct from old.model_id then raise exception 'ai_key_model_immutable'; end if;
 return new;
end $$;
create trigger ai_key_model_immutable before update of model_id on public.ai_api_keys for each row execute function public.guard_ai_key_model();

-- Long-context Pro requests use a separate tariff, selected before reserving credits.
do $migration$
declare cc uuid; feature uuid; item record; rate record;
begin
 select id into cc from provider_cost_centers where provider='gemini';
 insert into provider_features(cost_center_id,feature_code,name,description,unit,enabled,billable)
 values(cc,'external_ai_long_context','API de IA: contexto extenso','Tarifa de contexto extenso dos modelos Pro.','input_token',true,true)
 on conflict(cost_center_id,feature_code) do update set name=excluded.name returning id into feature;
 for item in select id from provider_models where cost_center_id=cc and provider_model_id in ('gemini-3.1-pro-preview','gemini-3.1-pro-preview-customtools') loop
  for rate in select * from (values ('input_token',4.0::numeric),('output_token',18.0::numeric)) as r(unit,usd) loop
   insert into billing_rates(cost_center_id,feature_id,model_id,unit,provider_cost_per_unit,connecty_price_per_unit,margin_multiplier,minimum_charge_credits,currency,effective_from,active,metadata)
   values(cc,feature,item.id,rate.unit::billing_unit,rate.usd*6/1000000,rate.usd*2400/1000000,4,1,'BRL',now(),true,'{"pricing_source":"https://ai.google.dev/gemini-api/docs/pricing","verified_at":"2026-09-10","above_input":200000}');
  end loop;
 end loop;
end $migration$;
update ai_public_models set enabled=true where id in ('pro-3.1-preview','pro-3.1-preview-customtools');

update ai_public_models set profile='Uso geral, conversas e raciocínio, com equilíbrio entre rapidez e profundidade.' where id='flash-3.5';
update ai_public_models set profile='Conversas e análise multimodal para tarefas do dia a dia.' where id='flash-3.6';
update ai_public_models set profile='Programação e execução de tarefas em várias etapas.' where id='flash-3.7';
update ai_public_models set profile='Tarefas complexas de programação, agentes e fluxos empresariais extensos.' where id='flash-3.8';
